(function(g){var window=this;var oya=function(a,b){return g.Ib(a,b)},$5=function(a,b,c){a.A.set(b,c)},a6=function(a){$5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},b6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.A,b,c)},pya=function(a,b){var c=[];
g.hk(b,function(d){try{var e=g.eo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.co(e)&&c.push(d)},a);
return c},qya=function(a,b){var c=pya(a,b);
(0,g.y)(c,function(d){g.eo.prototype.remove.call(this,d)},a)},rya=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},sya=function(a,b){g.db(a,b)||a.push(b)},c6=function(a){var b=0,c;
for(c in a)b++;return b},tya=function(a,b){var c=b instanceof g.vc?b:g.Ac(b,/^data:image\//i.test(b));
a.src=g.wc(c)},d6=function(){},uya=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},vya=function(a){if(a.Rd&&"function"==typeof a.Rd)return a.Rd();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Eb(a)},wya=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Ze&&"function"==typeof a.Ze)var c=a.Ze();else if(a.Rd&&"function"==typeof a.Rd)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Fb(a);d=vya(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},xya=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.u=d);return e},e6=function(a,b){g.Mo[a]=!0;
var c=g.Ko();c&&c.publish.apply(c,arguments);g.Mo[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",yya(this,a.capabilities||""),zya(this,a.experiments||""))},yya=function(a,b){a.capabilities.clear();
(0,g.ye)(b.split(","),g.Qa(oya,Aya)).forEach(function(c){a.capabilities.add(c)})},zya=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Bya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Cya=function(a){return new g6(a)},Dya=function(a){return Array.isArray(a)?(0,g.Fc)(a,Cya):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return Array.isArray(a)?"["+(0,g.Fc)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},Eya=function(a){return(0,g.Fc)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.ab(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.ab(a,function(c){return h6(c,b)})},Fya=function(){var a=(0,g.Qs)();
a&&qya(a,a.o.Sh(!0))},n6=function(){var a=g.Ts("yt-remote-connected-devices")||[];
g.ub(a);return a},Gya=function(a){if(g.eb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Fc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Hya=function(a){g.Ss("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.Ts("yt-remote-device-id");a||(a=k6(),g.Ss("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.db(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.db(a,b);g.Vs()&&g.wb(a,b);a=Gya(a);if(g.eb(a))try{g.xq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.yq("remote_sid",a.join(","),-1)}catch(c){}},Iya=function(){return g.Ts("yt-remote-session-browser-channel")},Jya=function(){return g.Ts("yt-remote-local-screens")||[]},Kya=function(){g.Ss("yt-remote-lounge-token-expiration",!0,86400)},Lya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Fc)(Jya(),function(d){return d.loungeToken}),c=(0,g.Fc)(a,function(d){return d.loungeToken});
(0,g.ui)(c,function(d){return!g.db(b,d)})&&Kya();
g.Ss("yt-remote-local-screens",a,31536E3)},Mya=function(a,b){g.Ss("yt-remote-session-browser-channel",a);
g.Ss("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.db(c,d)||c.push(d);Hya(c);q6()},r6=function(a){a||(g.Us("yt-remote-session-screen-id"),g.Us("yt-remote-session-video-id"));
q6();a=n6();g.ib(a,p6());Hya(a)},Nya=function(){if(!s6){var a=g.ko();
a&&(s6=new g.Yn(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},Oya=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Pya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?Qya(a.shift(),function(){t6(a)}):u6()},Rya=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Qya=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=Pya();
a&&a(!1,"No cast extension found")},Tya=function(){if(Sya){var a=2,b=Pya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Qya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},Uya=function(){Tya();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},v6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Kd=b;this.C=(0,g.x)(this.OG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},w6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Kd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},x6=function(a){a.Ka=g.Xf(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,x6(a))},a.Kd);
var b=a.A;a.A=null;a.B.apply(null,b)},y6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return uya(a)},z6=function(){},A6=function(){},Vya=function(){},Xya=function(a){return(a=Wya(a))?new ActiveXObject(a):new XMLHttpRequest},Wya=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},B6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.B1(this);this.u=new g.Wf;this.u.setInterval(250)},Zya=function(a,b,c){a.Wl=1;
a.Vh=a6(b.clone());a.pk=c;a.F=!0;Yya(a,null)},C6=function(a,b,c,d,e){a.Wl=1;
a.Vh=a6(b.clone());a.pk=null;a.F=c;e&&(a.HD=!1);Yya(a,d)},Yya=function(a,b){a.Rl=(0,g.D)();
D6(a);a.Yi=a.Vh.clone();b6(a.Yi,"t",a.G);a.vo=0;a.dd=a.o.Gt(a.o.fo()?b:null);0<a.pu&&(a.xr=new w6((0,g.x)(a.HE,a,a.dd),a.pu));a.B.na(a.dd,"readystatechange",a.IO);var c=a.Jj?g.Ob(a.Jj):{};a.pk?(a.ks="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.dd.send(a.Yi,a.ks,a.pk,c)):(a.ks="GET",a.HD&&!g.ne&&(c.Connection="close"),a.dd.send(a.Yi,a.ks,null,c));a.o.Uf(1)},bza=function(a,b,c){for(var d=!0;!a.qj&&a.vo<c.length;){var e=$ya(a,c);
if(e==E6){4==b&&(a.ni=4,F6(15),d=!1);break}else if(e==aza){a.ni=4;F6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.ni=1,F6(17),d=!1);a.cg=a.cg&&d;d||(H6(a),I6(a))},$ya=function(a,b){var c=a.vo,d=b.indexOf("\n",c);
if(-1==d)return E6;c=Number(b.substring(c,d));if(isNaN(c))return aza;d+=1;if(d+c>b.length)return E6;var e=b.substr(d,c);a.vo=d+c;return e},dza=function(a,b){a.Rl=(0,g.D)();
D6(a);var c=b?window.location.hostname:"";a.Yi=a.Vh.clone();$5(a.Yi,"DOMAIN",c);$5(a.Yi,"t",a.G);try{a.hg=new ActiveXObject("htmlfile")}catch(n){H6(a);a.ni=7;F6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in J6)h=J6[l];else if(l in cza)h=J6[l]=cza[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
J6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.$c(g.$b("b/12014412"),d+"</body></html>");a.hg.open();a.hg.write(g.Uc(c));a.hg.close();a.hg.parentWindow.m=(0,g.x)(a.aO,a);a.hg.parentWindow.d=(0,g.x)(a.LC,a,!0);a.hg.parentWindow.rpcClose=(0,g.x)(a.LC,a,!1);c=a.hg.createElement("DIV");a.hg.parentWindow.document.body.appendChild(c);d=g.zc(a.Yi.toString());d=g.hd(g.wc(d));d=g.$c(g.$b("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ad(c,d);a.o.Uf(1)},D6=function(a){a.ix=(0,g.D)()+a.C;
eza(a,a.C)},eza=function(a,b){if(null!=a.fm)throw Error("WatchDog timer not null");
a.fm=K6((0,g.x)(a.iO,a),b)},L6=function(a){a.fm&&(g.v.clearTimeout(a.fm),a.fm=null)},I6=function(a){a.o.Mz()||a.qj||a.o.Np(a)},H6=function(a){L6(a);
g.Ke(a.xr);a.xr=null;a.u.stop();g.hta(a.B);if(a.dd){var b=a.dd;a.dd=null;b.abort();b.dispose()}a.hg&&(a.hg=null)},G6=function(a,b){try{a.o.DC(a,b),a.o.Uf(4)}catch(c){}},gza=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;fza(a,b,function(h){h?c(!0):g.v.setTimeout(function(){gza(a,b,c,d,f)},f)})}},fza=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
tya(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},hza=function(a){this.o=a;
this.u=new z6},iza=function(a){var b=N6(a.o,a.wm,"/mail/images/cleardot.gif");
a6(b);gza(b.toString(),5E3,(0,g.x)(a.OF,a),3,2E3);a.Uf(1)},P6=function(a){var b=a.o.M;
if(null!=b)F6(5),b?(F6(11),O6(a.o,a,!1)):(F6(12),O6(a.o,a,!0));else if(a.te=new B6(a,void 0,void 0,void 0),a.te.Jj=a.nu,b=a.o,b=N6(b,b.fo()?a.Vm:null,a.ou),F6(5),!g.le||g.Qd(10))b6(b,"TYPE","xmlhttp"),C6(a.te,b,!1,a.Vm,!1);else{b6(b,"TYPE","html");var c=a.te;a=!!a.Vm;c.Wl=3;c.Vh=a6(b.clone());dza(c,a)}},Q6=function(a){g.lf.call(this);
this.headers=new g.Nm;this.T=a||null;this.A=!1;this.U=this.o=null;this.ga=this.M="";this.F=0;this.B="";this.C=this.ba=this.I=this.Z=!1;this.G=0;this.N=null;this.ea="";this.R=this.aa=!1},jza=function(a){return g.le&&g.Pd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},kza=function(a){return"content-type"==a.toLowerCase()},mza=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;lza(a);R6(a)},lza=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},oza=function(a){if(a.A&&"undefined"!=typeof g.G1)if(a.U[1]&&4==S6(a)&&2==a.getStatus())T6(a,"Local request error detected and ignored");
else if(a.I&&4==S6(a))g.Xf(a.zC,0,a);else if(a.dispatchEvent("readystatechange"),4==S6(a)){T6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.rd(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!nza.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<S6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";lza(a)}}finally{R6(a)}}},R6=function(a,b){if(a.o){pza(a);
var c=a.o,d=a.U[0]?g.Ia:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},pza=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},S6=function(a){return a.o?a.o.readyState:0},U6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},T6=function(a,b){return b+" ["+a.ga+" "+a.M+" "+a.getStatus()+"]"},V6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new z6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},qza=function(a,b){this.o=a;
this.map=b;this.context=null},rza=function(a){g.Me.call(this,"statevent",a)},sza=function(a,b){g.Me.call(this,"timingevent",a);
this.size=b},tza=function(a){g.Me.call(this,"serverreachability",a)},wza=function(a){uza(a);
if(3==a.o){var b=a.Dn++,c=a.xp.clone();$5(c,"SID",a.A);$5(c,"RID",b);$5(c,"TYPE","terminate");W6(a,c);b=new B6(a,a.A,b,void 0);b.Wl=2;b.Vh=a6(c.clone());tya(new Image,b.Vh.toString());b.Rl=(0,g.D)();D6(b)}vza(a)},xza=function(a){a.mG(1,0);
a.xp=N6(a,null,a.mu);X6(a)},uza=function(a){a.Yh&&(a.Yh.abort(),a.Yh=null);
a.Dc&&(a.Dc.cancel(),a.Dc=null);a.Zg&&(g.v.clearTimeout(a.Zg),a.Zg=null);Y6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.fi&&(g.v.clearTimeout(a.fi),a.fi=null)},yza=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new qza(a.HK++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.ie||a.fi||(a.fi=K6((0,g.x)(a.KC,a),0),a.Xk=0)},Aza=function(a,b){if(1==a.o){if(!b){a.Dn=Math.floor(1E5*Math.random());
var c=a.Dn++,d=new B6(a,"",c,void 0);d.Jj=null;var e=Z6(a),f=a.xp.clone();$5(f,"RID",c);$5(f,"CVER","1");W6(a,f);Zya(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?zza(a,b):0==a.u.length||a.ie||zza(a))},zza=function(a,b){if(b)if(6<a.rj){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Dn-1;var d=Z6(a)}else c=b.I,d=b.pk;else c=a.Dn++,d=Z6(a);var e=a.xp.clone();$5(e,"SID",a.A);$5(e,"RID",c);$5(e,"AID",a.ul);W6(a,e);c=new B6(a,a.A,c,a.Xk+1);c.Jj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;Zya(c,e,d)},W6=function(a,b){if(a.Hd){var c=a.Hd.kz();
c&&g.yb(c,function(d,e){$5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.rj&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.rj?e:f-d;try{g.yb(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},Bza=function(a){a.Dc||a.Zg||(a.G=1,a.Zg=K6((0,g.x)(a.JC,a),0),a.Jk=0)},$6=function(a){if(a.Dc||a.Zg||3<=a.Jk)return!1;
a.G++;a.Zg=K6((0,g.x)(a.JC,a),Cza(a,a.Jk));a.Jk++;return!0},O6=function(a,b,c){a.gs=c;
a.rg=b.rh;a.F||xza(a)},Y6=function(a){null!=a.wj&&(g.v.clearTimeout(a.wj),a.wj=null)},Cza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Hd&&(c=null);var d=(0,g.x)(a.tP,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),a6(c));fza(c.toString(),1E4,d)}else F6(2);Dza(a,b)},Dza=function(a,b){a.o=0;
a.Hd&&a.Hd.yy(b);vza(a);uza(a)},vza=function(a){a.o=0;
a.rg=-1;if(a.Hd)if(0==a.B.length&&0==a.u.length)a.Hd.ot();else{g.lb(a.B);var b=g.lb(a.u);a.B.length=0;a.u.length=0;a.Hd.ot(b)}},N6=function(a,b,c){var d=g.Ym(c);
if(""!=d.o)b&&g.Sm(d,b+"."+d.o),g.Tm(d,d.B);else{var e=window.location;d=xya(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Lm&&g.yb(a.Lm,function(f,h){$5(d,h,f)});
$5(d,"VER",a.rj);W6(a,d);return d},K6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},F6=function(a){b7.dispatchEvent(new rza(b7,a))},Eza=function(){},Fza=function(){this.o=[];
this.u=[]},Gza=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.A.call(this);
this.o=new g.H(this.TN,0,this);g.C(this,this.o);this.Kd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},d7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.Xn;this.u=new c7(this.WO,this);this.o=null;this.Ob=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.R=c||!1},Hza=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.gs,sessionId:a.o.A,arrayId:a.o.ul}},Iza=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&Aza(a.o),wza(a.o));a.I=0},e7=function(a){return!!a.o&&3==a.o.o},Jza=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.rd(4,a))||"";b&&(this.port=":"+b);this.domain=g.sd(a)||"";a=g.Nc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.sc(a,"10.0")&&(this.u=!1))},g7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Cd(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.A,e),Oe:g.Qa(a.C,e)};c&&(a.Eb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.rq(b,a)},Nza=function(){var a=Kza;
Lza();i7.push(a);Mza(i7)},j7=function(a,b){Lza();
var c=i7,d=Oza(a,String(b));g.eb(c)?Pza(d):(Mza(c),(0,g.y)(c,function(e){e(d)}))},Lza=function(){i7||(i7=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",i7,void 0))},Pza=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},Mza=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},Oza=function(a,b){var c=((0,g.D)()-Qza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.N.call(this);
this.F=a;this.screens=[]},Rza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},Sza=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.ye)(a.screens,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Rza(a,b[d])||c;return c},Tza=function(a,b){var c=a.screens.length;
a.screens=(0,g.ye)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.N.call(this);
this.F=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ka=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;p7(this);this.info("Initializing with "+j6(this.screens))},Uza=function(a){if(a.screens.length){var b=(0,g.Fc)(a.screens,function(d){return d.id}),c=g7(a.u,"/pairing/get_lounge_token_batch");
h7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.YG,a),(0,g.x)(a.XG,a))}},p7=function(a){var b=Dya(Jya());
b=(0,g.ye)(b,function(c){return!c.uuid});
return Sza(a,b)},r7=function(a,b){Lya((0,g.Fc)(a.screens,Bya));
b&&Kya()},t7=function(a,b){g.N.call(this);
this.F=b;var c=g.Ts("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.db(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;s7("Initialized with "+g.Jk(this.o))},Vza=function(a,b,c){var d=g7(a.C,"/pairing/get_screen_availability");
h7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},u7=function(a,b){a:if(c6(b)!=c6(a.o))var c=!1;
else{c=g.Fb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Jk(a.o)),a.o=b,a.S("screenChange"));Wza(a)},v7=function(a){isNaN(a.A)||g.Jo(a.A);
a.A=g.Ho((0,g.x)(a.hw,a),0<a.B&&a.B<(0,g.D)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},Xza=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},Wza=function(a){a=g.Fb(g.zb(a.o,function(b){return b}));
g.ub(a);a.length?g.Ss("yt-remote-online-screen-ids",a.join(","),60):g.Us("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};Yza(this)},$za=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.He();if(h=(c?m6(h,c):null)||m6(h,b)){h.uuid=b;var l=x7(a,h);Vza(a.o,l,function(m){e(m?l:null)})}else c?Zza(a,c,(0,g.x)(function(m){var n=x7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));Vza(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},aAa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},Zza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Eb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.rq(g7(a.C,"/pairing/get_lounge_token_batch"),e)},bAa=function(a){a.screens=a.u.He();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.screens))},Yza=function(a){y7(a);
a.u=new q7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.gH,a));bAa(a);a.A=Dya(g.Ts("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+j6(a.A));a.o=new t7(a.C,(0,g.x)(a.He,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ss("yt-remote-automatic-screen-cache",(0,g.Fc)(a.A,Bya)));y7(a);a.B[b.uuid]=b.id;g.Ss("yt-remote-device-id-map",a.B,31536E3);return b},y7=function(a){a.B=g.Ts("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.N.call(this);
this.U=c;this.M=a;this.u=b;this.I=null},A7=function(a,b){j7(a.U,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.XP,this);this.B=(0,g.x)(this.pO,this);this.A=g.Ho((0,g.x)(function(){cAa(this,null)},this),12E4)},dAa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Jk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ia,(0,g.x)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Jk(b))},cAa=function(a,b){g.Jo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.jr,a),d=(0,g.x)(a.Ne,a);a.Fz(b,c,d,5)}}else a.Ne(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ia;this.C=NaN;this.R=(0,g.x)(this.aQ,this);this.o=g.Ia},eAa=function(a){a.o=a.M.NE(a.N,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ia;
this.jr(b)},a),(0,g.x)(function(b){this.o=g.Ia;
this.Ne(b)},a))},fAa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Nya()&&(b.env_useStageMdx=1);return g.Ad(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.Ho((0,g.x)(this.vl,this,null),150)},E7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.iN,this)},gAa=function(a,b){return b?g.ab(a.A,function(c){return h6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},Kza=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.C||!!a.A.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.Ke(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.IC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.vl(null)):a.S("yt-remote-cast2-session-change",null))},hAa=function(a){var b=a.u.ME(),c=a.o&&a.o.u;
a=(0,g.Fc)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=gAa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},nAa=function(a,b,c,d,e,f,h){iAa()?jAa(b,e,f,h)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?kAa(a,c):(window.__onGCastApiAvailable=function(l,m){l?kAa(a,c):(K7("Failed to load cast API: "+m),L7(!1),J7(!1),g.Us("yt-remote-cast-available"),g.Us("yt-remote-cast-receiver"),lAa(),c(!1))},d?g.To("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Uya():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(Tya(),t6(mAa.map(Rya))))):I7("Cannot initialize because not running Chrome")},lAa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);oAa(!1);g.Po(N7);N7.length=0},O7=function(){return!!g.Ts("yt-remote-cast-installed")},pAa=function(){var a=g.Ts("yt-remote-cast-receiver");
return a?a.friendlyName:null},qAa=function(){I7("clearCurrentReceiver");
g.Us("yt-remote-cast-receiver")},rAa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.Oo("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},iAa=function(){var a=0<=g.Nc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Kw||a},sAa=function(a,b){M7().init(a,b)},jAa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ss("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){I7("onReceiverSelected: "+f.friendlyName);
g.Ss("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){I7("onReceiverResumed: "+f.friendlyName);
g.Ss("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){I7("onSessionChange: "+i6(f));
f||g.Us("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},kAa=function(a,b){L7(!0);
J7(!1);sAa(a,function(c){c?(oAa(!0),g.Qo("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.Us("yt-remote-cast-available"),g.Us("yt-remote-cast-receiver"),lAa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.Ss("yt-remote-cast-installed",a)},P7=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},oAa=function(a){I7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.sg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.sg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.D)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},U7=function(a){return a.ob()?((0,g.D)()-a.F)/1E3:0},V7=function(a,b){a.G=b;
a.F=(0,g.D)()},W7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Qb(a.o);b.hasPrevious=a.sg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},$7=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new Fza;this.A=this.u=null;this.M=(0,g.x)(this.oL,this);this.G=(0,g.x)(this.Fn,this);this.I=(0,g.x)(this.nL,this);this.N=(0,g.x)(this.xL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.lx,this),tAa(this))):c=3;0!=c&&(b?this.lx(c):g.Ho((0,g.x)(function(){this.lx(c)},this),0));
var d=rAa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},a8=function(a){return new S7(a.B.getPlayerContextData())},tAa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Qa(this.fN,b),this))},a)},uAa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);c8(a,d)},e8=function(a,b,c){a.B.sendMessage(b,c)},c8=function(a,b){uAa(a);
a.B.setPlayerContextData(Y7(b));tAa(a)},Z7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Fn(null));
a.A=b;a.A&&(j7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Fn(a.A.media[0]))},vAa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.gb=this.o=null;this.Z=a;this.U.push(g.dp(window,"beforeunload",(0,g.x)(this.QG,this)));this.u=[];this.gb=new S7;this.T=b.id;this.o=wAa(this,c);this.o.subscribe("handlerOpened",this.sL,this);this.o.subscribe("handlerClosed",this.pL,this);this.o.subscribe("handlerError",this.qL,this);this.o.subscribe("handlerMessage",this.rL,this);Jza(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.gb.videoId;
g.Vs()&&g.Ss("yt-remote-session-video-id",d)},this)},h8=function(a){j7("conn",a)},wAa=function(a,b){return new d7(g7(a.Z,"/bc"),b)},i8=function(a,b){a.S("proxyStateChange",b)},xAa=function(a){a.C=g.Ho((0,g.x)(function(){h8("Connecting timeout");
this.Sk(1)},a),2E4)},j8=function(a){g.Jo(a.C);
a.C=NaN},k8=function(a){g.Jo(a.N);
a.N=NaN},yAa=function(a){l8(a);
a.M=g.Ho((0,g.x)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.Jo(a.M);
a.M=NaN},AAa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&isNaN(a.C))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.Dz()&&a.gb.reset(),i8(a,1),m8(a,"getNowPlaying"),zAa(a)):a.Sk(1)},BAa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.gb.videoId&&(g.Lb(b.params)?a.gb.o=null:a.gb.o=b.params,a.S("remotePlayerChange"))},CAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.gb.listId=b.params.listId||a.gb.listId;X7(a.gb,c,d);a.S("remoteQueueChange")},EAa=function(a,b){b.params=b.params||{};
CAa(a,b);DAa(a,b);a.S("autoplayDismissed")},DAa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.gb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.gb.playerState&&(c=-1E3);a.gb.playerState=c;c=Number(b.params.loadedTime);a.gb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.gb.I=isNaN(c)?0:c;c=a.gb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.gb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.gb.playerState?yAa(a):l8(a);a.S("remotePlayerChange")},FAa=function(a,b){if(-1E3!=
a.gb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.gb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.gb,isNaN(c)?0:c);a.S("remotePlayerChange")}},GAa=function(a,b){var c="true"==b.params.muted;
a.gb.volume=parseInt(b.params.volume,10);a.gb.muted=c;a.S("remotePlayerChange")},HAa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},IAa=function(a,b){var c="true"==b.params.hasNext;
a.gb.sg="true"==b.params.hasPrevious;a.gb.hasNext=c;a.S("previousNextChange")},zAa=function(a){g.Jo(a.I);
a.I=g.Ho((0,g.x)(a.Sk,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Jk(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.Jd=a;this.o=[];this.o.push(this.Jd.$_s("screenChange",(0,g.x)(this.VP,this)));this.o.push(this.Jd.$_s("onlineScreenChange",(0,g.x)(this.HM,this)))},NAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;Fya();q6();o8||(o8=new f7(b?b.loungeApiHost:void 0),Nya()&&(o8.o="/api/loungedev"));p8||(p8=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",p8,void 0));JAa();var c=q8();if(!c){var d=new w7(o8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);nAa(a,d,function(m){m?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Jk(b)),t8.push(g.Oo("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),t8.push(g.Oo("yt-remote-cast2-receiver-selected",function(){u8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.Oo("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.Oo("yt-remote-cast2-session-change",KAa)),t8.push(g.Oo("yt-remote-connection-change",function(m){m?R7(r8(),"YouTube TV"):v8()||(R7(null,null),qAa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.xo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),s8(" -- with channel params: "+
g.Jk(a)),LAa(a),c.start(),r8()||MAa())},PAa=function(){var a=OAa();
O7()&&g.Ts("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},OAa=function(){var a=q8().Jd.$_gos();
var b=x8();b&&y8()&&(l6(a,b)||a.push(b));return Eya(a)},z8=function(){var a=QAa();
!a&&O7()&&pAa()&&(a={key:"cast-selector-receiver",name:pAa()});return a},QAa=function(){var a=OAa(),b=x8();
b||(b=v8());return g.ab(a,function(c){return b&&h6(b,c.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().He();return m6(b,a)},KAa=function(a){s8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.Ha("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},RAa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},SAa=function(){return g.Ha("yt.mdx.remote.connectData_")},u8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.Ha("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||RAa("");g.Fa("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.y)(p8,function(c){c(a)}),p8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},v8=function(){var a=g.Vs();
if(!a)return null;var b=q8();if(!b)return null;b=b.He();return m6(b,a)},B8=function(a,b){r8();
x8()&&x8();if(F8)G8=a;else{RAa(a.id);var c=new g8(o8,a,w8());c.connect(b,SAa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){y8()&&(y8(),C8(null))});
C8(c)}},MAa=function(){var a=v8();
a?(s8("Resume connection to: "+i6(a)),B8(a,0)):(r6(),qAa(),s8("Skipping connecting because no session screen found."))},JAa=function(){var a=w8();
if(g.Lb(a)){a=p6();var b=g.Ts("yt-remote-session-name")||"",c=g.Ts("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},LAa=function(a){a?(g.Ss("yt-remote-session-app",a.app),g.Ss("yt-remote-session-name",a.name)):(g.Us("yt-remote-session-app"),g.Us("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},H8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.Xa=c;this.events=new g.Xr(this);this.M=this.events.L(this.H,"onVolumeChange",this.jC);this.B=!1;this.suggestion=null;this.C=new g.wC(64);this.o=new g.H(this.RD,500,this);this.u=new g.H(this.SD,1E3,this);this.G=new v6(this.BP,0,this);this.A={};this.I=new g.H(this.xE,1E3,this);this.F=new w6(this.seekTo,1E3,this);this.N=g.Ia;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.gM);this.events.L(b,"captionschanged",this.mL);this.events.L(b,"captionssettingschanged",
this.UD);this.events.L(b,"videoplayerreset",this.kr);this.events.L(b,"mdxautoplaycancel",function(){d.Xa.Ty()});
a=this.Xa;a.ha();a.subscribe("proxyStateChange",this.CC,this);a.subscribe("remotePlayerChange",this.Mn,this);a.subscribe("remoteQueueChange",this.kr,this);a.subscribe("previousNextChange",this.yC,this);a.subscribe("nowAutoplaying",this.uC,this);a.subscribe("autoplayDismissed",this.UB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.UD();this.kr();this.Mn()},TAa=function(a){a.hc(0);
a.o.stop();a.Mc(new g.wC(64))},J8=function(a,b){if(I8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Sb(c,b));a.Xa.KE(a.H.getVideoData(1).videoId,c);a.A=a8(a.Xa).o}},K8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.Xa.playVideo(c.videoId,b,d,e,c.playerParams,c.Kf,rya(c));a.Mc(new g.wC(1))},UAa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{dA:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},I8=function(a){return a8(a.Xa).videoId===a.H.getVideoData(1).videoId},L8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",W:"Nous allons bient\u00f4t supprimer la possibilit\u00e9 de se connecter \u00e0 un t\u00e9l\u00e9viseur via Internet \u00e0 l'aide d'un code"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"En savoir plus"},{D:"button",Y:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
W:"OK"}]}]}]});this.o=new g.PN(this,250);this.learnMoreButton=this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},M8=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",W:"Vous \u00eates d\u00e9connect\u00e9"},{D:"div",J:"ytp-mdx-popup-description",W:"Les vid\u00e9os que vous visionnez peuvent \u00eatre ajout\u00e9es \u00e0 l'historique des vid\u00e9os regard\u00e9es sur votre t\u00e9l\u00e9viseur et avoir une influence sur les recommandations qui vous sont faites. Pour \u00e9viter ce probl\u00e8me, annulez et connectez-vous \u00e0 YouTube sur un ordinateur."},
{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Annuler"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Confirmer"}]}]}]});this.o=new g.PN(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},N8=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.WL()]},{D:"div",J:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.PN(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);VAa(this,g.SL(a))},VAa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.wL("Erreur sur $RECEIVER_NAME",c):b.ob()||g.T(b,4)?g.wL("Lecture sur $RECEIVER_NAME",c):g.wL("Connect\u00e9 \u00e0 $RECEIVER_NAME",c);a.ma("statustext",c);a.o.show()}else a.o.hide()},O8=function(a,b){g.iR.call(this,"Lire sur",0,a,b);
this.H=a;this.Xi={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},P8=function(a){g.uN.call(this,a);
this.Pf={key:k6(),name:"Cet ordinateur"};this.De=null;this.subscriptions=[];this.Rv=this.Xa=null;this.Xi=[this.Pf];this.ai=this.Pf;this.Rb=new g.wC(64);this.uA=0;this.md=-1;this.xl=null;this.Nn=this.oq=!1;this.nk=this.Nl=null;if(!g.Dy(this.player.O())){a=this.player;var b=g.HM(a);b&&(b=b.Gj())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.gN(a,b.element,4);this.Nl=new M8;g.C(this,this.Nl);g.gN(a,this.Nl.element,4);g.Q(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.xl=new L8,g.C(this,this.xl),g.gN(a,this.xl.element,4));this.Nn=!!v8();this.oq=!!g.Ts("yt-remote-manual-pairing-warning-shown")}},Q8=function(a){a.nk&&(a.player.removeEventListener("presentingplayerstatechange",a.nk),a.nk=null)},WAa=function(a,b,c){a.Rb=c;
a.player.S("presentingplayerstatechange",new g.HC(c,b))},XAa=function(a,b,c){var d=!1;
1===b?d=!a.Nn:2===b&&(d=!a.oq);d&&g.JC(c,8)&&(a.player.pauseVideo(),Q8(a))},R8=function(a,b){if(b.key!==a.ai.key)if(b.key===a.Pf.key)A8();
else{if(a.xl&&!a.oq&&b!==a.Pf&&"cast-selector-receiver"!==b.key&&g.My(a.player.O()))YAa(a);else{var c;(c=!g.Q(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Nn||!a.Nl);(c?0:g.My(a.player.O())||g.Qy(a.player.O()))&&ZAa(a)}a.ai=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ca(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Kf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=rya(c))&&(d.locationInfo=c);c=d}s8("Connecting to: "+g.Jk(b));"cast-selector-receiver"==b.key?(u8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&D8()&&r8()==b.key?e6("yt-remote-connection-change",!0):(A8(),u8(c||null),c=q8().He(),(c=m6(c,b.key))&&B8(c,1))}},ZAa=function(a){g.SL(a.player).ob()?a.player.pauseVideo():(a.nk=function(b){XAa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.nk));
a.Nl&&a.Nl.Vb();y8()||(F8=!0)},YAa=function(a){g.SL(a.player).ob()?a.player.pauseVideo():(a.nk=function(b){XAa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.nk));
a.xl&&a.xl.Vb();y8()||(F8=!0)},cza={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},J6={"'":"\\'"},$Aa={},Aya={CQ:"atp",uT:"ska",fT:"que",uS:"mus",tT:"sus",AR:"dsp",mT:"seq"},s6,o6="",Sya=Oya("loadCastFramework")||Oya("loadCastApplicationFramework"),mAa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(v6,g.A);g.k=v6.prototype;g.k.NG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.D)()+this.Kd:this.Ka=g.Xf(this.C,this.Kd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();v6.uc.X.call(this)};
g.k.OG=function(){this.A?(this.Ka=g.Xf(this.C,this.A-(0,g.D)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(w6,g.A);g.k=w6.prototype;g.k.IA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:x6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,x6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};z6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
z6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};A6.prototype.o=null;A6.prototype.getOptions=function(){var a;(a=this.o)||(a={},Wya(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Sa(Vya,A6);S8=new Vya;g.k=B6.prototype;g.k.Jj=null;g.k.cg=!1;g.k.fm=null;g.k.ix=null;g.k.Rl=null;g.k.Wl=null;g.k.Vh=null;g.k.Yi=null;g.k.pk=null;g.k.dd=null;g.k.vo=0;g.k.hg=null;g.k.ks=null;g.k.ni=null;g.k.Wm=-1;g.k.HD=!0;g.k.qj=!1;g.k.pu=0;g.k.xr=null;var aza={},E6={};g.k=B6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.IO=function(a){a=a.target;var b=this.xr;b&&3==S6(a)?b.IA():this.HE(a)};
g.k.HE=function(a){try{if(a==this.dd)a:{var b=S6(this.dd),c=this.dd.F,d=this.dd.getStatus();if(g.le&&!g.Qd(10)||g.ne&&!g.Pd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.yh&&!U6(this.dd))break a;this.qj||4!=b||7==c||(8==c||0>=d?this.o.Uf(3):this.o.Uf(2));L6(this);var e=this.dd.getStatus();this.Wm=e;var f=U6(this.dd);(this.cg=200==e)?(4==b&&H6(this),this.F?(bza(this,b,f),g.yh&&this.cg&&3==b&&(this.B.na(this.u,"tick",this.CO),this.u.start())):G6(this,f),this.cg&&!this.qj&&(4==b?this.o.Np(this):(this.cg=
!1,D6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ni=3,F6(13)):(this.ni=0,F6(14)),H6(this),I6(this))}}catch(h){this.dd&&U6(this.dd)}finally{}};
g.k.CO=function(){var a=S6(this.dd),b=U6(this.dd);this.vo<b.length&&(L6(this),bza(this,a,b),this.cg&&4!=a&&D6(this))};
g.k.aO=function(a){K6((0,g.x)(this.ZN,this,a),0)};
g.k.ZN=function(a){this.qj||(L6(this),G6(this,a),D6(this))};
g.k.LC=function(a){K6((0,g.x)(this.YN,this,a),0)};
g.k.YN=function(a){this.qj||(H6(this),this.cg=a,this.o.Np(this),this.o.Uf(4))};
g.k.cancel=function(){this.qj=!0;H6(this)};
g.k.iO=function(){this.fm=null;var a=(0,g.D)();0<=a-this.ix?(2!=this.Wl&&this.o.Uf(3),H6(this),this.ni=2,F6(18),I6(this)):eza(this,this.ix-a)};
g.k.getLastError=function(){return this.ni};g.k=hza.prototype;g.k.nu=null;g.k.te=null;g.k.yr=!1;g.k.Nz=null;g.k.tp=null;g.k.Qu=null;g.k.ou=null;g.k.bf=null;g.k.rh=-1;g.k.Vm=null;g.k.wm=null;g.k.connect=function(a){this.ou=a;a=N6(this.o,null,this.ou);F6(3);this.Nz=(0,g.D)();var b=this.o.I;null!=b?(this.Vm=b[0],(this.wm=b[1])?(this.bf=1,iza(this)):(this.bf=2,P6(this))):(b6(a,"MODE","init"),this.te=new B6(this,void 0,void 0,void 0),this.te.Jj=this.nu,C6(this.te,a,!1,null,!0),this.bf=0)};
g.k.OF=function(a){if(a)this.bf=2,P6(this);else{F6(4);var b=this.o;b.rg=b.Yh.rh;a7(b,9)}a&&this.Uf(2)};
g.k.Gt=function(a){return this.o.Gt(a)};
g.k.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.rh=-1};
g.k.Mz=function(){return!1};
g.k.DC=function(a,b){this.rh=a.Wm;if(0==this.bf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.rg=this.rh;a7(c,2);return}this.Vm=c[0];this.wm=c[1]}else c=this.o,c.rg=this.rh,a7(c,2);else if(2==this.bf)if(this.yr)F6(7),this.Qu=(0,g.D)();else if("11111"==b){if(F6(6),this.yr=!0,this.tp=(0,g.D)(),c=this.tp-this.Nz,!g.le||g.Qd(10)||500>c)this.rh=200,this.te.cancel(),F6(12),O6(this.o,this,!0)}else F6(8),this.tp=this.Qu=(0,g.D)(),this.yr=!1};
g.k.Np=function(){this.rh=this.te.Wm;if(this.te.cg)0==this.bf?this.wm?(this.bf=1,iza(this)):(this.bf=2,P6(this)):2==this.bf&&((!g.le||g.Qd(10)?!this.yr:200>this.Qu-this.tp)?(F6(11),O6(this.o,this,!1)):(F6(12),O6(this.o,this,!0)));else{0==this.bf?F6(9):2==this.bf&&F6(10);var a=this.o;this.te.getLastError();a.rg=this.rh;a7(a,2)}};
g.k.fo=function(){return this.o.fo()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Uf=function(a){this.o.Uf(a)};g.Sa(Q6,g.lf);var nza=/^https?$/i,aBa=["POST","PUT"];g.k=Q6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ga=b;this.Z=!1;this.A=!0;this.o=this.T?Xya(this.T):Xya(S8);this.U=this.T?this.T.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.zC,this);try{d6(T6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){d6(T6(this,"Error opening Xhr: "+f.message));mza(this,f);return}a=
c||"";var e=this.headers.clone();d&&wya(d,function(f,h){e.set(h,f)});
d=g.ab(e.Ze(),kza);c=g.v.FormData&&a instanceof g.v.FormData;!g.db(aBa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{pza(this),0<this.G&&(this.R=jza(this.o),d6(T6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Oz,this)):this.N=g.Xf(this.Oz,this.G,this)),d6(T6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){d6(T6(this,"Send error: "+f.message)),mza(this,f)}};
g.k.Oz=function(){"undefined"!=typeof g.G1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,T6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(T6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),R6(this,!0));Q6.uc.X.call(this)};
g.k.zC=function(){this.ha()||(this.ba||this.I||this.C?oza(this):this.hN())};
g.k.hN=function(){oza(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<S6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=V6.prototype;g.k.Lm=null;g.k.ie=null;g.k.Dc=null;g.k.mu=null;g.k.xp=null;g.k.my=null;g.k.Mp=null;g.k.Dn=0;g.k.HK=0;g.k.Hd=null;g.k.fi=null;g.k.Zg=null;g.k.wj=null;g.k.Yh=null;g.k.gs=null;g.k.ul=-1;g.k.tA=-1;g.k.rg=-1;g.k.Xk=0;g.k.Jk=0;g.k.rj=8;var b7=new g.lf;g.Sa(rza,g.Me);g.Sa(sza,g.Me);g.Sa(tza,g.Me);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){F6(0);this.mu=b;this.Lm=c||{};d&&void 0!==e&&(this.Lm.OSID=d,this.Lm.OAID=e);this.F?(K6((0,g.x)(this.Fy,this,a),100),xza(this)):this.Fy(a)};
g.k.Fy=function(a){this.Yh=new hza(this);this.Yh.nu=null;this.Yh.u=this.C;this.Yh.connect(a)};
g.k.Mz=function(){return 0==this.o};
g.k.KC=function(a){this.fi=null;Aza(this,a)};
g.k.JC=function(){this.Zg=null;this.Dc=new B6(this,this.A,"rpc",this.G);this.Dc.Jj=null;this.Dc.pu=0;var a=this.my.clone();$5(a,"RID","rpc");$5(a,"SID",this.A);$5(a,"CI",this.gs?"0":"1");$5(a,"AID",this.ul);W6(this,a);if(!g.le||g.Qd(10))$5(a,"TYPE","xmlhttp"),C6(this.Dc,a,!0,this.Mp,!1);else{$5(a,"TYPE","html");var b=this.Dc,c=!!this.Mp;b.Wl=3;b.Vh=a6(a.clone());dza(b,c)}};
g.k.DC=function(a,b){if(0!=this.o&&(this.Dc==a||this.ie==a))if(this.rg=a.Wm,this.ie==a&&3==this.o)if(7<this.rj){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Zg){if(this.Dc)if(this.Dc.Rl+3E3<this.ie.Rl)Y6(this),this.Dc.cancel(),this.Dc=null;else break a;$6(this);F6(19)}}else this.tA=c[1],0<this.tA-this.ul&&37500>c[2]&&this.gs&&0==this.Jk&&!this.wj&&(this.wj=K6((0,g.x)(this.iL,this),6E3));else a7(this,11)}else b!=$Aa.ZQ.o&&a7(this,11);else if(this.Dc==
a&&Y6(this),!g.hc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ul=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Mp=e[2],e=e[3],null!=e?this.rj=e:this.rj=6,this.o=3,this.Hd&&this.Hd.Ay(),this.my=N6(this,this.fo()?this.Mp:null,this.mu),Bza(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Hd&&this.Hd.zy(e),this.Jk=0)}}};
g.k.iL=function(){null!=this.wj&&(this.wj=null,this.Dc.cancel(),this.Dc=null,$6(this),F6(20))};
g.k.Np=function(a){if(this.Dc==a){Y6(this);this.Dc=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.rg=a.Wm;if(0!=this.o)if(a.cg)1==b?(b=(0,g.D)()-a.Rl,b7.dispatchEvent(new sza(b7,a.pk?a.pk.length:0,b,this.Xk)),X6(this),this.B.length=0):Bza(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.rg)){if(d=1==b)this.ie||this.fi||1==this.o||2<=this.Xk?d=!1:(this.fi=K6((0,g.x)(this.KC,this,a),Cza(this,this.Xk)),this.Xk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.mG=function(a){if(!g.db(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.tP=function(a){a?F6(2):(F6(1),Dza(this,8))};
g.k.Gt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new Q6;a.aa=!1;return a};
g.k.isActive=function(){return!!this.Hd&&this.Hd.isActive(this)};
g.k.Uf=function(a){b7.dispatchEvent(new tza(b7,a))};
g.k.fo=function(){return!(!g.le||g.Qd(10))};
g.k=Eza.prototype;g.k.Ay=function(){};
g.k.zy=function(){};
g.k.yy=function(){};
g.k.ot=function(){};
g.k.kz=function(){return{}};
g.k.isActive=function(){return!0};g.k=Fza.prototype;g.k.isEmpty=function(){return g.eb(this.o)&&g.eb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.db(this.o,a)||g.db(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.mta)(b,a);0<=c?(g.gb(b,c),b=!0):b=!1;return b||g.ib(this.u,a)};
g.k.Rd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Sa(c7,g.A);g.k=c7.prototype;g.k.TN=function(){this.Kd=Math.min(3E5,2*this.Kd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Kd+15E3*Math.random();this.o.eb(a);this.u=(0,g.D)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Kd=5E3};g.Sa(d7,Eza);g.k=d7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ni=function(a){return this.A.Kj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Ob||(this.Ob=!0,g.Ke(this.A),Iza(this),g.Ke(this.u),this.u=null)};
g.k.ha=function(){return this.Ob};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Hd=null);d.Hd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.ul):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Sb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&yza(this.o,c)};
g.k.Ay=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)yza(this.o,a[b])}this.S("handlerOpened")};
g.k.yy=function(a){var b=2==a&&401==this.o.rg;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.ot=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.kz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Sb(a,this.C);return a};
g.k.zy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),wza(this.o)):this.S("handlerMessage",new Gza(a[0],a[1]))};
g.k.WO=function(){this.u.isActive();var a=this.o,b=0;a.Dc&&b++;a.ie&&b++;0==b&&this.connect(this.C,this.B)};f7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.C=function(a){a(Error("request timed out"))};var Qza=(0,g.D)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Sa(n7,g.N);n7.prototype.He=function(){return this.screens};
n7.prototype.contains=function(a){return!!l6(this.screens,a)};
n7.prototype.get=function(a){return a?m6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.F,a)};g.t(o7,g.N);g.k=o7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.LE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.Jo(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.LE=function(){this.Ka=NaN;this.o=g.rq(g7(this.F,"/pairing/get_screen"),{method:"POST",Eb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.TP,this),onError:(0,g.x)(this.SP,this),Oe:(0,g.x)(this.UP,this)})};
g.k.TP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new g6(c))};
g.k.SP=function(a){this.o=null;a.status&&404==a.status?this.u>=bBa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=bBa[this.u],this.Ka=g.Ho((0,g.x)(this.LE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.UP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var bBa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.S("screenChange");!g.Ts("yt-remote-lounge-token-expiration")&&Uza(this);g.Jo(this.o);this.o=g.Ho((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);Rza(this,a);r7(this,!1);this.S("screenChange");b(a);a.token||Uza(this)};
g.k.remove=function(a,b){var c=p7(this);Tza(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.Zr=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.Jo(this.o);q7.uc.X.call(this)};
g.k.YG=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.F,"Missed "+b+" lounge tokens.")};
g.k.XG=function(a){j7(this.F,"Requesting lounge tokens failed: "+a)};g.t(t7,g.N);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.Ts("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.D)()-144E5<a?0:a)?v7(this):(this.B=(0,g.D)()+3E5,g.Ss("yt-remote-fast-check-period",this.B),this.hw())};
g.k.isEmpty=function(){return g.Lb(this.o)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.zb(this.o,function(c,d){return c&&!!m6(a,d)},this);
u7(this,b)};
g.k.X=function(){g.Jo(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.hw=function(){g.Jo(this.A);this.A=NaN;this.u&&this.u.abort();var a=Xza(this);if(c6(a)){var b=g7(this.C,"/pairing/get_screen_availability");this.u=h7(this.C,b,{lounge_token:g.Fb(a).join(",")},(0,g.x)(this.DN,this,a),(0,g.x)(this.CN,this))}else u7(this,{}),v7(this)};
g.k.DN=function(a,b){this.u=null;var c=g.Fb(Xza(this));if(g.vb(c,g.Fb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.pc("Changing Screen set during request."),this.hw()};
g.k.CN=function(a){this.pc("Screen availability failed: "+a);this.u=null;v7(this)};
g.k.pc=function(a){j7("OnlineScreenService",a)};g.Sa(w7,n7);g.k=w7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.Zr=function(a,b,c,d){this.u.contains(a)?this.u.Zr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.F,a),d(Error(a)))};
g.k.He=function(a){return a?this.screens:g.kb(this.screens,(0,g.ye)(this.A,function(b){return!this.contains(b)},this))};
g.k.ME=function(){return(0,g.ye)(this.He(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.NE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Ke(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Ke(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.WP=function(a,b,c,d){g.rq(g7(this.C,"/pairing/get_screen"),{method:"POST",Eb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new g6(f.screen||{});if(!h.name||aAa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);aAa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Oe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Ke(this.u);g.Ke(this.o);w7.uc.X.call(this)};
g.k.gH=function(){bAa(this);this.S("screenChange");this.o.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Sa(z7,g.N);g.k=z7.prototype;g.k.getScreen=function(){return this.I};
g.k.jr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Ne=function(a){this.ha()||(a&&A7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){j7(this.U,a)};
g.k.PE=function(){return null};
g.k.rw=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.rw("");z7.uc.X.call(this)};g.t(B7,z7);g.k=B7.prototype;g.k.qw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);dAa(this)};
g.k.vl=function(a){this.info("launchWithParams no-op for Cast: "+g.Jk(a))};
g.k.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Ne()},this),(0,g.x)(function(){this.Ne(Error("Failed to stop receiver app."))},this)):this.Ne(Error("Stopping cast device witout session."))};
g.k.rw=function(){};
g.k.X=function(){this.info("disposeInternal");g.Jo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;z7.prototype.X.call(this)};
g.k.pO=function(a,b){if(!this.ha())if(b){var c=y6(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Jk(c));switch(d){case "mdxSessionStatus":cAa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.Fz=function(a,b,c,d){$za(this.M,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ho((0,g.x)(this.Fz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.PE=function(){return this.o};
g.k.XP=function(a){this.ha()||a||(A7(this,"Cast session died."),this.Ne())};g.t(C7,z7);g.k=C7.prototype;g.k.qw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.vl=function(a){this.B=a;this.F()};
g.k.stop=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A?this.A.stop((0,g.x)(this.Ne,this,null),(0,g.x)(this.Ne,this,"Failed to stop DIAL device.")):this.Ne()};
g.k.X=function(){this.o();this.o=g.Ia;g.Jo(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;z7.prototype.X.call(this)};
g.k.aQ=function(a){this.ha()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.Ia,this.Ne())};
g.k.Bu=function(a){this.N=k6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,fAa(this));a(b);eAa(this)}else this.F=(0,g.x)(function(){g.Jo(this.C);this.F=g.Ia;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,fAa(this));a(c);eAa(this)},this),this.C=g.Ho((0,g.x)(function(){this.F()},this),100)};
g.k.BH=function(a,b,c){$za(this.M,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.jr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Bu(b,c)},this),(0,g.x)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Bu(b,c)},this))};g.t(D7,z7);D7.prototype.stop=function(){this.Ne()};
D7.prototype.qw=function(){};
D7.prototype.vl=function(){g.Jo(this.o);this.o=NaN;var a=m6(this.M.He(),this.u.label);a?this.jr(a):this.Ne(Error("No such screen"))};
D7.prototype.X=function(){g.Jo(this.o);this.o=NaN;z7.prototype.X.call(this)};g.t(E7,g.N);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.mN,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.GC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.EL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),Nza(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.OE,this)),this.A=hAa(this),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.x)(function(h){this.pc("Failed to set initial custom receivers: "+g.Jk(h))},this)),this.S("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.x)(function(h){this.pc("Failed to initialize API: "+g.Jk(h));
b(!1)},this))};
g.k.dP=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.u.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=m6(this.u.He(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=gAa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ia,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.Jk(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.u,d),!0)}this.o.rw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.eP=function(a){this.ha()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.vl(a):this.pc("Setting connection data without a session")};
g.k.ZP=function(){this.ha()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.GC,this),(0,g.x)(this.GN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.OE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=Kza,b=g.Ha("yt.mdx.remote.debug.handlers_");g.ib(b||[],a);g.Ke(this.o);g.N.prototype.X.call(this)};
g.k.pc=function(a){j7("Controller",a)};
g.k.IC=function(a,b){this.o==a&&(b||H7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.iN=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.k.EL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return F7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.BH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Bu,b))};
g.k.GC=function(a){if(!this.ha()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=m6(this.u.He(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ke(this.o),this.o=new B7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.IC,this,this.o)),this.o.vl(null));this.o.qw(a)}}};
g.k.YP=function(){return this.o?this.o.PE():null};
g.k.GN=function(a){this.ha()||(this.pc("Failed to estabilish a session: "+g.Jk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.mN=function(a){F7("Receiver availability updated: "+a);if(!this.ha()){var b=G7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.S("yt-remote-cast2-availability-change",G7(this))}};
g.k.OE=function(){this.ha()||(this.A=hAa(this),F7("Updating custom receivers: "+g.Jk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ia,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.eP;E7.prototype.setConnectedScreenStatus=E7.prototype.dP;E7.prototype.stopSession=E7.prototype.ZP;E7.prototype.getCastSession=E7.prototype.YP;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.sg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.ob=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.t($7,g.N);g.k=$7.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ia,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ia,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.S("remotePlayerChange")):b8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ob()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ia,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.S("remotePlayerChange")}else b8(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ia,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.S("remotePlayerChange")}else b8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Qa(this.setVolume,a,b))};
g.k.KE=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Jk(b.style),g.Sb(d,c.o));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Qa(this.KE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();e8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;c8(this,d)}else b8(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Jk(h));e8(this,"setPlaylist",m);d||c8(this,l)};
g.k.tr=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Qa(this.tr,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Qa(this.nextVideo,a,b))};
g.k.Ty=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Ty)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){uAa(this);this.B=null;this.C.clear();Z7(this,null);g.N.prototype.X.call(this)};
g.k.lx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.eb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.fN=function(a,b){this.S(a,b)};
g.k.oL=function(a){if(!a)this.Fn(null),Z7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.k.Fn=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),vAa(this),this.S("remotePlayerChange")};
g.k.nL=function(a){a?(vAa(this),this.S("remotePlayerChange")):this.Fn(null)};
g.k.Mw=function(){e8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.xL=function(){var a=rAa();a&&Z7(this,a)};
g.k.pc=function(a){j7("CP",a)};g.t(g8,g.N);g.k=g8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.gb.listId=c);this.gb.videoId=d;this.gb.index=h||0;this.gb.state=3;V7(this.gb,m);this.B="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Jk(l));this.o.connect({method:"setPlaylist",
params:g.Jk(l)},a,Iya())}else h8("Connecting without params"),this.o.connect({},a,Iya());xAa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),i8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){j8(this);l8(this);k8(this);g.Jo(this.G);this.G=NaN;g.Jo(this.I);this.I=NaN;this.A=null;g.ep(this.U);this.U.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.gb=this.o=null};
g.k.QG=function(){this.Sk(2)};
g.k.sL=function(){h8("Channel opened");this.R&&(this.R=!1,k8(this),this.N=g.Ho((0,g.x)(function(){h8("Timing out waiting for a screen.");this.Sk(1)},this),15E3));
Mya(Hza(this.o),this.T)};
g.k.pL=function(){h8("Channel closed");isNaN(this.C)?r6(!0):r6();this.dispose()};
g.k.qL=function(a){r6();isNaN(this.Rm())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,h8("Channel error: "+a+" with reconnection in "+this.Rm()+" ms"),i8(this,2))};
g.k.rL=function(a){a.params?h8("Received: action="+a.action+", params="+g.Jk(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=y6(a.params.devices);this.u=(0,g.Fc)(a,function(c){return new f6(c)});
a=!!g.ab(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
AAa(this,a);break;case "loungeScreenDisconnected":g.jb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
AAa(this,!1);break;case "remoteConnected":var b=new f6(y6(a.params.device));g.ab(this.u,function(c){return b?c.id==b.id:!1})||sya(this.u,b);
break;case "remoteDisconnected":b=new f6(y6(a.params.device));g.jb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":CAa(this,a);break;case "nowPlaying":EAa(this,a);break;case "onStateChange":DAa(this,a);break;case "onAdStateChange":FAa(this,a);break;case "onVolumeChanged":GAa(this,a);break;case "onSubtitlesTrackChanged":BAa(this,a);break;case "nowAutoplaying":HAa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":IAa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.k.SO=function(){if(this.A){var a=this.A;this.A=null;this.gb.videoId!=a&&m8(this,"getNowPlaying")}};
g.k.HG=function(){var a=3;this.ha()||(a=0,isNaN(this.Rm())?e7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Sk=function(a){h8("Disconnecting with "+a);j8(this);this.S("beforeDisconnect",a);1==a&&r6();Iza(this.o,a);this.dispose()};
g.k.FG=function(){var a=this.gb;this.A&&(a=this.gb.clone(),X7(a,this.A,a.index));return Y7(a)};
g.k.fP=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.gb.videoId&&(this.A=b.videoId,g.Jo(this.G),this.G=g.Ho((0,g.x)(this.SO,this),5E3));var c=[];this.gb.listId==b.listId&&this.gb.videoId==b.videoId&&this.gb.index==b.index||c.push("remoteQueueChange");this.gb.playerState==b.playerState&&this.gb.volume==b.volume&&this.gb.muted==b.muted&&W7(this.gb)==W7(b)&&g.Jk(this.gb.o)==g.Jk(b.o)||c.push("remotePlayerChange");this.gb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.Dz=function(){var a=this.o.F.id,b=g.ab(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Rm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.D)():NaN};
g.k.uG=function(){return this.B||"UNSUPPORTED"};
g.k.vG=function(){return this.F||""};
g.k.RP=function(){if(!isNaN(this.Rm())){var a=this.o.u;g.vn(a.o);a.start()}};
g.k.aP=function(a,b){m8(this,a,b);zAa(this)};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.Ni;g8.prototype.getProxyState=g8.prototype.HG;g8.prototype.disconnect=g8.prototype.Sk;g8.prototype.getPlayerContextData=g8.prototype.FG;g8.prototype.setPlayerContextData=g8.prototype.fP;g8.prototype.getOtherConnectedRemoteId=g8.prototype.Dz;g8.prototype.getReconnectTimeout=g8.prototype.Rm;g8.prototype.getAutoplayMode=g8.prototype.uG;g8.prototype.getAutoplayVideoId=g8.prototype.vG;g8.prototype.reconnect=g8.prototype.RP;
g8.prototype.sendMessage=g8.prototype.aP;g.t(n8,n7);g.k=n8.prototype;g.k.He=function(a){return this.Jd.$_gs(a)};
g.k.contains=function(a){return!!this.Jd.$_c(a)};
g.k.get=function(a){return this.Jd.$_g(a)};
g.k.start=function(){this.Jd.$_st()};
g.k.add=function(a,b,c){this.Jd.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Jd.$_r(a,b,c)};
g.k.Zr=function(a,b,c,d){this.Jd.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Jd.$_ubk(this.o[a]);this.o.length=0;this.Jd=null;n7.prototype.X.call(this)};
g.k.VP=function(){this.S("screenChange")};
g.k.HM=function(){this.S("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.WP;w7.prototype.$_gsppc=w7.prototype.NE;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Zr;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.He;w7.prototype.$_gos=w7.prototype.ME;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.Ni;var G8=null,F8=!1,o8=null,p8=null,E8=null,t8=[];g.t(H8,g.A);g.k=H8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.Xa;a.unsubscribe("proxyStateChange",this.CC,this);a.unsubscribe("remotePlayerChange",this.Mn,this);a.unsubscribe("remoteQueueChange",this.kr,this);a.unsubscribe("previousNextChange",this.yC,this);a.unsubscribe("nowAutoplaying",this.uC,this);a.unsubscribe("autoplayDismissed",this.UB,this);this.Xa=this.module=null};
g.k.ZA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Xa.o)if(I8(this)){if(!a8(this.Xa).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.Xa).ob()?this.Xa.pause():this.Xa.play();break;case "control_play":this.Xa.play();break;case "control_pause":this.Xa.pause();break;case "control_seek":this.F.IA(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();K8(this,0===c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.mL=function(a){this.G.NG(a)};
g.k.BP=function(a){this.ZA("control_subtitles_set_track",g.Lb(a)?null:a)};
g.k.UD=function(){var a=this.H.getOption("captions","track");g.Lb(a)||J8(this,a)};
g.k.hc=function(a){this.module.hc(a,this.H.getVideoData().lengthSeconds)};
g.k.jC=function(a){if(I8(this)){this.Xa.unsubscribe("remotePlayerChange",this.Mn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.Xa);if(b!==c.volume||a!==c.muted)this.Xa.setVolume(b,a),this.I.start();this.Xa.subscribe("remotePlayerChange",this.Mn,this)}};
g.k.gM=function(){g.Lb(this.A)||UAa(this,this.A);this.B=!1};
g.k.CC=function(a,b){this.u.stop();2===b&&this.SD()};
g.k.Mn=function(){if(I8(this)){this.o.stop();var a=a8(this.Xa);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.md=1;break;case 1082:case 1083:this.module.md=0;break;default:this.module.md=-1}switch(a.playerState){case 1081:case 1:this.Mc(new g.wC(8));this.RD();break;case 1085:case 3:this.Mc(new g.wC(9));break;case 1083:case 0:this.Mc(new g.wC(2));this.F.stop();this.hc(this.H.getVideoData().lengthSeconds);break;case 1084:this.Mc(new g.wC(4));break;case 2:this.Mc(new g.wC(4));
this.hc(W7(a));break;case -1:this.Mc(new g.wC(64));break;case -1E3:this.Mc(new g.wC(128,{errorCode:"mdx.remoteerror",errorMessage:"Cette vid\u00e9o ne peut pas \u00eatre visionn\u00e9e \u00e0 distance."}))}a=a8(this.Xa).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,UAa(this,a));a=a8(this.Xa);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.xE()}else TAa(this)};
g.k.yC=function(){this.H.S("mdxpreviousnextchange")};
g.k.kr=function(){I8(this)||TAa(this)};
g.k.uC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.UB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){I8(this)&&this.Xa.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.Xa).playerState?K8(this,a):b&&this.Xa.seekTo(a)};
g.k.xE=function(){if(I8(this)){var a=a8(this.Xa);this.events.nb(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.jC)}};
g.k.RD=function(){this.o.stop();if(!this.Xa.ha()){var a=a8(this.Xa);a.ob()&&this.Mc(new g.wC(8));this.hc(W7(a));this.o.start()}};
g.k.SD=function(){this.u.stop();this.o.stop();var a=this.Xa.B.getReconnectTimeout();2==this.Xa.o&&!isNaN(a)&&this.u.start()};
g.k.Mc=function(a){this.u.stop();var b=this.C;if(!g.CC(b,a)){var c=g.T(a,2);c!==g.T(this.C,2)&&g.xT(this.H.app,c);this.C=a;WAa(this.module,b,a)}};g.t(L8,g.U);L8.prototype.Vb=function(){this.o.show()};
L8.prototype.Ra=function(){this.o.hide()};
L8.prototype.u=function(){g.WN("https://support.google.com/youtube/answer/7640706")};
L8.prototype.A=function(){e6("mdx-manual-pairing-popup-ok");this.Ra()};g.t(M8,g.U);M8.prototype.Vb=function(){this.o.show()};
M8.prototype.Ra=function(){this.o.hide()};
M8.prototype.u=function(){e6("mdx-privacy-popup-cancel");this.Ra()};
M8.prototype.A=function(){e6("mdx-privacy-popup-confirm");this.Ra()};g.t(N8,g.U);N8.prototype.u=function(a){VAa(this,a.state)};g.t(O8,g.iR);O8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Xi=g.xb(a,this.o,this),g.kR(this,(0,g.Fc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Mb(this.o(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.o=function(a){return a.key};
O8.prototype.Sf=function(a){return"cast-selector-receiver"===a?"Caster sur\u2026":this.Xi[a].name};
O8.prototype.xd=function(a){g.iR.prototype.xd.call(this,a);this.H.setOption("remote","currentReceiver",this.Xi[a]);this.Ma.Ra()};g.t(P8,g.uN);g.k=P8.prototype;
g.k.create=function(){NAa(g.sy(this.player.O()));this.subscriptions.push(g.Oo("yt-remote-before-disconnect",this.kL,this));this.subscriptions.push(g.Oo("yt-remote-connection-change",this.nN,this));this.subscriptions.push(g.Oo("yt-remote-receiver-availability-change",this.AC,this));this.subscriptions.push(g.Oo("yt-remote-auto-connect",this.lN,this));this.subscriptions.push(g.Oo("yt-remote-receiver-resumed",this.kN,this));this.subscriptions.push(g.Oo("mdx-privacy-popup-confirm",this.GO,this));this.subscriptions.push(g.Oo("mdx-privacy-popup-cancel",
this.FO,this));this.subscriptions.push(g.Oo("mdx-manual-pairing-popup-ok",this.UH,this));this.AC()};
g.k.load=function(){this.player.cancelPlayback();g.uN.prototype.load.call(this);this.De=new H8(this,this.player,this.Xa);var a=(a=SAa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.hc(a);WAa(this,this.Rb,this.Rb);g.ET(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.ai=this.Pf;g.Le(this.De,this.Xa);this.Xa=this.De=null;g.uN.prototype.unload.call(this);g.ET(this.player.app,5);Q8(this)};
g.k.X=function(){g.Po(this.subscriptions);g.uN.prototype.X.call(this)};
g.k.Hg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.De.ZA.apply(this.De,[a].concat(g.ka(c)))};
g.k.getAdState=function(){return this.md};
g.k.JG=function(){return this.loaded?this.De.suggestion:null};
g.k.sg=function(){return this.Xa?a8(this.Xa).sg:!1};
g.k.hasNext=function(){return this.Xa?a8(this.Xa).hasNext:!1};
g.k.hc=function(a,b){this.uA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.uA};
g.k.getProgressState=function(){var a=a8(this.Xa),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ld():!a.isAdPlaying()&&this.player.ld(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+U7(a):a.B,isAtLiveHead:1>=(a.A?a.u+U7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+U7(a):a.u,seekableStart:0<a.C?a.C+
U7(a):a.C}};
g.k.nextVideo=function(){this.Xa&&this.Xa.nextVideo()};
g.k.tr=function(){this.Xa&&this.Xa.tr()};
g.k.kL=function(a){1===a&&(this.Rv=this.Xa?a8(this.Xa):null)};
g.k.nN=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.ai;this.loaded&&this.unload();this.Xa=a;this.Rv=null;b.key!==this.Pf.key&&(this.ai=b,this.load())}else g.Ke(this.Xa),this.Xa=null,this.loaded&&(this.unload(),(a=this.Rv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.AC=function(){this.Xi=[this.Pf].concat(PAa());var a=z8()||this.Pf;R8(this,a);this.player.ra("onMdxReceiversChange")};
g.k.lN=function(){var a=z8();R8(this,a)};
g.k.kN=function(){this.ai=z8()};
g.k.GO=function(){this.Nn=!0;Q8(this);F8=!1;G8&&B8(G8,1);G8=null};
g.k.FO=function(){this.Nn=!1;Q8(this);R8(this,this.Pf);this.ai=this.Pf;F8=!1;G8=null;this.player.playVideo()};
g.k.UH=function(){this.oq=!0;Q8(this);g.Ss("yt-remote-manual-pairing-warning-shown",!0,2592E3);F8=!1;G8&&B8(G8,1);G8=null};
g.k.gd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Xi;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():R8(this,b)),this.loaded?this.ai:this.Pf;case "quickCast":return 2===this.Xi.length&&"cast-selector-receiver"===this.Xi[1].key?(b&&Q7(),!0):!1}};
g.k.Mw=function(){this.Xa.Mw()};
g.k.ag=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.FN.remote=P8;})(_yt_player);
