gapi.loaded_1(function(_){var window=this;
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.jh=function(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}return b};
var kh,lh,nh;kh={};lh=null;_.mh=_.Bc||_.Cc&&!_.ih||_.xc||!_.ih&&!_.yc&&"function"==typeof _.C.atob;_.oh=function(a,b){void 0===b&&(b=0);nh();b=kh[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],f=d+1<a.length,g=f?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2;e=(e&3)<<4|g>>4;g=(g&15)<<2|l>>6;l&=63;k||(l=64,f||(g=64));c.push(b[m],b[e],b[g]||"",b[l]||"")}return c.join("")};
_.ph=function(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),n=lh[m];if(null!=n)return n;if(!_.Hb(m))throw Error("v`"+m);}return l}nh();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|f>>4);64!=g&&(b(f<<4&240|g>>2),64!=k&&b(g<<6&192|k))}};
nh=function(){if(!lh){lh={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));kh[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===lh[f]&&(lh[f]=e)}}}};

_.Ih={};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Kh;_.Jh=function(a){this.ob=a||{cookie:""}};_.h=_.Jh.prototype;_.h.isEnabled=function(){if(!_.C.navigator.cookieEnabled)return!1;if(!this.isEmpty())return!0;this.set("TESTCOOKIESENABLED","1",{kC:60});if("1"!==this.get("TESTCOOKIESENABLED"))return!1;this.remove("TESTCOOKIESENABLED");return!0};
_.h.set=function(a,b,c){var d=!1;if("object"===typeof c){var e=c.Fba;d=c.secure||!1;var f=c.domain||void 0;var g=c.path||void 0;var k=c.kC}if(/[;=\s]/.test(a))throw Error("y`"+a);if(/[;\r\n]/.test(b))throw Error("z`"+b);void 0===k&&(k=-1);this.ob.cookie=a+"="+b+(f?";domain="+f:"")+(g?";path="+g:"")+(0>k?"":0==k?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*k)).toUTCString())+(d?";secure":"")+(null!=e?";samesite="+e:"")};
_.h.get=function(a,b){for(var c=a+"=",d=(this.ob.cookie||"").split(";"),e=0,f;e<d.length;e++){f=(0,_.Ib)(d[e]);if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};_.h.remove=function(a,b,c){var d=this.Pd(a);this.set(a,"",{kC:0,path:b,domain:c});return d};_.h.re=function(){return Kh(this).keys};_.h.Vc=function(){return Kh(this).values};_.h.isEmpty=function(){return!this.ob.cookie};_.h.Gb=function(){return this.ob.cookie?(this.ob.cookie||"").split(";").length:0};
_.h.Pd=function(a){return void 0!==this.get(a)};_.h.Vj=function(a){for(var b=Kh(this).values,c=0;c<b.length;c++)if(b[c]==a)return!0;return!1};_.h.clear=function(){for(var a=Kh(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};Kh=function(a){a=(a.ob.cookie||"").split(";");for(var b=[],c=[],d,e,f=0;f<a.length;f++)e=(0,_.Ib)(a[f]),d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
_.Lh=new _.Jh("undefined"==typeof document?null:document);

_.Wh={};_.Xh=function(a){return _.Wh[a||"token"]||null};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Di;_.Bi=function(a,b){b=(0,_.Ya)(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.Ci=function(a){a&&"function"==typeof a.Ca&&a.Ca()};Di=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};_.Ei=function(a){for(var b in a)return!1;return!0};_.Fi=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};
_.Gi=function(){this.Uf=this.Uf;this.mm=this.mm};_.Gi.prototype.Uf=!1;_.Gi.prototype.Ac=function(){return this.Uf};_.Gi.prototype.Ca=function(){this.Uf||(this.Uf=!0,this.na())};_.Ii=function(a,b){_.Hi(a,_.wi(_.Ci,b))};_.Hi=function(a,b){a.Uf?b():(a.mm||(a.mm=[]),a.mm.push(b))};_.Gi.prototype.na=function(){if(this.mm)for(;this.mm.length;)this.mm.shift()()};
_.Ji=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Mr=!1};_.Ji.prototype.stopPropagation=function(){this.Mr=!0};_.Ji.prototype.preventDefault=function(){this.defaultPrevented=!0};
var Ki=function(){if(!_.C.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{_.C.addEventListener("test",_.ab,b),_.C.removeEventListener("test",_.ab,b)}catch(c){}return a}();
_.Li=function(a,b){_.Ji.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.XC=!1;this.pointerId=0;this.pointerType="";this.Qd=null;a&&this.wc(a,b)};_.Va(_.Li,_.Ji);var Mi={2:"touch",3:"pen",4:"mouse"};
_.Li.prototype.wc=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?_.Bc&&(_.vc(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=_.Cc||void 0!==
a.offsetX?a.offsetX:a.layerX,this.offsetY=_.Cc||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.XC=_.Ec?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||
0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Mi[a.pointerType]||"";this.state=a.state;this.Qd=a;a.defaultPrevented&&_.Li.O.preventDefault.call(this)};_.Li.prototype.stopPropagation=function(){_.Li.O.stopPropagation.call(this);this.Qd.stopPropagation?this.Qd.stopPropagation():this.Qd.cancelBubble=!0};_.Li.prototype.preventDefault=function(){_.Li.O.preventDefault.call(this);var a=this.Qd;a.preventDefault?a.preventDefault():a.returnValue=!1};
_.Ni="closure_listenable_"+(1E6*Math.random()|0);_.Oi=function(a){return!(!a||!a[_.Ni])};
var Pi=0;
var Qi=function(a,b,c,d,e){this.listener=a;this.Sw=null;this.src=b;this.type=c;this.capture=!!d;this.Oe=e;this.key=++Pi;this.Sr=this.Lt=!1},Ri=function(a){a.Sr=!0;a.listener=null;a.Sw=null;a.src=null;a.Oe=null};
var Si=function(a){this.src=a;this.Jd={};this.Ns=0};Si.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.Jd[f];a||(a=this.Jd[f]=[],this.Ns++);var g=Ti(a,b,d,e);-1<g?(b=a[g],c||(b.Lt=!1)):(b=new Qi(b,this.src,f,!!d,e),b.Lt=c,a.push(b));return b};Si.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.Jd))return!1;var e=this.Jd[a];b=Ti(e,b,c,d);return-1<b?(Ri(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.Jd[a],this.Ns--),!0):!1};
var Ui=function(a,b){var c=b.type;if(!(c in a.Jd))return!1;var d=_.Bi(a.Jd[c],b);d&&(Ri(b),0==a.Jd[c].length&&(delete a.Jd[c],a.Ns--));return d};Si.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.Jd)if(!a||c==a){for(var d=this.Jd[c],e=0;e<d.length;e++)++b,Ri(d[e]);delete this.Jd[c];this.Ns--}return b};Si.prototype.Gn=function(a,b,c,d){a=this.Jd[a.toString()];var e=-1;a&&(e=Ti(a,b,c,d));return-1<e?a[e]:null};
Si.prototype.hasListener=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Di(this.Jd,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var Ti=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Sr&&f.listener==b&&f.capture==!!c&&f.Oe==d)return e}return-1};
var Vi,Wi,Xi,aj,cj,dj,ej,hj;Vi="closure_lm_"+(1E6*Math.random()|0);Wi={};Xi=0;_.Zi=function(a,b,c,d,e){if(d&&d.once)return _.Yi(a,b,c,d,e);if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Zi(a,b[f],c,d,e);return null}c=_.$i(c);return _.Oi(a)?a.U(b,c,_.$a(d)?!!d.capture:!!d,e):aj(a,b,c,!1,d,e)};
aj=function(a,b,c,d,e,f){if(!b)throw Error("A");var g=_.$a(e)?!!e.capture:!!e,k=_.bj(a);k||(a[Vi]=k=new Si(a));c=k.add(b,c,d,g,f);if(c.Sw)return c;d=cj();c.Sw=d;d.src=a;d.listener=c;if(a.addEventListener)Ki||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(dj(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("B");Xi++;return c};cj=function(){var a=ej,b=function(c){return a.call(b.src,b.listener,c)};return b};
_.Yi=function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)_.Yi(a,b[f],c,d,e);return null}c=_.$i(c);return _.Oi(a)?a.jo(b,c,_.$a(d)?!!d.capture:!!d,e):aj(a,b,c,!0,d,e)};_.fj=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)_.fj(a,b[f],c,d,e);else d=_.$a(d)?!!d.capture:!!d,c=_.$i(c),_.Oi(a)?a.Xb(b,c,d,e):a&&(a=_.bj(a))&&(b=a.Gn(b,c,d,e))&&_.gj(b)};
_.gj=function(a){if("number"===typeof a||!a||a.Sr)return!1;var b=a.src;if(_.Oi(b))return b.SE(a);var c=a.type,d=a.Sw;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(dj(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Xi--;(c=_.bj(b))?(Ui(c,a),0==c.Ns&&(c.src=null,b[Vi]=null)):Ri(a);return!0};dj=function(a){return a in Wi?Wi[a]:Wi[a]="on"+a};
ej=function(a,b){if(a.Sr)a=!0;else{b=new _.Li(b,this);var c=a.listener,d=a.Oe||a.src;a.Lt&&_.gj(a);a=c.call(d,b)}return a};_.bj=function(a){a=a[Vi];return a instanceof Si?a:null};hj="__closure_events_fn_"+(1E9*Math.random()>>>0);_.$i=function(a){if("function"===typeof a)return a;a[hj]||(a[hj]=function(b){return a.handleEvent(b)});return a[hj]};_.Ai(function(a){ej=a(ej)});
_.ij=function(){_.Gi.call(this);this.Qi=new Si(this);this.zR=this;this.TC=null};_.Va(_.ij,_.Gi);_.ij.prototype[_.Ni]=!0;_.h=_.ij.prototype;_.h.Kl=function(){return this.TC};_.h.tx=_.ha(10);_.h.addEventListener=function(a,b,c,d){_.Zi(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.fj(this,a,b,c,d)};
_.h.dispatchEvent=function(a){var b,c=this.Kl();if(c)for(b=[];c;c=c.Kl())b.push(c);c=this.zR;var d=a.type||a;if("string"===typeof a)a=new _.Ji(a,c);else if(a instanceof _.Ji)a.target=a.target||c;else{var e=a;a=new _.Ji(d,c);_.vb(a,e)}e=!0;if(b)for(var f=b.length-1;!a.Mr&&0<=f;f--){var g=a.currentTarget=b[f];e=g.iq(d,!0,a)&&e}a.Mr||(g=a.currentTarget=c,e=g.iq(d,!0,a)&&e,a.Mr||(e=g.iq(d,!1,a)&&e));if(b)for(f=0;!a.Mr&&f<b.length;f++)g=a.currentTarget=b[f],e=g.iq(d,!1,a)&&e;return e};
_.h.na=function(){_.ij.O.na.call(this);this.kD();this.TC=null};_.h.U=function(a,b,c,d){return this.Qi.add(String(a),b,!1,c,d)};_.h.jo=function(a,b,c,d){return this.Qi.add(String(a),b,!0,c,d)};_.h.Xb=function(a,b,c,d){return this.Qi.remove(String(a),b,c,d)};_.h.SE=function(a){return Ui(this.Qi,a)};_.h.kD=function(a){this.Qi&&this.Qi.removeAll(a)};
_.h.iq=function(a,b,c){a=this.Qi.Jd[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.Sr&&f.capture==b){var g=f.listener,k=f.Oe||f.src;f.Lt&&this.SE(f);d=!1!==g.call(k,c)&&d}}return d&&!c.defaultPrevented};_.h.Gn=function(a,b,c,d){return this.Qi.Gn(String(a),b,c,d)};_.h.hasListener=function(a,b){return this.Qi.hasListener(void 0!==a?String(a):void 0,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Gs=function(a,b,c){if(null!==a&&b in a)throw Error("e`"+b);a[b]=c};_.Hs=function(a){_.Gi.call(this);this.Vd=a;this.Nb={}};_.Va(_.Hs,_.Gi);var Is=[];_.Hs.prototype.U=function(a,b,c,d){return this.lr(a,b,c,d)};_.Hs.prototype.lr=function(a,b,c,d,e){Array.isArray(b)||(b&&(Is[0]=b.toString()),b=Is);for(var f=0;f<b.length;f++){var g=_.Zi(a,b[f],c||this.handleEvent,d||!1,e||this.Vd||this);if(!g)break;this.Nb[g.key]=g}return this};_.Hs.prototype.jo=function(a,b,c,d){return Js(this,a,b,c,d)};
var Js=function(a,b,c,d,e,f){if(Array.isArray(c))for(var g=0;g<c.length;g++)Js(a,b,c[g],d,e,f);else{b=_.Yi(b,c,d||a.handleEvent,e,f||a.Vd||a);if(!b)return a;a.Nb[b.key]=b}return a};_.Hs.prototype.Xb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)this.Xb(a,b[f],c,d,e);else c=c||this.handleEvent,d=_.$a(d)?!!d.capture:!!d,e=e||this.Vd||this,c=_.$i(c),d=!!d,b=_.Oi(a)?a.Gn(b,c,d,e):a?(a=_.bj(a))?a.Gn(b,c,d,e):null:null,b&&(_.gj(b),delete this.Nb[b.key]);return this};
_.Hs.prototype.removeAll=function(){_.sb(this.Nb,function(a,b){this.Nb.hasOwnProperty(b)&&_.gj(a)},this);this.Nb={}};_.Hs.prototype.na=function(){_.Hs.O.na.call(this);this.removeAll()};_.Hs.prototype.handleEvent=function(){throw Error("H");};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/

var bv,cv,dv,ev,gv,hv,iv,jv,lv;_.av=!1;bv=function(a){try{_.av&&window.console&&window.console.log&&window.console.log(a)}catch(b){}};cv=function(a,b){if(!a)return-1;if(a.indexOf)return a.indexOf(b,void 0);for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};dv=function(a,b){function c(){}if(!a)throw"Child class cannot be empty.";if(!b)throw"Parent class cannot be empty.";c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a};ev=function(a){return"[object Function]"===Object.prototype.toString.call(a)};
_.fv=function(a){var b={};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};gv=function(a){var b=location.hash;a=new RegExp("[&#]"+a+"=([^&]*)");b=decodeURIComponent(b);b=a.exec(b);return null==b?"":b[1].replace(/\+/g," ")};hv=function(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else throw"Add event handler for "+b+" failed.";};iv={token:1,id_token:1};
jv=function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")&&8==parseInt(a.split("msie")[1],10)};_.kv=window.JSON;lv=function(a){this.fF=a||[];this.Vb={}};lv.prototype.addEventListener=function(a,b){if(!(0<=cv(this.fF,a)))throw"Unrecognized event type: "+a;if(!ev(b))throw"The listener for event '"+a+"' is not a function.";this.Vb[a]||(this.Vb[a]=[]);0>cv(this.Vb[a],b)&&this.Vb[a].push(b)};
lv.prototype.removeEventListener=function(a,b){if(!(0<=cv(this.fF,a)))throw"Unrecognized event type: "+a;ev(b)&&this.Vb[a]&&this.Vb[a].length&&(b=cv(this.Vb[a],b),0<=b&&this.Vb[a].splice(b,1))};lv.prototype.dispatchEvent=function(a){var b=a.type;if(!(b&&0<=cv(this.fF,b)))throw"Failed to dispatch unrecognized event type: "+b;if(this.Vb[b]&&this.Vb[b].length)for(var c=0,d=this.Vb[b].length;c<d;c++)this.Vb[b][c](a)};
var mv,nv,ov,sv,tv,Kv,Lv,Nv,Ov,Qv,Zv;mv={};nv={};ov={google:{authServerUrl:"https://accounts.google.com/o/oauth2/auth",idpIFrameUrl:"https://accounts.google.com/o/oauth2/iframe"}};_.pv=function(a,b){if(a=ov[a])return a[b]};_.qv=function(a,b){if(!a)throw Error("M");if(!b.authServerUrl)throw Error("N");if(!b.idpIFrameUrl)throw Error("O");ov[a]={authServerUrl:b.authServerUrl,idpIFrameUrl:b.idpIFrameUrl}};_.rv=void 0;
sv=function(a){a.style.position="absolute";a.style.width="1px";a.style.height="1px";a.style.left="-9999px";a.style.top="-9999px";a.style.right="-9999px";a.style.bottom="-9999px";a.style.display="none";a.setAttribute("aria-hidden","true")};tv=function(){this.w2=window;this.eu=this.ul=this.Jr=this.Xg=null};
tv.prototype.open=function(a,b,c,d){uv(this);this.Jr?(this.ul&&(this.ul(),this.ul=null),vv(this)):this.Jr="authPopup"+Math.floor(1E6*Math.random()+1);a:{this.Xg=this.w2.open(a,this.Jr,b);try{this.Xg.focus();if(this.Xg.closed||"undefined"==typeof this.Xg.closed)throw Error("Q");_.rv=this.Xg}catch(e){d&&setTimeout(d,0);this.Xg=null;break a}c&&(this.ul=c,wv(this))}};
var uv=function(a){try{if(null==a.Xg||a.Xg.closed)a.Xg=null,a.Jr=null,vv(a),a.ul&&(a.ul(),a.ul=null)}catch(b){a.Xg=null,a.Jr=null,vv(a)}},wv=function(a){a.eu=window.setInterval(function(){uv(a)},300)},vv=function(a){a.eu&&(window.clearInterval(a.eu),a.eu=null)};nv=nv||{};var xv=function(a,b){this.Ob=a;this.OB=b;this.$c=null;this.Vl=!1};xv.prototype.start=function(){if(!this.Vl&&!this.$c){var a=this;this.$c=window.setTimeout(function(){a.clear();a.Vl||(a.Ob(),a.Vl=!0)},nv.vJ(this.OB))}};
xv.prototype.clear=function(){this.$c&&(window.clearTimeout(this.$c),this.$c=null)};var yv=function(a,b){var c=nv.qp;this.bX=nv.ip;this.XO=c;this.Ob=a;this.OB=b;this.$c=null;this.Vl=!1;var d=this;this.YO=function(){document[d.bX]||(d.clear(),d.start())}};yv.prototype.start=function(){if(!this.Vl&&!this.$c){hv(document,this.XO,this.YO);var a=this;this.$c=window.setTimeout(function(){a.clear();a.Vl||(a.Ob(),a.Vl=!0)},nv.vJ(this.OB))}};
yv.prototype.clear=function(){var a=this.XO,b=this.YO,c=document;if(c.removeEventListener)c.removeEventListener(a,b,!1);else if(c.detachEvent)c.detachEvent("on"+a,b);else throw"Remove event handler for "+a+" failed.";this.$c&&(window.clearTimeout(this.$c),this.$c=null)};nv.ip=null;nv.qp=null;
nv.yX=function(){var a=document;"undefined"!==typeof a.hidden?(nv.ip="hidden",nv.qp="visibilitychange"):"undefined"!==typeof a.msHidden?(nv.ip="msHidden",nv.qp="msvisibilitychange"):"undefined"!==typeof a.webkitHidden&&(nv.ip="webkitHidden",nv.qp="webkitvisibilitychange")};nv.yX();nv.HS=function(a,b){return nv.ip&&nv.qp?new yv(a,b):new xv(a,b)};nv.vJ=function(a){return Math.max(1,a-(new Date).getTime())};
var zv=function(a,b){document.cookie="G_ENABLED_IDPS="+a+";domain=."+b+";expires=Fri, 31 Dec 9999 12:00:00 GMT;path=/"},Av=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(q){for(var t=g,r=0;64>r;r+=4)t[r/4]=q[r]<<24|q[r+1]<<16|q[r+2]<<8|q[r+3];for(r=16;80>r;r++)q=t[r-3]^t[r-8]^t[r-14]^t[r-16],t[r]=(q<<1|q>>>31)&4294967295;q=e[0];var v=e[1],u=e[2],w=e[3],z=e[4];for(r=0;80>r;r++){if(40>r)if(20>r){var A=w^v&(u^w);var B=1518500249}else A=
v^u^w,B=1859775393;else 60>r?(A=v&u|w&(v|u),B=2400959708):(A=v^u^w,B=3395469782);A=((q<<5|q>>>27)&4294967295)+A+z+B+t[r]&4294967295;z=w;w=u;u=(v<<30|v>>>2)&4294967295;v=q;q=A}e[0]=e[0]+q&4294967295;e[1]=e[1]+v&4294967295;e[2]=e[2]+u&4294967295;e[3]=e[3]+w&4294967295;e[4]=e[4]+z&4294967295}function c(q,t){if("string"===typeof q){q=unescape(encodeURIComponent(q));for(var r=[],v=0,u=q.length;v<u;++v)r.push(q.charCodeAt(v));q=r}t||(t=q.length);r=0;if(0==m)for(;r+64<t;)b(q.slice(r,r+64)),r+=64,n+=64;for(;r<
t;)if(f[m++]=q[r++],n++,64==m)for(m=0,b(f);r+64<t;)b(q.slice(r,r+64)),r+=64,n+=64}function d(){var q=[],t=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var r=63;56<=r;r--)f[r]=t&255,t>>>=8;b(f);for(r=t=0;5>r;r++)for(var v=24;0<=v;v-=8)q[t++]=e[r]>>v&255;return q}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Fg:function(){for(var q=d(),t="",r=0;r<q.length;r++)t+="0123456789ABCDEF".charAt(Math.floor(q[r]/16))+"0123456789ABCDEF".charAt(q[r]%16);return t}}},Bv=
window.crypto,Cv=!1,Dv=0,Ev=1,Fv=0,Gv="",Hv=function(a){a=a||window.event;var b=a.screenX+a.clientX<<16;b+=a.screenY+a.clientY;b*=(new Date).getTime()%1E6;Ev=Ev*b%Fv;if(3==++Dv)if(a=window,b=Hv,a.removeEventListener)a.removeEventListener("mousemove",b,!1);else if(a.detachEvent)a.detachEvent("onmousemove",b);else throw Error("R`mousemove");},Iv=function(a){var b=Av();b.update(a);return b.Fg()};Cv=!!Bv&&"function"==typeof Bv.getRandomValues;
Cv||(Fv=1E6*(screen.width*screen.width+screen.height),Gv=Iv(document.cookie+"|"+document.location+"|"+(new Date).getTime()+"|"+Math.random()),hv(window,"mousemove",Hv));mv=mv||{};mv.LP="ssIFrame_";
_.Jv=function(a,b,c){c=void 0===c?!1:c;this.Bb=a;if(!this.Bb)throw Error("S");a=_.pv(a,"idpIFrameUrl");if(!a)throw Error("T");this.oK=a;if(!b)throw Error("U");this.Uk=b;a=this.oK;b=document.createElement("a");b.setAttribute("href",a);a=[b.protocol,"//",b.hostname];"http:"==b.protocol&&""!=b.port&&"0"!=b.port&&"80"!=b.port?(a.push(":"),a.push(b.port)):"https:"==b.protocol&&""!=b.port&&"0"!=b.port&&"443"!=b.port&&(a.push(":"),a.push(b.port));this.wB=a.join("");this.C_=[location.protocol,"//",location.host].join("");
this.Hs=this.vB=this.Yl=!1;this.kK=null;this.zw=[];this.wo=[];this.Ei={};this.Zl=void 0;this.To=c};_.h=_.Jv.prototype;_.h.show=function(){var a=this.Zl;a.style.position="fixed";a.style.width="100%";a.style.height="100%";a.style.left="0px";a.style.top="0px";a.style.right="0px";a.style.bottom="0px";a.style.display="block";a.style.zIndex="9999999";a.style.overflow="hidden";a.setAttribute("aria-hidden","false")};_.h.Ec=function(){sv(this.Zl)};
_.h.Xv=function(a){if(this.Yl)a&&a(this);else{if(!this.Zl){var b=mv.LP+this.Bb;var c=this.Bb;var d=location.hostname;var e,f=document.cookie.match("(^|;) ?G_ENABLED_IDPS=([^;]*)(;|$)");f&&2<f.length&&(e=f[2]);(f=e&&0<=cv(e.split("|"),c))?zv(e,d):zv(e?e+"|"+c:c,d);c=!f;var g=this.oK,k=this.C_;d=this.Uk;e=this.To;e=void 0===e?!1:e;f=document.createElement("iframe");f.setAttribute("id",b);b="allow-scripts allow-same-origin";document.requestStorageAccess&&ev(document.requestStorageAccess)&&(b+=" allow-storage-access-by-user-activation");
f.setAttribute("sandbox",b);sv(f);f.setAttribute("frame-border","0");b=[g,"#origin=",encodeURIComponent(k)];b.push("&rpcToken=");b.push(encodeURIComponent(d));c&&b.push("&clearCache=1");_.av&&b.push("&debug=1");e&&b.push("&supportBlocked3PCookies=1");document.body.appendChild(f);f.setAttribute("src",b.join(""));this.Zl=f}a&&this.zw.push(a)}};_.h.Mv=function(){return this.Yl&&this.Hs};_.h.Jl=function(){return this.kK};Kv=function(a){for(var b=0;b<a.zw.length;b++)a.zw[b](a);a.zw=[]};
_.Mv=function(a,b,c,d){if(a.Yl){if(a.Yl&&a.vB)throw a="Failed to communicate with IDP IFrame due to unitialization error: "+a.Jl(),bv(a),Error(a);Lv(a,{method:b,params:c},d)}else a.wo.push({Dm:{method:b,params:c},callback:d}),a.Xv()};Lv=function(a,b,c){if(c){for(var d=b.id;!d||a.Ei[d];)d=(new Date).getMilliseconds()+"-"+(1E6*Math.random()+1);b.id=d;a.Ei[d]=c}b.rpcToken=a.Uk;a.Zl.contentWindow.postMessage(_.kv.stringify(b),a.wB)};Nv=function(a){if(a&&0<=a.indexOf("::"))throw Error("V");};
_.Jv.prototype.Ph=function(a,b,c,d,e,f,g,k,l){l=void 0===l?!1:l;Nv(f);b=_.fv(b);_.Mv(this,"getTokenResponse",{clientId:a,loginHint:c,request:b,sessionSelector:d,forceRefresh:g,skipCache:k,id:f,userInteracted:l},e)};_.Jv.prototype.Wv=function(a,b,c,d,e){b=_.fv(b);_.Mv(this,"listIdpSessions",{clientId:a,request:b,sessionSelector:c,forceRefresh:e},d)};Ov=function(a,b,c){Nv(b.identifier);_.Mv(a,"getSessionSelector",b,c)};
_.Pv=function(a,b,c,d,e){Nv(b.identifier);_.Mv(a,"setSessionSelector",{domain:b.domain,crossSubDomains:b.crossSubDomains,policy:b.policy,id:b.id,hint:d,disabled:!!c},e)};Qv=function(a,b,c){_.Mv(a,"monitorClient",{clientId:b},c)};_.Jv.prototype.Ur=_.ha(28);_.Jv.prototype.Bx=function(a,b){_.Mv(this,"showDialog",{F$:a},b)};_.Jv.prototype.Jp=_.ha(30);mv.sv={};mv.yA=function(a){return mv.sv[a]};
mv.Xv=function(a,b,c){c=void 0===c?!1:c;var d=mv.yA(a);if(!d){d=String;if(Cv){var e=new window.Uint32Array(1);Bv.getRandomValues(e);e=Number("0."+e[0])}else e=Ev,e+=parseInt(Gv.substr(0,20),16),Gv=Iv(Gv),e/=Fv+Math.pow(16,20);d=new _.Jv(a,d(2147483647*e),c);mv.sv[a]=d}d.Xv(b)};mv.oU=function(a){for(var b in mv.sv){var c=mv.yA(b);if(c&&c.Zl&&c.Zl.contentWindow==a.source&&c.wB==a.origin)return c}};mv.bV=function(a){for(var b in mv.sv){var c=mv.yA(b);if(c&&c.wB==a)return c}};mv=mv||{};
var Sv=function(){var a=[],b;for(b in Rv)a.push(Rv[b]);lv.call(this,a);this.Ck={};bv("EventBus is ready.")};dv(Sv,lv);var Rv={WQ:"sessionSelectorChanged",xy:"sessionStateChanged",$x:"authResult",yP:"displayIFrame"},Uv=function(a){var b=Tv;a&&(b.Ck[a]||(b.Ck[a]=[]))},Vv=function(a,b,c){return b&&a.Ck[b]&&0<=cv(a.Ck[b],c)};_.h=Sv.prototype;
_.h.MZ=function(a){var b,c=!!a.source&&(a.source.opener===window||a.source===_.rv);if(b=c?mv.bV(a.origin):mv.oU(a)){try{var d=_.kv.parse(a.data)}catch(e){bv("Bad event, an error happened when parsing data.");return}if(!c){if(!d||!d.rpcToken||d.rpcToken!=b.Uk){bv("Bad event, no RPC token.");return}if(d.id&&!d.method){c=d;if(a=b.Ei[c.id])delete b.Ei[c.id],a(c.result,c.error);return}}"fireIdpEvent"!=d.method?bv("Bad IDP event, method unknown."):(a=d.params)&&a.type&&this.nK[a.type]?(d=this.nK[a.type],
c&&!d.FR?bv("Bad IDP event. Source window cannot be a popup."):d.$o&&!d.$o.call(this,b,a)?bv("Bad IDP event."):d.Oe.call(this,b,a)):bv("Bad IDP event.")}else bv("Bad event, no corresponding Idp Stub.")};_.h.h0=function(a,b){return Vv(this,a.Bb,b.clientId)};_.h.g0=function(a,b){b=b.clientId;return!b||Vv(this,a.Bb,b)};_.h.RR=function(a,b){return Vv(this,a.Bb,b.clientId)};_.h.YY=function(a,b){a.Yl=!0;a.Hs=!!b.cookieDisabled;Kv(a);for(b=0;b<a.wo.length;b++)Lv(a,a.wo[b].Dm,a.wo[b].callback);a.wo=[]};
_.h.XY=function(a,b){b={error:b.error};a.Yl=!0;a.vB=!0;a.kK=b;a.wo=[];Kv(a)};_.h.Xw=function(a,b){b.originIdp=a.Bb;this.dispatchEvent(b)};var Tv=new Sv,Wv=Tv,Xv={};Xv.idpReady={Oe:Wv.YY};Xv.idpError={Oe:Wv.XY};Xv.sessionStateChanged={Oe:Wv.Xw,$o:Wv.h0};Xv.sessionSelectorChanged={Oe:Wv.Xw,$o:Wv.g0};Xv.authResult={Oe:Wv.Xw,$o:Wv.RR,FR:!0};Xv.displayIFrame={Oe:Wv.Xw};Tv.nK=Xv||{};hv(window,"message",function(a){Tv.MZ.call(Tv,a)});
_.Yv=function(a,b){this.de=!1;if(!a)throw Error("W");var c=[],d;for(d in a)c.push(a[d]);lv.call(this,c);this.xd=[location.protocol,"//",location.host].join("");this.tc=b.crossSubDomains?b.domain||this.xd:this.xd;if(!b)throw Error("X");if(!b.idpId)throw Error("Y");if(!_.pv(b.idpId,"authServerUrl")||!_.pv(b.idpId,"idpIFrameUrl"))throw Error("Z`"+b.idpId);this.Bb=b.idpId;this.Sb=void 0;this.QS=!!b.disableTokenRefresh;this.JT=!!b.forceTokenRefresh;this.l1=!!b.skipTokenCache;this.To=!!b.supportBlocked3PCookies;
this.setOptions(b);this.Rp=[];this.Hs=this.dm=this.PK=!1;this.$n=void 0;this.FM();this.Xc=void 0;var e=this,f=function(){bv("Token Manager is ready.");if(e.Rp.length)for(var g=0;g<e.Rp.length;g++)e.Rp[g].call(e);e.PK=!0;e.Rp=[]};mv.Xv(this.Bb,function(g){e.Xc=g;g.Yl&&g.vB?(e.dm=!0,e.$n=g.Jl(),e.uw(e.$n)):(e.Hs=g.Mv(),e.Sb?Qv(e.Xc,e.Sb,function(k){if(k){k=e.Bb;var l=e.Sb,m=Tv;k&&l&&(m.Ck[k]||(m.Ck[k]=[]),0>cv(m.Ck[k],l)&&m.Ck[k].push(l));f()}else e.$n={error:"Not a valid origin for the client: "+e.xd+
" has not been registered for client ID "+e.Sb+". Please go to https://console.developers.google.com/ and register this origin for your project's client ID."},e.dm=!0,e.uw(e.$n)}):(Uv(e.Bb),f()))},this.To)};dv(_.Yv,lv);_.h=_.Yv.prototype;_.h.setOptions=function(){};_.h.FM=function(){};_.h.uw=function(){};_.h.Mv=function(){return this.Hs};_.h.Jl=function(){return this.$n};Zv=function(a,b,c){return function(){b.apply(a,c)}};
_.$v=function(a,b,c){if(a.PK)b.apply(a,c);else{if(a.dm)throw a.$n;a.Rp.push(Zv(a,b,c))}};_.Yv.prototype.dH=_.ha(31);_.Yv.prototype.Jp=_.ha(29);
_.bw=function(a,b){_.Yv.call(this,a,b);this.pM=new tv;this.hj=this.um=null;aw(this)};dv(_.bw,_.Yv);_.bw.prototype.setOptions=function(){};
var cw=function(a,b){a.$d={crossSubDomains:!!b.crossSubDomains,id:b.sessionSelectorId,domain:a.tc};b.crossSubDomains&&(a.$d.policy=b.policy)},dw=function(a,b){if(!b.authParameters)throw Error("$");if(!b.authParameters.scope)throw Error("aa");if(!b.authParameters.response_type)throw Error("ba");a.zp=b.authParameters;a.zp.redirect_uri||(a.zp.redirect_uri=[location.protocol,"//",location.host,location.pathname].join(""));a.$h=_.fv(b.rpcAuthParameters||a.zp);if(!a.$h.scope)throw Error("ca");if(!a.$h.response_type)throw Error("da");
a:{var c=a.$h.response_type.split(" ");for(var d=0,e=c.length;d<e;d++)if(c[d]&&!iv[c[d]]){c=!0;break a}c=!1}if(c)throw Error("ea");b.enableSerialConsent&&(a.$h.enable_serial_consent=!0);b.authResultIdentifier&&(a.SR=b.authResultIdentifier);b.spec_compliant&&(a.$h.spec_compliant=b.spec_compliant)};
_.bw.prototype.FM=function(){var a=this;Tv.addEventListener(Rv.WQ,function(b){a.de&&a.$d&&b.originIdp==a.Bb&&!b.crossSubDomains==!a.$d.crossSubDomains&&b.domain==a.$d.domain&&b.id==a.$d.id&&a.$L(b)});Tv.addEventListener(Rv.xy,function(b){a.de&&b.originIdp==a.Bb&&b.clientId==a.Sb&&a.aM(b)});Tv.addEventListener(Rv.$x,function(b){_.rv=void 0;a.de&&b.originIdp==a.Bb&&b.clientId==a.Sb&&b.id==a.dj&&(a.um&&(window.clearTimeout(a.um),a.um=null),a.dj=void 0,a.Ar(b))});Tv.addEventListener(Rv.yP,function(b){a.de&&
b.originIdp==a.Bb&&(b.Ec?a.Xc.Ec():a.Xc.show())})};_.bw.prototype.$L=function(){};_.bw.prototype.aM=function(){};_.bw.prototype.Ar=function(){};var fw=function(a,b){ew(a);a.QS||(a.hj=nv.HS(function(){a.Ph(!0)},b-3E5),navigator.onLine&&a.hj.start())},ew=function(a){a.hj&&(a.hj.clear(),a.hj=null)},aw=function(a){var b=window;jv()&&(b=document.body);hv(b,"online",function(){a.hj&&a.hj.start()});hv(b,"offline",function(){a.hj&&a.hj.clear()})};_.h=_.bw.prototype;_.h.Ph=function(){};
_.h.Bx=function(a,b){this.Xc.Bx(a,b)};_.h.IL=_.ha(32);_.h.gY=function(a,b){if(!this.Sb)throw Error("ia");this.Xc.Wv(this.Sb,this.$h,this.$d,a,b)};_.h.Wv=function(a,b){_.$v(this,this.gY,[a,b])};_.hw=function(a){this.Xd=void 0;this.Gg=!1;this.Io=void 0;_.bw.call(this,_.gw,a)};dv(_.hw,_.bw);_.gw={MF:"noSessionBound",np:"userLoggedOut",hP:"activeSessionChanged",xy:"sessionStateChanged",hG:"tokenReady",gR:"tokenFailed",$x:"authResult",ERROR:"error"};
_.hw.prototype.setOptions=function(a){if(!a.clientId)throw Error("ja");this.Sb=a.clientId;this.Aa=a.id;cw(this,a);dw(this,a)};_.hw.prototype.uw=function(a){this.dispatchEvent({type:_.gw.ERROR,error:"idpiframe_initialization_failed",details:a.error,idpId:this.Bb})};var iw=function(a){ew(a);a.Io=void 0;a.Sv=void 0};_.h=_.hw.prototype;
_.h.$L=function(a){var b=a.newValue||{};if(this.Xd!=b.hint||this.Gg!=!!b.disabled){a=this.Xd;var c=!this.Xd||this.Gg;iw(this);this.Xd=b.hint;this.Gg=!!b.disabled;(b=!this.Xd||this.Gg)&&!c?this.dispatchEvent({type:_.gw.np,idpId:this.Bb}):b||(a!=this.Xd&&this.dispatchEvent({type:_.gw.hP,idpId:this.Bb}),this.Xd&&this.Ph())}};
_.h.aM=function(a){this.Gg||(this.Xd?a.user||this.Io?a.user==this.Xd&&(this.Io?a.sessionState?this.Io=a.sessionState:(iw(this),this.dispatchEvent({type:_.gw.np,idpId:this.Bb})):a.sessionState&&(this.Io=a.sessionState,this.Ph())):this.Ph():this.dispatchEvent({type:_.gw.xy,idpId:this.Bb}))};_.h.Ar=function(a){this.dispatchEvent({type:_.gw.$x,authResult:a.authResult})};_.h.wq=_.ha(34);_.h.pq=function(a){_.$v(this,this.lA,[a])};_.h.lA=function(a){Ov(this.Xc,this.$d,a)};
_.h.Dx=function(a,b,c,d){d=void 0===d?!1:d;if(!a)throw Error("ka");iw(this);this.Xd=a;this.Gg=!1;b&&_.Pv(this.Xc,this.$d,!1,this.Xd);this.de=!0;this.Ph(c,!0,d)};_.h.start=function(){_.$v(this,this.q1,[])};
_.h.q1=function(){var a=this.Sb==gv("client_id")?gv("login_hint"):void 0;var b=this.Sb==gv("client_id")?gv("state"):void 0;this.BC=b;if(a)window.history.replaceState?window.history.replaceState(null,document.title,window.location.href.split("#")[0]):window.location.href.hash="",this.Dx(a,!0,!0,!0);else{var c=this;this.pq(function(d){c.de=!0;d&&d.hint?(iw(c),c.Xd=d.hint,c.Gg=!!d.disabled,c.Gg?c.dispatchEvent({type:_.gw.np,idpId:c.Bb}):c.Dx(d.hint)):(iw(c),c.Xd=void 0,c.Gg=!(!d||!d.disabled),c.dispatchEvent({type:_.gw.MF,
autoOpenAuthUrl:!c.Gg,idpId:c.Bb}))})}};_.h.GT=function(){var a=this;this.pq(function(b){b&&b.hint?b.disabled?a.dispatchEvent({type:_.gw.np,idpId:a.Bb}):a.Ph(!0):a.dispatchEvent({type:_.gw.MF,idpId:a.Bb})})};_.h.DI=function(){_.$v(this,this.GT,[])};
_.h.Ph=function(a,b,c){var d=this;this.Xc.Ph(this.Sb,this.$h,this.Xd,this.$d,function(e,f){(f=f||e.error)?"user_logged_out"==f?(iw(d),d.dispatchEvent({type:_.gw.np,idpId:d.Bb})):(d.Sv=null,d.dispatchEvent({type:_.gw.gR,idpId:d.Bb,error:f})):(d.Sv=e,d.Io=e.session_state,fw(d,e.expires_at),e.idpId=d.Bb,b&&d.BC&&(e.state=d.BC,d.BC=void 0),d.dispatchEvent({type:_.gw.hG,idpId:d.Bb,response:e}))},this.Aa,a,!1,void 0===c?!1:c)};_.h.Ur=_.ha(27);_.h.XM=_.ha(35);
_.jw=function(a){this.nl=null;_.bw.call(this,{},a);this.de=!0};dv(_.jw,_.bw);_.h=_.jw.prototype;_.h.setOptions=function(a){if(!a.clientId)throw Error("ja");this.Sb=a.clientId;this.Aa=a.id;cw(this,a);dw(this,a)};_.h.uw=function(a){this.nl&&(this.nl({authResult:{error:"idpiframe_initialization_failed",details:a.error}}),this.nl=null)};_.h.Ar=function(a){if(this.nl){var b=this.nl;this.nl=null;b(a)}};_.h.wq=_.ha(33);_.h.pq=function(a){this.dm?a(this.Jl()):_.$v(this,this.lA,[a])};
_.h.lA=function(a){Ov(this.Xc,this.$d,a)};_.kw=function(a,b,c){a.dm?c(a.Jl()):_.$v(a,a.mZ,[b,c])};_.jw.prototype.mZ=function(a,b){this.Xc.Ph(this.Sb,this.$h,a,this.$d,function(c,d){d?b({error:d}):b(c)},this.Aa,this.JT,this.l1)};_.jw.prototype.mL=_.ha(36);

var lw=function(a){return Array.prototype.concat.apply([],arguments)},mw=function(){try{var a=Array.from((window.crypto||window.msCrypto).getRandomValues(new Uint8Array(64)))}catch(c){a=[];for(var b=0;64>b;b++)a[b]=Math.floor(256*Math.random())}return _.oh(a,3).substring(0,64)},nw=function(){var a=navigator.userAgent.toLowerCase();return 0>a.indexOf("edge/")&&(-1<a.indexOf("chrome/")||-1<a.indexOf("crios/"))},ow=function(){var a=navigator.userAgent.toLowerCase();return-1<a.indexOf("firefox/")&&0>
a.indexOf("chrome/")&&0>a.indexOf("crios/")&&0>a.indexOf("safari/")},pw=function(a,b,c){if(!a.de)throw Error("fa");b?_.Pv(a.Xc,a.$d,!0,void 0,c):_.Pv(a.Xc,a.$d,!0,a.Xd,c)},qw=function(a){if(!a.de)throw Error("fa");return a.Sv},rw,sw,tw,uw,vw,ww,xw,yw,zw,Bw;_.jw.prototype.mL=_.Zc(36,function(a,b){var c=this.Xc,d=this.Sb,e=this.$d,f=_.fv(this.$h);delete f.response_type;_.Mv(c,"getOnlineCode",{clientId:d,loginHint:a,request:f,sessionSelector:e},b)});
_.hw.prototype.XM=_.Zc(35,function(a){qw(this)&&qw(this).access_token&&(this.Xc.Ur(this.Sb,qw(this).access_token,a),pw(this,!0))});
_.hw.prototype.wq=_.Zc(34,function(){var a=this;return function(b){if(b&&b.authResult&&b.authResult.login_hint)if(a.Mv()&&a.To&&(nw()||ow())){b=b.authResult;var c=Date.now(),d=b.expires_in;b={access_token:b.access_token,token_type:b.token_type,login_hint:b.login_hint,expires_in:d,id_token:b.id_token,scope:b.scope,first_issued_at:c,expires_at:c+1E3*d,idpId:a.Bb};a.Sv=b;a.dispatchEvent({type:_.gw.hG,idpId:a.Bb,response:b})}else a.Dx(b.authResult.login_hint,a.Gg||b.authResult.login_hint!=a.Xd,!0,!0)}});
_.jw.prototype.wq=_.Zc(33,function(a){var b=this;return function(c){c&&c.authResult&&c.authResult.login_hint?b.pq(function(d){_.Pv(b.Xc,b.$d,d&&d.disabled,c.authResult.login_hint,function(){_.kw(b,c.authResult.login_hint,a)})}):a(c&&c.authResult&&c.authResult.error?c.authResult:c&&c.authResult&&!c.authResult.login_hint?{error:"wrong_response_type"}:{error:"unknown_error"})}});_.bw.prototype.IL=_.Zc(32,function(){this.Sb&&_.Mv(this.Xc,"startPolling",{clientId:this.Sb,origin:this.xd,id:this.dj},void 0)});
_.Jv.prototype.Ur=_.Zc(28,function(a,b,c){_.Mv(this,"revoke",{clientId:a,token:b},c)});_.hw.prototype.Ur=_.Zc(27,function(a){_.$v(this,this.XM,[a])});rw=function(){var a=navigator.userAgent,b;if(b=!!a&&-1!=a.indexOf("CriOS"))b=-1,(a=a.match(/CriOS\/(\d+)/))&&a[1]&&(b=parseInt(a[1],10)||-1),b=48>b;return b};
sw=function(){var a=navigator.userAgent.toLowerCase();if(!(-1<a.indexOf("safari/")&&0>a.indexOf("chrome/")&&0>a.indexOf("crios/")&&0>a.indexOf("android")))return!1;var b=/version\/(\d+)\.(\d+)[\.0-9]*/.exec(navigator.userAgent.toLowerCase());if(!b||3>b.length)return!1;a=parseInt(b[1],10);b=parseInt(b[2],10);return 12<a||12==a&&1<=b};
tw=function(a,b,c,d,e,f,g){var k=_.pv(a,"authServerUrl");if(!k)throw Error("P`"+a);a=_.fv(d);a.response_type=g||"permission";a.client_id=c;a.ss_domain=b;if(f&&f.extraQueryParams)for(var l in f.extraQueryParams)a[l]=f.extraQueryParams[l];(b=e)&&!(b=sw())&&(b=navigator.userAgent.toLowerCase(),-1<b.indexOf("ipad;")||-1<b.indexOf("iphone;")?(b=/os (\d+)_\d+(_\d+)? like mac os x/.exec(navigator.userAgent.toLowerCase()),b=!b||2>b.length?!1:14<=parseInt(b[1],10)):b=!1);b&&!a.prompt&&(a.prompt="select_account");
k+=0>k.indexOf("?")?"?":"&";b=[];for(var m in a)if(a.hasOwnProperty(m)){c=a[m];if(null===c||void 0===c)c="";b.push(encodeURIComponent(m)+"="+encodeURIComponent(c))}return k+b.join("&")};
uw=function(a,b,c,d){if(!a.Sb)throw Error("ga");a.dj=c||a.SR||"auth"+Math.floor(1E6*Math.random()+1);b=b||{};b.extraQueryParams=b.extraQueryParams||{};if(!b.extraQueryParams.redirect_uri){var e=a.xd.split("//");c=b.extraQueryParams;var f=e[0],g=f.indexOf(":");0<g&&(f=f.substring(0,g));e=["storagerelay://",f,"/",e[1],"?"];e.push("id="+a.dj);c.redirect_uri=e.join("")}return tw(a.Bb,a.tc,a.Sb,a.zp,!0,b,d)};vw=function(a,b,c){if(!a.Sb)throw Error("ga");return tw(a.Bb,a.tc,a.Sb,a.zp,!1,b,c)};
ww=function(a){if(!a)return"permission token";var b=a.split(" ");if(-1<b.indexOf("token")||-1<b.indexOf("code")||-1<b.indexOf("gsession"))return a;b.push("token");return b.join(" ")};xw=function(a,b){a.um&&window.clearTimeout(a.um);a.um=window.setTimeout(function(){a.dj==b&&(_.rv=void 0,a.um=null,a.dj=void 0,a.Ar({authResult:{error:"popup_closed_by_user"}}))},1E3)};
yw=function(a,b,c){if(!a.Sb)throw Error("ha");c=c||{};a.Mv()&&a.To&&(nw()||ow())&&(c.responseType=ww(c.responseType));c=uw(a,c.sessionMeta,c.oneTimeId,c.responseType);(Object.hasOwnProperty.call(window,"ActiveXObject")&&!window.ActiveXObject||rw())&&_.$v(a,a.IL,[]);var d=a.dj;a.pM.open(c,b,function(){a.dj==d&&xw(a,d)},function(){a.dj=void 0;a.Ar({authResult:{error:"popup_blocked_by_browser"}})})};zw=function(a,b,c){a.dm?c(a.Jl()):_.$v(a,a.mL,[b,c])};
_.Aw=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var g=a[c++],k=a[c++];e=((e&7)<<18|(f&63)<<12|(g&63)<<6|k&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],g=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63)}return b.join("")};
Bw=function(a){var b=[];_.ph(a,function(c){b.push(c)});return b};_.Cw=function(a,b){_.Wh[b||"token"]=a};_.Dw=function(a){delete _.Wh[a||"token"]};
_.kv={parse:function(a){a=_.Af("["+String(a)+"]");if(!1===a||1!==a.length)throw new SyntaxError("JSON parsing failed.");return a[0]},stringify:function(a){return _.Bf(a)}};
_.jw.prototype.bA=function(a,b){_.$v(this,this.uT,[a,b])};_.jw.prototype.uT=function(a,b){this.Xc.bA(this.Sb,a,this.$h,this.$d,b)};
_.Jv.prototype.bA=function(a,b,c,d,e){c=_.fv(c);_.Mv(this,"gsi:fetchLoginHint",{clientId:a,loginHint:b,request:c,sessionSelector:d},e)};
var Ew,Fw=["client_id","cookie_policy","scope"],Gw="client_id cookie_policy fetch_basic_profile hosted_domain scope openid_realm disable_token_refresh login_hint ux_mode redirect_uri state prompt oidc_spec_compliant nonce enable_serial_consent include_granted_scopes response_type session_selection gsiwebsdk".split(" "),Hw=["authuser","after_redirect","access_type","hl"],Iw=["login_hint","prompt"],Jw={clientid:"client_id",cookiepolicy:"cookie_policy"},Kw=["approval_prompt","authuser","login_hint",
"prompt","hd"],Lw=["login_hint","g-oauth-window","status"],Mw=Math.min(_.Le("oauth-flow/authWindowWidth",599),screen.width-20),Nw=Math.min(_.Le("oauth-flow/authWindowHeight",600),screen.height-30);
var Ow=function(a){_.$c.call(this,a)};_.T(Ow,_.$c);Ow.prototype.name="gapi.auth2.ExternallyVisibleError";
var Pw=function(){};Pw.prototype.select=function(a,b){if(a.sessions&&1==a.sessions.length&&(a=a.sessions[0],a.login_hint)){b(a);return}b()};var Qw=function(){};Qw.prototype.select=function(a,b){if(a.sessions&&a.sessions.length)for(var c=0;c<a.sessions.length;c++){var d=a.sessions[c];if(d.login_hint){b(d);return}}b()};var Rw=function(a){this.TR=a};
Rw.prototype.select=function(a,b){if(a.sessions)for(var c=0;c<a.sessions.length;c++){var d=a.sessions[c];if(d.session_state&&d.session_state.extraQueryParams&&d.session_state.extraQueryParams.authuser==this.TR){d.login_hint?b(d):b();return}}b()};
var Sw=function(a){this.Nd=a;this.lx=[]};Sw.prototype.select=function(a){var b=0,c=this,d=function(e){if(e)a(e);else{var f=c.lx[b];f?(b++,c.Nd.Wv(function(g){g?f.select(g,d):d()})):a()}};d()};var Tw=function(a){a=new Sw(a);a.lx.push(new Pw);return a},Uw=function(a){a=new Sw(a);a.lx.push(new Qw);return a},Vw=function(a,b){void 0===b||null===b?b=Tw(a):(a=new Sw(a),a.lx.push(new Rw(b)),b=a);return b};
var Ww=function(a){this.Oe=a;this.Pc=!0};Ww.prototype.remove=function(){this.Pc=!1};Ww.prototype.trigger=function(){};var Xw=function(a){this.remove=function(){a.remove()};this.trigger=function(){a.trigger()}},Yw=function(){this.Vb=[]};Yw.prototype.add=function(a){this.Vb.push(a)};Yw.prototype.notify=function(a){for(var b=this.Vb,c=[],d=0;d<b.length;d++){var e=b[d];e.Pc&&(c.push(e),_.uk(Zw(e.Oe,a)))}this.Vb=c};var Zw=function(a,b){return function(){a(b)}};
var ax=function(a){this.fe=null;this.n2=new $w(this);this.Vb=new Yw;void 0!=a&&this.set(a)};ax.prototype.set=function(a){a!=this.fe&&(this.fe=a,this.n2.value=a,this.Vb.notify(this.fe))};ax.prototype.get=function(){return this.fe};ax.prototype.U=function(a){a=new bx(this,a);this.Vb.add(a);return a};ax.prototype.get=ax.prototype.get;var bx=function(a,b){Ww.call(this,b);this.jY=a};_.T(bx,Ww);bx.prototype.trigger=function(){var a=this.Oe;a(this.jY.get())};var $w=function(a){this.value=null;this.U=function(b){return new Xw(a.U(b))}};
var cx={P4:"fetch_basic_profile",U5:"login_hint",p7:"prompt",v7:"redirect_uri",P7:"scope",h9:"ux_mode",C8:"state"},dx=function(a){this.va={};if(a&&!_.Ei(a))if("function"==typeof a.get)this.va=a.get();else for(var b in cx){var c=cx[b];c in a&&(this.va[c]=a[c])}};dx.prototype.get=function(){return this.va};dx.prototype.SN=function(a){this.va.scope=a;return this};dx.prototype.Hq=function(){return this.va.scope};
var ex=function(a,b){var c=a.va.scope;b=lw(b.split(" "),c?c.split(" "):[]);_.fk(b);a.va.scope=b.join(" ")};_.h=dx.prototype;_.h.O0=function(a){this.va.prompt=a;return this};_.h.eV=function(){return this.va.prompt};_.h.k0=function(){_.Hf("Property app_package_name no longer supported and was not set");return this};_.h.QT=function(){_.Hf("Property app_package_name no longer supported")};_.h.Fe=function(a){this.va.state=a};_.h.getState=function(){return this.va.state};
var fx=function(){return["toolbar=no","location="+(window.opera?"no":"yes"),"directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no","width="+Mw,"height="+Nw,"top="+(screen.height-Nw)/2,"left="+(screen.width-Mw)/2].join()},gx=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+).?.?.?$/,"$1");return JSON.parse(_.Aw(Bw(a)))},hx=function(){Ew=_.Le("auth2/idpValue","google");var a=_.Le("oauth-flow/authUrl","https://accounts.google.com/o/oauth2/auth"),
b=_.Le("oauth-flow/idpIframeUrl","https://accounts.google.com/o/oauth2/iframe");_.qv(Ew,{authServerUrl:a,idpIFrameUrl:b})},ix=function(a,b,c){for(var d=0;d<b.length;d++){var e=b[d];if(d===b.length-1){a[e]=c;break}_.$a(a[e])||(a[e]={});a=a[e]}},jx=function(){var a=window.location.origin;a||(a=window.location.protocol+"//"+window.location.host);return a};
var kx=function(a){var b=a?(b=gx(a))?b.sub:null:null;this.Aa=b;this.qc=a?_.ik(a):null};_.h=kx.prototype;_.h.ka=function(){return this.Aa};_.h.vA=function(){var a=gx(this.qc);return a?a.hd:null};_.h.Bf=function(){return!!this.qc};_.h.jk=function(a){if(a)return this.qc;a=lx;var b=_.ik(this.qc);!a.Cv||a.qB||a.QW||(delete b.access_token,delete b.scope);return b};_.h.jD=function(){return lx.jD()};_.h.xj=function(){this.qc=null};_.h.yU=function(){return this.qc?this.qc.scope:null};
_.h.update=function(a){this.Aa=a.Aa;this.qc=a.qc;this.qc.id_token?this.Et=new mx(this.qc):this.Et&&(this.Et=null)};var nx=function(a){return a.qc&&"object"==typeof a.qc.session_state?_.ik(a.qc.session_state.extraQueryParams||{}):{}};_.h=kx.prototype;_.h.lq=function(){var a=nx(this);return a&&void 0!==a.authuser&&null!==a.authuser?a.authuser:null};
_.h.wj=function(a){var b=lx,c=new dx(a);b.qB=c.Hq()?!0:!1;lx.Cv&&ex(c,"openid profile email");return new _.Ek(function(d,e){var f=nx(this);f.login_hint=this.ka();f.scope=c.Hq();ox(b,d,e,f)},this)};_.h.Jq=function(a){return new _.Ek(function(b,c){var d=a||{},e=lx;d.login_hint=this.ka();e.Jq(d).then(b,c)},this)};_.h.AV=function(a){return this.wj(a)};_.h.disconnect=function(){return lx.disconnect()};_.h.TT=function(){return this.Et};
_.h.ov=function(a){if(!this.Bf())return!1;var b=this.qc&&this.qc.scope?this.qc.scope.split(" "):"";return _.rb(a?a.split(" "):[],function(c){return _.Za(b,c)})};var mx=function(a){a=gx(a);this.NT=a.sub;this.Ue=a.name;this.xV=a.given_name;this.sT=a.family_name;this.uK=a.picture;this.ou=a.email};_.h=mx.prototype;_.h.ka=function(){return this.NT};_.h.Ti=function(){return this.Ue};_.h.wU=function(){return this.xV};_.h.qU=function(){return this.sT};_.h.HU=function(){return this.uK};_.h.Pu=function(){return this.ou};
var qx=function(a,b,c){this.lm=b;this.KY=a;for(var d in a)a.hasOwnProperty(d)&&px(this,d);if(c&&c.length)for(a=0;a<c.length;a++)this[c[a]]=this.lm[c[a]]},px=function(a,b){a[b]=function(){return a.KY[b].apply(a.lm,arguments)}};qx.prototype.then=function(a,b,c){var d=this;return _.Ik().then(function(){return rx(d.lm,a,b,c)})};_.ok(qx);
var sx;sx=function(a){var b=location;if(a&&"none"!=a)return"single_host_origin"==a?b.protocol+"//"+b.host:a};
_.tx=function(a){if(!a)throw new Ow("No cookiePolicy");var b=window.location.hostname;"single_host_origin"==a&&(a=window.location.protocol+"//"+b);if("none"==a)return null;var c=/^(https?:\/\/)([0-9.\-_A-Za-z]+)(?::(\d+))?$/.exec(a);if(!c)throw new Ow("Invalid cookiePolicy");a=c[2];c=c[1];var d={};d.dotValue=a.split(".").length;d.isSecure=-1!=c.indexOf("https");d.domain=a;if(!_.Fi(b,"."+a)&&!_.Fi(b,a))throw new Ow("Invalid cookiePolicy domain");return d};
var vx=function(a){var b=a||{},c=ux();_.mb(Gw,function(d){"undefined"===typeof b[d]&&"undefined"!==typeof c[d]&&(b[d]=c[d])});return b},ux=function(){for(var a={},b=document.getElementsByTagName("meta"),c=0;c<b.length;++c)if(b[c].name){var d=b[c].name;if(0==d.indexOf("google-signin-")){d=d.substring(14);var e=b[c].content;Jw[d]&&(d=Jw[d]);_.Za(Gw,d)&&e&&(a[d]="true"==e?!0:"false"==e?!1:e)}}return a},wx=function(a){return String(a).replace(/_([a-z])/g,function(b,c){return c.toUpperCase()})},xx=function(a){_.mb(Gw,
function(b){var c=wx(b);"undefined"!==typeof a[c]&&"undefined"===typeof a[b]&&(a[b]=a[c],delete a[c])})},yx=function(a){a=vx(a);xx(a);a.cookie_policy||(a.cookie_policy="single_host_origin");var b=Gw+Hw,c;for(c in a)0>b.indexOf(c)&&delete a[c];return a},zx=function(a,b){if(!a)throw new Ow("Empty initial options.");for(var c=0;c<Fw.length;++c)if(!(b&&"scope"==Fw[c]||a[Fw[c]]))throw new Ow("Missing required parameter '"+Fw[c]+"'");_.tx(a.cookie_policy)},Bx=function(a){var b={authParameters:{redirect_uri:void 0,
response_type:"token id_token",scope:a.scope,"openid.realm":a.openid_realm},clientId:a.client_id,crossSubDomains:!0,domain:sx(a.cookie_policy),disableTokenRefresh:!!a.disable_token_refresh,idpId:Ew};Ax(b,a);_.mb(Iw,function(c){a[c]&&(b.authParameters[c]=a[c])});"boolean"==typeof a.enable_serial_consent&&(b.enableSerialConsent=a.enable_serial_consent);return b},Ax=function(a,b){var c=b.oidc_spec_compliant;b=b.nonce;c&&(a.spec_compliant=c,b=b||mw());b&&(a.authParameters.nonce=b,a.forceTokenRefresh=
!0,a.skipTokenCache=!0)},Gx=function(a){var b=a.client_id,c=a.cookie_policy,d=a.scope,e=a.openid_realm,f=a.hosted_domain,g=a.oidc_spec_compliant,k=a.nonce,l=Cx(a),m={authParameters:{response_type:l,scope:d,"openid.realm":e},rpcAuthParameters:{response_type:l,scope:d,"openid.realm":e},clientId:b,crossSubDomains:!0,domain:sx(c),idpId:Ew};f&&(m.authParameters.hd=f,m.rpcAuthParameters.hd=f);g&&(m.rpcAuthParameters.spec_compliant=g,k=k||mw());k&&(m.authParameters.nonce=k,m.rpcAuthParameters.nonce=k,m.forceTokenRefresh=
!0,m.skipTokenCache=!0);_.mb(Iw.concat(Hw),function(n){a[n]&&(m.authParameters[n]=a[n])});void 0!==a.authuser&&null!==a.authuser&&(m.authParameters.authuser=a.authuser);"boolean"==typeof a.include_granted_scopes&&(b=new Dx(a.response_type||"token"),Ex(b)&&(m.authParameters.include_granted_scopes=a.include_granted_scopes),Fx(b)&&(m.rpcAuthParameters.include_granted_scopes=a.include_granted_scopes,!1===a.include_granted_scopes&&(m.forceTokenRefresh=!0,m.skipTokenCache=!0)));"boolean"==typeof a.enable_serial_consent&&
(m.enableSerialConsent=a.enable_serial_consent);return m},Cx=function(a){a=new Dx(a.response_type||"token");var b=[];Fx(a)&&b.push("token");Hx(a,"id_token")&&b.push("id_token");0==b.length&&(b=["token","id_token"]);return b.join(" ")},Ix=["permission","id_token"],Jx=/(^|[^_])token/,Dx=function(a){this.Co=[];this.JB(a)};
Dx.prototype.JB=function(a){a?((0<=a.indexOf("permission")||a.match(Jx))&&this.Co.push("permission"),0<=a.indexOf("id_token")&&this.Co.push("id_token"),0<=a.indexOf("code")&&this.Co.push("code")):this.Co=Ix};var Ex=function(a){return Hx(a,"code")},Fx=function(a){return Hx(a,"permission")};Dx.prototype.toString=function(){return this.Co.join(" ")};var Hx=function(a,b){var c=!1;_.mb(a.Co,function(d){d==b&&(c=!0)});return c};
var lx,Kx,Mx;lx=null;_.Lx=function(){return lx?Kx():null};Kx=function(){return new qx(Mx.prototype,lx,["currentUser","isSignedIn"])};Mx=function(a){delete a.include_granted_scopes;this.va=Bx(a);this.DS=a.cookie_policy;this.QW=!!a.scope;(this.Cv=!1!==a.fetch_basic_profile)&&(this.va.authParameters.scope=Nx(this,"openid profile email"));_.Ih.GSI_SUPPORT_BLOCKED_3P_COOKIES&&(this.To=this.va.supportBlocked3PCookies=!0);this.Tq=a.hosted_domain;this.j2=a.ux_mode||"popup";this.SZ=a.redirect_uri||null;this.GB()};
Mx.prototype.GB=function(){this.currentUser=new ax(new kx(null));this.isSignedIn=new ax(!1);this.Nd=new _.hw(this.va);this.Iv=this.bo=null;this.XX=new _.Ek(function(a,b){this.bo=a;this.Iv=b},this);this.yw={};this.gr=!0;Ox(this);this.Nd.start()};
var Ox=function(a){a.Nd.addEventListener("error",function(b){a.gr&&a.bo&&(a.gr=!1,a.Iv({error:b.error,details:b.details}),a.bo=null,a.Iv=null)});a.Nd.addEventListener("authResult",function(b){b&&b.authResult&&a.Ke(b);a.Nd.wq()(b)});a.Nd.addEventListener("tokenReady",function(b){var c=new kx(b.response);if(a.Tq&&a.Tq!=c.vA())a.Ke({type:"tokenFailed",reason:"Account domain does not match hosted_domain specified by gapi.auth2.init.",accountDomain:c.vA(),expectedDomain:a.Tq});else{a.currentUser.get().update(c);
var d=a.currentUser;d.Vb.notify(d.fe);a.isSignedIn.set(!0);c=c.lq();(d=_.tx(a.DS))&&c&&_.Lh.set(["G_AUTHUSER_","https:"===window.location.protocol&&d.xe?"S":"H",d.rh].join(""),c,{domain:d.domain,secure:d.isSecure});_.Cw(b.response);a.Ke(b)}});a.Nd.addEventListener("noSessionBound",function(b){a.gr&&b.autoOpenAuthUrl?(a.gr=!1,Tw(a.Nd).select(function(c){if(c&&c.login_hint){var d=a.Nd;_.$v(d,d.Dx,[c.login_hint,!0])}else a.currentUser.set(new kx(null)),a.isSignedIn.set(!1),_.Dw(),a.Ke(b)})):(a.currentUser.set(new kx(null)),
a.isSignedIn.set(!1),_.Dw(),a.Ke(b))});a.Nd.addEventListener("tokenFailed",function(b){a.Ke(b)});a.Nd.addEventListener("userLoggedOut",function(b){a.currentUser.get().xj();var c=a.currentUser;c.Vb.notify(c.fe);a.isSignedIn.set(!1);_.Dw();a.Ke(b)})},rx=function(a,b,c,d){return a.XX.then(function(e){if(b)return b(e.yV)},c,d)};Mx.prototype.Ke=function(a){if(a){this.gr=!1;var b=a.type||"";if(this.yw[b])this.yw[b](a);this.bo&&(this.bo({yV:this}),this.Iv=this.bo=null)}};
var Px=function(a,b){_.sb(b,function(c,d){a.yw[d]=function(e){a.yw={};c(e)}})},ox=function(a,b,c,d){d=_.ik(d);a.Tq&&(d.hd=a.Tq);var e=d.ux_mode||a.j2;delete d.ux_mode;delete d.app_package_name;var f={sessionMeta:{extraQueryParams:d},responseType:"permission id_token"};"redirect"==e?(d.redirect_uri||(d.redirect_uri=a.SZ||jx()+window.location.pathname),Qx(a,f)):(delete d.redirect_uri,Rx(a,f),Px(a,{authResult:function(g){g.authResult&&g.authResult.error?c(g.authResult):Px(a,{tokenReady:function(){b(a.currentUser.get())},
tokenFailed:c})}}))};Mx.prototype.wj=function(a){return new _.Ek(function(b,c){var d=new dx(a);this.qB=d.Hq()?!0:!1;this.Cv?(d.va.fetch_basic_profile=!0,ex(d,"email profile openid")):d.va.fetch_basic_profile=!1;var e=Nx(this,d.Hq());d.SN(e);ox(this,b,c,d.get())},this)};
Mx.prototype.Jq=function(a){var b=a||{};this.qB=!!b.scope;a=Nx(this,b.scope);if(""==a)return _.Jk({error:"Missing required parameter: scope"});var c={scope:a,access_type:"offline",include_granted_scopes:!0};_.mb(Kw,function(d){null!=b[d]&&(c[d]=b[d])});c.hasOwnProperty("prompt")||c.hasOwnProperty("approval_prompt")||(c.prompt="consent");return"postmessage"==b.redirect_uri||void 0==b.redirect_uri?Sx(this,c):Tx(this,c,b.redirect_uri)};
var Tx=function(a,b,c){b.redirect_uri=c;Qx(a,{sessionMeta:{extraQueryParams:b},responseType:"code id_token"});return _.Ik({message:"Redirecting to IDP."})},Sx=function(a,b){b.origin=jx();delete b.redirect_uri;Rx(a,{sessionMeta:{extraQueryParams:b},responseType:"code permission id_token"});return new _.Ek(function(c,d){Px(this,{authResult:function(e){(e=e&&e.authResult)&&e.code?c({code:e.code}):d(e&&e.error?e:{error:"unknown_error"})}})},a)},Rx=function(a,b){ix(b,["sessionMeta","extraQueryParams",
"gsiwebsdk"],"2");yw(a.Nd,fx(),b)},Qx=function(a,b){ix(b,["sessionMeta","extraQueryParams","gsiwebsdk"],"2");b=b||{};window.location.assign(vw(a.Nd,b.sessionMeta,b.responseType))};Mx.prototype.xj=function(a){var b=a||!1;return new _.Ek(function(c){pw(this.Nd,b,function(){c()})},this)};Mx.prototype.dJ=function(){return this.va.authParameters.scope};var Nx=function(a,b){a=a.dJ();b=lw(b?b.split(" "):[],a?a.split(" "):[]);_.fk(b);return b.join(" ")};
Mx.prototype.jD=function(){var a=this;return new _.Ek(function(b,c){Px(a,{noSessionBound:c,tokenFailed:c,userLoggedOut:c,tokenReady:function(d){b(d.response)}});a.Nd.DI()})};Mx.prototype.KG=function(a,b,c,d){if(a="string"===typeof a?document.getElementById(a):a){var e=this;_.Zi(a,"click",function(){var f=b;"function"==typeof b&&(f=b());e.wj(f).then(function(g){c&&c(g)},function(g){d&&d(g)})})}else d&&d({error:"Could not attach click handler to the element. Reason: element not found."})};
Mx.prototype.disconnect=function(){return new _.Ek(function(a){this.Nd.Ur(function(){a()})},this)};Mx.prototype.attachClickHandler=Mx.prototype.KG;
var Ux;_.Ek.prototype["catch"]=_.Ek.prototype.Uo;Ux=null;_.Vx=function(a){a=yx(a);if(lx){if(_.hk(a,Ux||{}))return Kx();throw new Ow("gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().");}zx(a,!1!==a.fetch_basic_profile);hx();Ux=a;lx=new Mx(a);_.De.ga=1;return Kx()};
var Xx,Zx,Wx,ay,$x,by;_.Yx=function(a,b){hx();a=yx(a);zx(a);var c=Gx(a),d=new _.jw(c);"none"==a.prompt?Wx(d,a,function(e){e.status=e.error?{signed_in:!1,method:null,google_logged_in:!1}:{signed_in:!0,method:"AUTO",google_logged_in:!0};b(e)}):Xx(d,a,function(e){if(e.error)e.status={signed_in:!1,method:null,google_logged_in:!1};else{var f=e.access_token||e.id_token;e.status={signed_in:!!f,method:"PROMPT",google_logged_in:!!f}}e["g-oauth-window"]=d.pM.Xg;b(e)})};
Xx=function(a,b,c){var d=new Dx(b.response_type);c=Zx(a,d,c);var e={responseType:d.toString()};ix(e,["sessionMeta","extraQueryParams","gsiwebsdk"],b.gsiwebsdk||"2");Ex(d)&&ix(e,["sessionMeta","extraQueryParams","access_type"],b.access_type||"offline");b.redirect_uri&&ix(e,["sessionMeta","extraQueryParams","redirect_uri"],b.redirect_uri);b.state&&ix(e,["sessionMeta","extraQueryParams","state"],b.state);b=fx();a.dm?c({authResult:{error:"idpiframe_initialization_failed",details:a.Jl().error}}):(a.nl=
c,yw(a,b,e))};Zx=function(a,b,c){if(Fx(b)){var d=$x(c);return function(e){e&&e.authResult&&!e.authResult.error?a.wq(function(f){f&&!f.error?(f=_.ik(f),Ex(b)&&(f.code=e.authResult.code),d(f)):d(f?f:{error:"unknown_error"})})(e):d(e&&e.authResult?e.authResult:{error:"unknown_error"})}}return function(e){e&&e.authResult&&!e.authResult.error?c(_.ik(e.authResult)):c(e&&e.authResult?e.authResult:{error:"unknown_error"})}};
Wx=function(a,b,c){if(Ex(new Dx(b.response_type))&&"offline"==b.access_type)c({error:"immediate_failed",error_subtype:"access_denied"});else{var d=$x(c);b.login_hint?a.bA(b.login_hint,function(e){e?ay(a,b,e,d):c({error:"immediate_failed",error_subtype:"access_denied"})}):void 0!==b.authuser&&null!==b.authuser?Vw(a,b.authuser).select(function(e){e&&e.login_hint?ay(a,b,e.login_hint,d):d({error:"immediate_failed",error_subtype:"access_denied"})}):a.pq(function(e){e&&e.hint?ay(a,b,e.hint,d):e&&e.disabled?
d({error:"immediate_failed",error_subtype:"no_user_bound"}):("first_valid"==b.session_selection?Uw(a):Tw(a)).select(function(f){f&&f.login_hint?ay(a,b,f.login_hint,d):d({error:"immediate_failed",error_subtype:"no_user_bound"})})})}};ay=function(a,b,c,d){b=new Dx(b.response_type);var e=0,f={},g=function(k){!k||k.error?d(k):(e--,_.vb(f,k),0==e&&d(f))};(Fx(b)||Hx(b,"id_token"))&&e++;Ex(b)&&e++;(Fx(b)||Hx(b,"id_token"))&&_.kw(a,c,g);Ex(b)&&zw(a,c,g)};
$x=function(a){return function(b){if(!b||b.error)_.Dw(),b?a(b):a({error:"unknown_error"});else{if(b.access_token){var c=_.ik(b);by(c);delete c.id_token;delete c.code;_.Cw(c)}a(b)}}};by=function(a){_.mb(Lw,function(b){delete a[b]})};
_.M("gapi.auth2.init",_.Vx);_.M("gapi.auth2.authorize",function(a,b){if(null!=lx)throw new Ow("gapi.auth2.authorize cannot be called after GoogleAuth has been initialized (i.e. with a call to gapi.auth2.init, or gapi.client.init when given a 'clientId' and a 'scope' parameters).");_.Yx(a,function(c){by(c);b(c)})});_.M("gapi.auth2._gt",function(){return _.Xh()});_.M("gapi.auth2.enableDebugLogs",function(a){a=!1!==a;_.av="0"!=a&&!!a});_.M("gapi.auth2.getAuthInstance",_.Lx);
_.M("gapi.auth2.BasicProfile",mx);_.M("gapi.auth2.BasicProfile.prototype.getId",mx.prototype.ka);_.M("gapi.auth2.BasicProfile.prototype.getName",mx.prototype.Ti);_.M("gapi.auth2.BasicProfile.prototype.getGivenName",mx.prototype.wU);_.M("gapi.auth2.BasicProfile.prototype.getFamilyName",mx.prototype.qU);_.M("gapi.auth2.BasicProfile.prototype.getImageUrl",mx.prototype.HU);_.M("gapi.auth2.BasicProfile.prototype.getEmail",mx.prototype.Pu);_.M("gapi.auth2.GoogleAuth",Mx);
_.M("gapi.auth2.GoogleAuth.prototype.attachClickHandler",Mx.prototype.KG);_.M("gapi.auth2.GoogleAuth.prototype.disconnect",Mx.prototype.disconnect);_.M("gapi.auth2.GoogleAuth.prototype.grantOfflineAccess",Mx.prototype.Jq);_.M("gapi.auth2.GoogleAuth.prototype.signIn",Mx.prototype.wj);_.M("gapi.auth2.GoogleAuth.prototype.signOut",Mx.prototype.xj);_.M("gapi.auth2.GoogleAuth.prototype.getInitialScopes",Mx.prototype.dJ);_.M("gapi.auth2.GoogleUser",kx);_.M("gapi.auth2.GoogleUser.prototype.grant",kx.prototype.AV);
_.M("gapi.auth2.GoogleUser.prototype.getId",kx.prototype.ka);_.M("gapi.auth2.GoogleUser.prototype.isSignedIn",kx.prototype.Bf);_.M("gapi.auth2.GoogleUser.prototype.getAuthResponse",kx.prototype.jk);_.M("gapi.auth2.GoogleUser.prototype.getBasicProfile",kx.prototype.TT);_.M("gapi.auth2.GoogleUser.prototype.getGrantedScopes",kx.prototype.yU);_.M("gapi.auth2.GoogleUser.prototype.getHostedDomain",kx.prototype.vA);_.M("gapi.auth2.GoogleUser.prototype.grantOfflineAccess",kx.prototype.Jq);
_.M("gapi.auth2.GoogleUser.prototype.hasGrantedScopes",kx.prototype.ov);_.M("gapi.auth2.GoogleUser.prototype.reloadAuthResponse",kx.prototype.jD);_.M("gapi.auth2.LiveValue",ax);_.M("gapi.auth2.LiveValue.prototype.listen",ax.prototype.U);_.M("gapi.auth2.LiveValue.prototype.get",ax.prototype.get);_.M("gapi.auth2.SigninOptionsBuilder",dx);_.M("gapi.auth2.SigninOptionsBuilder.prototype.getAppPackageName",dx.prototype.QT);_.M("gapi.auth2.SigninOptionsBuilder.prototype.setAppPackageName",dx.prototype.k0);
_.M("gapi.auth2.SigninOptionsBuilder.prototype.getScope",dx.prototype.Hq);_.M("gapi.auth2.SigninOptionsBuilder.prototype.setScope",dx.prototype.SN);_.M("gapi.auth2.SigninOptionsBuilder.prototype.getPrompt",dx.prototype.eV);_.M("gapi.auth2.SigninOptionsBuilder.prototype.setPrompt",dx.prototype.O0);_.M("gapi.auth2.SigninOptionsBuilder.prototype.get",dx.prototype.get);

_.Ue.J4=function(a){var b=[];if(1<arguments.length)for(var c=0,d;d=arguments[c];++c)b.push(d);else b=a;return function(e){for(var f=0;b[f];++f)if(e===b[f])return!0;return!1}};_.Ue.L7=function(a){return function(b){return a.test(b)}};_.Ue.CP=function(a){return"undefined"!==typeof a};_.Ue.L6=function(a){return"string"===typeof a&&0<a.length};_.Ue.e3=function(a){return"boolean"===typeof a};_.Ue.Z5=function(a){return function(b){for(var c in a)if(a.hasOwnProperty(c)&&!(0,a[c])(b[c]))return!1;return!0}};

_.Qe=_.Qe||{};
(function(){function a(b){var c="";if(3==b.nodeType||4==b.nodeType)c=b.nodeValue;else if(b.innerText)c=b.innerText;else if(b.innerHTML)c=b.innerHTML;else if(b.firstChild){c=[];for(b=b.firstChild;b;b=b.nextSibling)c.push(a(b));c=c.join("")}return c}_.Qe.createElement=function(b){if(!document.body||document.body.namespaceURI)try{var c=document.createElementNS("http://www.w3.org/1999/xhtml",b)}catch(d){}return c||document.createElement(b)};_.Qe.wH=function(b){var c=_.Qe.createElement("iframe");try{var d=
["<","iframe"],e=b||{},f;for(f in e)e.hasOwnProperty(f)&&(d.push(" "),d.push(f),d.push('="'),d.push(_.Qe.tu(e[f])),d.push('"'));d.push("></");d.push("iframe");d.push(">");var g=_.Qe.createElement(d.join(""));g&&(!c||g.tagName==c.tagName&&g.namespaceURI==c.namespaceURI)&&(c=g)}catch(l){}d=c;b=b||{};for(var k in b)b.hasOwnProperty(k)&&(d[k]=b[k]);return c};_.Qe.JI=function(){if(document.body)return document.body;try{var b=document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml","body");if(b&&
1==b.length)return b[0]}catch(c){}return document.documentElement||document};_.Qe.gaa=function(b){return a(b)}})();

_.Qe=_.Qe||{};(function(){function a(d){b=d["core.util"]||{}}var b={},c={};_.Ue&&_.Ue.register("core.util",null,a);_.Qe.faa=function(d){return"undefined"===typeof b[d]?null:b[d]};_.Qe.hasFeature=function(d){return"undefined"!==typeof b[d]};_.Qe.uaa=function(){return c}})();

_.Mh=function(){function a(){e[0]=1732584193;e[1]=4023233417;e[2]=2562383102;e[3]=271733878;e[4]=3285377520;n=m=0}function b(q){for(var t=g,r=0;64>r;r+=4)t[r/4]=q[r]<<24|q[r+1]<<16|q[r+2]<<8|q[r+3];for(r=16;80>r;r++)q=t[r-3]^t[r-8]^t[r-14]^t[r-16],t[r]=(q<<1|q>>>31)&4294967295;q=e[0];var v=e[1],u=e[2],w=e[3],z=e[4];for(r=0;80>r;r++){if(40>r)if(20>r){var A=w^v&(u^w);var B=1518500249}else A=v^u^w,B=1859775393;else 60>r?(A=v&u|w&(v|u),B=2400959708):(A=v^u^w,B=3395469782);A=((q<<5|q>>>27)&4294967295)+
A+z+B+t[r]&4294967295;z=w;w=u;u=(v<<30|v>>>2)&4294967295;v=q;q=A}e[0]=e[0]+q&4294967295;e[1]=e[1]+v&4294967295;e[2]=e[2]+u&4294967295;e[3]=e[3]+w&4294967295;e[4]=e[4]+z&4294967295}function c(q,t){if("string"===typeof q){q=unescape(encodeURIComponent(q));for(var r=[],v=0,u=q.length;v<u;++v)r.push(q.charCodeAt(v));q=r}t||(t=q.length);r=0;if(0==m)for(;r+64<t;)b(q.slice(r,r+64)),r+=64,n+=64;for(;r<t;)if(f[m++]=q[r++],n++,64==m)for(m=0,b(f);r+64<t;)b(q.slice(r,r+64)),r+=64,n+=64}function d(){var q=[],
t=8*n;56>m?c(k,56-m):c(k,64-(m-56));for(var r=63;56<=r;r--)f[r]=t&255,t>>>=8;b(f);for(r=t=0;5>r;r++)for(var v=24;0<=v;v-=8)q[t++]=e[r]>>v&255;return q}for(var e=[],f=[],g=[],k=[128],l=1;64>l;++l)k[l]=0;var m,n;a();return{reset:a,update:c,digest:d,Fg:function(){for(var q=d(),t="",r=0;r<q.length;r++)t+="0123456789ABCDEF".charAt(Math.floor(q[r]/16))+"0123456789ABCDEF".charAt(q[r]%16);return t}}};
var Oh=function(a,b,c){var d=String(_.C.location.href);return d&&a&&b?[b,Nh(_.vg(d),a,c||null)].join(" "):null},Nh=function(a,b,c){var d=[],e=[];if(1==(Array.isArray(c)?2:1))return e=[b,a],_.mb(d,function(k){e.push(k)}),Ph(e.join(" "));var f=[],g=[];_.mb(c,function(k){g.push(k.key);f.push(k.value)});c=Math.floor((new Date).getTime()/1E3);e=0==f.length?[c,b,a]:[f.join(":"),c,b,a];_.mb(d,function(k){e.push(k)});a=Ph(e.join(" "));a=[c,a];0==g.length||a.push(g.join(""));return a.join("_")},Ph=function(a){var b=
_.Mh();b.update(a);return b.Fg().toLowerCase()};
var Sh;_.Qh=function(a){return!!_.Ih.FPA_SAMESITE_PHASE2_MOD||!(void 0===a||!a)};_.Rh=function(a){a=void 0===a?!1:a;var b=_.C.__SAPISID||_.C.__APISID||_.C.__3PSAPISID||_.C.__OVERRIDE_SID;_.Qh(a)&&(b=b||_.C.__1PSAPISID);if(b)return!0;var c=new _.Jh(document);b=c.get("SAPISID")||c.get("APISID")||c.get("__Secure-3PAPISID")||c.get("SID");_.Qh(a)&&(b=b||c.get("__Secure-1PAPISID"));return!!b};Sh=function(a,b,c,d){(a=_.C[a])||(a=(new _.Jh(document)).get(b));return a?Oh(a,c,d):null};
_.Th=function(a,b){b=void 0===b?!1:b;var c=_.vg(String(_.C.location.href)),d=[];if(_.Rh(b)){c=0==c.indexOf("https:")||0==c.indexOf("chrome-extension:")||0==c.indexOf("moz-extension:");var e=c?_.C.__SAPISID:_.C.__APISID;e||(e=new _.Jh(document),e=e.get(c?"SAPISID":"APISID")||e.get("__Secure-3PAPISID"));(e=e?Oh(e,c?"SAPISIDHASH":"APISIDHASH",a):null)&&d.push(e);c&&_.Qh(b)&&((b=Sh("__1PSAPISID","__Secure-1PAPISID","SAPISID1PHASH",a))&&d.push(b),(a=Sh("__3PSAPISID","__Secure-3PAPISID","SAPISID3PHASH",
a))&&d.push(a))}return 0==d.length?null:d.join(" ")};

_.Uh=function(a,b){var c={SAPISIDHASH:!0,SAPISID3PHASH:!0,APISIDHASH:!0};_.Qh(void 0===b?!1:b)&&(c.SAPISID1PHASH=!0);return a&&(a.OriginToken||a.Authorization&&c[String(a.Authorization).split(" ")[0]])?!0:!1};_.Vh={WJ:_.Uh,SX:_.Rh,iJ:function(){var a=null;_.Rh()&&(a=window.__PVT,null==a&&(a=(new _.Jh(document)).get("BEAT")));return a},HI:_.Th};

_.tg=window.gapi&&window.gapi.util||{};

_.tg=_.tg={};_.tg.lb=function(a){return _.vg(a)};

_.bz=function(a){if(0!==a.indexOf("GCSC"))return null;var b={TB:!1};a=a.substr(4);if(!a)return b;var c=a.charAt(0);a=a.substr(1);var d=a.lastIndexOf("_");if(-1==d)return b;var e=_.$y(a.substr(d+1));if(null==e)return b;a=a.substring(0,d);if("_"!==a.charAt(0))return b;d="E"===c&&e.xe;return!d&&("U"!==c||e.xe)||d&&!_.az?b:{TB:!0,xe:d,tS:a.substr(1),domain:e.domain,rh:e.rh}};
_.cz=function(a,b){this.Ue=a;a=b||{};this.uY=Number(a.maxAge)||0;this.tc=a.domain;this.Nk=a.path;this.O_=!!a.secure};_.cz.prototype.read=function(){for(var a=this.Ue+"=",b=document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c];if(0==d.indexOf(a))return d.substr(a.length)}};
_.cz.prototype.write=function(a,b){if(!dz.test(this.Ue))throw"Invalid cookie name";if(!ez.test(a))throw"Invalid cookie value";a=this.Ue+"="+a;this.tc&&(a+=";domain="+this.tc);this.Nk&&(a+=";path="+this.Nk);b="number"===typeof b?b:this.uY;if(0<=b){var c=new Date;c.setSeconds(c.getSeconds()+b);a+=";expires="+c.toUTCString()}this.O_&&(a+=";secure");document.cookie=a;return!0};_.cz.prototype.clear=function(){this.write("",0)};var ez=/^[-+/_=.:|%&a-zA-Z0-9@]*$/,dz=/^[A-Z_][A-Z0-9_]{0,63}$/;
_.cz.iterate=function(a){for(var b=document.cookie.split(/;\s*/),c=0;c<b.length;++c){var d=b[c].split("="),e=d.shift();a(e,d.join("="))}};
_.fz=function(a){this.Oh=a};_.fz.prototype.read=function(){if(gz.hasOwnProperty(this.Oh))return gz[this.Oh]};_.fz.prototype.write=function(a){gz[this.Oh]=a;return!0};_.fz.prototype.clear=function(){delete gz[this.Oh]};var gz={};_.fz.iterate=function(a){for(var b in gz)gz.hasOwnProperty(b)&&a(b,gz[b])};
var hz=function(){this.fe=null;this.key=function(){return null};this.getItem=function(){return this.fe};this.setItem=function(a,b){this.fe=b;this.length=1};this.removeItem=function(){this.clear()};this.clear=function(){this.fe=null;this.length=0};this.length=0},iz=function(a){try{var b=a||window.sessionStorage;if(!b)return!1;b.setItem("gapi.sessionStorageTest","gapi.sessionStorageTest"+b.length);b.removeItem("gapi.sessionStorageTest");return!0}catch(c){return!1}},jz=function(a,b){this.Ue=a;this.Kf=
iz(b)?b||window.sessionStorage:new hz};jz.prototype.read=function(){return this.Kf.getItem(this.Ue)};jz.prototype.write=function(a){try{this.Kf.setItem(this.Ue,a)}catch(b){return!1}return!0};jz.prototype.clear=function(){this.Kf.removeItem(this.Ue)};jz.iterate=function(a){if(iz())for(var b=0,c=window.sessionStorage.length;b<c;++b){var d=window.sessionStorage.key(b);a(d,window.sessionStorage[d])}};
for(var kz=0;64>kz;++kz);
_.az="https:"===window.location.protocol;_.lz=_.az||"http:"===window.location.protocol?_.cz:_.fz;_.$y=function(a){var b=a.substr(1),c="",d=window.location.hostname;if(""!==b){c=parseInt(b,10);if(isNaN(c))return null;b=d.split(".");if(b.length<c-1)return null;b.length==c-1&&(d="."+d)}else d="";return{xe:"S"==a.charAt(0),domain:d,rh:c}};
var mz,nz,qz,rz;mz=_.se();nz=_.se();_.oz=_.se();_.pz=_.se();qz="state code cookie_policy g_user_cookie_policy authuser prompt g-oauth-window status".split(" ");rz=function(a){this.oM=a;this.mC=null};
rz.prototype.write=function(a){var b=_.se(),c=_.se(),d=window.decodeURIComponent?decodeURIComponent:unescape,e;for(e in a)if(_.te(a,e)){var f=a[e];f=f.replace(/\+/g," ");c[e]=d(f);b[e]=a[e]}d=0;for(e=qz.length;d<e;++d)delete c[qz[d]];a=String(a.authuser||0);d=_.se();d[a]=c;c=_.Bf(d);this.oM.write(c);this.mC=b};rz.prototype.read=function(){return this.mC};rz.prototype.clear=function(){this.oM.clear();this.mC=_.se()};_.sz=function(a){return a?{domain:a.domain,path:"/",secure:a.xe}:null};
jz.iterate(function(a){var b=_.bz(a);b&&b.TB&&(mz[a]=new rz(new jz(a)))});_.lz.iterate(function(a){mz[a]&&(nz[a]=new _.lz(a,_.sz(_.bz(a))))});

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var rr,sr,ur,vr,wr,xr,yr,zr,Ar,Dr,Er,Fr,Gr,Kr,Or,Pr,Qr;_.fr=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};_.gr=function(a,b,c,d){return Array.prototype.splice.apply(a,_.fr(arguments,1))};_.hr=function(a,b){return a==b?!0:a&&b?a.x==b.x&&a.y==b.y:!1};_.ir=function(a,b){this.x=void 0!==a?a:0;this.y=void 0!==b?b:0};_.h=_.ir.prototype;_.h.clone=function(){return new _.ir(this.x,this.y)};
_.h.equals=function(a){return a instanceof _.ir&&_.hr(this,a)};_.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};_.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};_.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.h.translate=function(a,b){a instanceof _.ir?(this.x+=a.x,this.y+=a.y):(this.x+=Number(a),"number"===typeof b&&(this.y+=b));return this};
_.h.scale=function(a,b){this.x*=a;this.y*="number"===typeof b?b:a;return this};_.jr=function(a,b){this.width=a;this.height=b};_.h=_.jr.prototype;_.h.clone=function(){return new _.jr(this.width,this.height)};_.h.aspectRatio=function(){return this.width/this.height};_.h.isEmpty=function(){return!(this.width*this.height)};_.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
_.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.h.scale=function(a,b){this.width*=a;this.height*="number"===typeof b?b:a;return this};_.kr=function(a){return"CSS1Compat"==a.compatMode};_.lr=function(a){a=a.document;a=_.kr(a)?a.documentElement:a.body;return new _.jr(a.clientWidth,a.clientHeight)};_.mr=function(a){return _.lr(a||window)};
_.nr=function(a){return a.scrollingElement?a.scrollingElement:!_.Cc&&_.kr(a)?a.documentElement:a.body||a.documentElement};_.or=function(a){var b=_.nr(a);a=a.parentWindow||a.defaultView;return _.yc&&_.Uc("10")&&a.pageYOffset!=b.scrollTop?new _.ir(b.scrollLeft,b.scrollTop):new _.ir(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};_.pr=function(a,b,c,d){return _.Wd(a.ob,b,c,d)};_.qr=function(a){a.KB=void 0;a.Qa=function(){return a.KB?a.KB:a.KB=new a}};
rr=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");_.$c.call(this,c+a[d])};_.Va(rr,_.$c);rr.prototype.name="AssertionError";sr={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};_.tr=function(a){if(a instanceof _.Rb&&a.constructor===_.Rb)return a.dD;_.bb(a);return"type_error:SafeStyle"};ur=/\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g;
vr=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g;wr=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/;xr=/\/\*/;yr=function(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b};zr=function(a){return a.replace(vr,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(g,k,l){f=k;return l});b=(_.yd(d)||_.Pb).vd();return c+f+b+f+e})};
Ar=function(a){if(a instanceof _.Ob)return'url("'+_.td(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof _.Bb)a=_.Fb(a);else{a=String(a);var b=a.replace(ur,"$1").replace(ur,"$1").replace(vr,"url");if(wr.test(b)){if(b=!xr.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c&&yr(a)}a=b?zr(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new rr("Value does not allow [{;}], got: %s.",[a]);return a};
_.Br=function(a){var b="",c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("g`"+c);var d=a[c];null!=d&&(d=Array.isArray(d)?_.pb(d,Ar).join(" "):Ar(d),b+=c+":"+d+";")}return b?new _.Rb(b,_.Qb):_.Tb};_.Cr=function(a){if(a instanceof _.Vb&&a.constructor===_.Vb)return a.cD;_.bb(a);return"type_error:SafeStyleSheet"};Dr=/^[a-zA-Z0-9-]+$/;Er={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};
Fr={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};Gr=function(a){var b=_.Ad(_.mc),c=b.Ah(),d=[],e=function(f){Array.isArray(f)?_.mb(f,e):(f=_.Ad(f),d.push(_.kc(f).toString()),f=f.Ah(),0==c?c=f:0!=f&&c!=f&&(c=null))};_.mb(a,e);return _.lc(d.join(_.kc(b).toString()),c)};_.Hr=function(a){return Gr(Array.prototype.slice.call(arguments))};
_.Ir=function(a,b,c){var d=String(a);if(!Dr.test(d))throw Error("k");if(d.toUpperCase()in Fr)throw Error("k");a=String(a);d=null;var e="<"+a,f="";if(b)for(l in b)if(Object.prototype.hasOwnProperty.call(b,l)){if(!Dr.test(l))throw Error("k");var g=b[l];if(null!=g){var k=l;if(g instanceof _.Bb)g=_.Fb(g);else if("style"==k.toLowerCase()){if(!_.$a(g))throw Error("k");g instanceof _.Rb||(g=_.Br(g));g=_.tr(g)}else{if(/^on/i.test(k))throw Error("k");if(k.toLowerCase()in Er)if(g instanceof _.fd)g=_.hd(g);
else if(g instanceof _.Ob)g=_.td(g);else if("string"===typeof g)g=(_.yd(g)||_.Pb).vd();else throw Error("k");}g.Ih&&(g=g.vd());k=k+'="'+_.sd(String(g))+'"';f+=" "+k}}var l=e+f;null==c?c=[]:Array.isArray(c)||(c=[c]);!0===sr[a.toLowerCase()]?l+=">":(c=_.Hr(c),l+=">"+_.kc(c).toString()+"</"+a+">",d=c.Ah());(b=b&&b.dir)&&(d=/^(ltr|rtl|auto)$/i.test(b)?0:null);return _.lc(l,d)};_.Jr=function(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};
Kr=function(a){return a.replace(/(^|[\s]+)([a-z])/g,function(b,c,d){return c+d.toUpperCase()})};_.Lr=function(a,b,c){return _.be(document,arguments)};_.Mr=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};_.Nr=function(a){var b;if(_.Od&&!(_.yc&&_.Uc("9")&&!_.Uc("10")&&_.C.SVGElement&&a instanceof _.C.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return _.ke(b)?b:null};Or={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};Pr={IMG:" ",BR:"\n"};
Qr=function(a,b,c){if(!(a.nodeName in Or))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Pr)b.push(Pr[a.nodeName]);else for(a=a.firstChild;a;)Qr(a,b,c),a=a.nextSibling};
_.Rr=function(a){if(_.Nd&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Qr(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.Nd||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.Sr=function(a){var b=[];Qr(a,b,!1);return b.join("")};
_.Tr=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};_.h=_.Tr.prototype;_.h.Dc=function(){return this.right-this.left};_.h.Hd=function(){return this.bottom-this.top};_.h.clone=function(){return new _.Tr(this.top,this.right,this.bottom,this.left)};_.h.contains=function(a){return this&&a?a instanceof _.Tr?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
_.h.expand=function(a,b,c,d){_.$a(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=Number(b),this.bottom+=Number(c),this.left-=Number(d));return this};_.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
_.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};_.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
_.h.translate=function(a,b){a instanceof _.ir?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,"number"===typeof b&&(this.top+=b,this.bottom+=b));return this};_.h.scale=function(a,b){b="number"===typeof b?b:a;this.left*=a;this.right*=a;this.top*=b;this.bottom*=b;return this};
var Wr,bs,$r,es,qs,rs;_.Vr=function(a,b,c){if("string"===typeof b)(b=_.Ur(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=_.Ur(c,d);f&&(c.style[f]=e)}};Wr={};_.Ur=function(a,b){var c=Wr[b];if(!c){var d=_.Jr(b);c=d;void 0===a.style[d]&&(d=(_.Cc?"Webkit":_.Bc?"Moz":_.yc?"ms":_.xc?"O":null)+Kr(d),void 0!==a.style[d]&&(c=d));Wr[b]=c}return c};
_.Xr=function(a,b){var c=_.Td(a);return c.defaultView&&c.defaultView.getComputedStyle&&(a=c.defaultView.getComputedStyle(a,null))?a[b]||a.getPropertyValue(b)||"":""};_.Yr=function(a,b){return a.currentStyle?a.currentStyle[b]:null};_.Zr=function(a,b){return _.Xr(a,b)||_.Yr(a,b)||a.style&&a.style[b]};_.as=function(a,b,c){if(b instanceof _.ir){var d=b.x;b=b.y}else d=b,b=c;a.style.left=$r(d,!1);a.style.top=$r(b,!1)};
bs=function(a){try{return a.getBoundingClientRect()}catch(b){return{left:0,top:0,right:0,bottom:0}}};
_.fs=function(a,b){b=b||_.nr(document);var c=b||_.nr(document);var d=_.cs(a),e=_.cs(c),f=_.ds(c);if(c==_.nr(document)){var g=d.x-c.scrollLeft;d=d.y-c.scrollTop;_.yc&&!_.Kd(10)&&(g+=f.left,d+=f.top)}else g=d.x-e.x-f.left,d=d.y-e.y-f.top;a=es(a);f=c.clientHeight-a.height;e=c.scrollLeft;var k=c.scrollTop;e+=Math.min(g,Math.max(g-(c.clientWidth-a.width),0));k+=Math.min(d,Math.max(d-f,0));c=new _.ir(e,k);b.scrollLeft=c.x;b.scrollTop=c.y};
_.cs=function(a){var b=_.Td(a),c=new _.ir(0,0);var d=b?_.Td(b):document;d=!_.yc||_.Kd(9)||_.kr(_.Ud(d).ob)?d.documentElement:d.body;if(a==d)return c;a=bs(a);b=_.or(_.Ud(b).ob);c.x=a.left+b.x;c.y=a.top+b.y;return c};_.hs=function(a,b){var c=new _.ir(0,0),d=_.Zd(_.Td(a));if(!_.vc(d,"parent"))return c;do{var e=d==b?_.cs(a):_.gs(a);c.x+=e.x;c.y+=e.y}while(d&&d!=b&&d!=d.parent&&(a=d.frameElement)&&(d=d.parent));return c};_.gs=function(a){a=bs(a);return new _.ir(a.left,a.top)};
_.is=function(a,b,c){if(b instanceof _.jr)c=b.height,b=b.width;else if(void 0==c)throw Error("G");a.style.width=$r(b,!0);a.style.height=$r(c,!0)};$r=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};_.js=function(a){var b=es;if("none"!=_.Zr(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a};
es=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=_.Cc&&!b&&!c;return(void 0===b||d)&&a.getBoundingClientRect?(a=bs(a),new _.jr(a.right-a.left,a.bottom-a.top)):new _.jr(b,c)};_.ks=function(a,b){a.style.display=b?"":"none"};
_.ms=function(a){var b=_.Ud(void 0),c=b.tb();if(_.yc&&c.createStyleSheet)return b=c.createStyleSheet(),_.ls(b,a),b;c=_.pr(b,"HEAD")[0];if(!c){var d=_.pr(b,"BODY")[0];c=b.ma("HEAD");d.parentNode.insertBefore(c,d)}d=b.ma("STYLE");var e=_.Id();e&&d.setAttribute("nonce",e);_.ls(d,a);b.appendChild(c,d);return d};_.ls=function(a,b){b=_.Cr(b);_.yc&&void 0!==a.cssText?a.cssText=b:_.C.trustedTypes?_.me(a,b):a.innerHTML=b};_.ns=function(a){return"rtl"==_.Zr(a,"direction")};
_.os=_.Bc?"MozUserSelect":_.Cc||_.zc?"WebkitUserSelect":null;_.ps=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;b=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+b};qs={thin:2,medium:4,thick:6};rs=function(a,b){if("none"==_.Yr(a,b+"Style"))return 0;b=_.Yr(a,b+"Width");return b in qs?qs[b]:_.ps(a,b)};
_.ds=function(a){if(_.yc&&!_.Kd(9)){var b=rs(a,"borderLeft"),c=rs(a,"borderRight"),d=rs(a,"borderTop");a=rs(a,"borderBottom");return new _.Tr(d,c,a,b)}b=_.Xr(a,"borderLeftWidth");c=_.Xr(a,"borderRightWidth");d=_.Xr(a,"borderTopWidth");a=_.Xr(a,"borderBottomWidth");return new _.Tr(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.my=function(a,b,c){if("function"===typeof a)c&&(a=(0,_.R)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.R)(a.handleEvent,a);else throw Error("pa");return 2147483647<Number(b)?-1:_.C.setTimeout(a,b||0)};_.ny=function(a){_.C.clearTimeout(a)};_.oy=function(a){var b=null;return(new _.Ek(function(c,d){b=_.my(function(){c(void 0)},a);-1==b&&d(Error("qa"))})).Uo(function(c){_.ny(b);throw c;})};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.tz=function(a){this.R1=a};_.tz.prototype.toString=function(){return this.R1};
_.uz=function(a){_.Gi.call(this);this.Oh=1;this.Nw=[];this.Tw=0;this.df=[];this.vi={};this.OR=!!a};_.Va(_.uz,_.Gi);_.h=_.uz.prototype;_.h.subscribe=function(a,b,c){var d=this.vi[a];d||(d=this.vi[a]=[]);var e=this.Oh;this.df[e]=a;this.df[e+1]=b;this.df[e+2]=c;this.Oh=e+3;d.push(e);return e};_.h.Ds=_.ha(38);_.h.unsubscribe=function(a,b,c){if(a=this.vi[a]){var d=this.df;if(a=_.ti(a,function(e){return d[e+1]==b&&d[e+2]==c}))return this.Dj(a)}return!1};
_.h.Dj=function(a){var b=this.df[a];if(b){var c=this.vi[b];0!=this.Tw?(this.Nw.push(a),this.df[a+1]=_.ab):(c&&_.Bi(c,a),delete this.df[a],delete this.df[a+1],delete this.df[a+2])}return!!b};
_.h.vo=function(a,b){var c=this.vi[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.OR)for(e=0;e<c.length;e++){var g=c[e];vz(this.df[g+1],this.df[g+2],d)}else{this.Tw++;try{for(e=0,f=c.length;e<f;e++)g=c[e],this.df[g+1].apply(this.df[g+2],d)}finally{if(this.Tw--,0<this.Nw.length&&0==this.Tw)for(;c=this.Nw.pop();)this.Dj(c)}}return 0!=e}return!1};var vz=function(a,b,c){_.Ck(function(){a.apply(b,c)})};
_.uz.prototype.clear=function(a){if(a){var b=this.vi[a];b&&(_.mb(b,this.Dj,this),delete this.vi[a])}else this.df.length=0,this.vi={}};_.uz.prototype.Gb=function(a){if(a){var b=this.vi[a];return b?b.length:0}a=0;for(b in this.vi)a+=this.Gb(b);return a};_.uz.prototype.na=function(){_.uz.O.na.call(this);this.clear();this.Nw.length=0};
_.wz=function(a){_.Gi.call(this);this.Kd=new _.uz(a);_.Ii(this,this.Kd)};_.Va(_.wz,_.Gi);_.h=_.wz.prototype;_.h.subscribe=function(a,b,c){return this.Kd.subscribe(a.toString(),b,c)};_.h.Ds=_.ha(37);_.h.unsubscribe=function(a,b,c){return this.Kd.unsubscribe(a.toString(),b,c)};_.h.Dj=function(a){return this.Kd.Dj(a)};_.h.vo=function(a,b){return this.Kd.vo(a.toString(),b)};_.h.clear=function(a){this.Kd.clear(void 0!==a?a.toString():void 0)};
_.h.Gb=function(a){return this.Kd.Gb(void 0!==a?a.toString():void 0)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.xz=function(a,b){Array.isArray(b)||(b=[b]);b=_.pb(b,function(c){return"string"===typeof c?c:c.Rw+" "+c.duration+"s "+c.timing+" "+c.delay+"s"});_.Vr(a,"transition",b.join(","))};
_.yz=_.oc(function(){if(_.yc)return _.Uc("10.0");var a=_.ce("DIV"),b=_.Cc?"-webkit":_.Bc?"-moz":_.yc?"-ms":_.xc?"-o":null,c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=_.Ir("div",{style:c});_.Bd(a,b);a=a.firstChild;b=a.style[_.Jr("transition")];return""!=("undefined"!==typeof b?b:a.style[_.Ur(a,"transition")]||"")});

_.Az=function(){_.zz="oauth2relay"+String(2147483647*(0,_.yg)()|0)};_.Bz=new _.wz;_.Cz=new _.tz("oauth");_.Az();_.Le("oauth-flow/client_id");var Dz=String(_.Le("oauth-flow/redirectUri"));if(Dz)Dz.replace(/[#][\s\S]*/,"");else{var Ez=_.tg.lb(window.location.href);_.Le("oauth-flow/callbackUrl");encodeURIComponent(Ez)}_.tg.lb(window.location.href);

var Gz,Hz,Iz,Jz,Kz,Lz,Mz,Nz,Oz,Pz,Qz,nA,oA,pA,qA,rA,sA,tA,uA,vA,wA,xA,yA,zA,AA,BA,CA,DA,EA,FA,GA,HA,IA,JA,KA,LA,MA,NA,OA,PA,QA,RA,UA,TA,VA,WA,XA,YA,ZA,$A,bB,cB,eB;_.Fz=function(a,b){if(_.mh&&!b)return _.C.atob(a);var c="";_.ph(a,function(d){c+=String.fromCharCode(d)});return c};Gz=function(a){var b=String(a("immediate")||"");a=String(a("prompt")||"");return"true"===b||"none"===a};Hz=function(a){return _.Fh("enableMultilogin")&&a("cookie_policy")&&!Gz(a)?!0:!1};
Kz=function(){var a,b=null;_.lz.iterate(function(c,d){0===c.indexOf("G_AUTHUSER_")&&(c=_.$y(c.substring(11)),!a||c.xe&&!a.xe||c.xe==a.xe&&c.rh>a.rh)&&(a=c,b=d)});return{ZR:a,authuser:b}};Lz=[".APPS.GOOGLEUSERCONTENT.COM","@DEVELOPER.GSERVICEACCOUNT.COM"];Mz=function(a){a=a.toUpperCase();for(var b=0,c=Lz.length;b<c;++b){var d=a.split(Lz[b]);2==d.length&&""===d[1]&&(a=d[0])}a=a.replace(/-/g,"_").toUpperCase();40<a.length&&(b=new _.ai,b.Qx(a),a=b.Fg().toUpperCase());return a};
Nz=function(a){if(!a)return[];a=a.split("=");return a[1]?a[1].split("|"):[]};Oz=function(a){a=a.split(":");return{clientId:a[0].split("=")[1],i0:Nz(a[1]),Vaa:Nz(a[2]),S$:Nz(a[3])}};Pz=function(a){var b=Kz(),c=b.ZR;b=b.authuser;var d=a&&Mz(a);if(null!==b){var e;_.lz.iterate(function(g,k){(g=_.bz(g))&&g.TB&&(d&&g.tS!=d||g.xe==c.xe&&g.rh==c.rh&&(e=k))});if(e){var f=Oz(e);a=f&&f.i0[Number(b)];f=f&&f.clientId;if(a)return{authuser:b,Mba:a,clientId:f}}}return null};
Qz=function(a,b){a=_.Xh(a);if(!a||!b&&a.error)return null;b=Math.floor((new Date).getTime()/1E3);return a.expires_at&&b>a.expires_at?null:a};_.cA=function(a,b){if(b){var c=b;var d=a}else"string"===typeof a?d=a:c=a;c?_.Cw(c,d):_.Dw(d)};
nA=function(a){if(!a)return null;"single_host_origin"!==a&&(a=_.vg(a));var b=window.location.hostname,c=b,d=_.az;if("single_host_origin"!==a){c=a.split("://");if(2==c.length)d="https"===c.shift();else return _.Ff("WARNING invalid cookie_policy: "+a),null;c=c[0]}if(-1!==c.indexOf(":"))c=b="";else{a="."+c;if(b.lastIndexOf(a)!==b.length-a.length)return _.Ff("Invalid cookie_policy domain: "+c),null;c=a;b=c.split(".").length-1}return{domain:c,xe:d,rh:b}};
oA=function(a){var b=nA(a);if(!b)return new _.fz("G_USERSTATE_");a=["G_USERSTATE_",_.az&&b.xe?"S":"H",b.rh].join("");var c=_.pz[a];c||(c={kC:63072E3},_.ue(_.sz(b),c),c=new _.cz(a,c),_.pz[a]=c,b=c.read(),"undefined"!==typeof b&&null!==b&&(document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/",c.write(b)));return c};pA=function(a){var b=oA(a).read();a=_.se();if(b){b=b.split(":");for(var c;c=b.shift();)c=c.split("="),a[c[0]]=c[1]}return a};
qA=function(a,b,c){var d=pA(b),e=d[a];d[a]="0";var f=[];_.im(d,function(k,l){f.push(l+"="+k)});var g=f.join(":");b=oA(b);g?b.write(g):b.clear();d[a]!==e&&c&&c()};rA=function(a,b){b=pA(b);return"0"==b[a]||"X"==b[a]};sA=function(a){a=nA(a.g_user_cookie_policy);if(!a||a.xe&&!_.az)a=null;else{var b=["G_AUTHUSER_",_.az&&a.xe?"S":"H",a.rh].join(""),c=_.oz[b];c||(c=new _.lz(b,_.sz(a)),_.oz[b]=c);a=c}_.Ne("googleapis.config/sessionIndex",null);a.clear()};tA=function(a){return Gz(function(b){return a[b]})};
uA=0;vA=!1;wA=[];xA={};yA={};zA=null;AA=function(a){var b=_.zz;return function(c){if(this.f==b&&this.t==_.Mf.El(this.f)&&this.origin==_.Mf.Rl(this.f))return a.apply(this,arguments)}};BA=function(a){"function"===typeof a.setAttribute?a.setAttribute("aria-hidden","true"):a["aria-hidden"]="true"};CA=function(a){if(a&&!decodeURIComponent(a).startsWith("m;/_/scs/"))throw Error("ta");};
DA=function(a){var b=_.Qe.Me,c=b(a).jsh;if(null!=c)return CA(c),a;if(b=String(b().jsh||_.De.h||""))CA(b),c=(a+"#").indexOf("#"),a=a.substr(0,c)+(-1!==a.substr(0,c).indexOf("?")?"&":"?")+"jsh="+encodeURIComponent(b)+a.substr(c);return a};EA=function(){return!!_.Le("oauth-flow/usegapi")};FA=function(a,b){EA()?zA.unregister(a):_.Mf.unregister(a+":"+b)};GA=function(a,b,c){EA()?zA.register(a,c,_.ym):_.Mf.register(a+":"+b,AA(c))};HA=function(){Iz.parentNode.removeChild(Iz)};
IA=function(a){var b=Iz;_.xz(b,[{Rw:"-webkit-transform",duration:1,timing:"ease",delay:0}]);_.xz(b,[{Rw:"transform",duration:1,timing:"ease",delay:0}]);_.my(function(){b.style.webkitTransform="translate3d(0px,"+a+"px,0px)";b.style.transform="translate3d(0px,"+a+"px,0px)"},0)};JA=function(){var a=Jz+88;IA(a);Jz=a};KA=function(){var a=Jz-88;IA(a);Jz=a};
LA=function(a){var b=a?JA:KA,c=a?KA:JA;a=a?"-":"";Jz=parseInt(a+88,10);Iz.style.webkitTransform="translate3d(0px,"+a+88+"px,0px)";Iz.style.transform="translate3d(0px,"+a+88+"px,0px)";Iz.style.display="";Iz.style.visibility="visible";b();_.my(c,4E3);_.my(HA,5E3)};
MA=function(a){var b=_.Le("oauth-flow/toast/position");"top"!==b&&(b="bottom");var c=document.createElement("div");Iz=c;c.style.cssText="position:fixed;left:0px;z-index:1000;width:100%;";_.Vr(c,"visibility","hidden");_.Vr(c,b,"-40px");_.Vr(c,"height","128px");var d=c;if("desktop"==_.Le("deviceType")){d=document.createElement("div");d.style.cssText="float:left;position:relative;left:50%;";c.appendChild(d);var e=document.createElement("div");e.style.cssText="float:left;position:relative;left:-50%";
d.appendChild(e);d=e}e="top"==b?"-":"";Jz=parseInt(e+88,10);Iz.style.webkitTransform="translate3d(0px,"+e+88+"px,0px)";Iz.style.transform="translate3d(0px,"+e+88+"px,0px)";e=window;try{for(;e.parent!=e&&e.parent.document;)e=e.parent}catch(f){}e=e.document.body;try{e.insertBefore(c,e.firstChild)}catch(f){}_.em.Th({url:":socialhost:/:session_prefix:_/widget/oauthflow/toast",queryParams:{clientId:a.client_id,idToken:a.id_token},where:d,onRestyle:function(){"top"===b?LA(!0):LA(!1)}})};
NA=function(a){var b=_.En(),c=b&&b.scope;b=a&&a.scope;b="string"===typeof b?b.split(" "):b||[];if(c){c=c.split(" ");for(var d=0;d<c.length;++d){var e=c[d];-1==_.gm.call(b,e)&&b.push(e)}0<b.length&&(a.scope=b.join(" "))}return a};
OA=function(a,b){var c=null;a&&b&&(c=b.client_id=b.client_id||a.client_id,b.scope=b.scope||a.scope,b.g_user_cookie_policy=a.cookie_policy,b.cookie_policy=b.cookie_policy||a.cookie_policy,b.response_type=b.response_type||a.response_type);if(b){b.issued_at||(b.issued_at=String(Math.floor((new Date).getTime()/1E3)));var d=parseInt(b.expires_in,10)||86400;b.error&&(d=_.Le("oauth-flow/errorMaxAge")||86400);b.expires_in=String(d);b.expires_at||(b.expires_at=String(Math.floor((new Date).getTime()/1E3)+d));
b._aa||b.error||null!=Pz(c)||!tA(a)||(b._aa="1");a=b.status={};a.google_logged_in=!!b.session_state;c=a.signed_in=!!b.access_token;a.method=c?b["g-oauth-window"]?"PROMPT":"AUTO":null}return b};PA=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+)\.?\.?\.?$/,"$1");a=_.Af(_.Fz(a,!0));if(!1===a)throw Error("ua");return a};QA=function(a){return(a=PA(a))?a.sub:null};
RA=function(a){a&&wA.push(a);a=_.zz;var b=document.getElementById(a),c=(new Date).getTime();if(b){if(uA&&6E4>c-uA)return;var d=_.Mf.El(a);d&&(FA("oauth2relayReady",d),FA("oauth2callback",d));b.parentNode.removeChild(b);if(/Firefox/.test(navigator.userAgent))try{window.frames[a]=void 0}catch(f){}_.Az();a=_.zz}uA=c;var e=String(2147483647*(0,_.yg)()|0);b=_.Le("oauth-flow/proxyUrl")||_.Le("oauth-flow/relayUrl");EA()?zA=_.em.Th({where:_.Qe.JI(),url:b,id:a,attributes:{style:{width:"1px",height:"1px",position:"absolute",
top:"-100px",display:"none"},"aria-hidden":"true"},dontclear:!0}):(b=[b,"?parent=",encodeURIComponent(_.tg.lb(window.location.href)),"#rpctoken=",e,"&forcesecure=1"].join(""),c=_.Qe.JI(),d=_.Qe.wH({name:a,id:a}),d.src=DA(b),d.style.width="1px",d.style.height="1px",d.style.position="absolute",d.style.top="-100px",d.tabIndex=-1,BA(d),c.appendChild(d),_.Mf.ts(a));GA("oauth2relayReady",e,function(){FA("oauth2relayReady",e);var f=wA;if(null!==f){wA=null;for(var g=0,k=f.length;g<k;++g)f[g]()}});GA("oauth2callback",
e,function(f){var g=_.Qe.Me;g=g(f);var k=g.state;f=k.replace(/\|.*$/,"");f={}.hasOwnProperty.call(yA,f)?yA[f]:null;g.state=f;if(null!=g.state){f=xA[k];delete xA[k];k=f&&f.key||"token";var l=g=OA(f&&f.params,g);var m=(m=QA(l))?rA(m,l.cookie_policy):!1;!m&&l&&0<=(" "+(l.scope||"")+" ").indexOf(" https://www.googleapis.com/auth/plus.login ")&&_.Le("isLoggedIn")&&"1"===(l&&l._aa)&&(l._aa="0",vA||(vA=!0,MA(l)));_.cA(k,g);g=Qz(k);if(f){k=f.popup;l=f.after_redirect;if(k&&"keep_open"!=l)try{k.close()}catch(n){}f.callback&&
(f.callback(g),f.callback=null)}}})};_.SA=function(a){null!==wA?RA(a):a&&a()};UA=function(a,b){var c=TA,d=QA(a);d&&(sA(a),qA(d,b,function(){if(c){var e={error:"user_signed_out"};e.client_id=a.client_id;e.g_user_cookie_policy=a.g_user_cookie_policy;e.scope=a.scope;e.response_type=a.response_type;e.session_state=a.session_state;e=OA(null,e);c(e)}}))};
TA=function(a){a||(a=Qz(void 0,!0));a&&"object"===typeof a||(a={error:"invalid_request",error_description:"no callback data"});var b=a.error_description;b&&window.console&&(window.console.error(a.error),window.console.error(b));a.error||(_.De.drw=null);_.cA(a);if(b=a.authuser)_.Le("googleapis.config/sessionIndex"),_.Ne("googleapis.config/sessionIndex",b);_.Bz.vo(_.Cz,a);return a};VA=["client_id","cookie_policy","response_type"];WA="client_id response_type login_hint authuser prompt include_granted_scopes after_redirect access_type hl state".split(" ");
XA=function(a){var b=_.ik(a);b.session_state&&b.session_state.extraQueryParams&&(b.authuser=b.session_state.extraQueryParams.authuser);b.session_state=null;a.expires_at&&(b.expires_at=parseInt(a.expires_at/1E3).toString());a.expires_in&&(b.expires_in=a.expires_in.toString());a.first_issued_at&&(b.issued_at=parseInt(a.first_issued_at/1E3).toString(),delete b.first_issued_at);_.Cw(b);return b};
YA=function(a){if(void 0===a.include_granted_scopes){var b=_.Le("include_granted_scopes");a.include_granted_scopes=!!b}};ZA=function(a){window.console&&("function"===typeof window.console.warn?window.console.warn(a):"function"===typeof window.console.log&&window.console.log(a))};
$A=function(a){var b=a||{},c={};_.mb(WA,function(d){null!=b[d]&&(c[d]=b[d])});a=_.Le("googleapis/overrideClientId");null!=a&&(c.client_id=a);YA(c);"string"===typeof b.scope?c.scope=b.scope:Array.isArray(b.scope)&&(c.scope=b.scope.join(" "));null!=b["openid.realm"]&&(c.openid_realm=b["openid.realm"]);null!=b.cookie_policy?c.cookie_policy=b.cookie_policy:null!=b.cookiepolicy&&(c.cookie_policy=b.cookiepolicy);null==c.login_hint&&null!=b.user_id&&(c.login_hint=b.user_id);try{_.tx(c.cookie_policy)}catch(d){c.cookie_policy&&
ZA("The cookie_policy configuration: '"+c.cookie_policy+"' is illegal, and thus ignored."),delete c.cookie_policy}null!=b.hd&&(c.hosted_domain=b.hd);null==c.prompt&&(1==b.immediate||"true"==b.immediate?c.prompt="none":"force"==b.approval_prompt&&(c.prompt="consent"));"none"==c.prompt&&(c.session_selection="first_valid");"none"==c.prompt&&"offline"==c.access_type&&delete c.access_type;"undefined"===typeof c.authuser&&(a=_.Hh(),null!=a&&(c.authuser=a));a=b.redirect_uri||_.Le("oauth-flow/redirectUri");
null!=a&&"postmessage"!=a&&(c.redirect_uri=a);c.gsiwebsdk="shim";return c};
_.aB=function(a,b){var c=$A(a),d=new _.Ek(function(e,f){_.Yx(c,function(g){var k=g||{};_.mb(VA,function(l){null==k[l]&&(k[l]=c[l])});!c.include_granted_scopes&&a&&a.scope&&(k.scope=a.scope);a&&null!=a.state&&(k.state=a.state);k.error?("none"==c.prompt&&"user_logged_out"==k.error&&(k.error="immediate_failed_user_logged_out"),f(k)):(g=XA(k),null!=g.authuser&&_.Ne("googleapis.config/sessionIndex",g.authuser),e(g))})});b&&d.then(b,b);return d};bB=_.Vh.HI;cB=null;
_.fB=function(a,b){if("force"!==a.approvalprompt){a=_.dB(a);a.prompt="none";delete a.redirect_uri;delete a.approval_prompt;delete a.immediate;if(b=!b)cB?(a.client_id!==cB.client_id&&window.console&&window.console.log&&window.console.log("Ignoring mismatched page-level auth param client_id="+a.client_id),b=!0):(cB=a,b=!1);b||eB(a)}};
_.dB=function(a){var b=a.redirecturi||"postmessage",c=(0,_.Ib)((a.scope||"").replace(/[\s\xa0]+/g," "));b={client_id:a.clientid,redirect_uri:b,response_type:"code token id_token gsession",scope:c};a.approvalprompt&&(b.approval_prompt=a.approvalprompt);a.state&&(b.state=a.state);a.openidrealm&&(b["openid.realm"]=a.openidrealm);c="offline"==a.accesstype?!0:(c=a.redirecturi)&&"postmessage"!=c;c&&(b.access_type="offline");a.requestvisibleactions&&(b.request_visible_actions=(0,_.Ib)(a.requestvisibleactions.replace(/[\s\xa0]+/g,
" ")));a.after_redirect&&(b.after_redirect=a.after_redirect);a.cookiepolicy&&"none"!==a.cookiepolicy&&(b.cookie_policy=a.cookiepolicy);"undefined"!=typeof a.includegrantedscopes&&(b.include_granted_scopes=a.includegrantedscopes);a.e&&(b.e=a.e);(a=a.authuser||_.Le("googleapis.config/sessionIndex"))&&(b.authuser=a);(a=_.Le("useoriginassocialhost"))&&(b.use_origin_as_socialhost=a);return b};eB=function(a){_.to("waaf0","signin","0");_.aB(a,function(b){_.to("waaf1","signin","0");TA(b)})};
_.gB=function(a){a=_.dB(a);_.Ne("oauth-flow/authWindowWidth",445);_.Ne("oauth-flow/authWindowHeight",615);eB(a)};_.hB=function(a){_.Bz.unsubscribe(_.Cz,a);_.Bz.subscribe(_.Cz,a)};
var oB,rB;_.jB=function(a){return a.cookiepolicy?!0:(_.iB("cookiepolicy is a required field.  See https://developers.google.com/+/web/signin/#button_attr_cookiepolicy for more information."),!1)};_.iB=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))};_.nB=function(a,b){var c=_.En();_.ue(a,c);c=NA(c);if(_.jB(c)){var d=_.kB();_.lB(c);b?_.Ce(b,"click",function(){_.mB(c,d)}):_.mB(c,d)}};
_.kB=function(){var a=new oB;_.hB(function(b){a.lC&&b&&(b.access_token&&_.Ne("isPlusUser",!0),b["g-oauth-window"]&&(a.lC=!1,_.Hf("OTA app install is no longer supported.")))});return a};oB=function(){this.lC=!1};_.lB=function(a){a=_.pB(a);_.qB(a.callback);_.SA(function(){_.fB(a)})};_.pB=function(a){rB(a);a.redirecturi&&delete a.redirecturi;Hz(function(b){return a[b]})||(a.authuser=0);return a};rB=function(a){/^\s*$/.test(a.scope||"")&&(a.scope="https://www.googleapis.com/auth/plus.login")};
_.qB=function(a){if("string"===typeof a)if(window[a])a=window[a];else{_.iB('Callback function named "'+a+'" not found');return}a&&_.hB(a)};_.mB=function(a,b){b.lC=!0;a=_.pB(a);_.gB(a)};
_.M("gapi.auth.authorize",_.aB);_.M("gapi.auth.checkSessionState",function(a,b){var c=_.se();c.client_id=a.client_id;c.session_state=a.session_state;_.SA(function(){EA()?zA.send("check_session_state",c,function(d){b.call(null,d[0])},_.ym):_.Mf.call(_.zz,"check_session_state",AA(function(d){b.call(null,d)}),c.session_state,c.client_id)})});_.M("gapi.auth.getAuthHeaderValueForFirstParty",bB);_.M("gapi.auth.getToken",Qz);
_.M("gapi.auth.getVersionInfo",function(a,b){_.SA(function(){var c=_.Th()||"",d=null,e=null;c&&(e=c.split(" "),2==e.length&&(d=e[1]));d?EA()?zA.send("get_versioninfo",{xapisidHash:d,sessionIndex:b},function(f){a(f[0])},_.ym):_.Mf.call(_.zz,"get_versioninfo",AA(function(f){a(f)}),d,b):a()})});_.M("gapi.auth.init",_.SA);_.M("gapi.auth.setToken",_.cA);_.M("gapi.auth.signIn",function(a){_.nB(a)});_.M("gapi.auth.signOut",function(){var a=Qz();a&&UA(a,a.cookie_policy)});
_.M("gapi.auth.unsafeUnpackIdToken",PA);_.M("gapi.auth._pimf",_.fB);_.M("gapi.auth._oart",MA);_.M("gapi.auth._guss",function(a){return oA(a).read()});

var sB=_.En();sB.clientid&&sB.scope&&sB.callback&&!_.Le("disableRealtimeCallback")&&_.lB(sB);

});
// Google Inc.
