/* JS */ gapi.loaded_2(function(_){var window=this;
_.wG=function(a){_.os.call(this,a.ka);this.vg=a;this.Pp=null};_.ii(_.wG,_.qs);_.wG.prototype.open=function(){this.ua.targetPos=this.ua.targetPos||"top-start";this.ua.anchorPos=this.ua.anchorPos||"bottom-start";var a=this.Fh(),b=this.ka.Db();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.vg.open()};
_.wG.prototype.Bd=function(){if(this.ua.closeClickDetection){var a=this,b=function(e){_.ts(a.ka.Db(),e)||(a.ka.close(),a.Pp=null)};document.bS?(document.bS("click",b),this.Pp=function(){document.removeEventListener("click",b,!1)}):document.attachEvent&&(document.attachEvent("onclick",b),this.Pp=function(){document.detachEvent("onclick",b)})}var c=document.getElementById(this.ka.id),d=this.ka.Db();c.style.height=this.ka.height+"px";(c=this.Fh())&&_.Ds(d,this.ua.targetPos,c,this.ua.anchorPos,{x:this.ua.leftOffset||
0,y:this.ua.topOffset||0});d.style.visibility="visible"};_.wG.prototype.close=function(){this.vg.close();this.Pp&&this.Pp()};_.wG.prototype.open=_.wG.prototype.open;_.wG.prototype.onready=_.wG.prototype.Bd;_.wG.prototype.close=_.wG.prototype.close;
_.xG=function(a){_.os.call(this,a)};_.ii(_.xG,_.qs);_.h=_.xG.prototype;_.h.create=function(a){this.Ja=document.createElement("div");var b={position:"absolute",top:"-10000px",zIndex:_.us(this)};this.ua.width&&(b.width=this.ua.width+"px");for(var c in b)this.Ja.style[c]=b[c];(a||document.body).appendChild(this.Ja)};_.h.open=function(a){this.ka.Ug("updateContainer",(0,_.R)(this.Dj,this));this.create(a);this.ka.sg(this.Ja);this.ka.Qf(this.Ja)};
_.h.Bd=function(){var a=yG(this);if(a){var b=document.getElementById(this.ka.ma());b.style.height=a.height+"px";b.style.width=a.width+"px";this.ka.width=a.width;this.ka.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};_.h.close=function(){this.Ja.parentNode&&this.Ja.parentNode.removeChild(this.Ja)};
_.h.Dj=function(a,b,c){var d=this.ka.Db();d&&(a?(this.ih(b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.R)(function(){zG(d,!0);d.style.opacity=1},this),0)):(d.style.display="none",zG(d,!1),d.style.opacity=0))};var zG=function(a,b){for(var c=0;c<AG.length;c++)a.style[AG[c]]=b?"opacity .13s linear":""};
_.xG.prototype.ih=function(a,b){var c=this.ka.Qc();a+=10;b+=10;if(_.q.util&&(c&&(c=_.Ir(c.Db(),window),a+=c.x,b+=c.y),c=yG(this))){var d=_.Nq(window),e=_.Pq(document);if(d.width&&(a=Math.min(a,d.width+e.x-c.width-8),b+c.height>d.height+e.y-8)){b-=20+c.height;var f=window,g=f.document;d=0;if(g){d=g.body;var k=g.documentElement;if(k&&d)if(f=_.Mq(f).height,_.Lq(g)&&k.scrollHeight)d=k.scrollHeight!=f?k.scrollHeight:k.offsetHeight;else{g=k.scrollHeight;var l=k.offsetHeight;k.clientHeight!=l&&(g=d.scrollHeight,
l=d.offsetHeight);d=g>f?g>l?g:l:g<l?g:l}else d=0}b=Math.max(b,Math.min(e.y+1,d-c.height))}}c=this.ka.Db();c.style.left=a+"px";c.style.top=b+"px"};var yG=function(a){return a.ka.width&&a.ka.height?{width:a.ka.width,height:a.ka.height}:(a=a.ka.Ma())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null},AG=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.xG.prototype.open=_.xG.prototype.open;_.xG.prototype.onready=_.xG.prototype.Bd;
_.xG.prototype.close=_.xG.prototype.close;
_.BG=function(a){_.os.call(this,a)};_.ii(_.BG,_.qs);_.BG.prototype.open=function(){var a=document.createElement("div");_.vr(a,{top:"-10000px",position:"absolute",zIndex:_.us(this)});this.Fh().parentNode.appendChild(a);this.ka.Qf(a);this.ka.sg(a)};
_.BG.prototype.Bd=function(){var a=document.getElementById(this.ka.id);a.style.height=this.ka.height+"px";a.style.width=this.ka.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.ka.Db();b.style.lineHeight=0;var c=this.Fh(),d=this.ua.targetPos||"top-start",e=this.ua.anchorPos||"bottom-start",f=this.ua.leftOffset||0,g=this.ua.topOffset||0;_.Ds(b,d,c,e,{x:f,y:g});var k=_.Nq(window),l=_.Pq(document),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x;k=b.offsetTop<l.y||b.offsetTop+
b.offsetHeight>k.height+l.y;d=CG(d,m,k);e=CG(e,m,k);_.Ds(b,d,c,e,{x:f*(m?-1:1),y:g*(k?-1:1)});b.style.visibility="visible";this.Qv=_.Oi(document,"mouseover",(0,_.R)(function(n){n.target===a&&this.ql&&(window.clearTimeout(this.ql),this.ql=null)},this));this.sC=_.Oi(document,"mouseout",(0,_.R)(function(n){n.target===a&&(this.ql=window.setTimeout((0,_.R)(this.ka.close,this.ka),1E3))},this))};
var CG=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&DG[a[d]]&&(a[d]=DG[a[d]]),c&&EG[a[d]]&&(a[d]=EG[a[d]]);return a.join("-")};_.BG.prototype.close=function(){this.Qv&&(_.Vi(this.Qv),_.Vi(this.sC),this.sC=this.Qv=null);this.ql&&(window.clearTimeout(this.ql),this.ql=null);_.qs.prototype.close.call(this)};_.BG.prototype.Qv=null;_.BG.prototype.sC=null;_.BG.prototype.ql=null;var DG={end:"start",left:"right",right:"left",start:"end"},EG={top:"bottom",bottom:"top"};_.BG.prototype.open=_.BG.prototype.open;
_.BG.prototype.onready=_.BG.prototype.Bd;_.BG.prototype.close=_.BG.prototype.close;

_.jm.hover=function(a){var b=new _.xG(_.jV(a));b.create(a.where);a.where=b.Ja;a.onClose=function(){b.close()};a.onRestyle=function(c){if(c.updateContainer){var d=c.updateContainer;b.Dj(d.visible,d.x,d.y)}c.width&&(b.ka.width=c.width);c.height&&(b.ka.height=c.height)};a.onCreate=function(c){b.ka=c;c.Qc=function(){return a.openerIframe};c.register("_ready",(0,_.R)(b.Bd,b),_.Bm);c.updateContainer=function(d,e,f){b.Dj(d,e,f)}}};

var CQ=function(a,b){this.Wc=a;this.Te=b};CQ.prototype.cw=function(a){this.Wc.or(this.Te,a)};CQ.prototype.wr=function(){this.Wc.oh(this.Te)};CQ.prototype.Zv=function(){this.Wc.oc(this.Te)};CQ.prototype.Kba=function(a,b,c,d,e){this.Wc.oe(this.Te,a,b,c,d,e)};
_.DQ=function(a){this.w=this.Fb=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};_.DQ.prototype.sm=function(a,b){this.Fb.Eo(new CQ(a,this));this.n=b};_.DQ.prototype.sh=function(){this.Fb.show()};_.DQ.prototype.hi=function(){this.Fb.nc()};_.DQ.prototype.cl=function(){this.Fb.close()};_.DQ.prototype.en=function(){this.Fb.enable()};_.DQ.prototype.di=function(){this.Fb.disable()};_.DQ.prototype.hl=function(a){this.Fb.wU(a)};_.DQ.prototype.vr=function(a,b){this.Fb.oV(a,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.pt="StopIteration"in _.A?_.A.StopIteration:{message:"StopIteration",stack:""};_.qt=function(){};_.qt.prototype.next=function(){throw _.pt;};_.qt.prototype.zi=function(){return this};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.rt=function(a,b){this.Ha={};this.Qb=[];this.Hs=this.Wb=0;var c=arguments.length;if(1<c){if(c%2)throw Error("f");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};_.h=_.rt.prototype;_.h.Hb=function(){return this.Wb};_.h.Xc=function(){st(this);for(var a=[],b=0;b<this.Qb.length;b++)a.push(this.Ha[this.Qb[b]]);return a};_.h.ye=function(){st(this);return this.Qb.concat()};_.h.Td=function(a){return _.tt(this.Ha,a)};_.h.Rj=_.ja(9);
_.h.equals=function(a,b){if(this===a)return!0;if(this.Wb!=a.Hb())return!1;b=b||ut;st(this);for(var c,d=0;c=this.Qb[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};var ut=function(a,b){return a===b};_.rt.prototype.isEmpty=function(){return 0==this.Wb};_.rt.prototype.clear=function(){this.Ha={};this.Hs=this.Wb=this.Qb.length=0};_.rt.prototype.remove=function(a){return _.tt(this.Ha,a)?(delete this.Ha[a],this.Wb--,this.Hs++,this.Qb.length>2*this.Wb&&st(this),!0):!1};
var st=function(a){if(a.Wb!=a.Qb.length){for(var b=0,c=0;b<a.Qb.length;){var d=a.Qb[b];_.tt(a.Ha,d)&&(a.Qb[c++]=d);b++}a.Qb.length=c}if(a.Wb!=a.Qb.length){var e={};for(c=b=0;b<a.Qb.length;)d=a.Qb[b],_.tt(e,d)||(a.Qb[c++]=d,e[d]=1),b++;a.Qb.length=c}};_.h=_.rt.prototype;_.h.get=function(a,b){return _.tt(this.Ha,a)?this.Ha[a]:b};_.h.set=function(a,b){_.tt(this.Ha,a)||(this.Wb++,this.Qb.push(a),this.Hs++);this.Ha[a]=b};
_.h.addAll=function(a){if(a instanceof _.rt)for(var b=a.ye(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};_.h.forEach=function(a,b){for(var c=this.ye(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.rt(this)};_.h.zi=function(a){st(this);var b=0,c=this.Hs,d=this,e=new _.qt;e.next=function(){if(c!=d.Hs)throw Error("I");if(b>=d.Qb.length)throw _.pt;var f=d.Qb[b++];return a?f:d.Ha[f]};return e};
_.tt=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Cx=function(a,b){var c={},d;for(d in a)b.call(void 0,a[d],d,a)&&(c[d]=a[d]);return c};_.Dx=function(a,b){var c=_.hb(b),d=c?b:arguments;for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a};

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.yV=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};_.zV=!_.sc&&!_.Yg();

var mX=function(a){a.Wc.os(a.Te)},nX=function(a){this.Te=a;this.Ge=0;this.hs=!1;this.VH=!0;this.Sk=null},oX=function(a){return 5==a.Ge||4==a.Ge};nX.prototype.isEnabled=function(){return this.VH};nX.prototype.Jc=function(a){this.VH=a};
var pX=function(a,b,c){this.xw=a||{};this.DB=b||0;this.oX=c||0;a={};b=(0,_.R)(this.FI,this);a.fc=b;b=(0,_.R)(this.bD,this);a.rc=b;b=(0,_.R)(this.hE,this);a.sc=b;b=(0,_.R)(this.Nq,this);a.hc=b;b=(0,_.R)(this.Hp,this);a.cc=b;b=(0,_.R)(this.AJ,this);a.os=b;b=(0,_.R)(this.zJ,this);a.or=b;b=(0,_.R)(this.xJ,this);a.oh=b;b=(0,_.R)(this.vJ,this);a.oc=b;b=(0,_.R)(this.wJ,this);a.oe=b;b=(0,_.R)(this.yJ,this);a.oi=b;this.Wc=a};_.h=pX.prototype;
_.h.bD=function(a,b,c){try{a+=null!=b?"_"+b:"",c.sm(this.Wc,a),this.xw[a]=new nX(c)}catch(d){return!1}return!0};_.h.FI=function(a,b){return(a=this.xw[a+(null!=b?"_"+b:"")])?a.Te:null};_.h.hE=function(a){var b=qX(this,a);if(b&&(2==b.Ge||3==b.Ge)&&b.isEnabled()&&!b.hs){try{a.sh()}catch(c){}b.hs=!0}};_.h.Nq=function(a){var b=qX(this,a);if(b&&(2==b.Ge||3==b.Ge||oX(b))&&b.hs){try{a.hi()}catch(c){}b.hs=!1}};_.h.Hp=function(a){var b=qX(this,a);if(b&&5!=b.Ge){try{this.Nq(a),a.cl()}catch(c){}rX(this,b)}};
_.h.AJ=function(a){(a=qX(this,a))&&0==a.Ge&&(sX(this,a),a.Ge=1)};var sX=function(a,b){a.DB?(a=setTimeout((0,_.R)(function(){oX(b)||tX(this,b)},a),a.DB),b.Sk=a):tX(a,b)},tX=function(a,b){var c=a.oX-a.DB;0<c&&(a=setTimeout((0,_.R)(function(){oX(b)||(b.Ge=4,this.Hp(b.Te))},a),c),b.Sk=a)},uX=function(a){null!=a.Sk&&(clearTimeout(a.Sk),a.Sk=null)};_.h=pX.prototype;_.h.zJ=function(a){(a=qX(this,a))&&!oX(a)&&1==a.Ge&&(uX(a),a.Ge=3)};_.h.xJ=function(a){(a=qX(this,a))&&!oX(a)&&(a.hs=!1)};
_.h.vJ=function(a){var b=qX(this,a);if(b&&!oX(b)){try{this.Nq(a)}catch(c){}rX(this,b)}};_.h.wJ=function(a){(a=qX(this,a))&&!oX(a)&&(a.Ge=4,this.Hp(a.Te))};_.h.yJ=function(a,b){(a=qX(this,a))&&!oX(a)&&2<=b&&4>=b&&!oX(a)&&(uX(a),a.Ge=2)};var rX=function(a,b){uX(b);b.Ge=5;a=a.xw;for(var c in a)a[c]==b&&delete a[c]},qX=function(a,b){return a.xw[b.n]},vX=function(){this.Wc=window.gbar.wg};_.h=vX.prototype;_.h.bD=function(a,b,c){return this.Wc.rc(a,b,c)};_.h.FI=function(a,b){return this.Wc.fc(a,b)};
_.h.hE=function(a){this.Wc.sc(a)};_.h.Nq=function(a){this.Wc.hc(a)};_.h.Hp=function(a){this.Wc.cc(a)};_.h.AJ=function(a){this.Wc.os(a)};_.h.zJ=function(a,b){this.Wc.or(a,b)};_.h.xJ=function(a){this.Wc.oh(a)};_.h.vJ=function(a){this.Wc.oc(a)};_.h.wJ=function(a,b,c,d,e,f){this.Wc.oe(a,b,c,d,e,f)};_.h.yJ=function(a,b,c,d){this.Wc.oi(a,b,c,d)};var wX=function(){pX.call(this)};_.K(wX,pX);
var xX=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var d=new wX;window.___jsl.man=d;a(d)};if(window.gbar){var c=function(){if(window.gbar.wg){var d=new vX;window.___jsl.man=d;a(d)}else b()};window.gbar.wg?c():window.gbar.qm?window.gbar.qm(c):b()}else b()}},yX=function(){return window.___jsl.man};
var zX=function(a){this.Y_=a;this.Bb=null;a.then((0,_.R)(function(){},this),function(){},this)},AX=function(a,b){a.Y_.then(function(c){var d=c.startFeedback;if(!d)throw Error("eb`startFeedback");return d.apply(c,b)})},CX=function(a,b,c){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];e=BX(a,b).then(function(f){return f.apply(null,d)});return new zX(e)},DX={},BX=function(a,b){var c=DX[b];if(c)return c;c=(c=_.pi(b))?_.Kk(c):(new _.Gk(function(d,e){var f=(new _.Nd(document)).createElement("SCRIPT");
f.async=!0;_.nk(f,_.sd(a));f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||d()};f.onerror=e;(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){var d=_.pi(b);if(!d)throw Error("fb`"+b+"`"+a);return d});return DX[b]=c};
var EX=function(a){this.fY=a;this.Bb=null};EX.prototype.d1=function(a){AX(this.fY,arguments)};var FX=_.Rb("https://www.gstatic.com/feedback/js/help/prod/service/lazy.min.js");BX(FX,"help.service.Lazy.create").ws(function(){});
var GX={contactid:!0,cdu:!0,cmp:!0,email:!0,hl:!0,n:!0,m:!0,p:!0,src:!0,userid:!0,sp:!0,ytid:!0};_.Fb({nm:!0,s:!0,pr:!0,v:!0},GX);
var HX=function(){this.Sq=_.Qk();this.Sq.promise.then(function(a){_.vr(a.Ma(),{border:"none","margin-bottom":"-4px"});_.vr(a.Db(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})})};_.h=HX.prototype;_.h.yB=function(a){_.Wl.open(a,this.Sq.resolve)};_.h.$J=function(){this.Sq.promise.then(function(a){return a.close()})};_.h.xB=function(a,b,c,d){this.Sq.promise.then(function(e){return e.send(a,c,d,b)})};
_.h.wB=function(a,b,c){this.Sq.promise.then(function(d){return d.Ew({updateContainer:{visible:a,x:b,y:c}})})};_.h.Ij=function(a,b,c){_.Wl.Ij(a,c,b)};
var IX=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,JX={loadDelay:400,hoverDelay:500,closeDelay:500},KX=0,LX=function(a){return document.body==a?"body":a.__cardid||null},MX=function(a){var b=LX(a);b||(b=a.__cardid=KX++);return String(b)},NX=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");!(b=b&&IX.test(b))&&(b=a.getAttribute)&&(b=/-[a-z]/.test("hovercardId")?!1:_.zV&&a.dataset?"hovercardId"in a.dataset:a.hasAttribute?a.hasAttribute("data-"+_.yV("hovercardId")):!!a.getAttribute("data-"+
_.yV("hovercardId")));return b||"getAttribute"in a&&a.getAttribute("oid")&&36==_.S("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()},OX=function(a,b){var c={};_.Fb(c,JX,_.S("iframes/card")||{},_.S("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=LX(e);f&&b[f]&&d.push(b[f])}_.ob(d.reverse(),function(g){_.Fb(c,g)});b="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";d=a.attributes;for(e=0;e<d.length;e++)_.ed(d[e].name,b)&&(c[d[e].name.substring(b.length)]=d[e].value);"getAttribute"in a&&a.getAttribute("oid")&&
36==_.S("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&a.pathname&&(b=a.pathname.match(/^\/?(\d+)$/),/\.google\.com$/.test(a.hostname)&&b&&(c.userid=b[1]));c.hl||(c.hl=_.S("lang")||_.Oe.getUrlParameters().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c},PX=function(a,b){b=b[a];"number"!==typeof b&&(b=JX[a]);return 0>b?0:b};
var QX=function(a){this.Ep=a;this.Te=new _.DQ(this);this.Ga=null;this.tv=!1;this.KK=0;this.Bp=!1};_.h=QX.prototype;
_.h.load=function(a){mX(this.Ii);a=_.Cx(a,function(f,g){return GX[g]&&null!=f});a.origin=window.location.protocol+"//"+window.location.host;var b=this,c=this.Ep,d={_event:function(f){if(!(f.timestamp<c.TB)){if("sgcp_ams"==f.event)c.pv=!0,c.Rv=!1;else if(c.pv&&"mouseover"==f.event)c.Rv=!0;else if(c.pv&&"mouseout"==f.event)c.Rv=!1;else if("sgcp_amh"==f.event)c.pv=!1,c.Rv||RX(c);else{var g=!1;switch(f.event){case "calendar":g=c.nh.scheduleEventHandler;break;case "chat":g=c.nh.sendChatHandler;break;case "email":g=
c.nh.sendEmailHandler;break;case "feedback":g=c.nh.feedbackHandler;break;case "videoChat":g=c.nh.videoChatHandler}g&&g(c.nh["hovercard-id"]||c.nh.userid||c.nh.email)}if("mouseover"==f.event||"sgcp_ams"==f.event)window.clearTimeout(c.Nh),c.Nh=null;if(f.cpid){for(g=document.getElementById(f.cpid);g&&"BODY"!=g.parentNode.tagName;)g=g.parentNode;c.UB=g}f.fromCard&&"mouseout"==f.event&&RX(c)}},_ready:(0,_.R)(this.Bd,this),version:function(f){c.Se(c.tj,{type:"circles_changed",version:f.v})},loaded:function(f){f.ri==
b.KK&&b.$X()},rendered:function(){var f=b.Ep.fm,g=_.Pq(document);b.Bp&&(b.Dj(!0,f.x+g.x,f.y+g.y),b.Bp=!1,f=b.Ep,f.Se(f.tj,{type:"show",frame:b.Ga}))},renderfailed:function(){b.Bp=!1;b.Dj(!1,0,0)},disposed:function(){b.Ga.close()},cardAction:function(f){SX(c,f)}},e=":card";!_.S("iframes/card/url")&&_.S("iframes/hovercard/url")&&(e=":hovercard");a=_.oj(_.rj(_.qj(new _.mj({disableMultiLevelParentRelay:!0,hover:!0}),d),_.Bm),a).Nd("hover").setUrl(e);_.S("card/relayOpenTop")&&(_.pj(a,-1),_.sj(a).DD("_default"));
_.Wl.open(a.value(),(0,_.R)(function(f){this.Ga=f;_.vr(f.Ma(),{border:"none","margin-bottom":"-4px"});_.vr(f.Db(),{"border-radius":"4px",overflow:"hidden","box-shadow":"rgba(0, 0, 0, 0.3) 0px 4px 16px"})},this))};_.h.Bd=function(){this.tv=!0;this.Dj(!1,0,0);this.Ii.cw({});var a=this.Ep;a.Rd&&a.$B(a.Rd)};_.h.Eo=function(a){this.Ii=a};_.h.wU=function(a){this.Ga.send("getHealthc",void 0,a,_.Bm)};_.h.oV=function(a,b){this.Ga.send("getVarc",a,b,_.Bm)};
_.h.Dj=function(a,b,c){this.Ga.updateContainer?this.Ga.updateContainer(a,b,c):this.Ga.Ew({updateContainer:{visible:a,x:b,y:c}})};_.h.show=function(){this.Dj(!0,0,-1E4);this.Ga.send("render",void 0,void 0,_.Bm);this.Bp=!0};_.h.nc=function(){this.Ga.send("hide",void 0,void 0,_.Bm);this.Dj(!1,0,0);var a=this.Ep;a.Se(a.tj,{type:"hide"});a.tj=null;a.nh=null;this.Bp=!1};_.h.close=function(){this.Ga.send("dispose",void 0,void 0,_.Bm)};_.h.enable=function(){};_.h.disable=function(){};
var TX=function(){this.rL=0;this.VA=[];this.Di={};this.It={};this.Yb={};this.TB=this.Nh=this.qg=this.Nn=this.nh=this.tj=this.vc=this.Rd=this.vf=null;this.fm={x:0,y:0};this.Rv=this.pv=!1;this.UB=null;this.cH=new Map;_.pi("gapi.load")("gapi.iframes.style.slide-menu")},UX=function(a,b,c,d){var e=MX(b);e=a.Yb[e]||(a.Yb[e]={});e[c]||(e[c]=d=(0,_.R)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))},VX=function(a,
b,c){(a=a.Yb[MX(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])},WX=function(a,b){var c=a.Yb[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&VX(a,b,d)};_.h=TX.prototype;
_.h.Is=function(a,b,c){if(a=a||document.body){this.rL++;var d=MX(a);b&&(this.Di[d]=b);c&&(this.It[d]=c);UX(this,a,"mouseover",this.uJ);UX(this,a,"mouseout",this.gB);UX(this,a,"mousedown",this.Tu);UX(this,a,"focus",this.uJ);UX(this,a,"blur",this.gB);UX(this,document.body,"mouseout",this.gB);UX(this,document.body,"mousedown",this.Tu);c&&c.preload&&(b=this.Rd=document.createElement("div"),this.vc=OX(b,this.It),XX(this))}else window.setTimeout((0,_.R)(this.Is,this),100)};
_.h.GE=function(a){if(a=a||document.body)if(RX(this,0),a!=document.body?WX(this,a):VX(this,document.body,"mouseover"),a=MX(a),delete this.Di[a],delete this.It[a],!(0<--this.rL)){WX(this,document.body);var b=this.vf;this.rB();this.vf=null;window.setTimeout(function(){var c=yX();c&&b&&c.Hp(b.Te)},100)}};_.h.Sd=function(a){this.VA.push(a)};_.h.vm=function(a){_.oi(this.VA,a)};_.h.Se=function(a,b){for(var c=[];a;){var d=LX(a);d&&this.Di[d]&&c.push(this.Di[d]);a=a.parentNode}_.Je(c,this.VA);_.ob(c,function(e){e(b)})};
_.h.uJ=function(a){this.TB=_.lb();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!NX(b);)if(b=b.parentNode,!b||1!=b.nodeType)return;if(b)if(this.tj==b||this.Rd==b)this.Nh&&(window.clearTimeout(this.Nh),this.Nh=null);else{this.Rd=b;UX(this,b,"mousemove",this.dW);"focus"==a.type||"focusin"==a.type?(a=_.ms(b),this.fm.x=a.x,this.fm.y=a.y+b.offsetHeight):(this.fm.x=a.clientX,this.fm.y=a.clientY);this.Nn=_.lb();a=this.vc=OX(b,this.It);var c=PX("hoverDelay",a);this.vf?this.vf.tv&&(window.clearTimeout(this.qg),
this.qg=window.setTimeout((0,_.R)(this.$B,this,b),c-PX("loadDelay",a))):XX(this)}}};_.h.gB=function(a){this.TB=_.lb();if("blur"!=a.type||a.target==this.tj||a.target==this.Rd){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.UB)for(;a&&"BODY"!=a.tagName;){if(a==this.UB)return;a=a.parentNode}}RX(this)}};_.h.Tu=function(){RX(this,0)};_.h.dW=function(a){this.fm.x=a.clientX;this.fm.y=a.clientY};
var XX=function(a){a.qg&&(window.clearTimeout(a.qg),a.qg=null);if(a.Rd&&(a.Se(a.Rd,{type:"hover",config:a.vc}),!a.vf)){var b=a.vf=new QX(a);xX((0,_.R)(function(c){c.bD("card",YX++,b.Te)&&b.load(this.vc)},a))}};
TX.prototype.$B=function(a){this.qg&&(window.clearTimeout(this.qg),this.qg=null);if(this.Rd==a){var b=PX("hoverDelay",this.vc)-PX("loadDelay",this.vc)-_.lb()+this.Nn;if(0<b)this.qg=window.setTimeout((0,_.R)(this.$B,this,a),b);else{this.Se(a,{type:"hover",config:this.vc});this.vc.feedbackHandler||(this.vc.feedbackHandler=this.e1);this.vc.overrideFeedback=!0;this.vc.scheduleEventHandler&&(this.vc.overrideCalendar=!0);this.vc.sendChatHandler&&(this.vc.overrideChat=!0);this.vc.sendEmailHandler&&(this.vc.overrideEmail=
!0);this.vc.videoChatHandler&&(this.vc.overrideVideoChat=!0);b=this.vf;var c=this.vc;a=(0,_.R)(this.JN,this,a);b.tv&&(b.$X=a,c.ri=++b.KK,b.Ga.send("loadData",c,void 0,_.Bm))}}};
TX.prototype.e1=function(){var a={};a={apiKey:a.apiKey||a.apiKey,environment:a.Iaa||a.environment,helpCenterPath:a.qba||a.helpCenterPath,locale:a.locale||a.locale||"fr".replace(/-/g,"_"),nonce:a.nonce||a.nonce,productData:a.productData||a.productData,receiverUri:a.Sba||a.receiverUri,renderApiUri:a.$ba||a.renderApiUri,theme:a.zca||a.theme,window:a.window||a.window};a=CX(FX,"help.service.Lazy.create","5003140",a);(new EX(a)).d1({productVersion:"gapi",customZIndex:2000000002})};
TX.prototype.JN=function(a){if(this.Rd===a&&this.vf&&this.vf.tv&&this.Nn){var b=PX("hoverDelay",this.vc)-_.lb()+this.Nn;0<b?window.setTimeout((0,_.R)(this.JN,this,a),b):(this.rB(),this.tj=this.Rd,this.nh=this.vc,VX(this,this.Rd,"mousemove"),this.Nn=this.vc=this.Rd=null,yX().hE(this.vf.Te))}};
var RX=function(a,b){a.Rd&&VX(a,a.Rd,"mousemove");a.Rd=null;a.vc=null;a.Nn=null;a.qg&&(window.clearTimeout(a.qg),a.qg=null);!a.Nh&&a.tj&&(a.Nh=window.setTimeout((0,_.R)(a.rB,a),"number"===typeof b?b:PX("closeDelay",a.nh)))};TX.prototype.rB=function(){this.Nh&&(window.clearTimeout(this.Nh),this.Nh=null);this.tj&&yX().Nq(this.vf.Te)};var SX=function(a,b){a.Se(null,b);a.LC&&a.LC.send("cardAction",b,void 0,a.KC)};
TX.prototype.Vy=function(a,b,c){var d={};d.frame=a;d.filter=b||_.xm;d.callback=c||_.cb;this.cH.set(String(_.cd(a)),d);a.register("cardAction",(0,_.R)(function(e){SX(this,e);d.callback(e)},this),d.filter)};TX.prototype.Xy=function(a){this.KC=a||_.xm;_.Wl.Ij((0,_.R)(function(b){this.LC=b;this.LC.register("cardAction",(0,_.R)(this.xt,this),this.KC)},this),void 0,this.KC)};
TX.prototype.xt=function(a){this.cH.forEach(function(b){return b.frame.send("cardAction",a,void 0,b.filter)});this.vf&&this.vf.Ga.send("cardAction",a,void 0,_.Bm)};var YX=0;
_.ZX=function(){var a={},b=new TX,c=new HX;a.Is=function(d,e,f){b.Is(d,e,f)};a.GE=function(d){b.GE(d)};a.Sd=function(d){b.Sd(d)};a.vm=function(d){b.vm(d)};a.Vy=function(d,e,f){b.Vy(d,e,f)};a.Xy=function(d){b.Xy(d)};a.xt=function(d){b.xt(d)};a.wa=function(d,e){e.origin=window.location.protocol+"//"+window.location.host;var f=_.Wl.Vh({url:":card",where:document.getElementById(d),queryParams:e,messageHandlers:{_ready:function(){f.send("loadData",e,void 0,_.Bm)},loaded:function(){f.send("render",void 0,
void 0,_.Bm)}},messageHandlersFilter:_.Bm})};a.$J=function(){c.$J()};a.wB=function(d,e,f){c.wB(d,e,f)};a.xB=function(d,e,f,g){c.xB(d,e,f,g)};a.yB=function(d){c.yB(d)};a.gX=function(d,e,f){c.Ij(d,e,f)};a.iX=function(){return _.Bm};a.jX=function(){return _.xm};return a}();
_.C("gapi.card.watch",_.ZX.Is);_.C("gapi.card.unwatch",_.ZX.GE);_.C("gapi.card.addCallback",_.ZX.Sd);_.C("gapi.card.removeCallback",_.ZX.vm);_.C("gapi.card.render",_.ZX.wa);_.C("gapi.card.connectChild",_.ZX.Vy);_.C("gapi.card.connectOpener",_.ZX.Xy);_.C("gapi.card.broadcast",_.ZX.xt);_.C("gapi.card.iframeClose",_.ZX.close);_.C("gapi.card.iframeRestyle",_.ZX.wB);_.C("gapi.card.iframeSend",_.ZX.xB);_.C("gapi.card.iframeSetup",_.ZX.yB);_.C("gapi.card.iframeAddOnOpenerHandler",_.ZX.gX);
_.C("gapi.card.iframeGetCrossOriginFilter",_.ZX.iX);_.C("gapi.card.iframeGetSameOriginFilter",_.ZX.jX);

var $X,aY=function(){$X||(_.He("card/source","webmentions"),$X=!0,_.ZX.Is())};_.Nj("profile",aY);_.C("gapi.profile.watch",aY);

});
// Google Inc.
