(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g3=function(a){a.Y("cardstatechange",a.wh()&&a.nk()?1:0)},h3=function(a,b){var c=g.Ka(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},OMa=function(a){var b=g.El(a);
a=g.Kl(a);return new g.ol(b.x,b.y,a.width,a.height)},PMa=function(a){return Math.pow(a,3)},QMa=function(a){return 3*a*a-2*a*a*a},k3=function(a){a=g.Na(a);
delete i3[a];g.Rb(i3)&&j3&&j3.stop()},SMa=function(){j3||(j3=new g.K(function(){RMa()},20));
var a=j3;a.isActive()||a.start()},RMa=function(){var a=g.Pa();
g.Cb(i3,function(b){TMa(b,a)});
g.Rb(i3)||SMa()},l3=function(a,b,c,d){g.Qq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.I=0;this.u=null},TMa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.u);a.u=b;UMa(a,a.progress);1==a.progress?(a.Pa=0,k3(a),a.onFinish(),a.Nv()):a.yc()&&a.gB()},UMa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},VMa=function(a,b){g.kf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.Pa},m3=function(a,b,c,d,e){l3.call(this,b,c,d,e);
this.element=a},n3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
m3.call(this,a,b,c,d,e)},o3=function(a){g.G.call(this);
this.l=a||window;this.i=[]},p3=function(a){return a.baseUrl||null},q3=function(a,b){return g.Io(g.Pe(a,b,void 0),function(c){return!!c})},WMa=function(a,b,c){function d(qa){var za,Kb,Rc,Ob=qa.hovercardButton;
if(!Ob)return null;Ob=Ob.subscribeButtonRenderer;if(!Ob)return null;var bc=f(Ob.unsubscribedButtonText),kc=f(Ob.subscribedButtonText);if(Ob.subscribed){var fg=f(Ob.subscriberCountWithUnsubscribeText);var Tg=f(Ob.subscriberCountText)}else fg=f(Ob.subscriberCountText),Tg=f(Ob.subscriberCountWithSubscribeText);var lc=null;return qa.signinEndpoint&&(lc=h3(qa,"signinEndpoint","webNavigationEndpointData","url"),lc||(lc=null===(Rc=null===(Kb=null===(za=Ob.signInEndpoint)||void 0===za?void 0:za.commandMetadata)||
void 0===Kb?void 0:Kb.webCommandMetadata)||void 0===Rc?void 0:Rc.url),!lc)?null:bc&&(kc||lc)?{subscribed:Ob.subscribed,subscribeText:bc,subscribeCount:fg,unsubscribeText:kc,unsubscribeCount:Tg,enabled:Ob.enabled,signinUrl:lc,classic:qa.useClassicSubscribeButton}:null}
function e(qa){if(qa){var za=[],Kb=qa.videoId;Kb&&za.push("v="+Kb);(Kb=qa.playlistId)&&za.push("list="+Kb);(qa=qa.startTimeSeconds)&&za.push("t="+qa);return"/watch?"+za.join("&")}}
function f(qa){if(!qa)return null;var za=qa.simpleText;return za?za:qa.runs?g.Pe(qa.runs,function(Kb){return Kb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,x=!1,y=null,B=null,F=null,I=null,H=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=h3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((F=h3(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(H=f(b.additionalFeesText)),(n=h3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=h3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,X="";if(b.metadata){var Q=f(b.metadata);Q&&(X=Q)}return{id:"element-"+c,type:h,title:f(b.title),metadata:X,callToAction:f(b.callToAction),xI:b.image,
iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,nR:n,Xd:L?{itct:L}:null,aW:p,Nt:a?a:null,qR:b.isPlaceholder,impressionUrls:q3(b.impressionUrls||[],p3),gR:q3(b.hovercardShowUrls||[],p3),clickUrls:q3(l.loggingUrls||[],p3),visualElement:g.ay(b.trackingParams),productPrice:I,
additionalFeesText:H}},r3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:q3(a.impressionUrls||[],p3),elements:q3(a.elements||[],function(d,e){return WMa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.ay(a.trackingParams));return c},s3=function(a){g.fN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.U=!0;this.I=0;a=a.T();this.L=g.vF(a)||g.zF(a);this.events=new g.YM(this);g.J(this,this.events);this.events.N(this.player,g.iA("creatorendscreen"),this.Bd);this.events.N(this.player,g.jA("creatorendscreen"),this.qf);this.events.N(this.player,"resize",this.ub);this.events.N(window,"focus",this.iV);this.load();var b=g.qg("STYLE");(g.bg("HEAD")[0]||document.body).appendChild(b);g.jf(this,function(){g.ug(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},XMa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},t3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},YMa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=r3(f,XMa(a))));u3(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.ip;d&&(c.postParams={ad_tracking:d});if(b=g.moa(b))if(b=g.Lc(b),b=g.Hc(b))a.u=g.lt(b,c)},u3=function(a,b,c){c=void 0===c?!0:c;
a.player.We("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&ZMa(a);c=[];d=new g.fA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.VM(a.player,a.l.element,4),a.B=new g.JL(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=$Ma(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.VM(a.player,f.element,4);var h=new g.fA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);aNa(a,f,e)}else g.cz(new g.$v("buildEndscreenElement null",
e))}a.player.Hd(c);a.ub()}},ZMa=function(a){var b=g.ey(),c=g.gy();
c&&b&&a.endscreen.visualElement&&g.jz(void 0,c,b,[a.endscreen.visualElement])},$Ma=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ea:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.Nt||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:w3(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ea:["ytp-ce-video-title"].concat(g.v(c)),V:{dir:g.Zq(b.title||
"")},ra:b.title},{D:"div",K:"ytp-ce-video-duration",ra:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ea:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.Nt||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:w3(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ea:["ytp-ce-playlist-title"].concat(g.v(c)),V:{dir:g.Zq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ea:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.Nt||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ea:["ytp-ce-channel-title","ytp-ce-link"],V:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Zq(b.title||"")},ra:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{D:"div",Ea:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ra:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:v3(b)}]};c=new g.V(c);var d=g.cg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Xd.itct}else e="endscreen",f=null;e=new g.kO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ea:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.Nt||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",V:{dir:g.Zq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-website-metadata",ra:b.metadata},{D:"a",Ea:["ytp-ce-website-goto","ytp-ce-link"],V:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:v3(b)},{D:"div",
K:"ytp-ce-expanding-icon",V:bNa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={D:"div",Ea:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.Nt||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",V:{dir:g.Zq(b.title||"")},ra:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ra:b.metadata},{D:"a",Ea:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",V:v3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ra:b.callToAction||void 0}]}]},c=new g.V(a)}b.qR&&g.M(c.element,"ytp-ce-placeholder");return c},v3=function(a){if(a.xI)var b=a.xI.thumbnails;
return bNa(b?b[b.length-1].url:null)},bNa=function(a){return a?{style:"background-image: url("+a+")"}:{}},aNa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.U&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),x3(a,c.id,!0)):(g.Nq(b.element,"ytp-ce-force-expand"),g.Nq(b.element,"ytp-ce-element-hover"),x3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){y3(a,b,c)});
b.Ra("mouseleave",function(){z3(a,b,c)});
a.player.T().i||b.Ra("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){cNa(a,c,m)});
b.Ra("keypress",function(m){cNa(a,c,m)});
b.Ra("focus",function(){y3(a,b,c)});
b.Ra("blur",function(){z3(a,b,c)});
b.Ra("touchstart",function(){y3(a,b,c)});
var l=g.eg("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Nq(b.element,"ytp-ce-element-hover");g.Nq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.U=9===m.keyCode&&!m.shiftKey});
d(g.eg("ytp-sb-subscribe",b.element));d(g.eg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},cNa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Lq(d,"ytp-ce-element");){g.Lq(d,"subscribe-label")&&A3(a,b);
if(g.Lq(d,"ytp-ce-channel-subscribe"))return;d=g.vg(d)}if(!d||g.Lq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])z3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.aW)A3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Lc(w3(a,b.targetUrl)),c=g.Hc(c),g.LJ(c,void 0,b.Xd);else{var e=a.player.getVideoData().C,f=function(){var h=w3(a,b.targetUrl),l=b.Xd,m=g.xs(h);e&&m&&(m.v||m.list)?a.player.Kj(m.v,l,m.list,!1):g.KJ(h,l)};
A3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},w3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.ZF(a)+b}else return"";return b},y3=function(a,b,c){g.Lq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.K(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),B3(a,c.gR),x3(a,c.id,!0))},z3=function(a,b,c){g.Nq(b.element,"ytp-ce-element-hover");
g.Nq(b.element,"ytp-ce-force-expand");x3(a,c.id,!1)},x3=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},B3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||t3(a))c&&c();else{b=dNa(a,b);var e=0,f=!1,h=new g.K(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Mu(b[a],d)}},A3=function(a,b,c){B3(a,b.clickUrls,c);
(a=g.gy())&&b.nR&&g.sz(a,b.visualElement)},dNa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(eNa(b[d],c));return a},eNa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},fNa=function(a){return Array.isArray(a)&&a.length?a[0]:a},C3=function(a){return"string"===typeof a?a:""},D3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},gNa=function(a){this.externalId=a},hNa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},E3=function(a){return a.value?a.value:null},F3=function(a){if(!a)return null;
var b=g.Lc(C3(a.value));b=g.Hc(b);if(!b)return null;var c=D3(a.target,iNa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new hNa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},jNa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},mNa=function(a){if(!a)return null;
var b=D3(a.type,kNa),c=D3(a.trigger,lNa),d=fNa(a.url);d=F3(d?d:null);a=fNa(a.subscribeData);var e=a?a:null;e?(a=C3(e.external_user_id),e=C3(e.subscription_token),a=a&&e?new gNa(a):null):a=null;return b?new jNa(b,c,d,a):null},nNa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},pNa=function(a){return(a=oNa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},oNa=function(a,b){return g.db(a.action,b,void 0)},qNa=function(a,b){this.context=a;
this.i=b},H3=function(a){return a.customMessage?G3("div","iv-card-message",a.customMessage):""},I3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",V:{style:a},S:c}},J3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(G3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},G3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Zq(c);return{D:a,V:b,ra:c}},rNa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.ix&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.ix+");");c.dir=g.Zq(a.customMessage);var d=[{D:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ea:b,V:c,S:d}},K3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Xd,c.tracking.click,5)}},sNa=function(a,b){this.merchant=a;
this.price=b},tNa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},uNa=function(a,b){return b?b:tNa(a)?"current":"new"},L3=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Oa=new Map;this.Qa=new Map;this.context.G.addEventListener(g.iA("annotations_module"),function(d){(d=c.Oa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.jA("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)})},M3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.hB(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.bb=!1});
a.context.i.Ra(b,"touchmove",function(){a.bb=!0})},vNa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},N3=function(a,b,c){return{tJ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
bA:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Q3=function(a,b,c){L3.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ja=this.kb=this.u=this.Sd=!1;this.xa=null;this.cards=[];this.eb=this.L=this.Fa=this.C=this.Ia=this.i=null;this.Z=[];this.J=this.ue=this.Aa=null;this.I=0;this.ya=new g.K(g.Ha,c.W.ud?4E3:3E3);g.J(this,this.ya);this.Ya=new g.K(g.Ha);g.J(this,this.Ya);this.ea=new qNa(c,function(e,f,h,l,m,n){M3(d,e,f,h,l,m,n)});
this.U=new g.V({D:"div",K:"iv-drawer",V:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",V:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ea:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.J(this,this.U);this.B=this.U.element;this.Va=new g.JL(this.U,330);g.J(this,this.Va);this.fb=g.eg("iv-drawer-header-text",this.B);this.l=g.eg("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.kb&&O3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.kb=d.u)&&P3(d)})},wNa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){O3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){P3(a)});
var c=b.headerText;g.xg(a.fb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Aa=g.ay(b.trackingParams);a.J=g.ay(b.closeTrackingParams);a.ue=g.ay(b.iconTrackingParams)},xNa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.pA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Xd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.command),zl:d.trackingParams?g.ay(d.trackingParams):null,Pi:e.trackingParams?
g.ay(e.trackingParams):null,ue:f&&f.trackingParams?g.ay(f.trackingParams):null,imageUrl:S3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.pA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,ix:null,title:d.title?g.pA(d.title):"",customMessage:d.callToAction?g.pA(d.callToAction):"",url:d.command.urlEndpoint.url?F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};T3(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.pA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Xd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.endpoint),zl:d.trackingParams?g.ay(d.trackingParams):null,Pi:e.trackingParams?g.ay(e.trackingParams):null,ue:f&&f.trackingParams?g.ay(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.pA(d.customText):null,profileImageUrl:S3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.pA(d.channelName):"",metaInfo:[d.subscriberCountText?g.pA(d.subscriberCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};T3(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.pA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Xd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),zl:d.trackingParams?g.ay(d.trackingParams):null,Pi:e.trackingParams?g.ay(e.trackingParams):null,ue:f&&f.trackingParams?g.ay(f.trackingParams):
null,Fw:S3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.pA(d.customMessage):null,playlistVideoCount:g.pA(d.playlistVideoCount),title:d.playlistTitle?g.pA(d.playlistTitle):"",metaInfo:[d.channelName?g.pA(d.channelName):"",d.videoCountText?g.pA(d.videoCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:vNa(d.action)})};T3(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.pA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Xd:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),zl:d.trackingParams?g.ay(d.trackingParams):null,Pi:e.trackingParams?g.ay(e.trackingParams):null,ue:f&&f.trackingParams?g.ay(f.trackingParams):null,Fw:S3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.pA(d.lengthString):null,customMessage:d.customMessage?g.pA(d.customMessage):null,title:d.videoTitle?g.pA(d.videoTitle):"",metaInfo:[d.channelName?g.pA(d.channelName):"",d.viewCountText?g.pA(d.viewCountText):""],isLiveNow:!!d.badge,url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:vNa(d.action)})};T3(a,b)}a.I++},S3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},R3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},zNa=function(a,b){if(b=yNa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.ug(b.ZB),g.lb(a.cards,b),a.kx(),U3(a)},O3=function(a,b,c){if(!a.u){a.Va.show();
a.Ia=new g.K(function(){g.M(a.context.G.getRootNode(),g.PT.IV_DRAWER_OPEN)},0);
a.Ia.start();a.xa=g.ku(a.l,"mousewheel",function(h){a.ya.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.gy();d&&a.Aa&&a.J&&g.qz(d,[a.Aa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.aK||(f.aK=!0,ANa(a.context.logger,f.card.tracking.tJ,b)),d&&g.qz(d,[f.card.zl]);g3(a.G);c&&(a.C=new g.K(function(){a.Fa=a.L;a.eb.focus()},330),a.C.start())}},P3=function(a){a.u&&(a.Va.hide(),g.lu(a.xa),a.xa=null,g.Nq(a.context.G.getRootNode(),g.PT.IV_DRAWER_OPEN),a.u=!1,g3(a.G),a.C&&a.C.stop(),a.C=new g.K(function(){a.Fa&&(a.Fa.focus(),a.Fa=null)},330),a.C.start())},
CNa=function(a){g.Mq(a.element,[g.PT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.VM(a.G,a.B,5);BNa(a);a.L=g.eg("ytp-cards-button",a.G.getRootNode());a.eb=g.eg("iv-drawer-close-button",a.B);a.Sd=!0},BNa=function(a){var b=g.eg("iv-drawer-close-button",a.B);
a.context.i.Ra(b,"click",a.OP,a);a.context.i.Ra(a.l,"touchend",function(){a.ya.start()});
a.context.i.Ra(a.l,"scroll",a.bQ,a);a.context.l.subscribe("onHideControls",function(){a.Ja=!0});
a.context.l.subscribe("onShowControls",function(){a.Ja=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ja=g.Lq(a.G.getRootNode(),"ytp-autohide")});
a.Z.push(g.Tu("iv-button-shown",a.zR,a));a.Z.push(g.Tu("iv-button-hidden",a.yR,a));a.Z.push(g.Tu("iv-teaser-shown",a.oO,a));a.Z.push(g.Tu("iv-teaser-hidden",a.BR,a));a.Z.push(g.Tu("iv-teaser-clicked",a.nO,a))},T3=function(a,b){a.Sd||CNa(a);
zNa(a,b.id);var c=DNa(a,b);if(c){var d={card:b,ZB:c.element,aK:!1},e=ENa(a,d);g.sb(a.cards,e,0,d);c.Ba(a.l,e);a.kx();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,U3(a),FNa(a,d),O3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&GNa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){GNa(a,d)}),U3(a))}},DNa=function(a,b){switch(b.type){case "simple":a=a.ea;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ra:b.displayDomain}:void 0;var d=rNa(b);c={D:"div",Ea:["iv-card"],S:[{D:"a",K:"iv-click-target",V:{href:b.url?E3(b.url)||"":""},S:[I3(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[G3("h2",void 0,b.title),d]}]}]};c=new g.V(c);K3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ea,c={D:"div",Ea:["iv-card","iv-card-channel"],S:[{D:"a",Ea:["iv-click-target"],V:{href:E3(b.url)||"","data-ytid":b.channelId},S:[I3(b.profileImageUrl),
{D:"div",K:"iv-card-content",S:[H3(b),{D:"h2",K:"iv-card-primary-link",ra:b.title},J3(b)]}]}]},c=new g.V(c),K3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ea,c={D:"div",Ea:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",V:{href:E3(b.url)||""},S:[I3(b.Fw,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b)]}]}]},c=new g.V(c),
K3(a,g.dg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ea;var e=!g.ib(b.offers);c=["iv-card"];d="";var f=rNa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ra:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ra:f.merchant}),f={D:"div",S:e});e=b.url?E3(b.url)||"":"";c={D:"div",Ea:c,V:{tabindex:"0"},S:[{D:"a",Ea:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Lien commercial",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",ra:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",V:{href:e},S:[G3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.qg("span");g.xg(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.fd(d,"adInfo");K3(a,g.dg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ea,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ra:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ea:["yt-badge","yt-badge-live"],ra:"EN DIRECT MAINTENANT"}:null,d={D:"div",Ea:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",V:{href:(null===(c=b.url)||void 0===c?void 0:E3(c))||""},S:[I3(b.Fw,d),{D:"div",K:"iv-card-content",S:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b),f]}]}]},
c=new g.V(d),K3(a,g.dg("iv-click-target",c.element),b,b.url),c;default:return null}},ENa=function(a,b){if(0===a.cards.length)return 0;
a=g.eb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},HNa=function(a){return a.i?"productListing"===a.i.card.type:g.ym(a.cards,function(b){return"productListing"===b.card.type})},U3=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",HNa(a))},GNa=function(a,b){if(!g.Lq(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.gy(),d=a.i?a.i.card.ue:a.ue;
c&&d&&g.rz(c,[d]);a.i=b;U3(a)}if(c="none"!=a.element.style.display)g.T(a.context.G.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.G.getPresentingPlayerType()?(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.G.getAdState();c&&b.card.teaserDurationMs&&a.G.Fs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.ya.isActive()&&a.Ja)&&FNa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},
FNa=function(a,b){a.U.yb?(b=new l3([0,
a.l.scrollTop],[0,b.ZB.offsetTop],600,QMa),a.context.u.Ra(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Ra(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.$K(a.U,!0),a.l.scrollTop=b.ZB.offsetTop,g.$K(a.U,!1))},V3=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},yNa=function(a,b){return g.db(a.cards,function(c){return c.card.id===b})},W3=function(a,b,c){L3.call(this,a,b);
this.annotation=c;this.isActive=!1},INa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},X3=function(a,b,c){W3.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},JNa=function(a,b){var c=void 0===c?0:c;
var d=OMa(b).width;g.Cl(b,d);c=new n3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,PMa);g.J(a,c);a.context.u.Ra(c,"begin",function(){g.Ll(b,!0)});
c.play()},MNa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ea:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({D:"div",Ea:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.kO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.i.Ba(d));var f=a.createElement({D:"div",Ea:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ea:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Ll(h,!1);var l=a.createElement({D:"div",Ea:["branding-context-container-outer"]});l.appendChild(h);g.vl(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.K(function(){KNa(a,h,l)},500);
g.J(a,a.u);a.context.i.Ra(a.element,"mouseover",function(){LNa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.u.start()})}},LNa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Kl(b);a.i||(b.style.width=g.Bl(f.width,!0),c.style.width=g.Bl(f.width,!0));g.vl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.vl(d,"right","1px");a.B=!0;g.Ll(b,!0);a.C=new g.K(function(){g.M(this.element,"iv-branding-active")},0,a);
a.C.start()}},KNa=function(a,b,c){g.Nq(a.element,"iv-branding-active");
a.I=new g.K(function(){g.Ll(b,!1);a.i||(c.style.width=g.Bl(0,!0))},250);
a.I.start();a.B=!1},NNa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.W=c;this.videoData=d;this.logger=e;this.G=f;this.l=h},Y3=function(a,b,c){W3.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.U=!1;this.I=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ea:["iv-promo-contents"]});this.C=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.Ll(d.u,!1);g.Ll(d.l,!0)},700,this);
g.J(this,this.C)},ONa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=pNa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ea:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&M3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.nd(f,E3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
ra:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ea:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ea:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",ra:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&M3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",ra:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ea:["yt-badge","iv-promo-badge-live"],ra:"EN DIRECT MAINTENANT"})),g.M(a.i,"iv-click-target"),e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ea:["iv-promo-expand","ytp-button"]});a.l.title="Agrandir";a.context.i.Ra(a.l,"click",function(q){Z3(a,5E3,q)});
c.appendChild(a.l);g.Ll(a.l,!1);a.context.i.Ra(a.element,"mouseover",a.KQ,a);a.context.i.Ra(a.element,"mouseout",a.JQ,a);a.context.i.Ra(a.element,"touchend",function(q){Z3(a,5E3,q)});
a.u=a.createElement({D:"button",Ea:["iv-promo-close","ytp-button"]});a.u.title="Fermer";a.context.i.Ra(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.FQ:a.EQ,a);c.appendChild(a.u);g.Mq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},Z3=function(a,b,c){c.stopPropagation();
PNa(a);QNa(a,b);a.i.focus()},RNa=function(a){a.isCollapsed||a.L||a.B||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},PNa=function(a){a.C.stop();
a.isCollapsed&&(g.Oq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Ll(a.l,!1),g.Ll(a.u,!0))},QNa=function(a,b){a.B||(a.B=g.kh(function(){$3(this);
RNa(this)},b,a))},$3=function(a){a.B&&(g.C.clearTimeout(a.B),a.B=null)},SNa=function(a){this.G=a},ANa=function(a,b,c){b&&(c?a4(a,b.map(function(d){return g.zq(d,c)})):a4(a,b))},a4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Mu(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},b4=function(a){g.fN.call(this,a);
var b=this;this.U=!1;this.loadNumber=0;this.J={};this.logger=new SNa(this.player);this.C=new g.YM(this);this.I=this.u=null;this.events=new g.YM(this);this.L=this.i=null;this.Z=[];g.J(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.Y("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.Y("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.Y("onShowControls")});
this.C.N(this.player,"resize",function(d){b.Y("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.Y("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.pO,this);this.subscribe("resize",this.iz,this);this.player.T().U.subscribe("vast_info_card_add",this.oL,this);g.J(this,this.events);this.ea=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Ea:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.l);g.VM(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ea:["ytp-iv-video-content"]});g.J(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.ea);this.B.element.appendChild(a);this.kq()&&this.load();var c=this.createElement({D:"style"});(g.bg("HEAD")[0]||document.body).appendChild(c);g.jf(this,function(){g.ug(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},TNa=function(a){a=a.createElement({D:"div",
Ea:["annotation","annotation-type-custom"]});g.Ll(a,!1);return a},UNa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.$K(a.l,b);g.$K(a.B,b)},VNa=function(a,b,c){a.U=!0;
a.I=g.lt(b,c)},WNa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.La(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(WNa(a,e))}return c},ZNa=function(a){var b=a.player.getVideoData();
if(b.Ja){var c=a.player.T().U.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.dt(h)&&h.responseXML?h.responseXML:null)&&c4(a,h)}};
g.Du()&&(d.onFinish=XNa(a,d.onFinish));d.postParams={ic_only:"1"};YNa(d,c);a.U=!0;g.lt(b.Ja,d)}}},YNa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Zt&&(a.postParams.ic_coll=b.Zt);b.ox&&(a.postParams.ic_xml=b.ox);b.Iw&&(a.postParams.ic_track=b.Iw)},$Na=function(a){var b=new g.V({D:"div"});
g.Ll(b.element,!1);var c=new Q3(a.player,b.element,d4(a));g.J(c,b);b.Ba(a.l.element);c.ow();return c},d4=function(a){if(!a.L){var b=new o3(a);
g.J(a,b);var c=new g.vk(a);g.J(a,c);a.L=new NNa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.ud)}return a.L},c4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.gy();if(e){var f=g.ey();f&&g.jz(void 0,e,f,[g.ay(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=WNa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=D3(f.type,aOa),p=D3(f.style,bOa),q=C3(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=mNa;if(null==u)var x=null;else if(g.Ka(u)){l=[];for(var y=g.r(u),B=y.next();!B.done;B=y.next()){var F=f(B.value);
F&&l.push(F)}x=l}else{var I=f(u);x=I?[I]:[]}e=m&&n?new nNa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=TNa(f),L=null;switch(l.type){case "branding":if(f.player.T().Db)break;f.l.element.appendChild(H);L=new X3(H,d4(f),l);break;case "promotion":g.VM(f.player,H,4),L=new Y3(H,d4(f),l)}L&&L.ow();if(f=L)g.J(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=$Na(a),g.J(a,a.i));if("card"===e.type){c=a.i;var X=e&&e.data&&e.data.card_type;
f=e.data;if(X)switch(l=f.tracking||{},l={tJ:l.impression,click:l.click,close:l.close,nM:l.teaser_impression,bA:l.teaser_click},H=f.tracking_params||{},L=null,X){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Xd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,zl:H.card?g.ay(H.card):null,Pi:H.teaser?g.ay(H.teaser):null,ue:H.icon?g.ay(H.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Xd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,zl:H.card?g.ay(H.card):null,Pi:H.teaser?g.ay(H.teaser):
null,ue:H.icon?g.ay(H.icon):null,Fw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "productListing":f.signin_url&&(L=F3({target:"current",value:f.signin_url}));X=[];for(var Q=f.offers||[],qa=0;qa<Q.length;qa++)X.push(new sNa(g.ud(Q[qa].merchant),g.ud(Q[qa].price)));e={id:e.id,timestamp:f.timestamp||
0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Xd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,zl:H.card?g.ay(H.card):null,Pi:H.teaser?g.ay(H.teaser):null,ue:H.icon?g.ay(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,ix:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,
target:f.target||"new",value:f.url}),h$:L,g$:f.signin_title?f.signin_title:void 0,f$:f.signin_message?f.signin_message:void 0,offers:X};T3(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Xd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,zl:H.card?g.ay(H.card):null,Pi:H.teaser?g.ay(H.teaser):null,ue:H.icon?g.ay(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?
f.display_domain:null,showLinkIcon:!!f.show_link_icon,ix:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Xd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,zl:H.card?
g.ay(H.card):null,Pi:H.teaser?g.ay(H.teaser):null,ue:H.icon?g.ay(H.icon):null,Fw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},T3(c,e)}}else wNa(a.i,e);c=!0}}c&&(g3(a.player),a.iz())},cOa=function(a,b){var c=!1;
a.i||(a.i=$Na(a),g.J(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(xNa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.pA(b.headerText):"",g.xg(c.fb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Aa=b.trackingParams?g.ay(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.ay(b.closeButton.infoCardIconRenderer.trackingParams):null,c.ue=b.icon.infoCardIconRenderer.trackingParams?
g.ay(b.icon.infoCardIconRenderer.trackingParams):null,g3(a.player),a.iz())},dOa=function(a,b,c,d,e){if(!a.player.T().Db){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new jNa("openUrl","click",new hNa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.pA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.pA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.pA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.pA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.pA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.pA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new nNa(c,"branding","branding",f,d);l=TNa(a);a.l.element.appendChild(l);f=new X3(l,d4(a),f);f.ow();g.J(f,f);a.J[c]=f}},XNa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.Z.push(g.Au(0,function(){b.apply(null,g.v(d))}))}},eOa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.OM.prototype.Fs=g.ca(17,function(a,b){var c=g.wN(this.sb());c&&c.Fs(a,b)});
var i3={},j3=null;g.Qa(l3,g.Qq);g.k=l3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Pa)this.progress=0,this.coords=this.i;else if(this.yc())return!1;k3(this);this.startTime=a=g.Pa();-1==this.Pa&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.u=this.startTime;this.progress||this.ez();this.Yh("play");-1==this.Pa&&this.Yh("resume");this.Pa=1;var b=g.Na(this);b in i3||(i3[b]=this);SMa();TMa(this,a);return!0};
g.k.stop=function(a){k3(this);this.Pa=0;a&&(this.progress=1);UMa(this,this.progress);this.Yh("stop");this.Nv()};
g.k.pause=function(){this.yc()&&(k3(this),this.Pa=-1,this.Yh("pause"))};
g.k.va=function(){0==this.Pa||this.stop(!1);this.Yh("destroy");l3.Yd.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.gB=function(){this.Yh("animate")};
g.k.Yh=function(a){this.dispatchEvent(new VMa(a,this))};
g.Qa(VMa,g.kf);g.Qa(m3,l3);m3.prototype.l=g.Ha;m3.prototype.gB=function(){this.l();m3.Yd.gB.call(this)};
m3.prototype.Nv=function(){this.l();m3.Yd.Nv.call(this)};
m3.prototype.ez=function(){this.l();m3.Yd.ez.call(this)};
g.Qa(n3,m3);n3.prototype.l=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(o3,g.G);o3.prototype.Ra=function(a,b,c,d){c=(0,g.D)(c,d||this.l);a=g.ku(a,b,c);this.i.push(a);return a};
o3.prototype.Jy=function(a,b,c,d){c=(0,g.D)(c,d||this.l);a=g.uu(a,b,c);this.i.push(a);return a};
o3.prototype.jc=function(a){g.lu(a);g.lb(this.i,a)};
o3.prototype.va=function(){g.lu(this.i);this.i.length=0;g.G.prototype.va.call(this)};g.w(s3,g.fN);g.k=s3.prototype;g.k.load=function(){g.fN.prototype.load.call(this);if(!t3(this)){var a=g.noa(this.player.getVideoData());a?(a=r3(a,XMa(this)),u3(this,a,!1)):YMa(this)}};
g.k.unload=function(){u3(this,null);this.u&&(this.u.abort(),this.u=null);g.fN.prototype.unload.call(this)};
g.k.bf=function(a,b){return t3(this)?"loadCustomEndscreenRenderer"===a?(a=r3(b,"new"),u3(this,a),!0):null:null};
g.k.getOptions=function(){return t3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.ub=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<fOa.length;f++){var h=Math.abs(b.width-fOa[f]);if(-1===e||d>=h)e=f,d=h}d=gOa[e];this.l&&g.vl(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Jl(e.element,Math.round(h.width*a.width),f);g.Cl(e.element,m,n);g.Oq(e.element,hOa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Oq(e.element,gOa);g.M(e.element,d);(e=g.cg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.vl(e,"height",f+"px")}}}}};
g.k.Bd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())B3(this,this.endscreen.impressionUrls),(a=g.gy())&&this.endscreen.visualElement&&g.kz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");B3(this,c.impressionUrls);(b=g.gy())&&g.kz(b,c.visualElement,void 0);this.player.T().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.qf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Nq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Nq(b,"ytp-ce-shown");this.player.T().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.iV=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Oq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var fOa=[346,426,470,506,570,640,853,1280,1920],gOa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hOa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var iNa={v_:"current",f5:"new"};var kNa={CLOSE:"close",x5:"openUrl",qP:"subscribe"},lNa={UX:"click",CLOSE:"close",N0:"hidden",H6:"rollOut",I6:"rollOver",w7:"shown"};var bOa={nX:"anchored",ZM:"branding",CHANNEL:"channel",t_:"cta",Q0:"highlightText",R1:"label",PLAYLIST:"playlist",d6:"popup",F7:"speech",qP:"subscribe",W7:"title",VIDEO:"video",f9:"website"},aOa={ZM:"branding",GX:"card",J_:"drawer",P0:"highlight",z3:"marker",n6:"promotion",TEXT:"text",l9:"widget"};g.w(L3,g.G);g.k=L3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.fA(a,b,{id:c});a.namespace="annotations_module";d&&this.Oa.set(a,d);e&&this.Qa.set(a,e);this.context.G.Hd([a])};
g.k.ow=function(){this.context.l.subscribe("resize",this.kx,this)};
g.k.hB=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.ug(this.element)};
g.k.kx=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=E3(a);if(f){var h=uNa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.xs(f||"");m&&n&&(n.v||n.list)?e.context.G.Kj(n.v,b,n.list,!1):g.LJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);a4(this.context.logger,c,l,d);tNa(f)||(c=g.gy(),d=b.itct,c&&d&&g.sz(c,g.ay(d)))}};
g.k.va=function(){this.Oa.clear();this.Qa.clear();g.G.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.w(Q3,L3);g.k=Q3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Kl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.kx=function(){var a=this.isAvailable();g.Ll(this.element,a);g.N(this.context.G.getRootNode(),g.PT.IV_DRAWER_ENABLED,a);g3(this.G)};
g.k.destroy=function(){this.G.Fs(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.Uu(this.Z);g.lu(this.xa);this.Ia&&this.Ia.dispose();this.C&&this.C.dispose();L3.prototype.destroy.call(this)};
g.k.OP=function(){if(this.u){a4(this.context.logger,V3(this).tracking.close);var a=g.gy();a&&this.J&&g.sz(a,this.J);P3(this)}};
g.k.bQ=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.zR=function(){var a=g.gy(),b=V3(this);b=b?b.ue:this.ue;a&&b&&g.qz(a,[b])};
g.k.yR=function(){var a=g.gy(),b=V3(this);b=b?b.ue:this.ue;a&&b&&g.rz(a,[b])};
g.k.oO=function(){var a=V3(this);a4(this.context.logger,a.tracking.nM);var b=g.gy();b&&a&&g.qz(b,[a.Pi,a.ue])};
g.k.BR=function(){var a=g.gy(),b=V3(this);a&&b&&g.rz(a,[b.Pi])};
g.k.nO=function(a){var b=V3(this),c=g.gy();this.i?a?(a=this.context.logger,a4(a,b.tracking.bA),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Pi&&g.sz(c,b.Pi)):(a=this.context.logger,a4(a,b.tracking.bA),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.ue&&g.sz(c,b.ue)):(a=this.context.logger,a4(a,b.tracking.bA),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.ue&&g.sz(c,this.ue))};g.w(W3,L3);W3.prototype.ow=function(){L3.prototype.ow.call(this);INa(this)};
W3.prototype.show=function(){L3.prototype.show.call(this);var a=g.gy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.qz(a,[g.ay(b.itct)])};
W3.prototype.hide=function(){L3.prototype.hide.call(this);var a=g.gy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.rz(a,[g.ay(b.itct)])};g.w(X3,W3);
X3.prototype.show=function(){if(!this.isActive){W3.prototype.show.call(this);if(!this.J){g.M(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ea:["branding-img","iv-click-target"],V:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.Ll(this.l,!1);var b=this.createElement({D:"div",Ea:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=pNa(this.annotation))&&M3(this,this.l,b,this.annotation.id,
a.session_data);MNa(this,a);this.J=!0}g.Ll(this.element,!0);this.isActive=!0;this.l&&JNa(this,this.l)}};
X3.prototype.hide=function(){this.isActive&&(W3.prototype.hide.call(this),g.Ll(this.element,!1),this.isActive=!1)};
X3.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);W3.prototype.destroy.call(this)};g.w(Y3,W3);g.k=Y3.prototype;g.k.show=function(){this.isActive||(W3.prototype.show.call(this),this.U||(ONa(this),this.U=!0),g.Ll(this.element,!0),g.kh(function(){g.Nq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,$3(this),PNa(this),QNa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.hB=function(a,b,c,d,e,f){return this.isCollapsed?!1:W3.prototype.hB.call(this,a,b,c,d,e,f)};
g.k.KQ=function(a){this.L=!0;Z3(this,500,a)};
g.k.JQ=function(){this.L=!1;RNa(this)};
g.k.EQ=function(a){a.stopPropagation();this.hide()};
g.k.FQ=function(a){a.stopPropagation();$3(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();W3.prototype.destroy.call(this)};g.w(b4,g.fN);g.k=b4.prototype;g.k.bf=function(a,b){if(!eOa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.L1(b))&&c4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(zNa(this.i,b),g3(this.player)),!0}return null};
g.k.getOptions=function(){return eOa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.kq=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.BH||a.U.get(b.videoId)||g.tH(b)||g.uH(b)?!0:!1};
g.k.iz=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Jl(this.B.element,a.width,a.height);g.Cl(this.B.element,a.left,a.top)}if(this.i){var b=this.player.hj();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.pO=function(a){UNa(this,a.state);g.U(a.state,2)&&(this.wh()&&this.nk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Fs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.dt(h)&&h.responseXML?h.responseXML:null)&&(c4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fN.prototype.load.call(this);UNa(this,this.player.vb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Du()&&(a=XNa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().U.get(d);f&&YNa(e,f);f=f&&(f.ox||f.Zt);if(!c.ul||f)c.Ja?VNa(this,c.Ja,e):(this.u=function(){b.ob(e)},this.player.addEventListener("videodatachange",this.u));
g.VM(this.player,this.B.element,4);this.iz();(f=g.tH(c))&&cOa(this,f);(f=g.uH(c))&&f.featuredChannel&&dOa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.ob=function(a){var b=this.player.getVideoData();b.Ja&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),VNa(this,b.Ja,a))};
g.k.unload=function(){this.player.We("annotations_module");for(var a=g.r(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,g3(this.player));this.U=!1;this.I&&(this.I.abort(),this.I=null);this.J={};this.l.hide();g.fN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.oL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?ZNa(this):this.load())};
g.k.wh=function(){return!!this.i&&this.i.isAvailable()};
g.k.nk=function(){this.wh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.wh();this.i&&(a?c?O3(this.i,c,b):O3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):P3(this.i))};
g.k.Fs=function(a,b){this.player.Y(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.T().U.unsubscribe("vast_info_card_add",this.oL,this);g.Nq(this.player.getRootNode(),g.PT.IV_DRAWER_OPEN);for(var a=this.Z,b=0,c=a.length;b<c;b++)g.Eu(a[b]);this.Z.length=0;g.fN.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.J(this,a);return a.element};g.qN.annotations_module=b4;g.qN.creatorendscreen=s3;})(_yt_player);
