(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var i3=function(a){a.W("cardstatechange",a.hh()&&a.Nj()?1:0)},j3=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},ZKa=function(a){var b=g.Il(a);
a=g.Ol(a);return new g.pl(b.x,b.y,a.width,a.height)},$Ka=function(a){return Math.pow(a,3)},aLa=function(a){return 3*a*a-2*a*a*a},m3=function(a){a=g.Pa(a);
delete k3[a];g.Rb(k3)&&l3&&l3.stop()},cLa=function(){l3||(l3=new g.J(function(){bLa()},20));
var a=l3;a.isActive()||a.start()},bLa=function(){var a=g.Sa();
g.Eb(k3,function(b){dLa(b,a)});
g.Rb(k3)||cLa()},n3=function(a,b,c,d){g.Rq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.u=null},dLa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.u);a.u=b;eLa(a,a.progress);1==a.progress?(a.Oa=0,m3(a),a.onFinish(),a.Yt()):a.tc()&&a.yz()},eLa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},fLa=function(a,b){g.hf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Oa},o3=function(a,b,c,d,e){n3.call(this,b,c,d,e);
this.element=a},p3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
o3.call(this,a,b,c,d,e)},q3=function(a){g.E.call(this);
this.l=a||window;this.i=[]},r3=function(a){return a.baseUrl||null},s3=function(a,b){return g.Po(g.Oe(a,b,void 0),function(c){return!!c})},gLa=function(a,b,c){function d(Ba){var za,ed,We,oc=Ba.hovercardButton;
if(!oc)return null;oc=oc.subscribeButtonRenderer;if(!oc)return null;var Ee=f(oc.unsubscribedButtonText),Fd=f(oc.subscribedButtonText);if(oc.subscribed){var Hh=f(oc.subscriberCountWithUnsubscribeText);var Pg=f(oc.subscriberCountText)}else Hh=f(oc.subscriberCountText),Pg=f(oc.subscriberCountWithSubscribeText);var jc=null;return Ba.signinEndpoint&&(jc=j3(Ba,"signinEndpoint","webNavigationEndpointData","url"),jc||(jc=null===(We=null===(ed=null===(za=oc.signInEndpoint)||void 0===za?void 0:za.commandMetadata)||
void 0===ed?void 0:ed.webCommandMetadata)||void 0===We?void 0:We.url),!jc)?null:Ee&&(Fd||jc)?{subscribed:oc.subscribed,subscribeText:Ee,subscribeCount:Hh,unsubscribeText:Fd,unsubscribeCount:Pg,enabled:oc.enabled,signinUrl:jc,classic:Ba.useClassicSubscribeButton}:null}
function e(Ba){if(Ba){var za=[],ed=Ba.videoId;ed&&za.push("v="+ed);(ed=Ba.playlistId)&&za.push("list="+ed);(Ba=Ba.startTimeSeconds)&&za.push("t="+Ba);return"/watch?"+za.join("&")}}
function f(Ba){if(!Ba)return null;var za=Ba.simpleText;return za?za:Ba.runs?g.Oe(Ba.runs,function(ed){return ed.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,B=null,G=null,H=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=j3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((G=j3(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=j3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=j3(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:null,L="";if(b.metadata){var da=f(b.metadata);da&&(L=da)}return{id:"element-"+c,type:h,title:f(b.title),metadata:L,callToAction:f(b.callToAction),
IG:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,IP:n,Qd:M?{itct:M}:null,AU:p,ls:a?a:null,LP:b.isPlaceholder,impressionUrls:s3(b.impressionUrls||[],r3),BP:s3(b.hovercardShowUrls||[],r3),clickUrls:s3(l.loggingUrls||[],r3),visualElement:g.Cx(b.trackingParams),
productPrice:H,additionalFeesText:I}},t3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:s3(a.impressionUrls||[],r3),elements:s3(a.elements||[],function(d,e){return gLa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Cx(a.trackingParams));return c},u3=function(a){g.zN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.U=!0;this.G=0;a=a.T();this.K=g.SF(a)||g.WF(a);this.events=new g.qN(this);g.F(this,this.events);this.events.N(this.player,g.Iz("creatorendscreen"),this.yd);this.events.N(this.player,g.Jz("creatorendscreen"),this.bf);this.events.N(this.player,"resize",this.tb);this.events.N(window,"focus",this.ET);this.load();var b=g.ng("STYLE");(g.$f("HEAD")[0]||document.body).appendChild(b);g.gf(this,function(){g.rg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},hLa=function(a){return a.player.getVideoData().C?"current":a.K?"new":"current"},v3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},iLa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=t3(f,hLa(a))));w3(a,f)},
urlParams:{v:c},withCredentials:!0};a.K&&(c.urlParams.ptype="embedded");var d=b.Sk;d&&(c.postParams={ad_tracking:d});if(b=g.Yma(b))if(b=g.Jc(b),b=g.Fc(b))a.u=g.Ps(b,c)},w3=function(a,b,c){c=void 0===c?!0:c;
a.player.df("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&jLa(a);c=[];d=new g.Fz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",L:"ytp-ce-shadow"}),g.oN(a.player,a.l.element,4),a.B=new g.fM(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=kLa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.oN(a.player,f.element,4);var h=new g.Fz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);lLa(a,f,e)}else g.Ux(new g.Gv("buildEndscreenElement null",
e))}a.player.Dd(c);a.tb()}},jLa=function(a){var b=g.Gx(),c=g.Ix();
c&&b&&a.endscreen.visualElement&&g.hy(c,b,a.endscreen.visualElement)},kLa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.ls||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-covering-image",V:x3(b)},{D:"div",L:"ytp-ce-covering-shadow-top"},{D:"a",L:"ytp-ce-covering-overlay",V:{href:y3(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-video-title"].concat(g.ma(c)),V:{dir:g.Xq(b.title||
"")},oa:b.title},{D:"div",L:"ytp-ce-video-duration",oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.ls||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-covering-image",V:x3(b)},{D:"div",L:"ytp-ce-covering-shadow-top"},{D:"a",L:"ytp-ce-covering-overlay",V:{href:y3(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-playlist-title"].concat(g.ma(c)),V:{dir:g.Xq(b.title||"")},oa:b.title},{D:"div",L:"ytp-ce-playlist-count",S:[{D:"div",L:"ytp-ce-playlist-icon"},{D:"div",L:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.ls||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},
{D:"div",L:"ytp-ce-expanding-overlay",S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],V:{href:y3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Xq(b.title||"")},oa:b.title},b.subscribeButton?{D:"div",L:"ytp-ce-subscribe-container",S:[{D:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",L:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{D:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{D:"div",L:"ytp-ce-expanding-image",V:x3(b)}]};c=new g.V(c);var d=g.ag(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Qd.itct}else e="endscreen",f=null;e=new g.GO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ca:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.ls||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-expanding-overlay",S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},
{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",L:"ytp-ce-website-title",V:{dir:g.Xq(b.title||"")},oa:b.title},{D:"div",L:"ytp-ce-website-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],V:{href:y3(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{D:"div",L:"ytp-ce-expanding-image",V:x3(b)},{D:"div",
L:"ytp-ce-expanding-icon",V:mLa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",L:"ytp-ce-merchandise-price-container",S:[{D:"div",L:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",L:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={D:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.ls||"","aria-hidden":"true"},S:[{D:"div",L:"ytp-ce-element-shadow"},{D:"div",L:"ytp-ce-expanding-overlay",
S:[{D:"div",L:"ytp-ce-expanding-overlay-hider"},{D:"div",L:"ytp-ce-expanding-overlay-background"},{D:"div",L:"ytp-ce-expanding-overlay-content",S:[{D:"div",L:"ytp-ce-expanding-overlay-body",S:[{D:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",L:"ytp-ce-merchandise-title",V:{dir:g.Xq(b.title||"")},oa:b.title},c,{D:"div",L:"ytp-ce-merchandise-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:y3(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},
{D:"div",L:"ytp-ce-expanding-image",V:x3(b)},{D:"div",L:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",L:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.LP&&g.K(c.element,"ytp-ce-placeholder");return c},x3=function(a){if(a.IG)var b=a.IG.thumbnails;
return mLa(b?b[b.length-1].url:null)},mLa=function(a){return a?{style:"background-image: url("+a+")"}:{}},lLa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.U&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),z3(a,c.id,!0)):(g.Oq(b.element,"ytp-ce-force-expand"),g.Oq(b.element,"ytp-ce-element-hover"),z3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){A3(a,b,c)});
b.Ra("mouseleave",function(){B3(a,b,c)});
a.player.T().i||b.Ra("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){nLa(a,c,m)});
b.Ra("keypress",function(m){nLa(a,c,m)});
b.Ra("focus",function(){A3(a,b,c)});
b.Ra("blur",function(){B3(a,b,c)});
b.Ra("touchstart",function(){A3(a,b,c)});
var l=g.cg("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Oq(b.element,"ytp-ce-element-hover");g.Oq(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.U=9===m.keyCode&&!m.shiftKey});
d(g.cg("ytp-sb-subscribe",b.element));d(g.cg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},nLa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Mq(d,"ytp-ce-element");){g.Mq(d,"subscribe-label")&&C3(a,b);
if(g.Mq(d,"ytp-ce-channel-subscribe"))return;d=g.sg(d)}if(!d||g.Mq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])B3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.AU)C3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Jc(y3(a,b.targetUrl)),c=g.Fc(c),g.iK(c,void 0,b.Qd);else{var e=a.player.getVideoData().C,f=function(){var h=y3(a,b.targetUrl),l=b.Qd,m=g.$r(h);e&&m&&(m.v||m.list)?a.player.tj(m.v,l,m.list,!1):g.hK(h,l)};
C3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},y3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.MG(a)+b}else return"";return b},A3=function(a,b,c){g.Mq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),D3(a,c.BP),z3(a,c.id,!0))},B3=function(a,b,c){g.Oq(b.element,"ytp-ce-element-hover");
g.Oq(b.element,"ytp-ce-force-expand");z3(a,c.id,!1)},z3=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},D3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||v3(a))c&&c();else{b=oLa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.ou(b[a],d)}},C3=function(a,b,c){D3(a,b.clickUrls,c);
(a=g.Ix())&&b.IP&&g.Ty(a,b.visualElement)},oLa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(pLa(b[d],c));return a},pLa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},qLa=function(a){return Array.isArray(a)&&a.length?a[0]:a},E3=function(a){return"string"===typeof a?a:""},F3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},rLa=function(a){this.externalId=a},sLa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},G3=function(a){return a.value?a.value:null},H3=function(a){if(!a)return null;
var b=g.Jc(E3(a.value));b=g.Fc(b);if(!b)return null;var c=F3(a.target,tLa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new sLa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},uLa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},xLa=function(a){if(!a)return null;
var b=F3(a.type,vLa),c=F3(a.trigger,wLa),d=qLa(a.url);d=H3(d?d:null);a=qLa(a.subscribeData);var e=a?a:null;e?(a=E3(e.external_user_id),e=E3(e.subscription_token),a=a&&e?new rLa(a):null):a=null;return b?new uLa(b,c,d,a):null},yLa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ALa=function(a){return(a=zLa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},zLa=function(a,b){return g.gb(a.action,b,void 0)},BLa=function(a,b){this.context=a;
this.i=b},J3=function(a){return a.customMessage?I3("div","iv-card-message",a.customMessage):""},K3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",L:"iv-card-image",V:{style:a},S:c}},L3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(I3("li","",c.value));return{D:"ul",L:"iv-card-meta-info",S:b}},I3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Xq(c);return{D:a,V:b,oa:c}},CLa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Iv&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Iv+");");c.dir=g.Xq(a.customMessage);var d=[{D:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",L:"iv-card-link-icon"}));return{D:"div",Ca:b,V:c,S:d}},M3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Qd,c.tracking.click,5)}},DLa=function(a,b){this.merchant=a;
this.price=b},ELa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},FLa=function(a,b){return b?b:ELa(a)?"current":"new"},N3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.Va=!1;this.Ga=new Map;this.La=new Map;this.context.I.addEventListener(g.Iz("annotations_module"),function(d){(d=c.Ga.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Jz("annotations_module"),function(d){(d=c.La.get(d))&&d.apply(c)})},O3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.zz(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.Va=!1});
a.context.i.Ra(b,"touchmove",function(){a.Va=!0})},GLa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},P3=function(a,b,c){return{EH:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
yK:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uy:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},S3=function(a,b,c){N3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ea=this.eb=this.u=this.Ud=!1;this.ma=null;this.cards=[];this.Ya=this.K=this.Aa=this.C=this.Da=this.i=null;this.Y=[];this.J=this.ge=this.xa=null;this.G=0;this.va=new g.J(g.Ja,c.B.Ac?4E3:3E3);g.F(this,this.va);this.Ua=new g.J(g.Ja);g.F(this,this.Ua);this.X=new BLa(c,function(e,f,h,l,m,n){O3(d,e,f,h,l,m,n)});
this.U=new g.V({D:"div",L:"iv-drawer",V:{id:"iv-drawer"},S:[{D:"div",L:"iv-drawer-header",V:{"aria-role":"heading"},S:[{D:"span",L:"iv-drawer-header-text"},{D:"button",Ca:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{D:"div",L:"iv-drawer-content"}]});g.F(this,this.U);this.B=this.U.element;this.Pa=new g.fM(this.U,330);g.F(this,this.Pa);this.bb=g.cg("iv-drawer-header-text",this.B);this.l=g.cg("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.eb&&Q3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.eb=d.u)&&R3(d)})},HLa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){Q3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){R3(a)});
var c=b.headerText;g.ug(a.bb,c);a.K&&a.K.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.xa=g.Cx(b.trackingParams);a.J=g.Cx(b.closeTrackingParams);a.ge=g.Cx(b.iconTrackingParams)},ILa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.Pz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Qd:T3(a,c,b,d),sponsored:!1,tracking:P3(d,e,d.command),Wk:d.trackingParams?g.Cx(d.trackingParams):null,Bi:e.trackingParams?
g.Cx(e.trackingParams):null,ge:f&&f.trackingParams?g.Cx(f.trackingParams):null,imageUrl:U3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Pz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Iv:null,title:d.title?g.Pz(d.title):"",customMessage:d.callToAction?g.Pz(d.callToAction):"",url:d.command.urlEndpoint.url?H3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};V3(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.Pz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Qd:T3(a,c,b,d),sponsored:!1,tracking:P3(d,e,d.endpoint),Wk:d.trackingParams?g.Cx(d.trackingParams):null,Bi:e.trackingParams?g.Cx(e.trackingParams):null,ge:f&&f.trackingParams?g.Cx(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Pz(d.customText):null,profileImageUrl:U3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Pz(d.channelName):"",metaInfo:[d.subscriberCountText?g.Pz(d.subscriberCountText):""],url:H3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};V3(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.Pz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Qd:T3(a,c,b,d),sponsored:!1,tracking:P3(d,e,d.action),Wk:d.trackingParams?g.Cx(d.trackingParams):null,Bi:e.trackingParams?g.Cx(e.trackingParams):null,ge:f&&f.trackingParams?g.Cx(f.trackingParams):
null,Ru:U3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Pz(d.customMessage):null,playlistVideoCount:g.Pz(d.playlistVideoCount),title:d.playlistTitle?g.Pz(d.playlistTitle):"",metaInfo:[d.channelName?g.Pz(d.channelName):"",d.videoCountText?g.Pz(d.videoCountText):""],url:H3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:GLa(d.action)})};V3(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.Pz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Qd:T3(a,c,b,d),sponsored:!1,tracking:P3(d,e,d.action),Wk:d.trackingParams?g.Cx(d.trackingParams):null,Bi:e.trackingParams?g.Cx(e.trackingParams):null,ge:f&&f.trackingParams?g.Cx(f.trackingParams):null,Ru:U3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.Pz(d.lengthString):null,customMessage:d.customMessage?g.Pz(d.customMessage):null,title:d.videoTitle?g.Pz(d.videoTitle):"",metaInfo:[d.channelName?g.Pz(d.channelName):"",d.viewCountText?g.Pz(d.viewCountText):""],isLiveNow:!!d.badge,url:H3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:GLa(d.action)})};V3(a,b)}a.G++},U3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},T3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},KLa=function(a,b){if(b=JLa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.rg(b.tA),g.ob(a.cards,b),a.Kv(),W3(a)},Q3=function(a,b,c){if(!a.u){a.Pa.show();
a.Da=new g.J(function(){g.K(a.context.I.getRootNode(),g.ST.IV_DRAWER_OPEN)},0);
a.Da.start();a.ma=g.Ot(a.l,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.Ix();d&&a.xa&&a.J&&g.iy(d,[a.xa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.kI||(f.kI=!0,LLa(a.context.logger,f.card.tracking.EH,b)),d&&g.iy(d,[f.card.Wk]);i3(a.I);c&&(a.C=new g.J(function(){a.Aa=a.K;a.Ya.focus()},330),a.C.start())}},R3=function(a){a.u&&(a.Pa.hide(),g.Pt(a.ma),a.ma=null,g.Oq(a.context.I.getRootNode(),g.ST.IV_DRAWER_OPEN),a.u=!1,i3(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.Aa&&(a.Aa.focus(),a.Aa=null)},330),a.C.start())},
NLa=function(a){g.Nq(a.element,[g.ST.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.oN(a.I,a.B,5);MLa(a);a.K=g.cg("ytp-cards-button",a.I.getRootNode());a.Ya=g.cg("iv-drawer-close-button",a.B);a.Ud=!0},MLa=function(a){var b=g.cg("iv-drawer-close-button",a.B);
a.context.i.Ra(b,"click",a.kO,a);a.context.i.Ra(a.l,"touchend",function(){a.va.start()});
a.context.i.Ra(a.l,"scroll",a.xO,a);a.context.l.subscribe("onHideControls",function(){a.Ea=!0});
a.context.l.subscribe("onShowControls",function(){a.Ea=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ea=g.Mq(a.I.getRootNode(),"ytp-autohide")});
a.Y.push(g.wu("iv-button-shown",a.TP,a));a.Y.push(g.wu("iv-button-hidden",a.SP,a));a.Y.push(g.wu("iv-teaser-shown",a.GM,a));a.Y.push(g.wu("iv-teaser-hidden",a.VP,a));a.Y.push(g.wu("iv-teaser-clicked",a.FM,a))},V3=function(a,b){a.Ud||NLa(a);
KLa(a,b.id);var c=OLa(a,b);if(c){var d={card:b,tA:c.element,kI:!1},e=PLa(a,d);g.ub(a.cards,e,0,d);c.ya(a.l,e);a.Kv();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,W3(a),QLa(a,d),Q3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&RLa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){RLa(a,d)}),W3(a))}},OLa=function(a,b){switch(b.type){case "simple":a=a.X;
var c=b.displayDomain?{D:"div",L:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=CLa(b);c={D:"div",Ca:["iv-card"],S:[{D:"a",L:"iv-click-target",V:{href:b.url?G3(b.url)||"":""},S:[K3(b.imageUrl,c),{D:"div",L:"iv-card-content",S:[I3("h2",void 0,b.title),d]}]}]};c=new g.V(c);M3(a,g.bg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.X,c={D:"div",Ca:["iv-card","iv-card-channel"],S:[{D:"a",Ca:["iv-click-target"],V:{href:G3(b.url)||"","data-ytid":b.channelId},S:[K3(b.profileImageUrl),
{D:"div",L:"iv-card-content",S:[J3(b),{D:"h2",L:"iv-card-primary-link",oa:b.title},L3(b)]}]}]},c=new g.V(c),M3(a,g.bg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.X,c={D:"div",Ca:["iv-card","iv-card-playlist"],S:[{D:"a",L:"iv-click-target",V:{href:G3(b.url)||""},S:[K3(b.Ru,{D:"div",L:"iv-card-image-overlay",S:[{D:"span",L:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{D:"div",L:"iv-card-content",S:[J3(b),I3("h2","iv-card-primary-link",b.title),L3(b)]}]}]},c=new g.V(c),
M3(a,g.bg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.X;var e=0!=b.offers.length;c=["iv-card"];d="";var f=CLa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",L:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({D:"div",L:"iv-card-offer-merchant",oa:f.merchant}),f={D:"div",S:e});e=b.url?G3(b.url)||"":"";c={D:"div",Ca:c,V:{tabindex:"0"},S:[{D:"a",Ca:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",L:"iv-card-content",S:[b.sponsored?{D:"div",L:"iv-card-sponsored",S:["Lien commercial",{D:"div",L:"iv-ad-info-container",S:[{D:"div",L:"iv-ad-info",oa:"{{adInfo}}"},{D:"div",L:"iv-ad-info-icon-container",S:[{D:"div",L:"iv-ad-info-icon"},{D:"div",L:"iv-ad-info-callout"}]}]}]}:"",{D:"a",L:"iv-click-target",V:{href:e},S:[I3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.ng("span");g.ug(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.Vc(d,"adInfo");M3(a,g.bg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.X,d=b.videoDuration?{D:"span",L:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ca:["yt-badge","yt-badge-live"],oa:"EN DIRECT MAINTENANT"}:null,d={D:"div",Ca:["iv-card","iv-card-video"],S:[{D:"a",L:"iv-click-target",V:{href:(null===(c=b.url)||void 0===c?void 0:G3(c))||""},S:[K3(b.Ru,d),{D:"div",L:"iv-card-content",S:[J3(b),I3("h2","iv-card-primary-link",b.title),L3(b),f]}]}]},
c=new g.V(d),M3(a,g.bg("iv-click-target",c.element),b,b.url),c;default:return null}},PLa=function(a,b){if(0===a.cards.length)return 0;
a=g.ib(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},SLa=function(a){return a.i?"productListing"===a.i.card.type:g.ym(a.cards,function(b){return"productListing"===b.card.type})},W3=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",SLa(a))},RLa=function(a,b){if(!g.Mq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Ix(),d=a.i?a.i.card.ge:a.ge;
c&&d&&g.jy(c,[d]);a.i=b;W3(a)}if(c="none"!=a.element.style.display)g.S(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.ir(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ua.isActive()||((!a.u||!a.va.isActive()&&a.Ea)&&QLa(a,b),a.Ua.start(910+b.card.teaserDurationMs))}},
QLa=function(a,b){a.U.vb?(b=new n3([0,
a.l.scrollTop],[0,b.tA.offsetTop],600,aLa),a.context.u.Ra(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Ra(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.wL(a.U,!0),a.l.scrollTop=b.tA.offsetTop,g.wL(a.U,!1))},X3=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},JLa=function(a,b){return g.gb(a.cards,function(c){return c.card.id===b})},Y3=function(a,b,c){N3.call(this,a,b);
this.annotation=c;this.isActive=!1},TLa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Z3=function(a,b,c){Y3.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},ULa=function(a,b){var c=void 0===c?0:c;
var d=ZKa(b).width;g.Gl(b,d);c=new p3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,$Ka);g.F(a,c);a.context.u.Ra(c,"begin",function(){g.Pl(b,!0)});
c.play()},XLa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ca:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({D:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.GO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.ya(d));var f=a.createElement({D:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Pl(h,!1);var l=a.createElement({D:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.zl(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){VLa(a,h,l)},500);
g.F(a,a.u);a.context.i.Ra(a.element,"mouseover",function(){WLa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.u.start()})}},WLa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Ol(b);a.i||(b.style.width=g.Fl(f.width,!0),c.style.width=g.Fl(f.width,!0));g.zl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zl(d,"right","1px");a.B=!0;g.Pl(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},VLa=function(a,b,c){g.Oq(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Pl(b,!1);a.i||(c.style.width=g.Fl(0,!0))},250);
a.G.start();a.B=!1},YLa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},$3=function(a,b,c){Y3.call(this,a,b,c);
var d=this;this.K=this.isCollapsed=this.U=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ca:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Pl(d.u,!1);g.Pl(d.l,!0)},700,this);
g.F(this,this.C)},ZLa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=ALa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",L:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",L:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&O3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",L:"iv-promo-txt"}),g.kd(f,G3(e)),a.i=f):a.i=a.createElement({D:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
oa:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",L:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ca:["iv-button","iv-promo-button"],S:[{D:"span",L:"iv-button-content",oa:f}]});var p=a.createElement({D:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&O3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&O3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",oa:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ca:["yt-badge","iv-promo-badge-live"],oa:"EN DIRECT MAINTENANT"})),g.K(a.i,"iv-click-target"),e&&O3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",L:"iv-promo-actions"});a.l=a.createElement({D:"button",Ca:["iv-promo-expand","ytp-button"]});a.l.title="Agrandir";a.context.i.Ra(a.l,"click",function(r){a4(a,5E3,r)});
c.appendChild(a.l);g.Pl(a.l,!1);a.context.i.Ra(a.element,"mouseover",a.fP,a);a.context.i.Ra(a.element,"mouseout",a.eP,a);a.context.i.Ra(a.element,"touchend",function(r){a4(a,5E3,r)});
a.u=a.createElement({D:"button",Ca:["iv-promo-close","ytp-button"]});a.u.title="Fermer";a.context.i.Ra(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.aP:a.ZO,a);c.appendChild(a.u);g.Nq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},a4=function(a,b,c){c.stopPropagation();
$La(a);aMa(a,b);a.i.focus()},bMa=function(a){a.isCollapsed||a.K||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},$La=function(a){a.C.stop();
a.isCollapsed&&(g.Pq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Pl(a.l,!1),g.Pl(a.u,!0))},aMa=function(a,b){a.B||(a.B=g.jh(function(){b4(this);
bMa(this)},b,a))},b4=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},cMa=function(a){this.I=a},LLa=function(a,b,c){b&&(c?c4(a,b.map(function(d){return g.yq(d,c)})):c4(a,b))},c4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.ou(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},d4=function(a){g.zN.call(this,a);
var b=this;this.U=!1;this.loadNumber=0;this.J={};this.logger=new cMa(this.player);this.C=new g.qN(this);this.G=this.u=null;this.events=new g.qN(this);this.K=this.i=null;this.Y=[];g.F(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.C.N(this.player,"resize",function(d){b.W("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.HM,this);this.subscribe("resize",this.Dx,this);this.player.T().U.subscribe("vast_info_card_add",this.zJ,this);g.F(this,this.events);this.X=this.createElement({D:"div",L:"video-custom-annotations"});this.l=new g.V({D:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.l);g.oN(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ca:["ytp-iv-video-content"]});g.F(this,this.B);a=this.createElement({D:"div",L:"video-annotations"});
a.appendChild(this.X);this.B.element.appendChild(a);this.Ap()&&this.load();var c=this.createElement({D:"style"});(g.$f("HEAD")[0]||document.body).appendChild(c);g.gf(this,function(){g.rg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},dMa=function(a){a=a.createElement({D:"div",
Ca:["annotation","annotation-type-custom"]});g.Pl(a,!1);return a},eMa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.wL(a.l,b);g.wL(a.B,b)},fMa=function(a,b,c){a.U=!0;
a.G=g.Ps(b,c)},gMa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(gMa(a,e))}return c},jMa=function(a){var b=a.player.getVideoData();
if(b.Aa){var c=a.player.T().U.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.ls(h)&&h.responseXML?h.responseXML:null)&&e4(a,h)}};
g.fu()&&(d.onFinish=hMa(a,d.onFinish));d.postParams={ic_only:"1"};iMa(d,c);a.U=!0;g.Ps(b.Aa,d)}}},iMa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Cs&&(a.postParams.ic_coll=b.Cs);b.Ov&&(a.postParams.ic_xml=b.Ov);b.Uu&&(a.postParams.ic_track=b.Uu)},kMa=function(a){var b=new g.V({D:"div"});
g.Pl(b.element,!1);var c=new S3(a.player,b.element,f4(a));g.F(c,b);b.ya(a.l.element);c.Fu();return c},f4=function(a){if(!a.K){var b=new q3(a);
g.F(a,b);var c=new g.vk(a);g.F(a,c);a.K=new YLa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.bd)}return a.K},e4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ix();if(e){var f=g.Gx();f&&g.ay(g.Nr("use_default_events_client")?void 0:g.cx,e,f,[g.Cx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=gMa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=F3(f.type,lMa),p=F3(f.style,mMa),r=E3(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=xLa;if(null==u)var x=null;else if(g.Ma(u)){l=[];for(var y=g.q(u),B=y.next();!B.done;B=
y.next()){var G=f(B.value);G&&l.push(G)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new yLa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=dMa(f),M=null;switch(l.type){case "branding":if(f.player.T().wb)break;f.l.element.appendChild(I);M=new Z3(I,f4(f),l);break;case "promotion":g.oN(f.player,I,4),M=new $3(I,f4(f),l)}M&&M.Fu();if(f=M)g.F(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=kMa(a),g.F(a,a.i));if("card"===e.type){c=
a.i;var L=e&&e.data&&e.data.card_type;f=e.data;if(L)switch(l=f.tracking||{},l={EH:l.impression,click:l.click,close:l.close,yK:l.teaser_impression,uy:l.teaser_click},I=f.tracking_params||{},M=null,L){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Qd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wk:I.card?g.Cx(I.card):null,Bi:I.teaser?g.Cx(I.teaser):null,ge:I.icon?
g.Cx(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:H3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};V3(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Qd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wk:I.card?
g.Cx(I.card):null,Bi:I.teaser?g.Cx(I.teaser):null,ge:I.icon?g.Cx(I.icon):null,Ru:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:H3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};V3(c,e);break;case "productListing":f.signin_url&&(M=H3({target:"current",value:f.signin_url}));L=[];for(var da=f.offers||[],Ba=0;Ba<da.length;Ba++)L.push(new DLa(g.rd(da[Ba].merchant),g.rd(da[Ba].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Qd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wk:I.card?g.Cx(I.card):null,Bi:I.teaser?g.Cx(I.teaser):null,ge:I.icon?g.Cx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Iv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:H3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),h8:M,g8:f.signin_title?f.signin_title:void 0,f8:f.signin_message?f.signin_message:void 0,offers:L};V3(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Qd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wk:I.card?g.Cx(I.card):null,Bi:I.teaser?g.Cx(I.teaser):
null,ge:I.icon?g.Cx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Iv:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:H3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};V3(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,Qd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Wk:I.card?g.Cx(I.card):null,Bi:I.teaser?g.Cx(I.teaser):null,ge:I.icon?g.Cx(I.icon):null,Ru:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:H3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},V3(c,e)}}else HLa(a.i,e);c=!0}}c&&(i3(a.player),a.Dx())},nMa=function(a,b){var c=!1;
a.i||(a.i=kMa(a),g.F(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(ILa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Pz(b.headerText):"",g.ug(c.bb,d),c.K&&c.K.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.xa=b.trackingParams?g.Cx(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Cx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.ge=b.icon.infoCardIconRenderer.trackingParams?
g.Cx(b.icon.infoCardIconRenderer.trackingParams):null,i3(a.player),a.Dx())},oMa=function(a,b,c,d,e){if(!a.player.T().wb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new uLa("openUrl","click",new sLa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Pz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Pz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Pz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Pz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Pz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Pz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new yLa(c,"branding","branding",f,d);l=dMa(a);a.l.element.appendChild(l);f=new Z3(l,f4(a),f);f.Fu();g.F(f,f);a.J[c]=f}},hMa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||a.Y.push(g.cu(function(){b.apply(null,g.ma(d))}))}},pMa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.hN.prototype.ir=g.ca(17,function(a,b){var c=g.QN(this.rb());c&&c.ir(a,b)});
var k3={},l3=null;g.Ta(n3,g.Rq);g.k=n3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Oa)this.progress=0,this.coords=this.i;else if(this.tc())return!1;m3(this);this.startTime=a=g.Sa();-1==this.Oa&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.u=this.startTime;this.progress||this.Bx();this.Ph("play");-1==this.Oa&&this.Ph("resume");this.Oa=1;var b=g.Pa(this);b in k3||(k3[b]=this);cLa();dLa(this,a);return!0};
g.k.stop=function(a){m3(this);this.Oa=0;a&&(this.progress=1);eLa(this,this.progress);this.Ph("stop");this.Yt()};
g.k.pause=function(){this.tc()&&(m3(this),this.Oa=-1,this.Ph("pause"))};
g.k.ra=function(){0==this.Oa||this.stop(!1);this.Ph("destroy");n3.Rd.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.yz=function(){this.Ph("animate")};
g.k.Ph=function(a){this.dispatchEvent(new fLa(a,this))};
g.Ta(fLa,g.hf);g.Ta(o3,n3);o3.prototype.l=g.Ja;o3.prototype.yz=function(){this.l();o3.Rd.yz.call(this)};
o3.prototype.Yt=function(){this.l();o3.Rd.Yt.call(this)};
o3.prototype.Bx=function(){this.l();o3.Rd.Bx.call(this)};
g.Ta(p3,o3);p3.prototype.l=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(q3,g.E);q3.prototype.Ra=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.Ot(a,b,c);this.i.push(a);return a};
q3.prototype.Zw=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.Xt(a,b,c);this.i.push(a);return a};
q3.prototype.fc=function(a){g.Pt(a);g.ob(this.i,a)};
q3.prototype.ra=function(){g.Pt(this.i);this.i.length=0;g.E.prototype.ra.call(this)};g.v(u3,g.zN);g.k=u3.prototype;g.k.load=function(){g.zN.prototype.load.call(this);if(!v3(this)){var a=g.Zma(this.player.getVideoData());a?(a=t3(a,hLa(this)),w3(this,a,!1)):iLa(this)}};
g.k.unload=function(){w3(this,null);this.u&&(this.u.abort(),this.u=null);g.zN.prototype.unload.call(this)};
g.k.Se=function(a,b){return v3(this)?"loadCustomEndscreenRenderer"===a?(a=t3(b,"new"),w3(this,a),!0):null:null};
g.k.getOptions=function(){return v3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.tb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<qMa.length;f++){var h=Math.abs(b.width-qMa[f]);if(-1===e||d>=h)e=f,d=h}d=rMa[e];this.l&&g.zl(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Nl(e.element,Math.round(h.width*a.width),f);g.Gl(e.element,m,n);g.Pq(e.element,sMa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Pq(e.element,rMa);g.K(e.element,d);(e=g.ag(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.zl(e,"height",f+"px")}}}}};
g.k.yd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())D3(this,this.endscreen.impressionUrls),(a=g.Ix())&&this.endscreen.visualElement&&g.by(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");D3(this,c.impressionUrls);(b=g.Ix())&&g.by(b,c.visualElement,void 0);this.player.T().u&&this.player.Na("endscreenelementshown",
a)}};
g.k.bf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Oq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Oq(b,"ytp-ce-shown");this.player.T().u&&this.player.Na("endscreenelementhidden",a)}};
g.k.ET=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Pq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var qMa=[346,426,470,506,570,640,853,1280,1920],rMa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sMa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var tLa={DY:"current",h3:"new"};var vLa={CLOSE:"close",B3:"openUrl",KN:"subscribe"},wLa={sW:"click",CLOSE:"close",QZ:"hidden",K4:"rollOut",L4:"rollOver",x5:"shown"};var mMa={MV:"anchored",hL:"branding",CHANNEL:"channel",BY:"cta",TZ:"highlightText",P_:"label",PLAYLIST:"playlist",i4:"popup",F5:"speech",KN:"subscribe",W5:"title",VIDEO:"video",e7:"website"},lMa={hL:"branding",fW:"card",QY:"drawer",SZ:"highlight",y1:"marker",q4:"promotion",TEXT:"text",k7:"widget"};g.v(N3,g.E);g.k=N3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Fz(a,b,{id:c});a.namespace="annotations_module";d&&this.Ga.set(a,d);e&&this.La.set(a,e);this.context.I.Dd([a])};
g.k.Fu=function(){this.context.l.subscribe("resize",this.Kv,this)};
g.k.zz=function(a,b,c,d,e,f){if(this.Va)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.rg(this.element)};
g.k.Kv=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=G3(a);if(f){var h=FLa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.$r(f||"");m&&n&&(n.v||n.list)?e.context.I.tj(n.v,b,n.list,!1):g.iK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);c4(this.context.logger,c,l,d);ELa(f)||(c=g.Ix(),d=b.itct,c&&d&&g.Ty(c,g.Cx(d)))}};
g.k.ra=function(){this.Ga.clear();this.La.clear();g.E.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.v(S3,N3);g.k=S3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Ol(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Kv=function(){var a=this.isAvailable();g.Pl(this.element,a);g.N(this.context.I.getRootNode(),g.ST.IV_DRAWER_ENABLED,a);i3(this.I)};
g.k.destroy=function(){this.I.ir(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.xu(this.Y);g.Pt(this.ma);this.Da&&this.Da.dispose();this.C&&this.C.dispose();N3.prototype.destroy.call(this)};
g.k.kO=function(){if(this.u){c4(this.context.logger,X3(this).tracking.close);var a=g.Ix();a&&this.J&&g.Ty(a,this.J);R3(this)}};
g.k.xO=function(){g.N(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.TP=function(){var a=g.Ix(),b=X3(this);b=b?b.ge:this.ge;a&&b&&g.iy(a,[b])};
g.k.SP=function(){var a=g.Ix(),b=X3(this);b=b?b.ge:this.ge;a&&b&&g.jy(a,[b])};
g.k.GM=function(){var a=X3(this);c4(this.context.logger,a.tracking.yK);var b=g.Ix();b&&a&&g.iy(b,[a.Bi,a.ge])};
g.k.VP=function(){var a=g.Ix(),b=X3(this);a&&b&&g.jy(a,[b.Bi])};
g.k.FM=function(a){var b=X3(this),c=g.Ix();this.i?a?(a=this.context.logger,c4(a,b.tracking.uy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Bi&&g.Ty(c,b.Bi)):(a=this.context.logger,c4(a,b.tracking.uy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ge&&g.Ty(c,b.ge)):(a=this.context.logger,c4(a,b.tracking.uy),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.ge&&g.Ty(c,this.ge))};g.v(Y3,N3);Y3.prototype.Fu=function(){N3.prototype.Fu.call(this);TLa(this)};
Y3.prototype.show=function(){N3.prototype.show.call(this);var a=g.Ix(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iy(a,[g.Cx(b.itct)])};
Y3.prototype.hide=function(){N3.prototype.hide.call(this);var a=g.Ix(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.jy(a,[g.Cx(b.itct)])};g.v(Z3,Y3);
Z3.prototype.show=function(){if(!this.isActive){Y3.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ca:["branding-img","iv-click-target"],V:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.Pl(this.l,!1);var b=this.createElement({D:"div",Ca:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=ALa(this.annotation))&&O3(this,this.l,b,this.annotation.id,
a.session_data);XLa(this,a);this.J=!0}g.Pl(this.element,!0);this.isActive=!0;this.l&&ULa(this,this.l)}};
Z3.prototype.hide=function(){this.isActive&&(Y3.prototype.hide.call(this),g.Pl(this.element,!1),this.isActive=!1)};
Z3.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);Y3.prototype.destroy.call(this)};g.v($3,Y3);g.k=$3.prototype;g.k.show=function(){this.isActive||(Y3.prototype.show.call(this),this.U||(ZLa(this),this.U=!0),g.Pl(this.element,!0),g.jh(function(){g.Oq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,b4(this),$La(this),aMa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.zz=function(a,b,c,d,e,f){return this.isCollapsed?!1:Y3.prototype.zz.call(this,a,b,c,d,e,f)};
g.k.fP=function(a){this.K=!0;a4(this,500,a)};
g.k.eP=function(){this.K=!1;bMa(this)};
g.k.ZO=function(a){a.stopPropagation();this.hide()};
g.k.aP=function(a){a.stopPropagation();b4(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();Y3.prototype.destroy.call(this)};g.v(d4,g.zN);g.k=d4.prototype;g.k.Se=function(a,b){if(!pMa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.Q1(b))&&e4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(KLa(this.i,b),i3(this.player)),!0}return null};
g.k.getOptions=function(){return pMa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ap=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.MF||a.U.get(b.videoId)||g.UH(b)||g.VH(b)?!0:!1};
g.k.Dx=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Nl(this.B.element,a.width,a.height);g.Gl(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Ri();a=this.i;b=b.width;g.N(a.B,"iv-drawer-small",426>=b);g.N(a.B,"iv-drawer-big",1280<=b)}};
g.k.HM=function(a){eMa(this,a.state);g.U(a.state,2)&&(this.hh()&&this.Nj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ir(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.ls(h)&&h.responseXML?h.responseXML:null)&&(e4(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.zN.prototype.load.call(this);eMa(this,this.player.sb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.fu()&&(a=hMa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().U.get(d);f&&iMa(e,f);f=f&&(f.Ov||f.Cs);if(!c.Mk||f)c.Aa?fMa(this,c.Aa,e):(this.u=function(){b.kb(e)},this.player.addEventListener("videodatachange",this.u));
g.oN(this.player,this.B.element,4);this.Dx();(f=g.UH(c))&&nMa(this,f);(f=g.VH(c))&&f.featuredChannel&&oMa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.kb=function(a){var b=this.player.getVideoData();b.Aa&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),fMa(this,b.Aa,a))};
g.k.unload=function(){this.player.df("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,i3(this.player));this.U=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.zN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.zJ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?jMa(this):this.load())};
g.k.hh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Nj=function(){this.hh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.hh();this.i&&(a?c?Q3(this.i,c,b):Q3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):R3(this.i))};
g.k.ir=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.T().U.unsubscribe("vast_info_card_add",this.zJ,this);g.Oq(this.player.getRootNode(),g.ST.IV_DRAWER_OPEN);for(var a=this.Y,b=0,c=a.length;b<c;b++)g.gu(a[b]);this.Y.length=0;g.zN.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.KN.annotations_module=d4;g.KN.creatorendscreen=u3;})(_yt_player);
