(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var A3=function(a){a.Z("cardstatechange",a.Gh()&&a.Lk()?1:0)},B3=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},FUa=function(a){var b=g.qn(a);
a=g.Dn(a);return new g.$m(b.x,b.y,a.width,a.height)},GUa=function(a){return Math.pow(a,3)},HUa=function(a){return 3*a*a-2*a*a*a},E3=function(a){a=g.Ra(a);
delete C3[a];g.uf(C3)&&D3&&D3.stop()},JUa=function(){D3||(D3=new g.K(function(){IUa()},20));
var a=D3;a.isActive()||a.start()},IUa=function(){var a=g.Va();
g.ff(C3,function(b){KUa(b,a)});
g.uf(C3)||JUa()},F3=function(a,b,c,d){g.Qq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.j=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.C=null},KUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;LUa(a,a.progress);1==a.progress?(a.i=0,E3(a),a.onFinish(),a.lx()):a.Ic()&&a.VC()},LUa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.j.length);for(var c=0;c<a.j.length;c++)a.coords[c]=(a.N[c]-a.j[c])*b+a.j[c]},MUa=function(a,b){g.We.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.i},G3=function(a,b,c,d,e){F3.call(this,b,c,d,e);
this.element=a},H3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G3.call(this,a,b,c,d,e)},I3=function(a){g.G.call(this);
this.j=a||window;this.i=[]},J3=function(a){return a.baseUrl||null},K3=function(a,b){return g.Xo(g.Kn(a,b,void 0),function(c){return!!c})},NUa=function(a,b,c){function d(ra){var Ja=ra.hovercardButton;
if(!Ja)return null;Ja=Ja.subscribeButtonRenderer;if(!Ja)return null;var Sa=f(Ja.unsubscribedButtonText),Pc=f(Ja.subscribedButtonText);if(Ja.subscribed){var eb=f(Ja.subscriberCountWithUnsubscribeText);var id=f(Ja.subscriberCountText)}else eb=f(Ja.subscriberCountText),id=f(Ja.subscriberCountWithSubscribeText);var Ya=null;if(ra.signinEndpoint){Ya=B3(ra,"signinEndpoint","webNavigationEndpointData","url");if(!Ya){var jd,Rd,Gf;Ya=null==(jd=Ja.signInEndpoint)?void 0:null==(Rd=jd.commandMetadata)?void 0:
null==(Gf=Rd.webCommandMetadata)?void 0:Gf.url}if(!Ya)return null}return Sa&&(Pc||Ya)?{subscribed:Ja.subscribed,subscribeText:Sa,subscribeCount:eb,unsubscribeText:Pc,unsubscribeCount:id,enabled:Ja.enabled,signinUrl:Ya,classic:ra.useClassicSubscribeButton}:null}
function e(ra){if(ra){var Ja=[],Sa=ra.videoId;Sa&&Ja.push("v="+Sa);(Sa=ra.playlistId)&&Ja.push("list="+Sa);(ra=ra.startTimeSeconds)&&Ja.push("t="+ra);return"/watch?"+Ja.join("&")}}
function f(ra){if(!ra)return null;var Ja=ra.simpleText;return Ja?Ja:ra.runs?g.Kn(ra.runs,function(Sa){return Sa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,r=null,t=null,w=null,x=null,y=!1,z=null,F=null,I=null,H=null,N=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,r=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,r=a,w=f(b.playlistLength);else if("CHANNEL"===
k){if(y=B3(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;r="new";(y=!!b.isSubscribe)?z=d(b):F=f(b.subscribersText)}else"WEBSITE"===k?((I=B3(l,"urlEndpoint","url"))&&(m=I),n=!0,r="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(N=f(b.additionalFeesText)),(n=B3(l,"urlEndpoint","url"))&&(m=n),n=!0,r="new");a=B3(b,"title","accessibility","accessibilityData","label");var ka=b.endpoint?b.endpoint.clickTrackingParams:null,
O="";if(b.metadata){var na=f(b.metadata);na&&(O=na)}return{id:"element-"+c,type:k,title:f(b.title),metadata:O,callToAction:f(b.callToAction),bL:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:w,channelId:x,subscribeButton:z,subscribersText:F,isSubscribe:y,targetUrl:m||null,iU:n,sessionData:ka?{itct:ka}:null,VY:r,wv:a?a:
null,lU:b.isPlaceholder,impressionUrls:K3(b.impressionUrls||[],J3),aU:K3(b.hovercardShowUrls||[],J3),clickUrls:K3(l.loggingUrls||[],J3),visualElement:g.gx(b.trackingParams),productPrice:H,additionalFeesText:N}},L3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:K3(a.impressionUrls||[],J3),elements:K3(a.elements||[],function(d,e){return NUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.gx(a.trackingParams));return c},M3=function(a){g.tM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.j=null;this.J=[];this.W=!0;this.I=0;a=a.T();this.N=g.bE(a)||g.fE(a);this.events=new g.qC(this);g.J(this,this.events);this.events.S(this.player,g.my("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.ny("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.yb);this.events.S(window,"focus",this.UX);this.load();var b=g.Kh("STYLE");(g.rh("HEAD")[0]||document.body).appendChild(b);g.Ve(this,function(){g.Oh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},OUa=function(a){return a.player.getVideoData().C?"current":a.N?"new":"current"},N3=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},PUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=L3(f,OUa(a))));O3(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Mq;d&&(c.postParams={ad_tracking:d});if(b=g.Iua(b))if(b=g.yg(b),b=g.ug(b))a.u=g.at(b,c)},O3=function(a,b,c){c=void 0===c?!0:c;
a.player.gf("creatorendscreen");a.j&&(a.j.dispose(),a.j=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&QUa(a);c=[];d=new g.ky(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().isMobile||(a.j=new g.W({D:"div",K:"ytp-ce-shadow"}),g.fM(a.player,a.j.element,4),a.B=new g.OK(a.j,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=RUa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.fM(a.player,f.element,4);var k=new g.ky(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);SUa(a,
f,e)}else g.rx(new g.jv("buildEndscreenElement null",e))}a.player.Nd(c);a.yb()}},QUa=function(a){var b=g.jx(),c=g.kx();
c&&b&&a.endscreen.visualElement&&g.zx(void 0,c,b,[a.endscreen.visualElement])},RUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={D:"div",Ga:["ytp-ce-element","ytp-ce-video"],V:{tabindex:"0","aria-label":b.wv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:P3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:Q3(a,b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-video-title","ytp-webkit-ellipsis"],V:{dir:g.Vq(b.title||"")},qa:b.title},{D:"div",K:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
qa:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={D:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],V:{tabindex:"0","aria-label":b.wv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",V:P3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",V:{href:Q3(a,b.targetUrl),tabindex:"-1"},U:[{D:"div",Ga:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],V:{dir:g.Vq(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-playlist-count",
U:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={D:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],V:{tabindex:"0","aria-label":b.wv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Vq(b.title||"")},qa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",U:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{D:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],qa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:P3(b)}]};c=new g.W(c);var d=g.sh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.T().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.wN(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ga:["ytp-ce-element","ytp-ce-website"],V:{tabindex:"0","aria-label":b.wv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",
U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-website-title",V:{dir:g.Vq(b.title||"")},qa:b.title},{D:"div",K:"ytp-ce-website-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:P3(b)},{D:"div",K:"ytp-ce-expanding-icon",V:TUa(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",U:[{D:"div",K:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.U.push({D:"div",K:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={D:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],V:{tabindex:"0","aria-label":b.wv||"","aria-hidden":"true"},U:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",U:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},
{D:"div",K:"ytp-ce-expanding-overlay-content",U:[{D:"div",K:"ytp-ce-expanding-overlay-body",U:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",U:[{D:"div",K:"ytp-ce-merchandise-title",V:{dir:g.Vq(b.title||"")},qa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",qa:b.metadata},{D:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],V:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",V:P3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",
U:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",qa:b.callToAction||void 0}]}]},c=new g.W(a)}b.lU&&g.L(c.element,"ytp-ce-placeholder");return c},P3=function(a){if(a.bL)var b=a.bL.thumbnails;
return TUa(b?b[b.length-1].url:null)},TUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},SUa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.W&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",k))}
function e(m){a.I+=m;0<a.I?(g.L(b.element,"ytp-ce-force-expand"),R3(a,c.id,!0)):(g.Hq(b.element,"ytp-ce-force-expand"),g.Hq(b.element,"ytp-ce-element-hover"),R3(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Pa("mouseenter",function(){S3(a,b,c)});
b.Pa("mouseleave",function(){T3(a,b,c)});
a.player.T().isMobile||b.Pa("click",function(){g.L(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){UUa(a,c,m)});
b.Pa("keypress",function(m){UUa(a,c,m)});
b.Pa("focus",function(){S3(a,b,c)});
b.Pa("blur",function(){T3(a,b,c)});
b.Pa("touchstart",function(){S3(a,b,c)});
var l=g.uh("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Hq(b.element,"ytp-ce-element-hover");g.Hq(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.W=9===m.keyCode&&!m.shiftKey});
d(g.uh("ytp-sb-subscribe",b.element));d(g.uh("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",k)},UUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Fq(d,"ytp-ce-element");){g.Fq(d,"subscribe-label")&&U3(a,b);
if(g.Fq(d,"ytp-ce-channel-subscribe"))return;d=g.Ph(d)}if(!d||g.Fq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])T3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.VY)U3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.yg(Q3(a,b.targetUrl)),c=g.ug(c),g.nL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().C,f=function(){var k=Q3(a,b.targetUrl),l=b.sessionData,m=g.Ms(k);e&&m&&(m.v||m.list)?a.player.gk(m.v,l,m.list,!1):
g.mL(k,l)};
U3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q3=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.DE(a)+b}else return"";return b},S3=function(a,b,c){g.Fq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.L(b.element,"ytp-ce-element-hover"):a.player.T().isMobile?(new g.K(function(){g.L(b.element,"ytp-ce-element-hover")},200)).start():g.L(b.element,"ytp-ce-element-hover"),V3(a,c.aU),R3(a,c.id,!0))},T3=function(a,b,c){g.Hq(b.element,"ytp-ce-element-hover");
g.Hq(b.element,"ytp-ce-force-expand");R3(a,c.id,!1)},R3=function(a,b,c){a.j&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.i[e].element,"ytp-ce-element-shadow-show",c)},V3=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||N3(a))c&&c();else{b=VUa(a,b);var e=0,f=!1,k=new g.K(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.nw(b[a],d)}},U3=function(a,b,c){V3(a,b.clickUrls,c);
(a=g.kx())&&b.iU&&g.Fx(a,b.visualElement)},VUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(WUa(b[d],c));return a},WUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},XUa=function(a){return"string"===typeof a?a:""},W3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},YUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},X3=function(a){return a.value?a.value:null},Y3=function(a){if(!a)return null;
var b=g.yg(XUa(a.value));b=g.ug(b);if(!b)return null;var c=W3(a.target,ZUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new YUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$Ua=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},cVa=function(a){if(!a)return null;
var b=W3(a.type,aVa),c=W3(a.trigger,bVa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y3(a?a:null);return b?new $Ua(b,c,a):null},dVa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},fVa=function(a){return(a=eVa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},eVa=function(a,b){return g.Wb(a.action,b,void 0)},gVa=function(a,b){this.context=a;
this.i=b},$3=function(a){return a.customMessage?Z3("div","iv-card-message",a.customMessage):""},a4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",V:{style:a},U:c}},b4=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",U:b}},Z3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Vq(c);return{D:a,V:b,qa:c}},hVa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Xy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Xy+");");c.dir=g.Vq(a.customMessage);var d=[{D:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ga:b,V:c,U:d}},c4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},iVa=function(a,b){this.merchant=a;
this.price=b},jVa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},kVa=function(a,b){return b?b:jVa(a)?"current":"new"},d4=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.fb=!1;this.Qa=new Map;this.Ta=new Map;this.context.G.addEventListener(g.my("annotations_module"),function(d){(d=c.Qa.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.ny("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)})},e4=function(a,b,c,d,e,f,k){a.context.i.Pa(b,"click",function(l){a.WC(c,d,e,f||[],k||0,l)});
a.context.i.Pa(b,"touchstart",function(){a.fb=!1});
a.context.i.Pa(b,"touchmove",function(){a.fb=!0})},lVa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},f4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
jP:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
PB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},i4=function(a,b,c){d4.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.Ia=this.wb=this.u=this.isInitialized=!1;this.va=null;this.cards=[];this.jb=this.N=this.Ha=this.C=this.La=this.i=null;this.Y=[];this.J=this.Le=this.ya=null;this.I=0;this.xa=new g.K(function(){},c.X.ye?4E3:3E3);
g.J(this,this.xa);this.Ya=new g.K(function(){});
g.J(this,this.Ya);this.ea=new gVa(c,function(e,f,k,l,m,n){e4(d,e,f,k,l,m,n)});
this.W=new g.W({D:"div",K:"iv-drawer",V:{id:"iv-drawer"},U:[{D:"div",K:"iv-drawer-header",V:{"aria-role":"heading"},U:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ga:["iv-drawer-close-button","ytp-button"],V:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.J(this,this.W);this.B=this.W.element;this.Wa=new g.OK(this.W,330);g.J(this,this.Wa);this.kb=g.uh("iv-drawer-header-text",this.B);this.j=g.uh("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.wb&&g4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wb=d.u)&&h4(d)})},mVa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){g4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){h4(a)});
var c=b.headerText;g.Rh(a.kb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.ya=g.gx(b.trackingParams);a.J=g.gx(b.closeTrackingParams);a.Le=g.gx(b.iconTrackingParams)},nVa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.ry(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.command),Ul:d.trackingParams?g.gx(d.trackingParams):null,jj:e.trackingParams?
g.gx(e.trackingParams):null,Le:f&&f.trackingParams?g.gx(f.trackingParams):null,imageUrl:k4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.ry(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Xy:null,title:d.title?g.ry(d.title):"",customMessage:d.callToAction?g.ry(d.callToAction):"",url:d.command.urlEndpoint.url?Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};l4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.ry(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.endpoint),Ul:d.trackingParams?g.gx(d.trackingParams):null,jj:e.trackingParams?g.gx(e.trackingParams):null,Le:f&&f.trackingParams?
g.gx(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.ry(d.customText):null,profileImageUrl:k4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.ry(d.channelName):"",metaInfo:[d.subscriberCountText?g.ry(d.subscriberCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
l4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.ry(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Ul:d.trackingParams?g.gx(d.trackingParams):
null,jj:e.trackingParams?g.gx(e.trackingParams):null,Le:f&&f.trackingParams?g.gx(f.trackingParams):null,jy:k4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.ry(d.customMessage):null,playlistVideoCount:g.ry(d.playlistVideoCount),title:d.playlistTitle?g.ry(d.playlistTitle):"",metaInfo:[d.channelName?g.ry(d.channelName):"",d.videoCountText?g.ry(d.videoCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lVa(d.action)})};l4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.ry(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Ul:d.trackingParams?g.gx(d.trackingParams):null,jj:e.trackingParams?g.gx(e.trackingParams):null,Le:f&&f.trackingParams?g.gx(f.trackingParams):
null,jy:k4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.ry(d.lengthString):null,customMessage:d.customMessage?g.ry(d.customMessage):null,title:d.videoTitle?g.ry(d.videoTitle):"",metaInfo:[d.channelName?g.ry(d.channelName):"",d.viewCountText?g.ry(d.viewCountText):""],isLiveNow:!!d.badge,url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lVa(d.action)})};l4(a,b)}a.I++},k4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},pVa=function(a,b){if(b=oVa(a,b))b===a.i&&(a.i=null),a.G.removeCueRange(b.card.id),g.Oh(b.UD),g.cc(a.cards,b),a.bz(),m4(a)},g4=function(a,b,c){if(!a.u){a.Wa.show();
a.La=new g.K(function(){g.L(a.context.G.getRootNode(),g.iT.IV_DRAWER_OPEN)},0);
a.La.start();a.va=g.Qt(a.j,"mousewheel",function(k){a.xa.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.j.scrollTop+=k});
a.u=!0;var d=g.kx();d&&a.ya&&a.J&&g.Dx(d,[a.ya,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.LM||(f.LM=!0,qVa(a.context.logger,f.card.tracking.impression,b)),d&&g.Dx(d,[f.card.Ul]);A3(a.G);c&&(a.C=new g.K(function(){a.Ha=a.N;a.jb.focus()},330),a.C.start())}},h4=function(a){a.u&&(a.Wa.hide(),g.Rt(a.va),a.va=null,g.Hq(a.context.G.getRootNode(),g.iT.IV_DRAWER_OPEN),a.u=!1,A3(a.G),a.C&&a.C.stop(),a.C=new g.K(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.C.start())},
sVa=function(a){g.Gq(a.element,[g.iT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.fM(a.G,a.B,5);rVa(a);a.N=g.uh("ytp-cards-button",a.G.getRootNode());a.jb=g.uh("iv-drawer-close-button",a.B);a.isInitialized=!0},rVa=function(a){var b=g.uh("iv-drawer-close-button",a.B);
a.context.i.Pa(b,"click",a.ES,a);a.context.i.Pa(a.j,"touchend",function(){a.xa.start()});
a.context.i.Pa(a.j,"scroll",a.RS,a);a.context.j.subscribe("onHideControls",function(){a.Ia=!0});
a.context.j.subscribe("onShowControls",function(){a.Ia=!1});
a.context.j.subscribe("onVideoAreaChange",function(){a.Ia=g.Fq(a.G.getRootNode(),"ytp-autohide")});
a.Y.push(g.ju("iv-button-shown",a.rU,a));a.Y.push(g.ju("iv-button-hidden",a.qU,a));a.Y.push(g.ju("iv-teaser-shown",a.jR,a));a.Y.push(g.ju("iv-teaser-hidden",a.sU,a));a.Y.push(g.ju("iv-teaser-clicked",a.iR,a))},l4=function(a,b){a.isInitialized||sVa(a);
pVa(a,b.id);var c=tVa(a,b);if(c){var d={card:b,UD:c.element,LM:!1},e=uVa(a,d);g.jc(a.cards,e,0,d);c.Ca(a.j,e);a.bz();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,m4(a),vVa(a,d),g4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&wVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){wVa(a,d)}),m4(a))}},tVa=function(a,b){switch(b.type){case "simple":a=a.ea;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",qa:b.displayDomain}:void 0;var d=hVa(b);c={D:"div",Ga:["iv-card"],U:[{D:"a",K:"iv-click-target",V:{href:b.url?X3(b.url)||"":""},U:[a4(b.imageUrl,c),{D:"div",K:"iv-card-content",U:[Z3("h2",void 0,b.title),d]}]}]};c=new g.W(c);c4(a,g.th("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ea,c={D:"div",Ga:["iv-card","iv-card-channel"],U:[{D:"a",Ga:["iv-click-target"],V:{href:X3(b.url)||"","data-ytid":b.channelId},U:[a4(b.profileImageUrl),
{D:"div",K:"iv-card-content",U:[$3(b),{D:"h2",K:"iv-card-primary-link",qa:b.title},b4(b)]}]}]},c=new g.W(c),c4(a,g.th("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ea,c={D:"div",Ga:["iv-card","iv-card-playlist"],U:[{D:"a",K:"iv-click-target",V:{href:X3(b.url)||""},U:[a4(b.jy,{D:"div",K:"iv-card-image-overlay",U:[{D:"span",K:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",U:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b)]}]}]},c=new g.W(c),
c4(a,g.th("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ea;var e=!g.$b(b.offers);c=["iv-card"];d="";var f=hVa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",qa:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",qa:f.merchant}),f={D:"div",U:e});e=b.url?X3(b.url)||"":"";c={D:"div",Ga:c,V:{tabindex:"0"},U:[{D:"a",Ga:["iv-card-image","iv-click-target"],V:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",U:[b.sponsored?{D:"div",K:"iv-card-sponsored",U:["Lien commercial",{D:"div",K:"iv-ad-info-container",U:[{D:"div",K:"iv-ad-info",qa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",U:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",V:{href:e},U:[Z3("h2",d,b.title),f]}]}]};c=new g.W(c);d=g.Kh("span");g.Rh(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.yd(d,"adInfo");c4(a,g.th("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ea,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",qa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ga:["yt-badge","yt-badge-live"],qa:"EN DIRECT MAINTENANT"}:null,e={D:"div",Ga:["iv-card","iv-card-video"],U:[{D:"a",K:"iv-click-target",V:{href:(null==(c=b.url)?void 0:X3(c))||""},U:[a4(b.jy,d),{D:"div",K:"iv-card-content",U:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b),f]}]}]},c=new g.W(e),
c4(a,g.th("iv-click-target",c.element),b,b.url),c;default:return null}},uVa=function(a,b){if(0===a.cards.length)return 0;
a=g.Xb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},xVa=function(a){return a.i?"productListing"===a.i.card.type:g.Ln(a.cards,function(b){return"productListing"===b.card.type})},m4=function(a){g.M(a.G.getRootNode(),"ytp-cards-shopping-active",xVa(a))},wVa=function(a,b){if(!g.Fq(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.kx(),d=a.i?a.i.card.Le:a.Le;
c&&d&&g.Ex(c,[d]);a.i=b;m4(a)}if(c="none"!=a.element.style.display)c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.G.Wt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.xa.isActive()&&a.Ia)&&vVa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},vVa=function(a,b){a.W.sb?(b=new F3([0,
a.j.scrollTop],[0,b.UD.offsetTop],600,HUa),a.context.u.Pa(b,"animate",function(c){a.j.scrollTop=c.y}),a.context.u.Pa(b,"finish",function(c){a.j.scrollTop=c.y}),b.play()):(g.ZJ(a.W,!0),a.j.scrollTop=b.UD.offsetTop,g.ZJ(a.W,!1))},n4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},oVa=function(a,b){return g.Wb(a.cards,function(c){return c.card.id===b})},o4=function(a,b,c){d4.call(this,a,b);
this.annotation=c;this.isActive=!1},yVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p4=function(a,b,c){o4.call(this,a,b,c);
this.j=null;this.J=!1;this.u=null;this.B=!1;this.i=this.I=this.C=null},zVa=function(a,b){var c=void 0===c?0:c;
var d=FUa(b).width;g.on(b,d);c=new H3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,GUa);g.J(a,c);a.context.u.Pa(c,"begin",function(){g.En(b,!0)});
c.play()},CVa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ga:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({D:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.wN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.i.Ca(d));var f=a.createElement({D:"div",Ga:["iv-branding-context-subscribe-caret"]}),k=a.createElement({D:"div",Ga:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.En(k,!1);var l=a.createElement({D:"div",Ga:["branding-context-container-outer"]});l.appendChild(k);g.gn(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.K(function(){AVa(a,k,l)},500);
g.J(a,a.u);a.context.i.Pa(a.element,"mouseover",function(){BVa(a,k,l,f,b.image_height)});
a.context.i.Pa(a.element,"mouseout",function(){a.u.start()})}},BVa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Dn(b);a.i||(b.style.width=g.nn(f.width,!0),c.style.width=g.nn(f.width,!0));g.gn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.gn(d,"right","1px");a.B=!0;g.En(b,!0);a.C=new g.K(function(){g.L(this.element,"iv-branding-active")},0,a);
a.C.start()}},AVa=function(a,b,c){g.Hq(a.element,"iv-branding-active");
a.I=new g.K(function(){g.En(b,!1);a.i||(c.style.width=g.nn(0,!0))},250);
a.I.start();a.B=!1},DVa=function(a,b,c,d,e,f,k){this.i=a;
this.u=b;this.X=c;this.videoData=d;this.logger=e;this.G=f;this.j=k},q4=function(a,b,c){o4.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.W=!1;this.I=5E3;this.j=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ga:["iv-promo-contents"]});this.C=new g.K(function(){d.i.setAttribute("aria-hidden","true");g.En(d.u,!1);g.En(d.j,!0)},700,this);
g.J(this,this.C)},EVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=fVa(a.annotation),f=b.image_url;if(f){var k=a.createElement({D:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",V:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",qa:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),k.appendChild(f));e&&e4(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.Tg(f,X3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",U:[{D:"strong",
qa:b.text_line_1}]});var m=a.createElement({D:"p",U:[{D:"span",K:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ga:["iv-button","iv-promo-button"],U:[{D:"span",K:"iv-button-content",qa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&e4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.i,
"iv-click-target");e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",U:[{D:"span",qa:b.text_line_1}]}),m=a.createElement({D:"p",U:[{D:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ga:["yt-badge","iv-promo-badge-live"],qa:"EN DIRECT MAINTENANT"})),g.L(a.i,"iv-click-target"),e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.j=a.createElement({D:"button",Ga:["iv-promo-expand","ytp-button"]});a.j.title="Agrandir";a.context.i.Pa(a.j,"click",function(r){r4(a,5E3,r)});
c.appendChild(a.j);g.En(a.j,!1);a.context.i.Pa(a.element,"mouseover",a.CT,a);a.context.i.Pa(a.element,"mouseout",a.BT,a);a.context.i.Pa(a.element,"touchend",function(r){r4(a,5E3,r)});
a.u=a.createElement({D:"button",Ga:["iv-promo-close","ytp-button"]});a.u.title="Fermer";a.context.i.Pa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.wT:a.vT,a);c.appendChild(a.u);g.Gq(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},r4=function(a,b,c){c.stopPropagation();
FVa(a);GVa(a,b);a.i.focus()},HVa=function(a){a.isCollapsed||a.N||a.B||(g.L(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},FVa=function(a){a.C.stop();
a.isCollapsed&&(g.Iq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.En(a.j,!1),g.En(a.u,!0))},GVa=function(a,b){a.B||(a.B=g.Ai(function(){s4(this);
HVa(this)},b,a))},s4=function(a){a.B&&(g.C.clearTimeout(a.B),a.B=null)},IVa=function(a){this.G=a},qVa=function(a,b,c){b&&(c?t4(a,b.map(function(d){return g.nq(d,c)})):t4(a,b))},t4=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.nw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},u4=function(a){g.tM.call(this,a);
var b=this;this.N=!1;this.loadNumber=0;this.I={};this.logger=new IVa(this.player);this.B=new g.qC(this);this.C=this.El=null;this.events=new g.qC(this);this.J=this.i=null;this.W=[];g.J(this,this.B);this.B.S(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.B.S(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.B.S(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.B.S(this.player,"resize",function(d){b.Z("resize",d)});
this.B.S(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.kR,this);this.subscribe("resize",this.TA,this);this.player.T().W.subscribe("vast_info_card_add",this.bO,this);g.J(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.j=new g.W({D:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.j);g.fM(this.player,this.j.element,4);this.j.hide();this.u=new g.W({D:"div",Ga:["ytp-iv-video-content"]});g.J(this,this.u);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.u.element.appendChild(a);this.Xq()&&this.load();var c=this.createElement({D:"style"});(g.rh("HEAD")[0]||document.body).appendChild(c);g.Ve(this,function(){g.Oh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},JVa=function(a){a=a.createElement({D:"div",
Ga:["annotation","annotation-type-custom"]});g.En(a,!1);return a},KVa=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.ZJ(a.j,b);g.ZJ(a.u,b)},LVa=function(a,b,c){a.N=!0;
a.C=g.at(b,c)},MVa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(MVa(a,e))}return c},PVa=function(a){var b=a.player.getVideoData();
if(b.Qa){var c=a.player.T().W.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.Us(k)&&k.responseXML?k.responseXML:null)&&v4(a,k)}};
g.rt()&&(d.onFinish=NVa(a,d.onFinish));d.postParams={ic_only:"1"};OVa(d,c);a.N=!0;g.at(b.Qa,d)}}},OVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Fv&&(a.postParams.ic_coll=b.Fv);b.iz&&(a.postParams.ic_xml=b.iz);b.py&&(a.postParams.ic_track=b.py)},QVa=function(a){var b=new g.W({D:"div"});
g.En(b.element,!1);var c=new i4(a.player,b.element,w4(a));g.J(c,b);b.Ca(a.j.element);c.Qx();return c},w4=function(a){if(!a.J){var b=new I3(a);
g.J(a,b);var c=new g.Jl(a);g.J(a,c);a.J=new DVa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Md)}return a.J},v4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.kx();if(e){var f=g.jx();f&&g.zx(void 0,e,f,[g.gx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=MVa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=W3(f.type,RVa),p=W3(f.style,SVa),r=XUa(f.data),t=0!==r.length?JSON.parse(r):{};var w=f.action;f=cVa;if(null==w)var x=null;else if(g.Oa(w)){l=[];for(var y=g.q(w),z=y.next();!z.done;z=y.next()){var F=f(z.value);
F&&l.push(F)}x=l}else{var I=f(w);x=I?[I]:[]}e=m&&n?new dVa(m,n,p,x,t):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var H=JVa(f),N=null;switch(l.type){case "branding":if(f.player.T().Rb)break;f.j.element.appendChild(H);N=new p4(H,w4(f),l);break;case "promotion":g.fM(f.player,H,4),N=new q4(H,w4(f),l)}N&&N.Qx();if(f=N)g.J(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=QVa(a),g.J(a,a.i));if("card"===e.type){c=a.i;var ka=e&&e.data&&e.data.card_type;
f=e.data;if(ka)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,jP:l.teaser_impression,PB:l.teaser_click},H=f.tracking_params||{},N=null,ka){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:H.card?g.gx(H.card):null,jj:H.teaser?g.gx(H.teaser):null,Le:H.icon?g.gx(H.icon):
null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:H.card?g.gx(H.card):
null,jj:H.teaser?g.gx(H.teaser):null,Le:H.icon?g.gx(H.icon):null,jy:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "productListing":f.signin_url&&(N=Y3({target:"current",value:f.signin_url}));ka=[];for(var O=f.offers||[],na=0;na<O.length;na++)ka.push(new iVa(g.hh(O[na].merchant),g.hh(O[na].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:H.card?g.gx(H.card):null,jj:H.teaser?g.gx(H.teaser):null,Le:H.icon?g.gx(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Xy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Qfa:N,Pfa:f.signin_title?f.signin_title:void 0,Ofa:f.signin_message?f.signin_message:void 0,offers:ka};l4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:H.card?g.gx(H.card):null,jj:H.teaser?
g.gx(H.teaser):null,Le:H.icon?g.gx(H.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Xy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ul:H.card?g.gx(H.card):null,jj:H.teaser?g.gx(H.teaser):null,Le:H.icon?g.gx(H.icon):null,jy:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},l4(c,e)}}else mVa(a.i,e);c=!0}}c&&(A3(a.player),a.TA())},TVa=function(a,
b){var c=!1;
a.i||(a.i=QVa(a),g.J(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(nVa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.ry(b.headerText):"",g.Rh(c.kb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ya=b.trackingParams?g.gx(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.gx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Le=b.icon.infoCardIconRenderer.trackingParams?
g.gx(b.icon.infoCardIconRenderer.trackingParams):null,A3(a.player),a.TA())},UVa=function(a,b,c,d,e){if(!a.player.T().Rb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new $Ua("openUrl","click",new YUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.ry(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.ry(b.subscriberCountText))):(b.subscriberCountText&&(e=g.ry(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.ry(b.subscriberCountWithSubscribeText)));if(b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url)var m=b.signInEndpoint.webNavigationEndpointData.url;else{var n,p;m=(null==(l=b.signInEndpoint)?void 0:null==(n=l.commandMetadata)?void 0:null==(p=n.webCommandMetadata)?void 0:p.url)||""}l={subscribeText:g.ry(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.ry(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:m};d.standalone_subscribe_button_data=l}f=new dVa(c,
"branding","branding",f,d);l=JVa(a);a.j.element.appendChild(l);f=new p4(l,w4(a),f);f.Qx();g.J(f,f);a.I[c]=f}},NVa=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.W.push(g.du.Uf(function(){b.apply(null,g.u(c))}))}},VVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.ZL.prototype.Wt=g.ca(18,function(a,b){var c=g.IM(this.tb());c&&c.Wt(a,b)});
var C3={},D3=null;g.Wa(F3,g.Qq);g.h=F3.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.j;else if(this.Ic())return!1;E3(this);this.startTime=a=g.Va();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.PA();this.Ai("play");-1==this.i&&this.Ai("resume");this.i=1;var b=g.Ra(this);b in C3||(C3[b]=this);JUa();KUa(this,a);return!0};
g.h.stop=function(a){E3(this);this.i=0;a&&(this.progress=1);LUa(this,this.progress);this.Ai("stop");this.lx()};
g.h.pause=function(){this.Ic()&&(E3(this),this.i=-1,this.Ai("pause"))};
g.h.ra=function(){0==this.i||this.stop(!1);this.Ai("destroy");F3.ue.ra.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.VC=function(){this.Ai("animate")};
g.h.Ai=function(a){this.dispatchEvent(new MUa(a,this))};
g.Wa(MUa,g.We);g.Wa(G3,F3);G3.prototype.B=g.La;G3.prototype.VC=function(){this.B();G3.ue.VC.call(this)};
G3.prototype.lx=function(){this.B();G3.ue.lx.call(this)};
G3.prototype.PA=function(){this.B();G3.ue.PA.call(this)};
g.Wa(H3,G3);H3.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(I3,g.G);I3.prototype.Pa=function(a,b,c,d){c=(0,g.Ta)(c,d||this.j);a=g.Qt(a,b,c);this.i.push(a);return a};
I3.prototype.zA=function(a,b,c,d){c=(0,g.Ta)(c,d||this.j);a=g.Pka(a,b,c);this.i.push(a);return a};
I3.prototype.xc=function(a){g.Rt(a);g.cc(this.i,a)};
I3.prototype.ra=function(){g.Rt(this.i);this.i.length=0;g.G.prototype.ra.call(this)};g.v(M3,g.tM);g.h=M3.prototype;g.h.load=function(){g.tM.prototype.load.call(this);if(!N3(this)){var a=g.Jua(this.player.getVideoData());a?(a=L3(a,OUa(this)),O3(this,a,!1)):PUa(this)}};
g.h.unload=function(){O3(this,null);this.u&&(this.u.abort(),this.u=null);g.tM.prototype.unload.call(this)};
g.h.tf=function(a,b){return N3(this)?"loadCustomEndscreenRenderer"===a?(a=L3(b,"new"),O3(this,a),!0):null:null};
g.h.getOptions=function(){return N3(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<WVa.length;f++){var k=Math.abs(b.width-WVa[f]);if(-1===e||d>=k)e=f,d=k}d=XVa[e];this.j&&g.gn(this.j.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Cn(e.element,Math.round(k.width*a.width),f);g.on(e.element,m,n);g.Iq(e.element,YVa);m=k.left+k.width/2;k=k.top+l/2;g.L(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Iq(e.element,XVa);g.L(e.element,d);(e=g.sh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.gn(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V3(this,this.endscreen.impressionUrls),(a=g.kx())&&this.endscreen.visualElement&&g.Ax(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");V3(this,c.impressionUrls);(b=g.kx())&&g.Ax(b,c.visualElement,void 0);this.player.T().u&&this.player.Oa("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Hq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Hq(b,"ytp-ce-shown");this.player.T().u&&this.player.Oa("endscreenelementhidden",a)}};
g.h.UX=function(a){var b=this;a.target===window&&(new g.K(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Iq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var WVa=[346,426,470,506,570,640,853,1280,1920],XVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),YVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ZUa={P3:"current",g$:"new"};var aVa={CLOSE:"close",A$:"openUrl",SUBSCRIBE:"subscribe"},bVa={r0:"click",CLOSE:"close",m5:"hidden",dba:"rollOut",eba:"rollOver",Zba:"shown"};var SVa={p_:"anchored",ZP:"branding",CHANNEL:"channel",O3:"cta",p5:"highlightText",Q6:"label",PLAYLIST:"playlist",vaa:"popup",ica:"speech",SUBSCRIBE:"subscribe",Aca:"title",VIDEO:"video",eea:"website"},RVa={ZP:"branding",b0:"card",g4:"drawer",o5:"highlight",u8:"marker",Faa:"promotion",TEXT:"text",Iea:"widget"};g.v(d4,g.G);g.h=d4.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.ky(a,b,{id:c,namespace:"annotations_module"});d&&this.Qa.set(a,d);e&&this.Ta.set(a,e);this.context.G.Nd([a])};
g.h.Qx=function(){this.context.j.subscribe("resize",this.bz,this)};
g.h.WC=function(a,b,c,d,e,f){if(this.fb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Oh(this.element)};
g.h.bz=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=X3(a);if(f){var k=kVa(f,a.target),l=function(){a.i&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.Ms(f||"");m&&n&&(n.v||n.list)?e.context.G.gk(n.v,b,n.list,!1):g.nL(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);t4(this.context.logger,c,l,d);jVa(f)||(c=g.kx(),d=b.itct,c&&d&&g.Fx(c,g.gx(d)))}};
g.h.ra=function(){this.Qa.clear();this.Ta.clear();g.G.prototype.ra.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.v(i4,d4);g.h=i4.prototype;g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Dn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.bz=function(){var a=this.isAvailable();g.En(this.element,a);g.M(this.context.G.getRootNode(),g.iT.IV_DRAWER_ENABLED,a);A3(this.G)};
g.h.destroy=function(){this.G.Wt(!1);try{this.G.getRootNode().removeChild(this.B)}catch(a){}g.ku(this.Y);g.Rt(this.va);this.La&&this.La.dispose();this.C&&this.C.dispose();d4.prototype.destroy.call(this)};
g.h.ES=function(){if(this.u){t4(this.context.logger,n4(this).tracking.close);var a=g.kx();a&&this.J&&g.Fx(a,this.J);h4(this)}};
g.h.RS=function(){g.M(this.B,"iv-drawer-scrolled",0<this.j.scrollTop)};
g.h.rU=function(){var a=g.kx(),b=n4(this);b=b?b.Le:this.Le;a&&b&&g.Dx(a,[b])};
g.h.qU=function(){var a=g.kx(),b=n4(this);b=b?b.Le:this.Le;a&&b&&g.Ex(a,[b])};
g.h.jR=function(){var a=n4(this);t4(this.context.logger,a.tracking.jP);var b=g.kx();b&&a&&g.Dx(b,[a.jj,a.Le])};
g.h.sU=function(){var a=g.kx(),b=n4(this);a&&b&&g.Ex(a,[b.jj])};
g.h.iR=function(a){var b=n4(this),c=g.kx();this.i?a?(a=this.context.logger,t4(a,b.tracking.PB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.jj&&g.Fx(c,b.jj)):(a=this.context.logger,t4(a,b.tracking.PB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Le&&g.Fx(c,b.Le)):(a=this.context.logger,t4(a,b.tracking.PB),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.Le&&g.Fx(c,this.Le))};g.v(o4,d4);o4.prototype.Qx=function(){d4.prototype.Qx.call(this);yVa(this)};
o4.prototype.show=function(){d4.prototype.show.call(this);var a=g.kx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Dx(a,[g.gx(b.itct)])};
o4.prototype.hide=function(){d4.prototype.hide.call(this);var a=g.kx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ex(a,[g.gx(b.itct)])};g.v(p4,o4);
p4.prototype.show=function(){if(!this.isActive){o4.prototype.show.call(this);if(!this.J){g.L(this.element,"iv-branding");var a=this.annotation.data;this.j=this.createElement({D:"img",Ga:["branding-img","iv-click-target"],V:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.En(this.j,!1);var b=this.context.X.L("html5_player_branding_button_killswitch")?this.createElement({D:"div",Ga:["branding-img-container"]}):this.createElement({D:"button",Ga:["branding-img-container",
"ytp-button"]});b.appendChild(this.j);this.element.appendChild(b);var c=fVa(this.annotation);c&&(b=this.context.X.L("html5_player_branding_button_killswitch")?this.j:b,e4(this,b,c,this.annotation.id,a.session_data));CVa(this,a);this.J=!0}g.En(this.element,!0);this.isActive=!0;this.j&&zVa(this,this.j)}};
p4.prototype.hide=function(){this.isActive&&(o4.prototype.hide.call(this),g.En(this.element,!1),this.isActive=!1)};
p4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);o4.prototype.destroy.call(this)};g.v(q4,o4);g.h=q4.prototype;g.h.show=function(){this.isActive||(o4.prototype.show.call(this),this.W||(EVa(this),this.W=!0),g.En(this.element,!0),g.Ai(function(){g.Hq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,s4(this),FVa(this),GVa(this,this.I))};
g.h.hide=function(){this.isActive&&(g.L(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.WC=function(a,b,c,d,e,f){return this.isCollapsed?!1:o4.prototype.WC.call(this,a,b,c,d,e,f)};
g.h.CT=function(a){this.N=!0;r4(this,500,a)};
g.h.BT=function(){this.N=!1;HVa(this)};
g.h.vT=function(a){a.stopPropagation();this.hide()};
g.h.wT=function(a){a.stopPropagation();s4(this);this.isCollapsed=!0;g.L(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.h.destroy=function(){this.C.dispose();o4.prototype.destroy.call(this)};g.v(u4,g.tM);g.h=u4.prototype;g.h.tf=function(a,b){if(!VVa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.Z1(b))&&v4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(pVa(this.i,b),A3(this.player)),!0}return null};
g.h.getOptions=function(){return VVa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Xq=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.HM||a.W.get(b.videoId)||g.SF(b)||g.TF(b)?!0:!1};
g.h.TA=function(){if(this.u){var a=this.player.bb().getVideoContentRect(!0);g.Cn(this.u.element,a.width,a.height);g.on(this.u.element,a.left,a.top)}if(this.i){var b=this.player.Ej();a=this.i;b=b.width;g.M(a.B,"iv-drawer-small",426>=b);g.M(a.B,"iv-drawer-big",1280<=b)}};
g.h.kR=function(a){KVa(this,a.state);g.V(a.state,2)&&(this.Gh()&&this.Lk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Wt(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.Us(k)&&k.responseXML?k.responseXML:null)&&(v4(b,k),g.L(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.tM.prototype.load.call(this);KVa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.rt()&&(a=NVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().W.get(d);f&&OVa(e,f);f=f&&(f.iz||f.Fv);if(!c.Ap||f)c.Qa?LVa(this,c.Qa,e):(this.El=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.El));
g.fM(this.player,this.u.element,4);this.TA();(f=g.SF(c))&&TVa(this,f);(f=g.TF(c))&&f.featuredChannel&&UVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Qa&&(this.El&&(this.player.removeEventListener("videodatachange",this.El),this.El=null),LVa(this,b.Qa,a))};
g.h.unload=function(){this.player.gf("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.i&&(this.i.destroy(),this.i=null,A3(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.I={};this.j.hide();g.tM.prototype.unload.call(this);this.u.detach();this.El&&(this.player.removeEventListener("videodatachange",this.El),this.El=null)};
g.h.bO=function(a){a===this.player.getVideoData().videoId&&(this.loaded?PVa(this):this.load())};
g.h.Gh=function(){return!!this.i&&this.i.isAvailable()};
g.h.Lk=function(){this.Gh();return!!this.i&&this.i.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Gh();this.i&&(a?c?g4(this.i,c,b):g4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):h4(this.i))};
g.h.Wt=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.ra=function(){this.player.T().W.unsubscribe("vast_info_card_add",this.bO,this);g.Hq(this.player.getRootNode(),g.iT.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.du.wi(a[b]);this.W.length=0;g.tM.prototype.ra.call(this)};
g.h.createElement=function(a){a=new g.W(a);g.J(this,a);return a.element};g.sM("annotations_module",u4);g.sM("creatorendscreen",M3);})(_yt_player);
