(function(g){var window=this;'use strict';var A4=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},B4=function(a){return g.tE(a)&&a.L("web_player_i_see_captions_3")},ZVa=function(a,b){var c,d,e;
return g.B(function(f){if(1==f.i)return c=a+"|"+b,g.A(f,g.Vv(),2);if(3!=f.i){d=f.j;if(!d)throw g.uv("gct");return g.A(f,g.WE(d),3)}e=f.j;return f.return(e.get("captions",c))})},$Va=function(a,b){var c=new g.ZE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},aWa=function(a,b,c){ZVa(a,b).then(function(d){d&&c(d.trackData,new g.ZE(d.metadata))})},C4=function(){this.segments=[]},bWa=function(a,b){var c=g.mc(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.bc(a.segments,c),g.bc(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.jc(a.segments,c,0,b),g.jc(a.segments,c+1,0,b)))},D4=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.Y=c;this.N=d;this.C=e;this.W=f;this.X=this.player.T();this.B=new C4;this.I=-1;this.u=this.j=this.i=null;this.J=new g.K(this.IM,1E3,this);this.events=new g.qC(this);g.J(this,this.J);g.J(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.VA);this.VA();this.IM()},cWa=function(a){return a.i&&a.i.C?a.i.C+a.player.kd()<a.player.getCurrentTime():!1},dWa=function(a,b){var c=g.kB(g.GB(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.dt(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.j){var f=!(a.C?e.response:e.responseText)||400<=e.status,k=g.Zqa(e);if(k){e=g.GB(a.j,a.policy,{});a.j.Gj(e,k);dWa(a,a.j);break a}f||(k=a.j.i[0].Na,null!=a.N&&a.I!==k&&(f=a.j.i[0],a.C?a.N(e.response,1E3*(f.startTime+a.player.kd())):a.N(e.responseText,1E3*(f.startTime+a.player.kd())),a.I=k))}a.j=null;a.u=null}}).yh(function(){a.j=null;
a.u=null;a.ma()});
a.j=b;bWa(a.B,a.j.i[0].Na)},E4=function(a,b){g.wM.call(this,b.T());
this.i=a;this.G=b;this.u=null;this.C=!1;this.I=g.vE(this.G.T())&&!this.i.isManifestless},fWa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.yM(e,b||null)){var f=e.info.id,k=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.gUa.get(e);null==n&&(n=eWa[e]||eWa[e.replace(/-/g,"_")],g.gUa.set(e,n));k=n||k}c.push(new g.ZE({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},gWa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},hWa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.yM(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},F4=function(a){if(!iWa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(jWa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},G4=function(a,b,c,d,e,f){var k={};
Object.assign(k,b);Object.assign(k,a.params);Object.assign(k,c);var l={};Object.assign(l,b.Bd);a.params.Bd&&Object.assign(l,a.params.Bd);Object.assign(l,c.Bd);k.Bd=l;g.W.call(this,{D:"div",K:"caption-window",V:{id:"caption-window-"+a.id,dir:1===k.Of?"rtl":"ltr",tabindex:"0",lang:k.lang},U:[{D:"span",K:"captions-text",V:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ea=!1;this.j=a;this.ya=this.xa=null;this.playerWidth=e;this.playerHeight=f;this.I=null;this.maxWidth=.96*e;this.Ta=.96*
f;this.i=k;this.Ab=c;this.Ha=b;this.B=this.Da("captions-text");this.kb=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Ia=d/360*16;this.type=0;this.Wa=this.Ia*kWa(l);a=new g.Yw(this.element,!0);g.J(this,a);a.subscribe("dragstart",this.nR,this);a.subscribe("dragmove",this.mR,this);a.subscribe("dragend",this.lR,this);this.fb=this.Ya=0;b="";this.i.windowOpacity&&(a=F4(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+
","+this.i.windowOpacity+")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":lWa[this.i.textAlign]};this.kb&&(a["border-radius"]=b?this.Wa/8+"px":"");if(this.u=2===this.j.params.Of||3===this.j.params.Of)b=this.element,c="vertical-rl",1===this.i.KH&&(c="vertical-lr"),g.Ic&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.gn(b,"-o-writing-mode",c),g.gn(b,"-webkit-writing-mode",c),g.gn(b,"writing-mode",c),g.gn(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3===this.j.params.Of&&
(g.gn(b,"text-orientation",""),g.gn(b,"transform","rotate(180deg)"));g.gn(this.element,a);switch(this.i.ri){case 0:case 1:case 2:g.L(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},kWa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},mWa=function(a,b){var c={},d=b.background?b.background:a.i.Bd.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Bd.backgroundOpacity;d=F4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.kb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ia*kWa(b)+"px";d=1;e=b.color||a.i.Bd.color;if(b.color||null!=b.textOpacity)e=F4(e),d=null==b.textOpacity?a.i.Bd.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.XD&&(k=e=b.XD);var l=a.Ia/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.wt()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Bd.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ij&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.ZT&&(c.visibility="hidden");1===b.YL&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.zE||g.rv,3===a.j.params.Of?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Zj||2===b.Zj||3===b.Zj||4===b.Zj||5===b.Zj)if(g.zE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Zj){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},nWa=function(a){a.I=g.Kh("SPAN");
g.gn(a.I,{display:"block"});g.L(a.I,"caption-visual-line");a.B.appendChild(a.I)},oWa=function(a,b){var c=g.Kh("SPAN");
g.gn(c,{display:"inline-block","white-space":"pre-wrap"});g.gn(c,mWa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.gn(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.gn(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},pWa=function(a,b,c){a.ea=a.ea||!!c;
var d={};Object.assign(d,a.i.Bd);Object.assign(d,c||b.i);Object.assign(d,a.Ab.Bd);(c=!a.I)&&nWa(a);for(var e=a.xa&&a.ya&&g.xf(d,a.ya)?a.xa:oWa(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(nWa(a),e=oWa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Lh(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.zE||!g.kn(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.kn(n.children[2],"text-emphasis-position")&&(m=
a.u?"padding-left":"padding-bottom"),g.$e?g.gn(e,m,"1em"):g.gn(e,m,"0.5em")))}a.ya=d;a.xa=e;a.C.push(b)},H4=function(a,b,c,d){g.wM.call(this,a);
this.videoData=b;this.audioTrack=c;this.Sa=d;this.B=b.BE},I4=function(a,b,c,d,e,f,k){G4.call(this,a,b,c,d,e,f,k);
this.type=1},J4=function(a,b,c,d,e,f,k){G4.call(this,a,b,c,d,e,f,k);
this.type=2;this.J=[];this.W=this.N=this.La=0;this.Y=NaN;this.jb=0;this.xb=null;this.Qa=new g.K(this.XW,433,this);g.L(this.element,"ytp-caption-window-rollup");g.J(this,this.Qa);g.gn(this.element,"overflow","hidden")},qWa=function(a,b){if(!b)return"";
a.u&&1!==a.j.params.KH&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},rWa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.j.params.Rm,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.N=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Dn)?(e=g.Kh("SPAN"),g.Rh(e,"\u2013".repeat(d)),g.gn(e,mWa(a,a.i.Bd)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.W=c.call(b,a.Y,a.jb,(a.u?d.offsetHeight:d.offsetWidth)+1)},sWa=function(a,b){rWa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.La){var d=0<c&&0===a.La;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.zq(a.Qa));g.gn(a.B,"transform",qWa(a,c));a.La=c}rWa(a)},K4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.ky.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=k},L4=function(a,b,c,d,e){g.ky.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},tWa=function(a){var b="_"+M4++;
return new L4(0,0x8000000000000,0,b,a)},vWa=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.re){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=uWa(l.textContent,n.textContent,p.textContent,f.textContent,k);return new K4(a,b,e,c,l,d,m)}switch(m.re){case 9:case 10:m.Zj=1;break;case 11:m.Zj=2;break;case 12:m.Zj=3;break;case 13:m.Zj=4;break;case 14:m.Zj=5}return new K4(a,b,e,c,l.textContent||"",d,m)},uWa=function(a,b,c,d,e){var f=g.wt(),k=
f?g.Kh("DIV"):g.Kh("RUBY"),l=g.Kh("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.Kh("DIV"):g.Kh("RP");a.textContent=b;k.appendChild(a);b=f?g.Kh("DIV"):g.Kh("RT");b.textContent=c;k.appendChild(b);c=e.re;if(10===c||11===c||12===c||13===c||14===c)if(g.gn(b,"text-emphasis-style","filled circle"),g.gn(b,"text-emphasis-color","currentcolor"),g.gn(b,"webkit-text-emphasis","filled circle"),11===e.re||13===e.re)g.gn(b,"webkit-text-emphasis-position","under left"),g.gn(b,"text-emphasis-position","under left");c=!0;if(4===e.re||7===e.re||12===e.re||
14===e.re)g.gn(k,"ruby-position","over"),g.gn(k,"-webkit-ruby-position","before");else if(5===e.re||6===e.re||11===e.re||13===e.re)g.gn(k,"ruby-position","under"),g.gn(k,"-webkit-ruby-position","after"),c=!1;e=f?g.Kh("DIV"):g.Kh("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.gn(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.gn(f,"display","none"),f=f.nextElementSibling,g.gn(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.gn(k.lastElementChild,"display","none"),d?(g.gn(k,"padding-top","0.6em"),g.gn(f,"top","0")):(g.gn(k,"padding-bottom","0.6em"),g.gn(f,"bottom","0")));return k},N4=function(){g.G.apply(this,arguments)},O4=function(a){N4.call(this);
this.B=a;this.pens={};this.N={};this.W={};this.C="_"+M4++;this.J={};this.u=this.i=null;this.I=!0},P4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},Q4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},R4=function(a,b){a=P4(a,b);
return void 0!==a?a:null},T4=function(a,b){a=a.getAttribute(b);
if(null!=a)return S4.test(a),a},wWa=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.W[d]:a.B);a=R4(b,"mh");null!=a&&(c.Dt=a);a=R4(b,"ju");null!=a&&(c.textAlign=a);a=R4(b,"pd");null!=a&&(c.Of=a);a=R4(b,"sd");null!=a&&(c.KH=a);a=T4(b,"wfc");null!=a&&(c.windowColor=a);b=P4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},xWa=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=R4(b,"ap");null!=a&&(c.ri=a);a=P4(b,"cc");null!=a&&(c.Dn=a);a=P4(b,"ah");null!=a&&(c.kh=a);a=P4(b,"rc");null!=a&&(c.Rm=a);b=P4(b,"av");null!=b&&(c.bk=b);return c},yWa=function(a,b,c,d){var e={};
Object.assign(e,xWa(a,b));Object.assign(e,wWa(a,b));d?g.xf(e,a.B)?(d=a.C,e=a.B):d="_"+M4++:d=b.getAttribute("id")||"_"+M4++;a=P4(b,"t")+c;b=P4(b,"d")||0x8000000000000;if(2===e.Of||3===e.Of)c=e.Rm,e.Rm=e.Dn,e.Dn=c;return new L4(a,b,0,d,e)},U4=function(a){N4.call(this);
this.I=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},V4=function(a){a=g.Wg(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},zWa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Rm=a);b=b.ccColCount;void 0!==b&&(f.Dn=b);if(2===f.Of||3===f.Of)b=f.Rm,f.Rm=f.Dn,f.Dn=b;return new L4(c,d,0,e,f)},X4=function(){this.u=this.time=this.mode=this.j=0;
this.B=new W4(this);this.C=new W4(this);this.i=[];this.clear()},BWa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Lp:a,
zn:b,result:0};a=AWa[a];b=AWa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.zn===d;if(d)return{Lp:a,zn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Lp:a,zn:b,result:2};return{Lp:a,zn:b,result:3}},DWa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.j.clear(),a.C.j.clear()):(a.u=0,CWa(a.B,b,c,d))},EWa=function(a,b){a.i.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?DWa(a,d.BK,d.CK,b):1===d.type&&a.j&496&&CWa(a.C,d.BK,d.CK,b);a.i.length=0},Y4=function(){this.type=0},Z4=function(){this.state=this.zn=this.Lp=0},FWa=function(){this.timestamp=this.i=0},$4=function(a){this.C=a;
this.u=[];this.i=this.j=this.row=0;this.style=new Y4;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new FWa}},a5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===r.i||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.u[k][m],r=p.i,0!==r&&(0===c&&(c=k,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},KWa=function(a,b){switch(a){case 0:return GWa[(b&127)-32];
case 1:return HWa[b&15];case 2:return IWa[b&31];case 3:return JWa[b&31]}return 0},b5=function(a){return a.u[a.row][a.j]},c5=function(a,b,c){2<=b&&1<a.j&&(--a.j,b5(a).i=0);
var d=b5(a);d.timestamp=a.C.time+0;d.i=KWa(b,c);32>a.j&&a.j++},LWa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.u[b+e][f],l=a.u[c+e][f];
k.i=l.i;k.timestamp=l.timestamp}},d5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},e5=function(a){a.row=0<a.i?a.i:1;
a.j=1;d5(a,0,15)},f5=function(a){this.u=a;
this.C=0;this.style=new Y4;this.I=new $4(this.u);this.J=new $4(this.u);this.text=new $4(this.u);this.j=this.I;this.B=this.J;this.i=this.j},g5=function(a,b,c){var d=a.j,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(a5(d,c),e5(a.j),e5(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.j=1:d.i!==b&&(d.i>b?(a5(d,c),d5(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},MWa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},NWa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},W4=function(a){this.i=a;
this.C=0;this.u=new f5(this.i);this.I=new f5(this.i);this.j=new Z4;this.B=this.u},CWa=function(a,b,c,d){a.j.update();
b=BWa(b,c,a.j);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Lp;c=b.zn;if(32<=e||!e)a.i.mode&a.i.j&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&c5(a,0,b),c&96&&c5(a,0,c),0!==b&&0!==c&&3===a.style.type&&a5(a,d));else if(e&16)a:if(!a.j.matches(e,c)&&(b=a.j,b.Lp=e,b.zn=c,b.state=2,b=e&8?a.I:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.j))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,k=1+d-c.i;LWa(c,k,f,c.i);b=f;e=c.i;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));d5(c,b,e)}}c.row=d;c.j=a+1}else switch(e&7){case 1:switch(c&112){case 32:c5(b.i,0,32);break a;case 48:57===c?(d=b.i,b5(d).i=0,32>d.j&&d.j++):c5(b.i,1,c&15)}break;case 2:c&32&&c5(b.i,2,c&31);break;case 3:c&32&&c5(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:MWa(b);
break;case 33:d=b.i;1<d.j&&(--d.j,b5(d).i=0);break;case 36:d=b.i;b=b5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:g5(b,2,d);break;case 38:g5(b,3,d);break;case 39:g5(b,4,d);break;case 40:c5(b.i,0,32);break;case 41:b.style.set(2);b.i=b.j;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);e5(d);NWa(b);break;case 43:NWa(b);break;case 44:a=b.j;switch(b.style.get()){case 1:case 2:case 3:a5(a,d)}d5(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.j=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;a5(a,d);LWa(a,b,b+1,a.i-1);d5(a,a.row,1)}break;case 46:d5(b.B,0,15);break;case 47:a5(b.j,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.j,b.j=d,MWa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.j+=c&3)&&(d.j=32)}}},OWa=function(){},h5=function(a,b,c){this.trackData=a;
this.J=c;this.version=this.I=this.B=this.i=0;this.j=new DataView(this.trackData);this.u=[]},i5=function(a){var b=a.i;
a.i+=1;return a.j.getUint8(b)},j5=function(a){var b=a.i;
a.i+=4;return a.j.getUint32(b)},k5=function(a,b){N4.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new X4;this.i.j=1<<this.track},l5=function(a){if("string"===typeof a)return!1;
a=new h5(a,8,0);return PWa(a)},PWa=function(a){if(!(a.i<a.j.byteLength)||1380139777!==j5(a))return!1;
a.version=i5(a);if(1<a.version)return!1;i5(a);i5(a);i5(a);return!0},m5=function(){N4.call(this)},QWa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ij=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3===p.nodeType)p=new K4(b,c,d,e.id,p.nodeValue,f||0<n,g.uf(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};Object.assign(r,l);QWa(a,b,c,d,e,!0,p,r,m)}}},n5=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},RWa=function(a,b,c,d){d=Object.assign({Dt:0},d);
return new L4(a,b,c,"_"+M4++,d)},o5=function(a,b){g.G.call(this);
this.G=a;this.X=b;this.i=null;this.j=this.G.Vs()},XWa=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.X.L("enable_h5_ssdai_caption")&&b){var f=e,k=SWa(a,b,d),l=[];try{for(var m=g.q(k),n=m.next();!n.done;n=m.next()){var p=n.value,r=p.trackData,t=p.BH;l="string"!==typeof r?l.concat(TWa(a,c,r,t,f)):"WEBVTT"===r.substring(0,6)?l.concat(UWa(a,r,t)):l.concat(VWa(a,c,r,t))}var w=l}catch(x){g.S(x),a.clear(),w=[]}if(0!==w.length)return w}b=WWa(b);if(!b)return[];try{return"string"!==typeof b?TWa(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?UWa(a,b,d):VWa(a,c,b,d)}catch(x){return g.S(x),a.clear(),[]}},
WWa=function(a){if("string"===typeof a||l5(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.dA(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.Qz(a)},SWa=function(a,b,c){if("string"===typeof b||l5(b))return[{trackData:b,
BH:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Opa(d);if(a.j&&e){var f=g.Hpa(e);e=e.i;f&&e&&a.j.qy(e,f)}f=g.VA(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.q(f.entries());for(e=f.next();!e.done;e=f.next()){var k=g.q(e.value);e=k.next().value;k=k.next().value;k=new Uint8Array(b,k.dataOffset,k.size-(k.dataOffset-k.offset));k=g.Qz(k);a.push({trackData:k,BH:c+1E3*e})}YWa(d,a,c);return a=a.filter(function(l){return!!l.trackData})},YWa=function(a,
b,c){var d=g.dA(a,0,1836476516),e=9E4;
d&&(e=g.eA(d)||9E4);d=0;var f=g.VA(a,1836019558);f=g.q(f.entries());for(var k=f.next();!k.done;k=f.next()){var l=g.q(k.value);k=l.next().value;l=l.next().value;k<b.length&&(l=g.dA(a,l.dataOffset,1953653094))&&(l=g.dA(a,l.dataOffset,1952867444))&&(l=g.TA(l)/e*1E3,0===k&&(d=l),b[k].BH=l-d+c||c*k*1E3)}},TWa=function(a,b,c,d,e){if(!l5(c))throw Error("Invalid binary caption track data");
a.i||(a.i=new k5(e,b));return a.i.j(c,d)},UWa=function(a,b,c){a.i||(a.i=new m5);
a=a.i.j(b,c);.01>Math.random()&&g.rx(Error("Deprecated subtitles format in web player: WebVTT"));return a},VWa=function(a,b,c,d){if("{"===c[0])try{return a.i||(a.i=new U4(ZWa(b))),a.i.j(c,d)}catch(f){return g.S(f),[]}var e=g.Z1(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.i||(a.i=new O4(ZWa(b),a.X)),a.i.j(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},ZWa=function(a){var b=
{};
if(a=g.bF(a))b.lang=a,g.ySa.test(a)&&(b.Of=1);return b},r5=function(a){g.tM.call(this,a);
var b=this;this.G=a;this.X=this.G.T();this.videoData=this.G.getVideoData();this.jb=this.G.bb();this.B={Bd:{}};this.C={Bd:{}};this.va=[];this.N={};this.Ia={};this.Y=!1;this.xb=g.$F(this.videoData);this.Wa=g.cAa(this.videoData,this.G);this.wb=!!this.videoData.captionTracks.length;this.Ab=!!this.videoData.Rb;this.La="3"===this.X.controlsType;this.j=this.I=this.J=this.Ha=this.Ya=null;this.Qa=new o5(this.G,this.X);this.i=null;this.ea=new g.qC(this);this.Ta=new g.W({D:"div",K:"ytp-caption-window-container",
V:{id:"ytp-caption-window-container"}});var c=null,d=g.nr("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.br(d));this.storage=c;var e;this.fb=!(null==(e=a.ud())||!e.ey());this.u=$Wa(this);this.W=!this.u&&this.La&&this.fb&&this.Wa;g.J(this,this.Qa);this.u?this.ya=this.xa=null:(this.xa=new g.xq(this.bI,void 0,this),g.J(this,this.xa),this.ya=new g.K(this.pY,2E3,this),g.J(this,this.ya));g.J(this,this.ea);this.X.L("caption_window_container_killswitch")||g.fM(this.player,this.Ta.element,4);
g.J(this,this.Ta);this.u||this.ea.S(a,"resize",this.dI);(this.kb=!g.Nw()&&!this.G.isFullscreen()&&!this.u&&!this.W&&!this.X.L("switch_captions_to_track_tag_when_fullscreen_api_unavailable_killswitch"))&&this.ea.S(a,"resize",this.fW);this.ea.S(a,"onPlaybackAudioChange",this.nV);this.ea.S(a,g.my("captions"),function(f){b.onCueRangeEnter(f)});
this.ea.S(a,g.ny("captions"),function(f){b.onCueRangeExit(f)});
p5(this,q5(this)||{})},cXa=function(a){if(1===a.X.Wa||1===a.videoData.ov||"alwayson"===g.KF(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().j;var c=a.X;if(g.tE(c)&&c.L("web_player_prioritize_caption_visibility_on")&&("ON"===b||"on"===g.KF(a.videoData,"yt:cc")))return!0;if(2===a.X.Wa){var d;g.xE(a.X)?d=aXa(a):d=bXa(a,"module-enabled");if(null!=d)return!!d}c=A4(a.player.getAudioTrack(),B4(a.X));d=g.KF(a.videoData,"yt:cc");if(void 0===s5(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===
d;return"ON"===b||"on"===g.KF(a.videoData,"yt:cc")},t5=function(a,b){if(a.i&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.j},s5=function(a){var b=void 0,c=g.Wu(g.Vu.getInstance(),65);
if(g.xE(a.X)&&null!=c){if(null!=aXa(a))return!1;b=!c}return b},dXa=function(a){var b;
a.xb?b=new H4(a.X,a.videoData,a.player.getAudioTrack(),a.player):a.Wa?b=new E4(a.videoData.i,a.player):a.wb?b=new g.xM(a.X,a.videoData,a.player.getAudioTrack()):b=new g.zM(a.X,a.videoData.Rb,a.videoData.videoId,g.Oua(a.videoData),a.videoData.uj);return b},v5=function(a,b){if(a.j){if(a.I&&a.I.B)return a.I.B;
b||(b=a.Ab?!1:a.wb?!1:!0);b=g.uM(a.j.j,b);for(var c=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.KF(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(g.bF(b[e])===c[d])return b[e];return a.I&&a.I.u?a.I.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||u5(a)}return null},u5=function(a){return a.I&&a.I.i},w5=function(a){var b=u5(a);
return!!b&&a.i===b},eXa=function(a){var b=A4(a.player.getAudioTrack(),B4(a.X)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=v5(a,a.Y):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&t5(a)?c=u5(a):s5(a)||a.Y||cXa(a)?c=v5(a,a.Y):t5(a)&&(c=u5(a));if(a.u||a.W){var d=g.uM(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],k=g.Kh("TRACK");k.setAttribute("kind","subtitles");k.setAttribute("label",g.$E(f));k.setAttribute("srclang",g.bF(f));k.setAttribute("id",f.toString());a.W||k.setAttribute("src",a.j.iq(f,"vtt"));f===c&&k.setAttribute("default","1");b.push(k)}c=a.G.ud();c.yv(b);c=c.He();
a.fb&&a.ea.S(c.textTracks,"change",a.FX)}else!a.i&&c&&x5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},fXa=function(a,b){var c=a.G.ud().He().textTracks;
a=a.i.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},x5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Y=c,a.Y&&(g.xE(a.X)?y5(a,!!b):z5(a,"module-enabled",!!b)));a.i=b;t5(a)&&(a.i=u5(a));a.load()},gXa=function(a,b){a.X.L("caption_window_container_killswitch")?g.fM(a.player,b,4):a.Ta.element.appendChild(b)},hXa=function(a,b){var c=a.jb.getVideoContentRect(!0).height;
if(!c)return null;var d=a.i?g.bF(a.i):null;d&&g.ySa.test(d)&&(b.params.Of=1);d=a.jb.getPlayerSize();switch(null!=b.params.Dt?b.params.Dt:1<b.i.length?1:0){case 1:return new I4(b,a.B,a.C,c,d.width,d.height,a.X.experiments);case 2:return new J4(b,a.B,a.C,c,d.width,d.height,a.X.experiments);default:return new G4(b,a.B,a.C,c,d.width,d.height,a.X.experiments)}},p5=function(a,b,c){c=void 0===c?!1:c;
var d=A5.Bd;a.B={};Object.assign(a.B,A5);a.B.Bd={};Object.assign(a.B.Bd,d);a.C={Bd:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;S4.test(f);e.Bd.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;S4.test(f);e.Bd.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||A5.windowColor;S4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bd.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Bd.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Ij?3:d.bold?1:d.Ij?2:0);f=f.Bd;switch(e){case 1:f.bold=!0;delete f.Ij;break;case 2:delete f.bold;f.Ij=!0;break;case 3:f.bold=!0;f.Ij=!0;break;default:delete f.bold,delete f.Ij}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bd.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=A5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Bd.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bd.fontFamily=f;a.loaded&&a.dI();c&&(a.X.L("web_player_local_storage_for_captions_setting_killswitch")?z5(a,"display-settings",b):g.Jx("yt-player-caption-display-settings",b,2592E3))},B5=function(a,b,c){b&&!a.J?(b=tWa({Of:0,
lang:"fr"}),a.J=[b,new K4(b.start,b.end-b.start,0,b.id,null!=c?c:"Aper\u00e7u des sous-titres")],a.player.Nd(a.J)):!b&&a.J&&(iXa(a,a.J),a.J=null)},iXa=function(a,b){a.player.Mf(b);
g.rc(b,function(c){g.cc(this.va,c)},a);
g.yq(a.xa)},bXa=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},z5=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}},y5=function(a,b){a.G.isInline()||g.Jx("yt-player-sticky-caption",b,2592E3)},aXa=function(a){if(!a.G.isInline())return g.Kx("yt-player-sticky-caption")},q5=function(a){return a.X.L("web_player_local_storage_for_captions_setting_killswitch")?bXa(a,"display-settings"):g.Kx("yt-player-caption-display-settings")},$Wa=function(a){var b,c=!(null==(b=a.G.ud())||!b.by());
return a.La&&c&&!a.Wa};
g.AS.prototype.ew=g.ca(34,function(a){var b=2;this.ya.has(a)?b=0:g.WFa(this,a)&&(b=1);return b});
g.fV.prototype.ew=g.ca(33,function(a){return this.pd.ew(a)});
g.AS.prototype.qy=g.ca(32,function(a,b){this.Qa.set(a,b)});
g.fV.prototype.qy=g.ca(31,function(a,b){this.pd.qy(a,b)});
g.LM.prototype.Bs=g.ca(30,function(){this.ma();for(var a=g.sh(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Oh(a[b])});
g.hS.prototype.Bs=g.ca(29,function(){this.oa.Bs()});
g.LM.prototype.ey=g.ca(28,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.hS.prototype.ey=g.ca(27,function(){return this.oa.ey()});
g.LM.prototype.by=g.ca(26,function(){return!!this.i.textTracks});
g.hS.prototype.by=g.ca(25,function(){return this.oa.by()});
g.LM.prototype.yv=g.ca(24,function(a){this.ma();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.hS.prototype.yv=g.ca(23,function(a){this.oa.yv(a)});
g.wM.prototype.PG=g.ca(22,function(){return!1});
g.wM.prototype.Do=g.ca(21,function(){});
g.xM.prototype.Do=g.ca(20,function(a,b,c){var d=this;this.isDisposed();b=this.iq(a,b);this.Zm();this.i=g.at(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.zM.prototype.Do=g.ca(19,function(a,b,c){var d=this;this.isDisposed();b=this.iq(a,b);this.Zm();this.i=g.at(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})});
g.QU.prototype.xw=g.ca(7,function(){return this.J});
g.UX.prototype.xw=g.ca(6,function(){var a;return(null==(a=g.hM(this))?void 0:a.Vs())||null});
g.ZL.prototype.Vs=g.ca(5,function(){return this.app.xw()});
g.vX.prototype.Vs=g.ca(4,function(){var a;return(null==(a=this.Va)?void 0:a.xw())||null});
var eWa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",
az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bh:"Bhojpuri",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",
cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",
de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",
es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",
gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",
iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",
kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",
lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",
mi:"M\u0101ori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",
ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",
pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",
sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",
sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",swc:"Congo Swahili",
syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",
uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};C4.prototype.contains=function(a){a=g.mc(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
C4.prototype.length=function(){return this.segments.length/2};
g.v(D4,g.G);g.h=D4.prototype;g.h.ra=function(){g.G.prototype.ra.call(this);this.u&&this.u.cancel()};
g.h.VA=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.kd();var b=this.i;this.i=g.Ub(this.Y.pm(a).i);b!==this.i&&this.W&&this.W()};
g.h.reset=function(){this.B=new C4;this.I=-1;this.u&&(this.u.cancel(),this.u=null)};
g.h.IM=function(){this.isDisposed();var a;if(a=null!=this.i)a=this.i,a=a.i.hn(a);if(a&&!this.u&&!(this.i&&30<this.i.startTime-this.player.getCurrentTime())){a=this.i;a=a.i.Tu(a);var b;if(this.X.L("enable_h5_ssdai_caption")&&(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)){var c=this.player.Vs();if(c){var d=a.i[0].Na;if(b=c.jm(a.i[0].B,d,a.i[0].i.info.id,3))if(c=c.ew(d),0===c)b&&(a.u=new g.Cz(b));else if(2===c){this.J.start();cWa(this)&&this.seekTo(this.player.getCurrentTime());
return}}}a.i[0].duration?(this.B.contains(a.i[0].Na)||dWa(this,a),this.i=g.Ub(a.i)):!this.X.L("force_caption_seek_for_live_killswitch")&&cWa(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.h.ma=function(){};
g.v(E4,g.wM);g.h=E4.prototype;g.h.Do=function(a,b,c){var d=this;this.Zm();b=gWa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?hWa(this,b,"386"):hWa(this,b));if(b){var e=1E3*(b.index.getStartTimeInPeriod(b.index.getFirstSegmentNumber())-b.index.getStartTime(b.index.getFirstSegmentNumber())),f=new g.aAa(this.X);this.u=new D4(f,this.G,b,function(k,l){c(k,a,l,e)},this.I||g.$B(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.h.PG=function(){var a=this.C;this.C=!1;return a};
g.h.zt=function(a){var b=this.I?[new g.ZE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.ZE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?fWa(this,"386"):fWa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g.vM(this.j,c.value);a()};
g.h.Zm=function(){this.u&&(this.u.dispose(),this.u=null)};
g.h.iq=function(){return""};
var S4=/^#(?:[0-9a-f]{3}){1,2}$/i,jWa=/#(.)(.)(.)/,iWa=/^#(?:[0-9a-f]{3}){1,2}$/i;var lWa=["left","right","center","justify"];g.v(G4,g.W);g.h=G4.prototype;g.h.nR=function(a,b){var c=g.Bn(this.element,this.element.parentElement);this.Ya=a-c.x;this.fb=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.mR=function(a,b){var c=g.Dn(this.element);a=a-this.Ya-.02*this.playerWidth;var d=b-this.fb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Wg(e,0,2));var f=(d+c.height/2)/this.Ta*3;f=Math.floor(g.Wg(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.Wg(a,0,1);c=(d+f/2*c.height)/this.Ta;c=100*g.Wg(c,0,1);this.j.params.ri=b;this.j.params.bk=c;this.j.params.kh=a;this.i.ri=b;this.i.bk=c;this.i.kh=a;this.Ha.ri=b;this.Ha.bk=c;this.Ha.kh=a;this.JO()};
g.h.lR=function(){g.Hq(this.element,"ytp-dragging")};
g.h.JO=function(){this.du(this.C)};
g.h.getType=function(){return this.type};
g.h.du=function(a){var b=Math.min(this.xL(),this.maxWidth),c=this.wL(),d="";3===this.j.params.Of&&(d="rotate(180deg)");g.gn(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.HD(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.kh+2;d=this.i.ri;switch(d){case 0:case 3:case 6:(b=this.i.Bd.fontSizeIncrement)&&0<b&&2!==this.i.Of&&3!==
this.i.Of&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.bk+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.gn(this.element,
a)};
g.h.HD=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ea||this.C.length>b)b=0,this.ea=!1,this.C=[],this.I=this.ya=this.xa=null,g.Mh(this.B);for(;b<a.length;b++)pWa(this,a[b])};
g.h.xL=function(){return 0};
g.h.wL=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};g.v(H4,g.wM);H4.prototype.Do=function(a,b,c){aWa(this.videoData.videoId,a.vssId,c)};
H4.prototype.zt=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.vM(this.j,c.value);a()};g.v(I4,G4);I4.prototype.HD=function(a){var b=this.j.i;G4.prototype.HD.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};Object.assign(d,c.i);Object.assign(d,jXa);var e=c.i;var f=d}pWa(this,c,d)}};
var jXa={ZT:!0};g.v(J4,G4);g.h=J4.prototype;g.h.JO=function(){g.Aq(this.Qa)};
g.h.XW=function(){g.Hq(this.element,"ytp-rollup-mode");this.du(this.xb,!0)};
g.h.wL=function(){return this.u?this.W:this.N};
g.h.xL=function(){return this.u?this.N:this.W};
g.h.du=function(a,b){this.xb=a;if(this.j.params.Rm){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.jb=this.W;this.N=this.W=0;G4.prototype.du.call(this,a);sWa(this,b)}G4.prototype.du.call(this,a)};g.v(K4,g.ky);K4.prototype.toString=function(){return g.ky.prototype.toString.call(this)};g.v(L4,g.ky);L4.prototype.toString=function(){return g.ky.prototype.toString.call(this)};
var M4=0;g.v(N4,g.G);N4.prototype.j=function(){return[]};
N4.prototype.reset=function(){};g.v(O4,N4);O4.prototype.reset=function(){this.J={};this.u=this.i=null;this.I=!0};
O4.prototype.j=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,k={},l=a.getAttribute("p");l&&Object.assign(k,this.pens[l]);l=Q4(a,"b");
null!=l&&(k.bold=l);l=Q4(a,"i");null!=l&&(k.Ij=l);l=Q4(a,"u");null!=l&&(k.underline=l);l=R4(a,"et");null!=l&&(k.charEdgeStyle=l);l=R4(a,"of");null!=l&&(k.offset=l);l=T4(a,"bc");null!=l&&(k.background=l);l=T4(a,"ec");null!=l&&(k.XD=l);l=T4(a,"fc");null!=l&&(k.color=l);l=R4(a,"fs");null!=l&&0!==l&&(k.fontFamily=l);l=P4(a,"sz");void 0!==l&&(k.fontSizeIncrement=l/100-1);l=P4(a,"bo");void 0!==l&&(k.backgroundOpacity=l/255);l=P4(a,"fo");void 0!==l&&(k.textOpacity=l/255);l=R4(a,"rb");null!=l&&10!==l&&0!==
l&&(k.re=10<l?l-1:l);a=R4(a,"hg");null!=a&&(k.YL=a);f[c]=k;break;case "ws":c=a.getAttribute("id");this.W[c]=wWa(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=xWa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=yWa(this,a,b,!1);(a=this.J[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.J[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.C;k=
!!Q4(a,"a");l=(P4(a,"t")||0)+l;var m=P4(a,"d")||5E3;k||(!this.I&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=k?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var r=Array.from(a.childNodes);r.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var w=r[t],x=void 0;0<t&&(k=!0);var y=void 0;1===w.nodeType&&(y=w);if(y&&"s"===y.tagName){if((w=(w=y.getAttribute("p"))?this.pens[w]:null)&&w.re&&(1===w.re?(w=r.slice(t,t+4),
4===w.length&&(x=vWa(l,m,f,k,n,w,this.pens),t+=3)):x=vWa(l,m,f,k,n,[y],this.pens)),!x){var z=y;x=l;y=m;w=f;var F=k,I=n,H=z.textContent?z.textContent:"",N=z.getAttribute("p");N=N?this.pens[N]:null;z=P4(z,"t")||0;x=new K4(x+z,y-z,I,w,H,F,N)}}else x=new K4(l,m,n,f,w.textContent||"",k,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.C&&(this.i=yWa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var kXa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(U4,N4);U4.prototype.reset=function(){this.u.clear()};
U4.prototype.j=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},k=e.pParentId;k&&Object.assign(f,this.i.get(k));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Ij=!0);e.uAttr&&(f.underline=!0);k=e.ofOffset;null!=k&&(f.offset=k);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);k=e.etEdgeType;null!=k&&(f.charEdgeStyle=k);void 0!==e.ecEdgeColor&&(f.XD=V4(e.ecEdgeColor));k=e.fsFontStyle;null!=k&&0!==k&&(f.fontFamily=
k);void 0!==e.fcForeColor&&(f.color=V4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=V4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(k=e.rbRuby)&&10!==k&&(f.re=10<k?k-1:k,f.Zj=kXa.get(f.re));e.hgHorizGroup&&(f.YL=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wsParentId)?Object.assign(f,this.C.get(k)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Dt=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Of=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.KH=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=V4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(k=e.wpParentId)&&Object.assign(f,this.B.get(k)),void 0!==e.ahHorPos&&
(f.kh=e.ahHorPos),void 0!==e.apPoint&&(f.ri=e.apPoint),void 0!==e.avVerPos&&(f.bk=e.avVerPos),void 0!==e.ccCols&&(f.Dn=e.ccCols),void 0!==e.rcRows&&(f.Rm=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=zWa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+M4++,k=zWa(this,l,d,e,f),a.push(k),this.u.set(f,k));0===e&&(e=5E3);k=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],w=t.utf8;if(w){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=k.params.Dt?k.params.Dt:1<k.i.length?1:0)&&m&&"\n"===w)continue;if(t=y&&1===y.re)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var z=p[t+1].pPenId;(z=this.i.get(z))&&z.re&&2===z.re?(z=p[t+2].pPenId,z=this.i.get(z),!z||!z.re||3>z.re?t=!1:(z=p[t+3].pPenId,t=(z=this.i.get(z))&&
z.re&&2===z.re?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;z=p[l+2].utf8;var F=this.i.get(p[l+2].pPenId);w=uWa(w,x,z,t,F);m=new K4(d,e,n,f,w,m,y);l+=3}else m=new K4(d+x,e-x,n,k.id,w,m,y||r);m&&(a.push(m),k.i.push(m))}m=!0}}}b=a}else b=[];return b};X4.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
X4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var AWa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Y4.prototype.set=function(a){this.type=a};
Y4.prototype.get=function(){return this.type};
Z4.prototype.clear=function(){this.state=0};
Z4.prototype.update=function(){this.state=2===this.state?1:0};
Z4.prototype.isValid=function(){return 0!==this.state};
Z4.prototype.matches=function(a,b){return this.isValid()&&a===this.Lp&&b===this.zn};
FWa.prototype.reset=function(){this.timestamp=this.i=0};
$4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
$4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
$4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.j=this.row=1};
var GWa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],HWa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],IWa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],JWa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];f5.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.j=this.I;this.B=this.J;this.i=this.j;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
W4.prototype.reset=function(a){this.C=a;this.j.clear();this.B=this.u;this.u.reset(a,0);this.I.reset(a,1)};OWa.prototype.C=function(){};g.v(h5,OWa);h5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+M4++;c=c/1E3-this.J;d=d/1E3-this.J;a=new L4(c,d-c,5,f,{textAlign:0,ri:0,kh:2.5*b,bk:5.33*a});e=new K4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(k5,N4);k5.prototype.j=function(a){a=new h5(a,a.byteLength,this.u);if(PWa(a)){for(;a.i<a.j.byteLength;)for(0===a.version?a.B=j5(a)*(1E3/45):1===a.version&&(a.B=4294967296*j5(a)+j5(a)),a.I=i5(a);0<a.I;a.I--){var b=i5(a),c=i5(a),d=i5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.B,type:this.track,BK:c,CK:d,order:b.i.length}))}EWa(this.i,a);return a.u}return[]};
k5.prototype.reset=function(){this.i.clear()};g.v(m5,N4);
m5.prototype.j=function(a,b){var c=[];a=a.split(lXa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!mXa.test(e)){var k=C5.exec(e);if(k&&4<=k.length){var l=n5(k[1]),m=n5(k[2])-l;l+=f;var n=(k=k[3])?k.split(" "):[];k={};var p=null;var r="";var t=null,w="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],k.bk=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];k.kh=Number.parseInt(t,10);2===x.length&&(w=x[1].trim());break;case "align":switch(y){case "start":k.textAlign=0;break;case "middle":k.textAlign=2;break;case "end":k.textAlign=1}}}p||r||(r="end");if(!t)switch(k.textAlign){case 0:k.kh=0;break;case 1:k.kh=100;break;case 2:k.kh=50}if(null!=k.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(k.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;k.ri=r}e=e.substring(C5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=k;k=e;e={};if(0>k.indexOf("<")&&0>k.indexOf("&"))f=RWa(l,m,5,w),m=new K4(l,m,5,f.id,k,!1,g.uf(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=k.split(nXa),1===r.length?(k=5,w=RWa(l,m,k,w)):(p=k=6,w=Object.assign({Dn:32},w),w=new L4(l,m,p,"_"+M4++,w)),c.push(w),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.Z1("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,QWa(this,p,m-(p-l),k,w,0<t,y,e,c)):p=n5(n)+f}C5.lastIndex=0}}return c};
var mXa=/^NOTE/,lXa=/(?:\r\n|\r|\n){2,}/,C5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),nXa=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.oS.oA(m5,{j:"wvppt"});g.v(o5,g.G);o5.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
o5.prototype.reset=function(){this.i&&this.i.reset()};
o5.prototype.ra=function(){g.G.prototype.ra.call(this);this.clear()};var A5={windowColor:"#080808",windowOpacity:0,textAlign:2,ri:7,kh:50,bk:100,Bd:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(r5,g.tM);g.h=r5.prototype;g.h.ra=function(){if(this.u||this.W){var a=this.G.ud();a&&!a.isDisposed()&&a.Bs()}else B5(this,!1);g.tM.prototype.ra.call(this)};
g.h.Xq=function(){if(this.La)return this.u||this.W;var a=A4(this.player.getAudioTrack(),B4(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?t5(this):s5(this)||t5(this)?!0:cXa(this)};
g.h.load=function(){var a=this;g.tM.prototype.load.call(this);var b=!this.X.L("web_player_captions_track_list_changed_killswitch");this.I=this.player.getAudioTrack();this.j?(this.i&&(this.Qa.clear(),this.u?fXa(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Do(this.i,"json3",function(c,d,e,f){c&&(a.j.PG()&&(a.va=[],a.G.gf("captions"),g.yq(a.xa),a.Qa.reset()),c=XWa(a.Qa,c,d,e,f),a.player.Nd(c,void 0,a.Wa),!a.Y||a.W||w5(a)||g.kE(a.X)||g.dE(a.X)||(g.Bq(a.ya),c=tWa({ri:0,kh:5,bk:5,Rm:2,textAlign:0,
Of:0,lang:"fr"}),a.Ha=[c],d=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],a.Ya||(e=new g.WJ(g.pK()),g.J(a,e),a.Ya=e.element),e=c.end-c.start,(f=g.$E(a.i))&&a.Ha.push(new K4(c.start,e,0,c.id,f)),a.Ha.push(new K4(c.start,e,0,c.id,d[0]),new K4(c.start,e,0,c.id,a.Ya,!0),new K4(c.start,e,0,c.id,d[1],!0)),a.player.Nd(a.Ha),g.zq(a.ya)),!a.Y||a.W||w5(a)||(g.xE(a.X)?y5(a,!0):z5(a,"module-enabled",!0),a.I&&(a.I.B=a.i),a.player.qr()),a.Y=!1)}),!b||this.u||this.W||w5(this)||this.player.Oa("captionschanged",
g.aF(this.i))),b||(this.i&&!w5(this)?this.player.Oa("captionschanged",g.aF(this.i)):this.player.Oa("onCaptionsTrackListChanged"))):(this.j=dXa(this),g.J(this,this.j),this.j.zt(function(){eXa(a)}))};
g.h.unload=function(){this.u&&this.i?fXa(this,!1):(this.ya&&g.Bq(this.ya),this.player.gf("captions"),this.va=[],this.j&&this.j.Zm(),this.Qa.clear(),this.J&&this.player.Nd(this.J),this.dI());g.tM.prototype.unload.call(this);this.player.qr();this.player.Oa("captionschanged",{})};
g.h.create=function(){this.Xq()&&this.load()};
g.h.FX=function(){for(var a=this.G.ud().He().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=g.uM(this.j.j,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.i:null)!==b&&x5(this,b,!0)};
g.h.nZ=function(){!this.i&&this.u||this.unload()};
g.h.onCueRangeEnter=function(a){this.va.push(a);g.yq(this.xa)};
g.h.onCueRangeExit=function(a){g.cc(this.va,a);this.j instanceof E4&&this.j.I&&this.player.Mf([a]);g.yq(this.xa)};
g.h.iY=function(a){if(a instanceof L4){var b=this.N[a.id];b&&b.j!==a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=hXa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.Ia[b]||(this.Ia[b]=[]),this.Ia[b].push(a)};
g.h.getCaptionWindowContainerId=function(){return this.Ta.element.id};
g.h.pY=function(){iXa(this,this.Ha);this.Ha=null};
g.h.bI=function(){var a=this;if(!this.kb||!this.u){this.xa.stop();g.vf(this.Ia);this.va.sort(g.ly);var b=this.va;if(this.J){var c=g.Xo(b,function(d){return-1===this.J.indexOf(d)},this);
c.length&&(b=c)}g.rc(b,this.iY,this);g.ff(this.N,function(d,e){a.Ia[e]?(d.element.parentNode||(d instanceof J4||d instanceof I4||g.kf(a.N,function(f,k){k!==e&&f.j.params.ri===d.j.params.ri&&f.j.params.kh===d.j.params.kh&&f.j.params.bk===d.j.params.bk&&(f.dispose(),delete a.N[k]);return k===e},a),gXa(a,d.element)),d.du(a.Ia[e])):(d.dispose(),delete a.N[e])},this)}};
g.h.tY=function(){p5(this,{},!0);this.X.L("web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Oa("captionssettingschanged")};
g.h.tT=function(){var a=A5.Bd;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ij?3:a.bold?1:a.Ij?2:0,textOpacity:a.textOpacity,windowColor:A5.windowColor,windowOpacity:A5.windowOpacity};var b=q5(this)||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.HP=function(a,b){var c={};Object.assign(c,q5(this));Object.assign(c,a);p5(this,c,b);this.player.Oa("captionssettingschanged")};
g.h.dI=function(){!this.u&&this.loaded&&(g.ff(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.bI())};
g.h.tf=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Wg(b,-2,4);this.HP({fontSizeIncrement:c});return c;case "reload":b&&!this.u&&x5(this,this.i,!0);break;case "stickyLoading":void 0!==b&&this.X.u&&(g.xE(this.X)?y5(this,!!b):z5(this,"module-enabled",!!b));break;case "track":if(!this.j)return{};if(b){if(this.u)break;if(!g.Pa(b))break;if(g.uf(b)){x5(this,null,!0);break}a=g.uM(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?$Va(e,b.translationLanguage):e)}!c||c===this.i&&this.loaded||(b=g.Kra(),a=g.bF(c),b.length&&a===b[b.length-1]||(b.push(a),g.Jx("yt-player-caption-language-preferences",b)),x5(this,c,!0))}else return this.loaded&&this.i&&!w5(this)?g.aF(this.i):{};return"";case "tracklist":return this.j?g.Kn(g.uM(this.j.j,!(!b||!b.includeAsr)),function(f){return g.aF(f)}):[];
case "translationLanguages":return this.j?this.j.B.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.u||void 0===b||B5(this,!!b);break;case "sampleSubtitlesCustomized":this.u||B5(this,!!b,b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.u&&a.push("stickyLoading");return a};
g.h.XE=function(){var a=this.i;if(a){var b=a.vssId;a.translationLanguage&&b&&!this.X.L("auto_translation_logging_killswitch")&&(b="t"+b+"."+g.bF(a));return{cc:b}}return{}};
g.h.cZ=function(){this.loaded&&this.i&&!w5(this)?(g.xE(this.X)?y5(this,!1):z5(this,"module-enabled",!1),this.unload(),t5(this,!0)&&x5(this,u5(this),!1)):this.pP()};
g.h.pP=function(){this.loaded&&this.i&&!w5(this)||x5(this,w5(this)||!this.i?v5(this,!0):this.i,!0)};
g.h.nV=function(){var a=w5(this);t5(this,a)?x5(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Xq()&&(a?x5(this,v5(this),!1):this.load()))};
g.h.fW=function(){var a=this.G.ud();a&&!a.isDisposed()&&a.Bs();this.G.isFullscreen()?(this.u=this.La=!0,this.loaded&&eXa(this)):(this.La="3"===this.X.controlsType,this.u=$Wa(this));x5(this,this.i)};
g.oS.oA(r5,{bI:"smucd"});g.sM("captions",r5);})(_yt_player);
