(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var g3=function(a){a.Z("cardstatechange",a.qh()&&a.ek()?1:0)},h3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},nMa=function(a){var b=g.Ll(a);
a=g.Rl(a);return new g.sl(b.x,b.y,a.width,a.height)},oMa=function(a){return Math.pow(a,3)},pMa=function(a){return 3*a*a-2*a*a*a},k3=function(a){a=g.Oa(a);
delete i3[a];g.Sb(i3)&&j3&&j3.stop()},rMa=function(){j3||(j3=new g.J(function(){qMa()},20));
var a=j3;a.isActive()||a.start()},qMa=function(){var a=g.Ra();
g.Eb(i3,function(b){sMa(b,a)});
g.Sb(i3)||rMa()},l3=function(a,b,c,d){g.Sq.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.u=null},sMa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.u);a.u=b;tMa(a,a.progress);1==a.progress?(a.Pa=0,k3(a),a.onFinish(),a.Bv()):a.xc()&&a.SA()},tMa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},uMa=function(a,b){g.mf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Pa},m3=function(a,b,c,d,e){l3.call(this,b,c,d,e);
this.element=a},n3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
m3.call(this,a,b,c,d,e)},o3=function(a){g.E.call(this);
this.l=a||window;this.i=[]},p3=function(a){return a.baseUrl||null},q3=function(a,b){return g.To(g.Se(a,b,void 0),function(c){return!!c})},vMa=function(a,b,c){function d(wa){var Ba,$b,jd,Ob=wa.hovercardButton;
if(!Ob)return null;Ob=Ob.subscribeButtonRenderer;if(!Ob)return null;var dc=f(Ob.unsubscribedButtonText),nc=f(Ob.subscribedButtonText);if(Ob.subscribed){var eg=f(Ob.subscriberCountWithUnsubscribeText);var Qg=f(Ob.subscriberCountText)}else eg=f(Ob.subscriberCountText),Qg=f(Ob.subscriberCountWithSubscribeText);var oc=null;return wa.signinEndpoint&&(oc=h3(wa,"signinEndpoint","webNavigationEndpointData","url"),oc||(oc=null===(jd=null===($b=null===(Ba=Ob.signInEndpoint)||void 0===Ba?void 0:Ba.commandMetadata)||
void 0===$b?void 0:$b.webCommandMetadata)||void 0===jd?void 0:jd.url),!oc)?null:dc&&(nc||oc)?{subscribed:Ob.subscribed,subscribeText:dc,subscribeCount:eg,unsubscribeText:nc,unsubscribeCount:Qg,enabled:Ob.enabled,signinUrl:oc,classic:wa.useClassicSubscribeButton}:null}
function e(wa){if(wa){var Ba=[],$b=wa.videoId;$b&&Ba.push("v="+$b);($b=wa.playlistId)&&Ba.push("list="+$b);(wa=wa.startTimeSeconds)&&Ba.push("t="+wa);return"/watch?"+Ba.join("&")}}
function f(wa){if(!wa)return null;var Ba=wa.simpleText;return Ba?Ba:wa.runs?g.Se(wa.runs,function($b){return $b.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,z=null,G=null,H=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=h3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((G=h3(l,"urlEndpoint","url"))&&(m=G),n=!0,p="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=h3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=h3(b,"title","accessibility","accessibilityData","label");var L=b.endpoint?b.endpoint.clickTrackingParams:null,Z="";if(b.metadata){var R=f(b.metadata);R&&(Z=R)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Z,callToAction:f(b.callToAction),jI:b.image,
iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,cR:n,Ud:L?{itct:L}:null,OV:p,Dt:a?a:null,fR:b.isPlaceholder,impressionUrls:q3(b.impressionUrls||[],p3),VQ:q3(b.hovercardShowUrls||[],p3),clickUrls:q3(l.loggingUrls||[],p3),visualElement:g.Xx(b.trackingParams),productPrice:H,
additionalFeesText:I}},r3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:q3(a.impressionUrls||[],p3),elements:q3(a.elements||[],function(d,e){return vMa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Xx(a.trackingParams));return c},s3=function(a){g.oN.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.V=!0;this.G=0;a=a.S();this.L=g.CF(a)||g.GF(a);this.events=new g.fN(this);g.F(this,this.events);this.events.N(this.player,g.dA("creatorendscreen"),this.Ad);this.events.N(this.player,g.eA("creatorendscreen"),this.mf);this.events.N(this.player,"resize",this.tb);this.events.N(window,"focus",this.WU);this.load();var b=g.rg("STYLE");(g.cg("HEAD")[0]||document.body).appendChild(b);g.lf(this,function(){g.vg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},wMa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},t3=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},xMa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=r3(f,wMa(a))));u3(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.bp;d&&(c.postParams={ad_tracking:d});if(b=g.Wna(b))if(b=g.Nc(b),b=g.Jc(b))a.u=g.jt(b,c)},u3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ue("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&yMa(a);c=[];d=new g.aA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.cN(a.player,a.l.element,4),a.B=new g.TL(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=zMa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.cN(a.player,f.element,4);var h=new g.aA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);AMa(a,f,e)}else g.oy(new g.Yv("buildEndscreenElement null",
e))}a.player.Gd(c);a.tb()}},yMa=function(a){var b=g.ay(),c=g.cy();
c&&b&&a.endscreen.visualElement&&g.fz(void 0,c,b,[a.endscreen.visualElement])},zMa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ea:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Dt||"","aria-hidden":"true"},T:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:w3(a,b.targetUrl),tabindex:"-1"},T:[{D:"div",Ea:["ytp-ce-video-title"].concat(g.la(c)),U:{dir:g.Yq(b.title||
"")},ra:b.title},{D:"div",K:"ytp-ce-video-duration",ra:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.X("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ea:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Dt||"","aria-hidden":"true"},T:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:v3(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:w3(a,
b.targetUrl),tabindex:"-1"},T:[{D:"div",Ea:["ytp-ce-playlist-title"].concat(g.la(c)),U:{dir:g.Yq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-playlist-count",T:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",ra:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ea:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Dt||"","aria-hidden":"true"},T:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",T:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",T:[{D:"div",K:"ytp-ce-expanding-overlay-body",T:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",T:[{D:"a",Ea:["ytp-ce-channel-title","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Yq(b.title||"")},ra:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",T:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",ra:b.subscribersText}:"",b.metadata?{D:"div",Ea:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ra:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:v3(b)}]};c=new g.V(c);var d=g.dg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.S().i){var e=null;var f=b.Ud.itct}else e="endscreen",f=null;e=new g.vO(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ea:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Dt||"","aria-hidden":"true"},T:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",T:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",T:[{D:"div",K:"ytp-ce-expanding-overlay-body",T:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",T:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.Yq(b.title||"")},ra:b.title},{D:"div",K:"ytp-ce-website-metadata",ra:b.metadata},{D:"a",Ea:["ytp-ce-website-goto","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:v3(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:BMa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",T:[{D:"div",K:"ytp-ce-merchandise-price",ra:b.productPrice}]},b.additionalFeesText&&c.T.push({D:"div",K:"ytp-ce-merchandise-additional-fees",ra:b.additionalFeesText})),a={D:"div",Ea:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Dt||"","aria-hidden":"true"},T:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
T:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",T:[{D:"div",K:"ytp-ce-expanding-overlay-body",T:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",T:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.Yq(b.title||"")},ra:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",ra:b.metadata},{D:"a",Ea:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:w3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ra:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:v3(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",T:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",ra:b.callToAction||void 0}]}]},c=new g.V(a)}b.fR&&g.K(c.element,"ytp-ce-placeholder");return c},v3=function(a){if(a.jI)var b=a.jI.thumbnails;
return BMa(b?b[b.length-1].url:null)},BMa=function(a){return a?{style:"background-image: url("+a+")"}:{}},AMa=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),x3(a,c.id,!0)):(g.Pq(b.element,"ytp-ce-force-expand"),g.Pq(b.element,"ytp-ce-element-hover"),x3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){y3(a,b,c)});
b.Qa("mouseleave",function(){z3(a,b,c)});
a.player.S().i||b.Qa("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){CMa(a,c,m)});
b.Qa("keypress",function(m){CMa(a,c,m)});
b.Qa("focus",function(){y3(a,b,c)});
b.Qa("blur",function(){z3(a,b,c)});
b.Qa("touchstart",function(){y3(a,b,c)});
var l=g.gg("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Pq(b.element,"ytp-ce-element-hover");g.Pq(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.gg("ytp-sb-subscribe",b.element));d(g.gg("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},CMa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Nq(d,"ytp-ce-element");){g.Nq(d,"subscribe-label")&&A3(a,b);
if(g.Nq(d,"ytp-ce-channel-subscribe"))return;d=g.wg(d)}if(!d||g.Nq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])z3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.OV)A3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Nc(w3(a,b.targetUrl)),c=g.Jc(c),g.UJ(c,void 0,b.Ud);else{var e=a.player.getVideoData().C,f=function(){var h=w3(a,b.targetUrl),l=b.Ud,m=g.us(h);e&&m&&(m.v||m.list)?a.player.Ij(m.v,l,m.list,!1):g.TJ(h,l)};
A3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},w3=function(a,b){a=a.player.S();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.gG(a)+b}else return"";return b},y3=function(a,b,c){g.Nq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.S().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),B3(a,c.VQ),x3(a,c.id,!0))},z3=function(a,b,c){g.Pq(b.element,"ytp-ce-element-hover");
g.Pq(b.element,"ytp-ce-force-expand");x3(a,c.id,!1)},x3=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.i[e].element,"ytp-ce-element-shadow-show",c)},B3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||t3(a))c&&c();else{b=DMa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ku(b[a],d)}},A3=function(a,b,c){B3(a,b.clickUrls,c);
(a=g.cy())&&b.cR&&g.oz(a,b.visualElement)},DMa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(EMa(b[d],c));return a},EMa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},FMa=function(a){return Array.isArray(a)&&a.length?a[0]:a},C3=function(a){return"string"===typeof a?a:""},D3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},GMa=function(a){this.externalId=a},HMa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},E3=function(a){return a.value?a.value:null},F3=function(a){if(!a)return null;
var b=g.Nc(C3(a.value));b=g.Jc(b);if(!b)return null;var c=D3(a.target,IMa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new HMa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},JMa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},MMa=function(a){if(!a)return null;
var b=D3(a.type,KMa),c=D3(a.trigger,LMa),d=FMa(a.url);d=F3(d?d:null);a=FMa(a.subscribeData);var e=a?a:null;e?(a=C3(e.external_user_id),e=C3(e.subscription_token),a=a&&e?new GMa(a):null):a=null;return b?new JMa(b,c,d,a):null},NMa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},PMa=function(a){return(a=OMa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},OMa=function(a,b){return g.fb(a.action,b,void 0)},QMa=function(a,b){this.context=a;
this.i=b},H3=function(a){return a.customMessage?G3("div","iv-card-message",a.customMessage):""},I3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},T:c}},J3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(G3("li","",c.value));return{D:"ul",K:"iv-card-meta-info",T:b}},G3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Yq(c);return{D:a,U:b,ra:c}},RMa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Xw&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Xw+");");c.dir=g.Yq(a.customMessage);var d=[{D:"span",ra:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ea:b,U:c,T:d}},K3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Ud,c.tracking.click,5)}},SMa=function(a,b){this.merchant=a;
this.price=b},TMa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},UMa=function(a,b){return b?b:TMa(a)?"current":"new"},L3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.La=new Map;this.Sa=new Map;this.context.I.addEventListener(g.dA("annotations_module"),function(d){(d=c.La.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.eA("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},M3=function(a,b,c,d,e,f,h){a.context.i.Qa(b,"click",function(l){a.TA(c,d,e,f||[],h||0,l)});
a.context.i.Qa(b,"touchstart",function(){a.bb=!1});
a.context.i.Qa(b,"touchmove",function(){a.bb=!0})},VMa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},N3=function(a,b,c){return{gJ:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
dM:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Sz:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Q3=function(a,b,c){L3.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ja=this.jb=this.u=this.ke=!1;this.xa=null;this.cards=[];this.eb=this.L=this.Da=this.C=this.Ia=this.i=null;this.ea=[];this.J=this.re=this.Aa=null;this.G=0;this.ya=new g.J(g.Ia,c.W.ud?4E3:3E3);g.F(this,this.ya);this.Ya=new g.J(g.Ia);g.F(this,this.Ya);this.Y=new QMa(c,function(e,f,h,l,m,n){M3(d,e,f,h,l,m,n)});
this.V=new g.V({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},T:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},T:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ea:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.F(this,this.V);this.B=this.V.element;this.Ta=new g.TL(this.V,330);g.F(this,this.Ta);this.fb=g.gg("iv-drawer-header-text",this.B);this.l=g.gg("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.jb&&O3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.jb=d.u)&&P3(d)})},WMa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){O3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){P3(a)});
var c=b.headerText;g.yg(a.fb,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Aa=g.Xx(b.trackingParams);a.J=g.Xx(b.closeTrackingParams);a.re=g.Xx(b.iconTrackingParams)},XMa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ud:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.command),ul:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?
g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):null,imageUrl:S3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.kA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Xw:null,title:d.title?g.kA(d.title):"",customMessage:d.callToAction?g.kA(d.callToAction):"",url:d.command.urlEndpoint.url?F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};T3(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ud:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.endpoint),ul:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.kA(d.customText):null,profileImageUrl:S3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.kA(d.channelName):"",metaInfo:[d.subscriberCountText?g.kA(d.subscriberCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};T3(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ud:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),ul:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):
null,uw:S3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.kA(d.customMessage):null,playlistVideoCount:g.kA(d.playlistVideoCount),title:d.playlistTitle?g.kA(d.playlistTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.videoCountText?g.kA(d.videoCountText):""],url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:VMa(d.action)})};T3(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.kA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ud:R3(a,c,b,d),sponsored:!1,tracking:N3(d,e,d.action),ul:d.trackingParams?g.Xx(d.trackingParams):null,Li:e.trackingParams?g.Xx(e.trackingParams):null,re:f&&f.trackingParams?g.Xx(f.trackingParams):null,uw:S3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.kA(d.lengthString):null,customMessage:d.customMessage?g.kA(d.customMessage):null,title:d.videoTitle?g.kA(d.videoTitle):"",metaInfo:[d.channelName?g.kA(d.channelName):"",d.viewCountText?g.kA(d.viewCountText):""],isLiveNow:!!d.badge,url:F3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:VMa(d.action)})};T3(a,b)}a.G++},S3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},R3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},ZMa=function(a,b){if(b=YMa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.vg(b.MB),g.ob(a.cards,b),a.Zw(),U3(a)},O3=function(a,b,c){if(!a.u){a.Ta.show();
a.Ia=new g.J(function(){g.K(a.context.I.getRootNode(),g.IT.IV_DRAWER_OPEN)},0);
a.Ia.start();a.xa=g.iu(a.l,"mousewheel",function(h){a.ya.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.cy();d&&a.Aa&&a.J&&g.mz(d,[a.Aa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.PJ||(f.PJ=!0,$Ma(a.context.logger,f.card.tracking.gJ,b)),d&&g.mz(d,[f.card.ul]);g3(a.I);c&&(a.C=new g.J(function(){a.Da=a.L;a.eb.focus()},330),a.C.start())}},P3=function(a){a.u&&(a.Ta.hide(),g.ju(a.xa),a.xa=null,g.Pq(a.context.I.getRootNode(),g.IT.IV_DRAWER_OPEN),a.u=!1,g3(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.Da&&(a.Da.focus(),a.Da=null)},330),a.C.start())},
bNa=function(a){g.Oq(a.element,[g.IT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.cN(a.I,a.B,5);aNa(a);a.L=g.gg("ytp-cards-button",a.I.getRootNode());a.eb=g.gg("iv-drawer-close-button",a.B);a.ke=!0},aNa=function(a){var b=g.gg("iv-drawer-close-button",a.B);
a.context.i.Qa(b,"click",a.DP,a);a.context.i.Qa(a.l,"touchend",function(){a.ya.start()});
a.context.i.Qa(a.l,"scroll",a.RP,a);a.context.l.subscribe("onHideControls",function(){a.Ja=!0});
a.context.l.subscribe("onShowControls",function(){a.Ja=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ja=g.Nq(a.I.getRootNode(),"ytp-autohide")});
a.ea.push(g.Ru("iv-button-shown",a.nR,a));a.ea.push(g.Ru("iv-button-hidden",a.mR,a));a.ea.push(g.Ru("iv-teaser-shown",a.dO,a));a.ea.push(g.Ru("iv-teaser-hidden",a.pR,a));a.ea.push(g.Ru("iv-teaser-clicked",a.cO,a))},T3=function(a,b){a.ke||bNa(a);
ZMa(a,b.id);var c=cNa(a,b);if(c){var d={card:b,MB:c.element,PJ:!1},e=dNa(a,d);g.ub(a.cards,e,0,d);c.Ba(a.l,e);a.Zw();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,U3(a),eNa(a,d),O3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&fNa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){fNa(a,d)}),U3(a))}},cNa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",ra:b.displayDomain}:void 0;var d=RMa(b);c={D:"div",Ea:["iv-card"],T:[{D:"a",K:"iv-click-target",U:{href:b.url?E3(b.url)||"":""},T:[I3(b.imageUrl,c),{D:"div",K:"iv-card-content",T:[G3("h2",void 0,b.title),d]}]}]};c=new g.V(c);K3(a,g.fg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ea:["iv-card","iv-card-channel"],T:[{D:"a",Ea:["iv-click-target"],U:{href:E3(b.url)||"","data-ytid":b.channelId},T:[I3(b.profileImageUrl),
{D:"div",K:"iv-card-content",T:[H3(b),{D:"h2",K:"iv-card-primary-link",ra:b.title},J3(b)]}]}]},c=new g.V(c),K3(a,g.fg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ea:["iv-card","iv-card-playlist"],T:[{D:"a",K:"iv-click-target",U:{href:E3(b.url)||""},T:[I3(b.uw,{D:"div",K:"iv-card-image-overlay",T:[{D:"span",K:"iv-card-playlist-video-count",ra:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",T:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b)]}]}]},c=new g.V(c),
K3(a,g.fg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.kb(b.offers);c=["iv-card"];d="";var f=RMa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",ra:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",ra:f.merchant}),f={D:"div",T:e});e=b.url?E3(b.url)||"":"";c={D:"div",Ea:c,U:{tabindex:"0"},T:[{D:"a",Ea:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",T:[b.sponsored?{D:"div",K:"iv-card-sponsored",T:["Lien commercial",{D:"div",K:"iv-ad-info-container",T:[{D:"div",K:"iv-ad-info",ra:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",T:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},T:[G3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.rg("span");g.yg(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.cd(d,"adInfo");K3(a,g.fg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",ra:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ea:["yt-badge","yt-badge-live"],ra:"EN DIRECT MAINTENANT"}:null,d={D:"div",Ea:["iv-card","iv-card-video"],T:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:E3(c))||""},T:[I3(b.uw,d),{D:"div",K:"iv-card-content",T:[H3(b),G3("h2","iv-card-primary-link",b.title),J3(b),f]}]}]},
c=new g.V(d),K3(a,g.fg("iv-click-target",c.element),b,b.url),c;default:return null}},dNa=function(a,b){if(0===a.cards.length)return 0;
a=g.gb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},gNa=function(a){return a.i?"productListing"===a.i.card.type:g.Fm(a.cards,function(b){return"productListing"===b.card.type})},U3=function(a){g.M(a.I.getRootNode(),"ytp-cards-shopping-active",gNa(a))},fNa=function(a,b){if(!g.Nq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.cy(),d=a.i?a.i.card.re:a.re;
c&&d&&g.nz(c,[d]);a.i=b;U3(a)}if(c="none"!=a.element.style.display)g.S(a.context.I.S().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.rs(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ya.isActive()||((!a.u||!a.ya.isActive()&&a.Ja)&&eNa(a,b),a.Ya.start(910+b.card.teaserDurationMs))}},
eNa=function(a,b){a.V.xb?(b=new l3([0,
a.l.scrollTop],[0,b.MB.offsetTop],600,pMa),a.context.u.Qa(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Qa(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.jL(a.V,!0),a.l.scrollTop=b.MB.offsetTop,g.jL(a.V,!1))},V3=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},YMa=function(a,b){return g.fb(a.cards,function(c){return c.card.id===b})},W3=function(a,b,c){L3.call(this,a,b);
this.annotation=c;this.isActive=!1},hNa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},X3=function(a,b,c){W3.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},iNa=function(a,b){var c=void 0===c?0:c;
var d=nMa(b).width;g.Jl(b,d);c=new n3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,oMa);g.F(a,c);a.context.u.Qa(c,"begin",function(){g.Sl(b,!0)});
c.play()},lNa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ea:["iv-branding-context-name"],ra:b.channel_name}),d=a.createElement({D:"div",Ea:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.vO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.Ba(d));var f=a.createElement({D:"div",Ea:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ea:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Sl(h,!1);var l=a.createElement({D:"div",Ea:["branding-context-container-outer"]});l.appendChild(h);g.Cl(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){jNa(a,h,l)},500);
g.F(a,a.u);a.context.i.Qa(a.element,"mouseover",function(){kNa(a,h,l,f,b.image_height)});
a.context.i.Qa(a.element,"mouseout",function(){a.u.start()})}},kNa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Rl(b);a.i||(b.style.width=g.Il(f.width,!0),c.style.width=g.Il(f.width,!0));g.Cl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Cl(d,"right","1px");a.B=!0;g.Sl(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},jNa=function(a,b,c){g.Pq(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Sl(b,!1);a.i||(c.style.width=g.Il(0,!0))},250);
a.G.start();a.B=!1},mNa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.W=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},Y3=function(a,b,c){W3.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.V=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ea:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Sl(d.u,!1);g.Sl(d.l,!0)},700,this);
g.F(this,this.C)},nNa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=PMa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ea:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",ra:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",ra:b.playlist_length.toString()}),h.appendChild(f));e&&M3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.pd(f,E3(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",T:[{D:"strong",
ra:b.text_line_1}]});var m=a.createElement({D:"p",T:[{D:"span",K:"iv-promo-link",ra:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ea:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ea:["iv-button","iv-promo-button"],T:[{D:"span",K:"iv-button-content",ra:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&M3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",T:[{D:"span",ra:b.text_line_1}]}),m=a.createElement({D:"p",T:[{D:"strong",ra:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ea:["yt-badge","iv-promo-badge-live"],ra:"EN DIRECT MAINTENANT"})),g.K(a.i,"iv-click-target"),e&&M3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);
p&&a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ea:["iv-promo-expand","ytp-button"]});a.l.title="Agrandir";a.context.i.Qa(a.l,"click",function(r){Z3(a,5E3,r)});
c.appendChild(a.l);g.Sl(a.l,!1);a.context.i.Qa(a.element,"mouseover",a.zQ,a);a.context.i.Qa(a.element,"mouseout",a.yQ,a);a.context.i.Qa(a.element,"touchend",function(r){Z3(a,5E3,r)});
a.u=a.createElement({D:"button",Ea:["iv-promo-close","ytp-button"]});a.u.title="Fermer";a.context.i.Qa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.uQ:a.tQ,a);c.appendChild(a.u);g.Oq(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},Z3=function(a,b,c){c.stopPropagation();
oNa(a);pNa(a,b);a.i.focus()},qNa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},oNa=function(a){a.C.stop();
a.isCollapsed&&(g.Qq(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Sl(a.l,!1),g.Sl(a.u,!0))},pNa=function(a,b){a.B||(a.B=g.nh(function(){$3(this);
qNa(this)},b,a))},$3=function(a){a.B&&(g.B.clearTimeout(a.B),a.B=null)},rNa=function(a){this.I=a},$Ma=function(a,b,c){b&&(c?a4(a,b.map(function(d){return g.Bq(d,c)})):a4(a,b))},a4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ku(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},b4=function(a){g.oN.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.J={};this.logger=new rNa(this.player);this.C=new g.fN(this);this.G=this.u=null;this.events=new g.fN(this);this.L=this.i=null;this.ea=[];g.F(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.Z("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.Z("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.Z("onShowControls")});
this.C.N(this.player,"resize",function(d){b.Z("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.Z("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.eO,this);this.subscribe("resize",this.Xy,this);this.player.S().V.subscribe("vast_info_card_add",this.dL,this);g.F(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Ea:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.l);g.cN(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ea:["ytp-iv-video-content"]});g.F(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.eq()&&this.load();var c=this.createElement({D:"style"});(g.cg("HEAD")[0]||document.body).appendChild(c);g.lf(this,function(){g.vg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},sNa=function(a){a=a.createElement({D:"div",
Ea:["annotation","annotation-type-custom"]});g.Sl(a,!1);return a},tNa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.jL(a.l,b);g.jL(a.B,b)},uNa=function(a,b,c){a.V=!0;
a.G=g.jt(b,c)},vNa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(vNa(a,e))}return c},yNa=function(a){var b=a.player.getVideoData();
if(b.Da){var c=a.player.S().V.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.bt(h)&&h.responseXML?h.responseXML:null)&&c4(a,h)}};
g.Bu()&&(d.onFinish=wNa(a,d.onFinish));d.postParams={ic_only:"1"};xNa(d,c);a.V=!0;g.jt(b.Da,d)}}},xNa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Ot&&(a.postParams.ic_coll=b.Ot);b.ex&&(a.postParams.ic_xml=b.ex);b.yw&&(a.postParams.ic_track=b.yw)},zNa=function(a){var b=new g.V({D:"div"});
g.Sl(b.element,!1);var c=new Q3(a.player,b.element,d4(a));g.F(c,b);b.Ba(a.l.element);c.cw();return c},d4=function(a){if(!a.L){var b=new o3(a);
g.F(a,b);var c=new g.xk(a);g.F(a,c);a.L=new mNa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.ud)}return a.L},c4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.cy();if(e){var f=g.ay();f&&g.fz(void 0,e,f,[g.Xx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=vNa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=D3(f.type,ANa),p=D3(f.style,BNa),r=C3(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=MMa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var G=f(z.value);
G&&l.push(G)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new NMa(m,n,p,x,t):null}else e=null}catch(Ba){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=sNa(f),L=null;switch(l.type){case "branding":if(f.player.S().Db)break;f.l.element.appendChild(I);L=new X3(I,d4(f),l);break;case "promotion":g.cN(f.player,I,4),L=new Y3(I,d4(f),l)}L&&L.cw();if(f=L)g.F(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=zNa(a),g.F(a,a.i));if("card"===e.type){c=a.i;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={gJ:l.impression,click:l.click,close:l.close,dM:l.teaser_impression,Sz:l.teaser_click},I=f.tracking_params||{},L=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ud:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ud:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):
null,re:I.icon?g.Xx(I.icon):null,uw:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "productListing":f.signin_url&&(L=F3({target:"current",value:f.signin_url}));Z=[];for(var R=f.offers||[],wa=0;wa<R.length;wa++)Z.push(new SMa(g.wd(R[wa].merchant),g.wd(R[wa].price)));e={id:e.id,timestamp:f.timestamp||
0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ud:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Xw:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,
target:f.target||"new",value:f.url}),F9:L,E9:f.signin_title?f.signin_title:void 0,D9:f.signin_message?f.signin_message:void 0,offers:Z};T3(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ud:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:I.card?g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?
f.display_domain:null,showLinkIcon:!!f.show_link_icon,Xw:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};T3(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ud:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,ul:I.card?
g.Xx(I.card):null,Li:I.teaser?g.Xx(I.teaser):null,re:I.icon?g.Xx(I.icon):null,uw:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:F3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},T3(c,e)}}else WMa(a.i,e);c=!0}}c&&(g3(a.player),a.Xy())},CNa=function(a,b){var c=!1;
a.i||(a.i=zNa(a),g.F(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(XMa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.kA(b.headerText):"",g.yg(c.fb,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Aa=b.trackingParams?g.Xx(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Xx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.re=b.icon.infoCardIconRenderer.trackingParams?
g.Xx(b.icon.infoCardIconRenderer.trackingParams):null,g3(a.player),a.Xy())},DNa=function(a,b,c,d,e){if(!a.player.S().Db){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new JMa("openUrl","click",new HMa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.kA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.kA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.kA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.kA(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.kA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.kA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new NMa(c,"branding","branding",f,d);l=sNa(a);a.l.element.appendChild(l);f=new X3(l,d4(a),f);f.cw();g.F(f,f);a.J[c]=f}},wNa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.isDisposed()||a.ea.push(g.yu(function(){b.apply(null,g.la(d))}))}},ENa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.WM.prototype.rs=g.ca(17,function(a,b){var c=g.FN(this.sb());c&&c.rs(a,b)});
var i3={},j3=null;g.Sa(l3,g.Sq);g.k=l3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Pa)this.progress=0,this.coords=this.i;else if(this.xc())return!1;k3(this);this.startTime=a=g.Ra();-1==this.Pa&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.u=this.startTime;this.progress||this.Ty();this.Xh("play");-1==this.Pa&&this.Xh("resume");this.Pa=1;var b=g.Oa(this);b in i3||(i3[b]=this);rMa();sMa(this,a);return!0};
g.k.stop=function(a){k3(this);this.Pa=0;a&&(this.progress=1);tMa(this,this.progress);this.Xh("stop");this.Bv()};
g.k.pause=function(){this.xc()&&(k3(this),this.Pa=-1,this.Xh("pause"))};
g.k.va=function(){0==this.Pa||this.stop(!1);this.Xh("destroy");l3.Vd.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.SA=function(){this.Xh("animate")};
g.k.Xh=function(a){this.dispatchEvent(new uMa(a,this))};
g.Sa(uMa,g.mf);g.Sa(m3,l3);m3.prototype.l=g.Ia;m3.prototype.SA=function(){this.l();m3.Vd.SA.call(this)};
m3.prototype.Bv=function(){this.l();m3.Vd.Bv.call(this)};
m3.prototype.Ty=function(){this.l();m3.Vd.Ty.call(this)};
g.Sa(n3,m3);n3.prototype.l=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(o3,g.E);o3.prototype.Qa=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.iu(a,b,c);this.i.push(a);return a};
o3.prototype.Ay=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.ru(a,b,c);this.i.push(a);return a};
o3.prototype.hc=function(a){g.ju(a);g.ob(this.i,a)};
o3.prototype.va=function(){g.ju(this.i);this.i.length=0;g.E.prototype.va.call(this)};g.v(s3,g.oN);g.k=s3.prototype;g.k.load=function(){g.oN.prototype.load.call(this);if(!t3(this)){var a=g.Xna(this.player.getVideoData());a?(a=r3(a,wMa(this)),u3(this,a,!1)):xMa(this)}};
g.k.unload=function(){u3(this,null);this.u&&(this.u.abort(),this.u=null);g.oN.prototype.unload.call(this)};
g.k.Ze=function(a,b){return t3(this)?"loadCustomEndscreenRenderer"===a?(a=r3(b,"new"),u3(this,a),!0):null:null};
g.k.getOptions=function(){return t3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.tb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<FNa.length;f++){var h=Math.abs(b.width-FNa[f]);if(-1===e||d>=h)e=f,d=h}d=GNa[e];this.l&&g.Cl(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ql(e.element,Math.round(h.width*a.width),f);g.Jl(e.element,m,n);g.Qq(e.element,HNa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Qq(e.element,GNa);g.K(e.element,d);(e=g.dg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Cl(e,"height",f+"px")}}}}};
g.k.Ad=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())B3(this,this.endscreen.impressionUrls),(a=g.cy())&&this.endscreen.visualElement&&g.gz(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");B3(this,c.impressionUrls);(b=g.cy())&&g.gz(b,c.visualElement,void 0);this.player.S().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.mf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.Pq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Pq(b,"ytp-ce-shown");this.player.S().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.WU=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.Qq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var FNa=[346,426,470,506,570,640,853,1280,1920],GNa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),HNa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var IMa={WZ:"current",C4:"new"};var KMa={CLOSE:"close",U4:"openUrl",fP:"subscribe"},LMa={IX:"click",CLOSE:"close",l0:"hidden",e6:"rollOut",f6:"rollOver",S6:"shown"};var BNa={cX:"anchored",OM:"branding",CHANNEL:"channel",UZ:"cta",o0:"highlightText",o1:"label",PLAYLIST:"playlist",A5:"popup",b7:"speech",fP:"subscribe",s7:"title",VIDEO:"video",A8:"website"},ANa={OM:"branding",vX:"card",i_:"drawer",n0:"highlight",U2:"marker",K5:"promotion",TEXT:"text",G8:"widget"};g.v(L3,g.E);g.k=L3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.aA(a,b,{id:c});a.namespace="annotations_module";d&&this.La.set(a,d);e&&this.Sa.set(a,e);this.context.I.Gd([a])};
g.k.cw=function(){this.context.l.subscribe("resize",this.Zw,this)};
g.k.TA=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.vg(this.element)};
g.k.Zw=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=E3(a);if(f){var h=UMa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.us(f||"");m&&n&&(n.v||n.list)?e.context.I.Ij(n.v,b,n.list,!1):g.UJ(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);a4(this.context.logger,c,l,d);TMa(f)||(c=g.cy(),d=b.itct,c&&d&&g.oz(c,g.Xx(d)))}};
g.k.va=function(){this.La.clear();this.Sa.clear();g.E.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.v(Q3,L3);g.k=Q3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Rl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Zw=function(){var a=this.isAvailable();g.Sl(this.element,a);g.M(this.context.I.getRootNode(),g.IT.IV_DRAWER_ENABLED,a);g3(this.I)};
g.k.destroy=function(){this.I.rs(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.Su(this.ea);g.ju(this.xa);this.Ia&&this.Ia.dispose();this.C&&this.C.dispose();L3.prototype.destroy.call(this)};
g.k.DP=function(){if(this.u){a4(this.context.logger,V3(this).tracking.close);var a=g.cy();a&&this.J&&g.oz(a,this.J);P3(this)}};
g.k.RP=function(){g.M(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.nR=function(){var a=g.cy(),b=V3(this);b=b?b.re:this.re;a&&b&&g.mz(a,[b])};
g.k.mR=function(){var a=g.cy(),b=V3(this);b=b?b.re:this.re;a&&b&&g.nz(a,[b])};
g.k.dO=function(){var a=V3(this);a4(this.context.logger,a.tracking.dM);var b=g.cy();b&&a&&g.mz(b,[a.Li,a.re])};
g.k.pR=function(){var a=g.cy(),b=V3(this);a&&b&&g.nz(a,[b.Li])};
g.k.cO=function(a){var b=V3(this),c=g.cy();this.i?a?(a=this.context.logger,a4(a,b.tracking.Sz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Li&&g.oz(c,b.Li)):(a=this.context.logger,a4(a,b.tracking.Sz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.re&&g.oz(c,b.re)):(a=this.context.logger,a4(a,b.tracking.Sz),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.re&&g.oz(c,this.re))};g.v(W3,L3);W3.prototype.cw=function(){L3.prototype.cw.call(this);hNa(this)};
W3.prototype.show=function(){L3.prototype.show.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.mz(a,[g.Xx(b.itct)])};
W3.prototype.hide=function(){L3.prototype.hide.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.nz(a,[g.Xx(b.itct)])};g.v(X3,W3);
X3.prototype.show=function(){if(!this.isActive){W3.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ea:["branding-img","iv-click-target"],U:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.Sl(this.l,!1);var b=this.createElement({D:"div",Ea:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=PMa(this.annotation))&&M3(this,this.l,b,this.annotation.id,
a.session_data);lNa(this,a);this.J=!0}g.Sl(this.element,!0);this.isActive=!0;this.l&&iNa(this,this.l)}};
X3.prototype.hide=function(){this.isActive&&(W3.prototype.hide.call(this),g.Sl(this.element,!1),this.isActive=!1)};
X3.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);W3.prototype.destroy.call(this)};g.v(Y3,W3);g.k=Y3.prototype;g.k.show=function(){this.isActive||(W3.prototype.show.call(this),this.V||(nNa(this),this.V=!0),g.Sl(this.element,!0),g.nh(function(){g.Pq(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,$3(this),oNa(this),pNa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.TA=function(a,b,c,d,e,f){return this.isCollapsed?!1:W3.prototype.TA.call(this,a,b,c,d,e,f)};
g.k.zQ=function(a){this.L=!0;Z3(this,500,a)};
g.k.yQ=function(){this.L=!1;qNa(this)};
g.k.tQ=function(a){a.stopPropagation();this.hide()};
g.k.uQ=function(a){a.stopPropagation();$3(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();W3.prototype.destroy.call(this)};g.v(b4,g.oN);g.k=b4.prototype;g.k.Ze=function(a,b){if(!ENa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.O1(b))&&c4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(ZMa(this.i,b),g3(this.player)),!0}return null};
g.k.getOptions=function(){return ENa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.eq=function(){var a=this.player.S(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.kH||a.V.get(b.videoId)||g.CH(b)||g.DH(b)?!0:!1};
g.k.Xy=function(){if(this.B){var a=this.player.Za().getVideoContentRect(!0);g.Ql(this.B.element,a.width,a.height);g.Jl(this.B.element,a.left,a.top)}if(this.i){var b=this.player.cj();a=this.i;b=b.width;g.M(a.B,"iv-drawer-small",426>=b);g.M(a.B,"iv-drawer-big",1280<=b)}};
g.k.eO=function(a){tNa(this,a.state);g.U(a.state,2)&&(this.qh()&&this.ek()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.rs(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.bt(h)&&h.responseXML?h.responseXML:null)&&(c4(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.oN.prototype.load.call(this);tNa(this,this.player.ub());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Bu()&&(a=wNa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().V.get(d);f&&xNa(e,f);f=f&&(f.ex||f.Ot);if(!c.fl||f)c.Da?uNa(this,c.Da,e):(this.u=function(){b.ob(e)},this.player.addEventListener("videodatachange",this.u));
g.cN(this.player,this.B.element,4);this.Xy();(f=g.CH(c))&&CNa(this,f);(f=g.DH(c))&&f.featuredChannel&&DNa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.ob=function(a){var b=this.player.getVideoData();b.Da&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),uNa(this,b.Da,a))};
g.k.unload=function(){this.player.Ue("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,g3(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.oN.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.dL=function(a){a===this.player.getVideoData().videoId&&(this.loaded?yNa(this):this.load())};
g.k.qh=function(){return!!this.i&&this.i.isAvailable()};
g.k.ek=function(){this.qh();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.qh();this.i&&(a?c?O3(this.i,c,b):O3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):P3(this.i))};
g.k.rs=function(a,b){this.player.Z(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.S().V.unsubscribe("vast_info_card_add",this.dL,this);g.Pq(this.player.getRootNode(),g.IT.IV_DRAWER_OPEN);for(var a=this.ea,b=0,c=a.length;b<c;b++)g.Cu(a[b]);this.ea.length=0;g.oN.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.F(this,a);return a.element};g.zN.annotations_module=b4;g.zN.creatorendscreen=s3;})(_yt_player);
