(function(g){var window=this;'use strict';var pcb=function(a,b){a.Oa("onAutonavCoundownStarted",b)},x5=function(a,b,c){g.fo(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Zf(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.ZI&&(b.lengthText?(e=b.lengthText||null,f=b.Ou||null):b.lengthSeconds&&(e=g.dO(b.lengthSeconds),f=g.dO(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.XI(d).type;var l=b instanceof g.ZI?b.isLivePlayback:null,m=b instanceof g.ZI?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],v=[];n&&r.push(n);p&&(r.push(p),v.push(p));q&&v.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.BL("Regarder $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.jo(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:v.join(" \u2022 "),autoplayAlternativeHeader:b.Sq};b instanceof g.YI&&(c.playlist_length=b.playlistLength);a.update(c)},y5=function(a){var b=a.V(),c=b.u;
g.T.call(this,{G:"a",K:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],qa:"En direct"},
{G:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u00c0 venir"},{G:"div",K:"ytp-autonav-list-overlay",W:[{G:"div",K:"ytp-autonav-mix-text",qa:"Mix"},{G:"div",K:"ytp-autonav-mix-icon"}]}]},{G:"div",Ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{G:"div",Ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.F=
a;this.suggestion=null;this.j=c;this.Pa("click",this.onClick);this.Pa("keypress",this.onKeyPress)},z5=function(a,b){b=void 0===b?!1:b;
g.T.call(this,{G:"div",K:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.T({G:"div",K:"ytp-autonav-endscreen-countdown-container"});g.E(this,this.container);this.container.Ca(this.element);b=a.V();var d=b.u;this.F=a;this.suggestion=null;this.onVideoDataChange("newdata",this.F.getVideoData());this.N(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.S("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.T({G:"div",K:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",K:"ytp-autonav-endscreen-upnext-header"},{G:"div",K:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{G:"a",K:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.T:""},W:[{G:"div",Ga:e,X:{style:"{{background}}"},W:[{G:"div",
X:{"aria-label":"{{timestamp}}"},Ga:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ga:["ytp-autonav-live-stamp"],qa:"En direct"},{G:"div",Ga:["ytp-autonav-upcoming-stamp"],qa:"\u00c0 venir"}]},{G:"div",K:"ytp-autonav-endscreen-video-info",W:[{G:"div",K:"ytp-autonav-endscreen-premium-badge"},{G:"div",K:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{G:"div",K:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},{G:"div",K:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},
{G:"div",K:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.E(this,this.j);this.j.Ca(this.container.element);d||this.N(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.lP);this.F.rb(this.container.element,this,115127);this.F.rb(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({G:"div",K:"ytp-autonav-overlay"});g.E(this,this.overlay);this.overlay.Ca(this.container.element);this.u=new g.T({G:"div",K:"ytp-autonav-endscreen-button-container"});
g.E(this,this.u);this.u.Ca(this.container.element);this.cancelButton=new g.T({G:"button",Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Annuler la lecture automatique"},qa:"Annuler"});g.E(this,this.cancelButton);this.cancelButton.Ca(this.u.element);this.cancelButton.Pa("click",this.fY,this);this.F.rb(this.cancelButton.element,this,115129);this.playButton=new g.T({G:"a",
Ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.S("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},qa:"Regarder"});g.E(this,this.playButton);this.playButton.Ca(this.u.element);this.playButton.Pa("click",this.lP,this);this.F.rb(this.playButton.element,this,115130);this.C=new g.Tn(function(){qcb(c)},500);
g.E(this,this.C);this.kP();this.N(a,"autonavvisibility",this.kP);this.F.S("web_autonav_color_transition")&&(this.N(a,"autonavchange",this.eY),this.N(a,"onAutonavCoundownStarted",this.T3))},A5=function(a){var b=a.F.jk(!0,a.F.isFullscreen());
g.fo(a.container.element,"ytp-autonav-endscreen-small-mode",a.Yg(b));g.fo(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.XG);g.fo(a.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.F.If());g.fo(a.F.getRootNode(),"countdown-running",a.rk());g.fo(a.container.element,"ytp-player-content",a.F.If());g.ul(a.overlay.element,{width:b.width+"px"});if(!a.rk()){a.F.If()?rcb(a,Math.round(scb(a)/1E3)):rcb(a);b=!!a.suggestion&&!!a.suggestion.Sq;var c=a.F.If()||!b;
g.fo(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.fo(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.bN(a.u,a.F.If());g.fo(a.element,"ytp-enable-w2w-color-transitions",tcb(a))}},qcb=function(a){var b=scb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);rcb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.rk()?a.select(!0):a.rk()&&a.C.start()},scb=function(a){if(a.F.isFullscreen()){var b;
a=null==(b=a.F.getVideoData())?void 0:b.vz;return-1===a||void 0===a?8E3:a}return 0<=a.F.Ar()?a.F.Ar():g.GG(a.F.V().experiments,"autoplay_time")||1E4},tcb=function(a){var b;
return!(null==(b=a.F.getVideoData())||!b.watchToWatchTransitionRenderer)},rcb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.Qe(a);if(0<=b){b=String(b);var c="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Prochaine vid\u00e9o dans $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Oe("Prochaine vid\u00e9o dans $SECONDS".slice(0,d)));var e=g.Ne("span");g.Zn(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ve(e,b);a.appendChild(e);a.appendChild(g.Oe("Prochaine vid\u00e9o dans $SECONDS".slice(d+c.length)));return}}g.Ve(a,"\u00c0 suivre")},
B5=function(a,b){g.T.call(this,{G:"div",
Ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},C5=function(a){g.T.call(this,{G:"div",
Ga:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{G:"div",K:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",K:"ytp-upnext-top",W:[{G:"span",K:"ytp-upnext-header",qa:"\u00c0 suivre"},{G:"span",K:"ytp-upnext-title",qa:"{{title}}"},{G:"span",K:"ytp-upnext-author",qa:"{{author}}"}]},{G:"a",K:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},W:[{G:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},W:[{G:"circle",K:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",K:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",K:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",K:"ytp-upnext-bottom",W:[{G:"span",K:"ytp-upnext-cancel"},{G:"span",K:"ytp-upnext-paused",
qa:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ea("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.Tn(this.iE,5E3,this);this.u=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.T({G:"button",Ga:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Annuler la lecture automatique"},qa:"Annuler"});g.E(this,this.cancelButton);this.cancelButton.Pa("click",this.gY,this);this.cancelButton.Ca(b);
this.cancelButton&&this.api.rb(this.cancelButton.element,this,115129);g.E(this,this.C);this.api.rb(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.N(b,"click",this.hY);this.api.rb(b,this,115130);this.mP();this.N(a,"autonavvisibility",this.mP);this.N(a,"mdxnowautoplaying",this.E4);this.N(a,"mdxautoplaycanceled",this.F4);g.fo(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},ucb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.vz;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ar()?a.api.Ar():g.GG(a.api.V().experiments,"autoplay_time")||1E4},vcb=function(a,b){b=ucb(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.rk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.rk()&&a.j.start()},D5=function(a){B5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({G:"div",K:"ytp-suggestion-panel",W:[{G:"div",Ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"Plus de vid\u00e9os"}]});this.J=new g.T({G:"div",K:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new z5(this.player);g.E(this,this.u);this.u.Ca(this.element);a.getVideoData().xc?this.j=this.u:(this.j=new C5(a),g.iQ(this.player,this.j.element,4),g.E(this,this.j));this.overlay=new g.T({G:"div",
K:"ytp-autonav-overlay-cancelled-state"});g.E(this,this.overlay);this.overlay.Ca(this.element);this.C=new g.HF(this);g.E(this,this.C);g.E(this,this.table);this.table.Ca(this.element);this.table.show();g.E(this,this.J);this.J.Ca(this.table.element);this.hide()},E5=function(a){var b=a.If();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},F5=function(a,b){g.T.call(this,{G:"button",
Ga:["ytp-watch-on-youtube-button","ytp-button"],qa:"{{content}}"});this.F=a;this.buttonType=this.buttonType=b;b=this.F.getVideoData();if(a.S("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.watchNextResponse)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.N(a.watchOnYoutubeButton,g.kKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.F.Fg(this.element,this),this.F.yh(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Regarder \u00e0 nouveau sur YouTube";d=156915;break;case 2:c="Continuer \u00e0 regarder sur YouTube";d=156942;break;default:c="Continuer \u00e0 regarder sur YouTube",d=156942}this.update({content:c});this.F.rb(this.element,this,d)}2===this.buttonType&&g.ao(this.element,"ytp-continue-watching-button");this.Pa("click",this.onClick);g.bN(this,!0)},G5=function(a,b){B5.call(this,a,"embeds-lite-endscreen");
this.F=a;this.j=b;this.F.rb(this.element,this,156943);this.watchButton=new F5(a,2);g.E(this,this.watchButton);this.watchButton.Ca(this.element);this.hide()},wcb=function(a){B5.call(this,a,"subscribecard-endscreen");
this.j=new g.T({G:"div",K:"ytp-subscribe-card",W:[{G:"img",K:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",K:"ytp-subscribe-card-right",W:[{G:"div",K:"ytp-author-name",qa:"{{author}}"},{G:"div",K:"html5-subscribe-button-container"}]}]});g.E(this,this.j);this.j.Ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.UR("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.Ol,b.subscribed,"trailer-endscreen",null,null,a);g.E(this,this.subscribeButton);this.subscribeButton.Ca(this.j.Ea("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.La);this.La();this.hide()},H5=function(a){var b=a.V(),c=g.KF||g.AH?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.T.call(this,{G:"a",Ga:e,X:{href:"{{url}}",target:d?b.T:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",K:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",K:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-info-bg",W:[{G:"span",K:"ytp-videowall-still-info-content",X:c,W:[{G:"span",K:"ytp-videowall-still-info-title",
qa:"{{title}}"},{G:"span",K:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{G:"span",K:"ytp-videowall-still-info-live",qa:"En direct"},{G:"span",K:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{G:"span",Ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",K:"ytp-videowall-still-listlabel-length",W:[" (",{G:"span",qa:"{{playlist_length}}"},")"]}]},
{G:"span",Ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",K:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",K:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.HF(this);g.E(this,this.j);this.Pa("click",this.onClick);this.Pa("keypress",this.onKeyPress);this.j.N(a,"videodatachange",this.onVideoDataChange);a.Fg(this.element,this);this.onVideoDataChange()},I5=function(a){B5.call(this,
a,"videowall-endscreen");
var b=this;this.F=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.HF(this);g.E(this,this.u);this.Z=a.S("web_rounded_thumbnails");this.I=new g.Tn(function(){g.ao(b.element,"ytp-show-tiles")},0);
g.E(this,this.I);var c=new g.T({G:"button",Ga:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Pr\u00e9c\u00e9dente"},W:[g.gN()]});g.E(this,c);c.Ca(this.element);c.Pa("click",this.lY,this);this.table=new g.ZM({G:"div",K:"ytp-endscreen-content"});g.E(this,this.table);this.table.Ca(this.element);c=new g.T({G:"button",Ga:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Suivante"},W:[g.hN()]});g.E(this,c);c.Ca(this.element);c.Pa("click",this.kY,this);a.getVideoData().xc?this.j=new z5(a,!0):
this.j=new C5(a);g.E(this,this.j);g.iQ(this.player,this.j.element,4);a.rb(this.element,this,158789);this.hide()},J5=function(a){return g.jQ(a.player)&&a.dA()&&!a.C},xcb=function(a){var b,c,d,e;
return(null==(b=a.videoData)?0:null==(c=b.suggestions)?0:c.length)?null==(d=a.videoData)?void 0:d.suggestions:[null==(e=a.videoData)?void 0:g.aJ(e)]},K5=function(a){var b=a.If();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},L5=function(a){B5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new F5(a,1);g.E(this,this.watchButton);this.watchButton.Ca(this.element);g.A4a(a)&&(this.j=new g.w2(a,g.WP(a)),g.E(this,this.j),this.u=new g.T({G:"div",Ga:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.E(this,this.u),this.j.Ca(this.u.element),this.u.Ca(this.element));a.rb(this.element,this,156914);this.hide()},Bcb=function(a){g.RQ.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.HF(this);g.E(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.Fw(g.UH(c))&&d&&!g.fQ(a))this.u=!0,this.endScreen=new G5(a,g.WP(a));else{var e;(null==(e=g.WP(a))?0:e.qk())?this.endScreen=new L5(a):ycb(a)?(this.C=!0,zcb(this),this.j?this.endScreen=new D5(a):this.endScreen=new I5(a)):c.Rg?this.endScreen=new wcb(a):this.endScreen=new B5(a)}g.E(this,this.endScreen);g.iQ(a,this.endScreen.element,
4);Acb(this);this.listeners.N(a,"videodatachange",this.onVideoDataChange,this);this.listeners.N(a,g.LB("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.N(a,g.MB("endscreen"),function(f){b.onCueRangeExit(f)})},zcb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Yd&&a.B===b.xc)return!1;a.j=b.Yd;a.B=b.xc;return!0},ycb=function(a){a=a.V();
return a.zd&&!a.Rg},Acb=function(a){a.player.Sf("endscreen");
var b=a.player.getVideoData();b=new g.JB(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.JB(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Ke([b,c])};
g.aV.prototype.Qy=g.ba(37,function(a){this.GM!==a&&(this.GM=a,this.Pk())});
g.LS.prototype.zq=g.ba(36,function(a){this.u!==a&&(this.u=a,this.La())});
g.aV.prototype.zq=g.ba(35,function(a){this.shareButton&&this.shareButton.zq(a)});
g.AS.prototype.yq=g.ba(34,function(a){this.j!==a&&(this.j=a,this.La())});
g.aV.prototype.yq=g.ba(33,function(a){this.overflowButton&&this.overflowButton.yq(a)});
g.GR.prototype.HC=g.ba(32,function(a){this.HM!==a&&(this.HM=a,this.So())});
g.bQ.prototype.Ar=g.ba(6,function(){return this.app.Ar()});
g.nZ.prototype.Ar=g.ba(5,function(){return this.getVideoData().KO});g.w(y5,g.T);y5.prototype.select=function(){this.F.jn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.zA||void 0)&&this.F.sb(this.element)};
y5.prototype.onClick=function(a){g.rR(a,this.F,this.j,this.suggestion.sessionData||void 0)&&this.select()};
y5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.iz(a)||(this.select(),g.hz(a))}};g.w(z5,g.T);g.k=z5.prototype;g.k.pD=function(a){this.suggestion!==a&&(this.suggestion=a,x5(this.j,a),this.playButton.updateValue("url",this.suggestion.jo()),A5(this))};
g.k.rk=function(){return 0<this.B};
g.k.Wy=function(){this.rk()||(this.B=Date.now(),qcb(this),pcb(this.F,scb(this)),g.fo(this.F.getRootNode(),"countdown-running",this.rk()))};
g.k.hv=function(){this.Cq();qcb(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.Ve(a,"\u00c0 suivre")};
g.k.Cq=function(){this.rk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Cq()};
g.k.lP=function(a){g.rR(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.sb(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.F.Sa(a,!0),this.F.sb(a)),this.select())};
g.k.fY=function(){this.F.sb(this.cancelButton.element);g.dQ(this.F,!0);this.D&&this.F.Oa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.gP)?void 0:c.command};
g.k.T3=function(a){if(tcb(this)){var b=this.F.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.oO(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.oO(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.oO(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.oO(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.oO(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.oO(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.fo(this.element,"ytp-w2w-animate",!0)}};
g.k.eY=function(a){this.F.S("web_autonav_color_transition")&&2!==a&&g.fo(this.element,"ytp-w2w-animate",!1)};
g.k.kP=function(){var a=this.F.If();this.I&&this.ub!==a&&g.bN(this,a);A5(this);this.F.Sa(this.container.element,a);this.F.Sa(this.cancelButton.element,a);this.F.Sa(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.F.Sa(this.playButton.element,a)};
g.k.Yg=function(a){return 400>a.width||459>a.height};g.w(B5,g.T);g.k=B5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.dA=function(){return!1};
g.k.If=function(){return!1};
g.k.qT=function(){return!1};g.w(C5,g.T);g.k=C5.prototype;g.k.iE=function(){this.notification&&(this.C.stop(),this.Gc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.pD=function(a){this.suggestion=a;x5(this,a,"hqdefault.jpg")};
g.k.mP=function(){g.bN(this,this.api.If());this.api.Sa(this.element,this.api.If());this.api.Sa(this.Ea("ytp-upnext-autoplay-icon"),this.api.If());this.cancelButton&&this.api.Sa(this.cancelButton.element,this.api.If())};
g.k.N4=function(){window.focus();this.iE()};
g.k.Wy=function(a){var b=this;this.rk()||(g.xz("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.u=(0,g.Q)(),this.j=new g.Tn(function(){vcb(b,a)},25),vcb(this,a),pcb(this.api,ucb(this,a)));
g.co(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.rk=function(){return!!this.j};
g.k.hv=function(){this.Cq();this.u=(0,g.Q)();vcb(this);g.ao(this.element,"ytp-upnext-autoplay-paused")};
g.k.Cq=function(){this.rk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().S("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.iE(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.Zf()}),this.B=this.N(this.notification,"click",this.N4),this.C.start())}this.Cq();this.api.nextVideo(!1,a)};
g.k.hY=function(a){!g.Ue(this.cancelButton.element,g.dz(a))&&g.rR(a,this.api)&&(this.api.If()&&this.api.sb(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.gY=function(){this.api.If()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.dQ(this.api,!0)};
g.k.E4=function(a){this.api.getPresentingPlayerType();this.show();this.Wy(a)};
g.k.F4=function(){this.api.getPresentingPlayerType();this.Cq();this.hide()};
g.k.ra=function(){this.Cq();this.iE();g.T.prototype.ra.call(this)};g.w(D5,B5);g.k=D5.prototype;g.k.create=function(){B5.prototype.create.call(this);this.C.N(this.player,"appresize",this.Hz);this.C.N(this.player,"onVideoAreaChange",this.Hz);this.C.N(this.player,"videodatachange",this.onVideoDataChange);this.C.N(this.player,"autonavchange",this.nP);this.C.N(this.player,"autonavcancel",this.iY);this.onVideoDataChange()};
g.k.show=function(){B5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.dQ(this.player,!1);g.jQ(this.player)&&this.dA()&&!this.B?(E5(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Wy():3===this.videoData.autonavState&&this.j.hv()):(g.dQ(this.player,!0),E5(this));this.Hz()};
g.k.hide=function(){B5.prototype.hide.call(this);this.j.hv();E5(this)};
g.k.Hz=function(){var a=this.player.jk(!0,this.player.isFullscreen());E5(this);A5(this.u);g.fo(this.element,"ytp-autonav-cancelled-small-mode",this.Yg(a));g.fo(this.element,"ytp-autonav-cancelled-tiny-mode",this.uF(a));g.fo(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.ul(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.t(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.t(b.value);b=c.next().value;c=c.next().value;g.fo(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){var b=g.aJ(this.videoData);b&&(this.j.pD(b),this.j!==this.u&&this.u.pD(b));for(b=0;b<Ccb.length;++b){var c=Ccb[b];if(a&&a[c]){this.videos[b]=new y5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,x5(d,c));g.E(this,this.videos[b]);this.videos[b].Ca(this.J.element)}}}this.Hz()}};
g.k.nP=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Cq(),this.ub&&this.Hz()):(this.I=!0,this.If()&&(2===a?this.j.Wy():3===a&&this.j.hv()))};
g.k.iY=function(a){a?this.nP(1):(this.B=null,this.I=!1)};
g.k.dA=function(){return 1!==this.videoData.autonavState};
g.k.Yg=function(a){return(910>a.width||459>a.height)&&!this.uF(a)&&!(400>=a.width||360>=a.height)};
g.k.uF=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.If=function(){return this.ub&&g.jQ(this.player)&&this.dA()&&!this.B};
var Ccb=[1,3,2,4];g.w(F5,g.T);g.k=F5.prototype;g.k.onClick=function(a){this.j?this.F.Oa("innertubeCommand",this.j.onTap):g.sR(this.getVideoUrl(),this.F,a);this.F.sb(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.F.getVideoUrl(a,!1,!1,!0);var b=this.F.V();if(g.CH(b)||g.MH(b)){var c={};b.Ka&&g.CH(b)&&g.qP(c,b.loaderUrl);g.CH(b)&&g.TP(this.F,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.pP(c,b);a=g.Yh(a,c)}return a};
g.k.Sa=function(){this.F.Sa(this.element,this.ub&&this.ya)};
g.k.show=function(){g.T.prototype.show.call(this);this.Sa()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.Sa()};
g.k.jc=function(a){g.T.prototype.jc.call(this,a);this.Sa()};g.w(G5,B5);G5.prototype.show=function(){3!==this.player.getPlayerState()&&(B5.prototype.show.call(this),this.j.Qy(!0),this.j.zq(!0),this.F.V().Ll||this.j.yq(!0),this.F.Sa(this.element,!0),this.watchButton.jc(!0))};
G5.prototype.hide=function(){B5.prototype.hide.call(this);this.j.Qy(!1);this.j.zq(!1);this.j.yq(!1);this.F.Sa(this.element,!1);this.watchButton.jc(!1)};g.w(wcb,B5);wcb.prototype.La=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Ol;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.w(H5,g.T);H5.prototype.select=function(){this.api.jn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.zA||void 0)&&this.api.sb(this.element)};
H5.prototype.onClick=function(a){g.rR(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
H5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.iz(a)||(this.select(),g.hz(a))}};
H5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.u};g.w(I5,B5);g.k=I5.prototype;g.k.create=function(){B5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.ep();this.u.N(this.player,"appresize",this.ep);this.u.N(this.player,"onVideoAreaChange",this.ep);this.u.N(this.player,"videodatachange",this.onVideoDataChange);this.u.N(this.player,"autonavchange",this.OH);this.u.N(this.player,"autonavcancel",this.jY);a=this.videoData.autonavState;a!==this.T&&this.OH(a);this.u.N(this.element,"transitionend",this.b6)};
g.k.destroy=function(){g.rA(this.u);g.ab(this.stills);this.stills=[];B5.prototype.destroy.call(this);g.co(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.dA=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.ub;B5.prototype.show.call(this);xcb(this);g.co(this.element,"ytp-show-tiles");this.player.V().isMobile?g.Vn(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.dQ(this.player,!1);J5(this)?(K5(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Wy():3===this.videoData.autonavState&&this.j.hv()):(g.dQ(this.player,!0),K5(this));a!==this.ub&&
this.player.Sa(this.element,!0)};
g.k.hide=function(){var a=this.ub;B5.prototype.hide.call(this);this.j.hv();K5(this);a!==this.ub&&this.player.Sa(this.element,!1)};
g.k.b6=function(a){g.dz(a)===this.element&&this.ep()};
g.k.ep=function(){var a=xcb(this);if(a.length){g.ao(this.element,"ytp-endscreen-paginate");var b=this.F.jk(!0,this.F.isFullscreen()),c=g.WP(this.F);c&&(c=c.dg()?48:32,b.width-=2*c);var d=b.width/b.height,e=96/54,f=c=2,h=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=a.length,n=Math.pow(2,2);var p=m*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-n;for(p-=n;0<p&&(c<h||f<l);){var q=c/2,r=f/2,v=c<=h-2&&p>=r*n,x=f<=l-2&&p>=q*n;if((q+1)/r*e/d>d/(q/(r+1)*e)&&x)p-=q*n,f+=2;else if(v)p-=r*n,c+=2;else if(x)p-=q*
n,f+=2;else break}e=!1;p>=3*n&&6>=m*n-p&&(4<=f||4<=c)&&(e=!0);n=96*c;p=54*f;d=n/p<d?b.height/p:b.width/n;d=Math.min(d,2);n=Math.floor(Math.min(b.width,n*d));p=Math.floor(Math.min(b.height,p*d));b=this.table.element;b.ariaLive="polite";g.El(b,n,p);g.ul(b,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.pD(g.aJ(this.videoData));this.j instanceof z5&&A5(this.j);g.fo(this.element,"ytp-endscreen-takeover",J5(this));K5(this);n+=4;p+=4;d=0;b.ariaBusy="true";for(h=0;h<c;h++)for(l=0;l<f;l++)if(q=d,v=0,e&&
h>=c-2&&l>=f-2?v=1:0===l%2&&0===h%2&&(2>l&&2>h?0===l&&0===h&&(v=2):v=2),q=g.de(q+this.B,m),0!==v){r=this.stills[d];r||(r=new H5(this.player),this.stills[d]=r,b.appendChild(r.element));x=Math.floor(p*l/f);var z=Math.floor(n*h/c),B=Math.floor(p*(l+v)/f)-x-4,D=Math.floor(n*(h+v)/c)-z-4;g.Al(r.element,z,x);g.El(r.element,D,B);g.ul(r.element,"transitionDelay",(l+h)/20+"s");g.fo(r.element,"ytp-videowall-still-mini",1===v);g.fo(r.element,"ytp-videowall-still-large",2<v);this.Z&&(v=Math.max(D,B),g.fo(r.element,
"ytp-videowall-still-round-large",256<=v),g.fo(r.element,"ytp-videowall-still-round-medium",96<v&&256>v),g.fo(r.element,"ytp-videowall-still-round-small",96>=v));q=a[q];r.suggestion!==q&&(r.suggestion=q,v=r.api.V(),x=g.$n(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",x5(r,q,x),g.CH(v)&&(x=q.jo(),z={},v.Ka&&g.qP(z,v.loaderUrl),g.TP(r.api,"addEmbedsConversionTrackingParams",[z]),x=g.Yh(x,g.pP(z,"emb_rel_end")),r.updateValue("url",x)),(q=(q=q.sessionData)&&q.itct)&&r.api.yh(r.element,
q));d++}b.ariaBusy="false";g.fo(this.element,"ytp-endscreen-paginate",d<m);for(a=this.stills.length-1;a>=d;a--)c=this.stills[a],g.Se(c.element),g.$a(c);this.stills.length=d}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.ep())};
g.k.kY=function(){this.B+=this.stills.length;this.ep()};
g.k.lY=function(){this.B-=this.stills.length;this.ep()};
g.k.qT=function(){return this.j.rk()};
g.k.OH=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Cq(),this.ub&&this.ep()):(this.D=!0,this.ub&&J5(this)&&(2===a?this.j.Wy():3===a&&this.j.hv()))};
g.k.jY=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Sa(this.stills[a].element,!0);this.OH(1)}else this.C=null,this.D=!1;this.ep()};
g.k.If=function(){return this.ub&&J5(this)};g.w(L5,B5);L5.prototype.show=function(){if(3!==this.player.getPlayerState()){B5.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.fo(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.WP(this.player))||c.HC(!0);this.player.Sa(this.element,!0);this.watchButton.jc(!0)}};
L5.prototype.hide=function(){B5.prototype.hide.call(this);var a;null==(a=g.WP(this.player))||a.HC(!1);this.player.Sa(this.element,!1);this.watchButton.jc(!1)};g.w(Bcb,g.RQ);g.k=Bcb.prototype;g.k.Hv=function(){var a;if((null==(a=g.WP(this.player))?0:a.qk())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.aJ(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!ycb(this.player)||c;c=a.Ej||g.MH(a.u);var d=this.player.KA();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.If=function(){return this.endScreen.If()};
g.k.B2=function(){return this.If()?this.endScreen.qT():!1};
g.k.ra=function(){this.player.Sf("endscreen");g.RQ.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.tb().Xe.get("heartbeat"),d=g.aJ(a);!d||b.videoId!==d.videoId||a.II?(this.player.jn(b.videoId,void 0,void 0,!0,!0,b),c&&c.AF("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.RQ.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.RQ.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Hv()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Acb(this);this.C&&zcb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new D5(this.player):this.endScreen=new I5(this.player),g.E(this,this.endScreen),g.iQ(this.player,this.endScreen.element,4))};g.QQ("endscreen",Bcb);})(_yt_player);
