(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var t3=function(a){a.ea("cardstatechange",a.Bh()&&a.qk()?1:0)},u3=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},HPa=function(a){var b=g.om(a);
a=g.um(a);return new g.bm(b.x,b.y,a.width,a.height)},IPa=function(a){return Math.pow(a,3)},JPa=function(a){return 3*a*a-2*a*a*a},x3=function(a){a=g.Pa(a);
delete v3[a];g.De(v3)&&w3&&w3.stop()},LPa=function(){w3||(w3=new g.I(function(){KPa()},20));
var a=w3;a.isActive()||a.start()},KPa=function(){var a=g.Sa();
g.qe(v3,function(b){MPa(b,a)});
g.De(v3)||LPa()},y3=function(a,b,c,d){g.vr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},MPa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;NPa(a,a.progress);1==a.progress?(a.i=0,x3(a),a.onFinish(),a.Cw()):a.Ec()&&a.fC()},NPa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},OPa=function(a,b){g.ie.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},z3=function(a,b,c,d,e){y3.call(this,b,c,d,e);
this.element=a},A3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
z3.call(this,a,b,c,d,e)},B3=function(a){g.E.call(this);
this.u=a||window;this.i=[]},C3=function(a){return a.baseUrl||null},D3=function(a,b){return g.ap(g.Mm(a,b,void 0),function(c){return!!c})},PPa=function(a,b,c){function d(V){var xa,La,rb,pb=V.hovercardButton;
if(!pb)return null;pb=pb.subscribeButtonRenderer;if(!pb)return null;var Pb=f(pb.unsubscribedButtonText),lc=f(pb.subscribedButtonText);if(pb.subscribed){var Qa=f(pb.subscriberCountWithUnsubscribeText);var cc=f(pb.subscriberCountText)}else Qa=f(pb.subscriberCountText),cc=f(pb.subscriberCountWithSubscribeText);var Ib=null;return V.signinEndpoint&&(Ib=u3(V,"signinEndpoint","webNavigationEndpointData","url"),Ib||(Ib=null===(rb=null===(La=null===(xa=pb.signInEndpoint)||void 0===xa?void 0:xa.commandMetadata)||
void 0===La?void 0:La.webCommandMetadata)||void 0===rb?void 0:rb.url),!Ib)?null:Pb&&(lc||Ib)?{subscribed:pb.subscribed,subscribeText:Pb,subscribeCount:Qa,unsubscribeText:lc,unsubscribeCount:cc,enabled:pb.enabled,signinUrl:Ib,classic:V.useClassicSubscribeButton}:null}
function e(V){if(V){var xa=[],La=V.videoId;La&&xa.push("v="+La);(La=V.playlistId)&&xa.push("list="+La);(V=V.startTimeSeconds)&&xa.push("t="+V);return"/watch?"+xa.join("&")}}
function f(V){if(!V)return null;var xa=V.simpleText;return xa?xa:V.runs?g.Mm(V.runs,function(La){return La.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,q=null,t=null,u=null,v=!1,y=null,z=null,C=null,G=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,q=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(v=u3(l,"browseEndpoint","browseId"))u=v,m="/channel/"+u;n=!1;p="new";(v=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((C=u3(l,"urlEndpoint","url"))&&(m=C),n=!0,p="new",C=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=u3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=u3(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,U="";if(b.metadata){var K=f(b.metadata);K&&(U=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:U,callToAction:f(b.callToAction),WJ:b.image,
iconUrl:C,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:q,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:v,targetUrl:m||null,LS:n,sessionData:J?{itct:J}:null,uX:p,Hu:a?a:null,OS:b.isPlaceholder,impressionUrls:D3(b.impressionUrls||[],C3),CS:D3(b.hovercardShowUrls||[],C3),clickUrls:D3(l.loggingUrls||[],C3),visualElement:g.Zx(b.trackingParams),
productPrice:G,additionalFeesText:F}},E3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:D3(a.impressionUrls||[],C3),elements:D3(a.elements||[],function(d,e){return PPa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Zx(a.trackingParams));return c},F3=function(a){g.LM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.DE(a)||g.HE(a);this.events=new g.WC(this);g.H(this,this.events);this.events.T(this.player,g.cz("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.dz("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.xb);this.events.T(window,"focus",this.wW);this.load();var b=g.Ng("STYLE");(g.zg("HEAD")[0]||document.body).appendChild(b);g.he(this,function(){g.Rg(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},QPa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},G3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},RPa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=E3(f,QPa(a))));H3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.bq;d&&(c.postParams={ad_tracking:d});if(b=g.Oqa(b))if(b=g.Hf(b),b=g.Df(b))a.B=g.Yt(b,c)},H3=function(a,b,c){c=void 0===c?!0:c;
a.player.Xe("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&SPa(a);c=[];d=new g.az(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.X({G:"div",L:"ytp-ce-shadow"}),g.yM(a.player,a.u.element,4),a.C=new g.hL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=TPa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.yM(a.player,f.element,4);var h=new g.az(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);UPa(a,
f,e)}else g.ky(new g.iw("buildEndscreenElement null",e))}a.player.Dd(c);a.xb()}},SPa=function(a){var b=g.by(),c=g.cy();
c&&b&&a.endscreen.visualElement&&g.oy(void 0,c,b,[a.endscreen.visualElement])},TPa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Hu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-video-title"].concat(g.la(c)),W:{dir:g.Fr(b.title||
"")},ya:b.title},{G:"div",L:"ytp-ce-video-duration",ya:b.videoDuration||void 0}]}]};c=new g.X(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ga:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Hu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:I3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:J3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ga:["ytp-ce-playlist-title"].concat(g.la(c)),W:{dir:g.Fr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={G:"div",Ga:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Hu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ga:["ytp-ce-channel-title","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Fr(b.title||"")},ya:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{G:"div",Ga:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)}]};c=new g.X(c);var d=g.Ag(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.ON(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ga:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Hu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Fr(b.title||"")},ya:b.title},{G:"div",L:"ytp-ce-website-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-website-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:VPa(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={G:"div",Ga:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Hu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Fr(b.title||"")},ya:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",ya:b.metadata},{G:"a",Ga:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:J3(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:I3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",ya:b.callToAction||void 0}]}]},c=new g.X(a)}b.OS&&g.L(c.element,"ytp-ce-placeholder");return c},I3=function(a){if(a.WJ)var b=a.WJ.thumbnails;
return VPa(b?b[b.length-1].url:null)},VPa=function(a){return a?{style:"background-image: url("+a+")"}:{}},UPa=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.L(b.element,"ytp-ce-force-expand"),K3(a,c.id,!0)):(g.kr(b.element,"ytp-ce-force-expand"),g.kr(b.element,"ytp-ce-element-hover"),K3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){L3(a,b,c)});
b.Qa("mouseleave",function(){M3(a,b,c)});
a.player.V().isMobile||b.Qa("click",function(){g.L(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){WPa(a,c,m)});
b.Qa("keypress",function(m){WPa(a,c,m)});
b.Qa("focus",function(){L3(a,b,c)});
b.Qa("blur",function(){M3(a,b,c)});
b.Qa("touchstart",function(){L3(a,b,c)});
var l=g.Cg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.kr(b.element,"ytp-ce-element-hover");g.kr(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Cg("ytp-sb-subscribe",b.element));d(g.Cg("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},WPa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.ir(d,"ytp-ce-element");){g.ir(d,"subscribe-label")&&N3(a,b);
if(g.ir(d,"ytp-ce-channel-subscribe"))return;d=g.Sg(d)}if(!d||g.ir(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])M3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.uX)N3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hf(J3(a,b.targetUrl)),c=g.Df(c),g.HL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=J3(a,b.targetUrl),l=b.sessionData,m=g.gt(h);e&&m&&(m.v||m.list)?a.player.Oj(m.v,l,m.list,!1):
g.GL(h,l)};
N3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.fF(a)+b}else return"";return b},L3=function(a,b,c){g.ir(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.L(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.I(function(){g.L(b.element,"ytp-ce-element-hover")},200)).start():g.L(b.element,"ytp-ce-element-hover"),O3(a,c.CS),K3(a,c.id,!0))},M3=function(a,b,c){g.kr(b.element,"ytp-ce-element-hover");
g.kr(b.element,"ytp-ce-force-expand");K3(a,c.id,!1)},K3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.M(a.i[e].element,"ytp-ce-element-shadow-show",c)},O3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G3(a))c&&c();else{b=XPa(a,b);var e=0,f=!1,h=new g.I(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.wv(b[a],d)}},N3=function(a,b,c){O3(a,b.clickUrls,c);
(a=g.cy())&&b.LS&&g.uy(a,b.visualElement)},XPa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(YPa(b[d],c));return a},YPa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},ZPa=function(a){return"string"===typeof a?a:""},P3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},$Pa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},Q3=function(a){return a.value?a.value:null},R3=function(a){if(!a)return null;
var b=g.Hf(ZPa(a.value));b=g.Df(b);if(!b)return null;var c=P3(a.target,aQa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new $Pa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},bQa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},eQa=function(a){if(!a)return null;
var b=P3(a.type,cQa),c=P3(a.trigger,dQa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=R3(a?a:null);return b?new bQa(b,c,a):null},fQa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},hQa=function(a){return(a=gQa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},gQa=function(a,b){return g.Mb(a.action,b,void 0)},iQa=function(a,b){this.context=a;
this.i=b},T3=function(a){return a.customMessage?S3("div","iv-card-message",a.customMessage):""},U3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},V3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(S3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},S3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Fr(c);return{G:a,W:b,ya:c}},jQa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.oy&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.oy+");");c.dir=g.Fr(a.customMessage);var d=[{G:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ga:b,W:c,U:d}},W3=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},kQa=function(a,b){this.merchant=a;
this.price=b},lQa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},mQa=function(a,b){return b?b:lQa(a)?"current":"new"},X3=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.bb=!1;this.Sa=new Map;this.Va=new Map;this.context.J.addEventListener(g.cz("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.dz("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},Y3=function(a,b,c,d,e,f,h){a.context.i.Qa(b,"click",function(l){a.gC(c,d,e,f||[],h||0,l)});
a.context.i.Qa(b,"touchstart",function(){a.bb=!1});
a.context.i.Qa(b,"touchmove",function(){a.bb=!0})},nQa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},Z3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
iB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},b4=function(a,b,c){X3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ka=this.rb=this.B=this.isInitialized=!1;this.va=null;this.cards=[];this.kb=this.S=this.Ha=this.D=this.La=this.i=null;this.Z=[];this.K=this.Be=this.Ba=null;this.I=0;this.Aa=new g.I(g.Ia,c.Y.Vd?4E3:3E3);g.H(this,this.Aa);this.Za=new g.I(g.Ia);g.H(this,this.Za);this.oa=new iQa(c,function(e,f,h,l,m,n){Y3(d,e,f,h,l,m,n)});
this.X=new g.X({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ga:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Masquer les fiches",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.X);this.C=this.X.element;this.Wa=new g.hL(this.X,330);g.H(this,this.Wa);this.jb=g.Cg("iv-drawer-header-text",this.C);this.u=g.Cg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.rb&&$3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.rb=d.B)&&a4(d)})},oQa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){$3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){a4(a)});
var c=b.headerText;g.Ug(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.Zx(b.trackingParams);a.K=g.Zx(b.closeTrackingParams);a.Be=g.Zx(b.iconTrackingParams)},pQa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.Sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.command),Gl:d.trackingParams?g.Zx(d.trackingParams):null,Ti:e.trackingParams?
g.Zx(e.trackingParams):null,Be:f&&f.trackingParams?g.Zx(f.trackingParams):null,imageUrl:d4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Sz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,oy:null,title:d.title?g.Sz(d.title):"",customMessage:d.callToAction?g.Sz(d.callToAction):"",url:d.command.urlEndpoint.url?R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};e4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.Sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.endpoint),Gl:d.trackingParams?g.Zx(d.trackingParams):null,Ti:e.trackingParams?g.Zx(e.trackingParams):null,Be:f&&f.trackingParams?
g.Zx(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Sz(d.customText):null,profileImageUrl:d4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Sz(d.channelName):"",metaInfo:[d.subscriberCountText?g.Sz(d.subscriberCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
e4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.Sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Gl:d.trackingParams?g.Zx(d.trackingParams):
null,Ti:e.trackingParams?g.Zx(e.trackingParams):null,Be:f&&f.trackingParams?g.Zx(f.trackingParams):null,xx:d4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Sz(d.customMessage):null,playlistVideoCount:g.Sz(d.playlistVideoCount),title:d.playlistTitle?g.Sz(d.playlistTitle):"",metaInfo:[d.channelName?g.Sz(d.channelName):"",d.videoCountText?g.Sz(d.videoCountText):""],url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:nQa(d.action)})};e4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.Sz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:c4(a,c,b,d),sponsored:!1,tracking:Z3(d,e,d.action),Gl:d.trackingParams?g.Zx(d.trackingParams):null,Ti:e.trackingParams?g.Zx(e.trackingParams):null,Be:f&&f.trackingParams?g.Zx(f.trackingParams):
null,xx:d4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Sz(d.lengthString):null,customMessage:d.customMessage?g.Sz(d.customMessage):null,title:d.videoTitle?g.Sz(d.videoTitle):"",metaInfo:[d.channelName?g.Sz(d.channelName):"",d.viewCountText?g.Sz(d.viewCountText):""],isLiveNow:!!d.badge,url:R3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:nQa(d.action)})};e4(a,b)}a.I++},d4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},c4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},rQa=function(a,b){if(b=qQa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.Rg(b.fD),g.Ub(a.cards,b),a.qy(),f4(a)},$3=function(a,b,c){if(!a.B){a.Wa.show();
a.La=new g.I(function(){g.L(a.context.J.getRootNode(),g.jT.IV_DRAWER_OPEN)},0);
a.La.start();a.va=g.Wu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.cy();d&&a.Ba&&a.K&&g.sy(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.IL||(f.IL=!0,sQa(a.context.logger,f.card.tracking.impression,b)),d&&g.sy(d,[f.card.Gl]);t3(a.J);c&&(a.D=new g.I(function(){a.Ha=a.S;a.kb.focus()},330),a.D.start())}},a4=function(a){a.B&&(a.Wa.hide(),g.Xu(a.va),a.va=null,g.kr(a.context.J.getRootNode(),g.jT.IV_DRAWER_OPEN),a.B=!1,t3(a.J),a.D&&a.D.stop(),a.D=new g.I(function(){a.Ha&&(a.Ha.focus(),a.Ha=null)},330),a.D.start())},
uQa=function(a){g.jr(a.element,[g.jT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.yM(a.J,a.C,5);tQa(a);a.S=g.Cg("ytp-cards-button",a.J.getRootNode());a.kb=g.Cg("iv-drawer-close-button",a.C);a.isInitialized=!0},tQa=function(a){var b=g.Cg("iv-drawer-close-button",a.C);
a.context.i.Qa(b,"click",a.pR,a);a.context.i.Qa(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Qa(a.u,"scroll",a.BR,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.ir(a.J.getRootNode(),"ytp-autohide")});
a.Z.push(g.Dv("iv-button-shown",a.US,a));a.Z.push(g.Dv("iv-button-hidden",a.SS,a));a.Z.push(g.Dv("iv-teaser-shown",a.UP,a));a.Z.push(g.Dv("iv-teaser-hidden",a.VS,a));a.Z.push(g.Dv("iv-teaser-clicked",a.TP,a))},e4=function(a,b){a.isInitialized||uQa(a);
rQa(a,b.id);var c=vQa(a,b);if(c){var d={card:b,fD:c.element,IL:!1},e=wQa(a,d);g.$b(a.cards,e,0,d);c.Ea(a.u,e);a.qy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,f4(a),xQa(a,d),$3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&yQa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){yQa(a,d)}),f4(a))}},vQa=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=jQa(b);c={G:"div",Ga:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?Q3(b.url)||"":""},U:[U3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[S3("h2",void 0,b.title),d]}]}]};c=new g.X(c);W3(a,g.Bg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={G:"div",Ga:["iv-card","iv-card-channel"],U:[{G:"a",Ga:["iv-click-target"],W:{href:Q3(b.url)||"","data-ytid":b.channelId},U:[U3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[T3(b),{G:"h2",L:"iv-card-primary-link",ya:b.title},V3(b)]}]}]},c=new g.X(c),W3(a,g.Bg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={G:"div",Ga:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:Q3(b.url)||""},U:[U3(b.xx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b)]}]}]},c=new g.X(c),
W3(a,g.Bg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Rb(b.offers);c=["iv-card"];d="";var f=jQa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",ya:f.merchant}),f={G:"div",U:e});e=b.url?Q3(b.url)||"":"";c={G:"div",Ga:c,W:{tabindex:"0"},U:[{G:"a",Ga:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Lien commercial",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",ya:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[S3("h2",d,b.title),f]}]}]};c=new g.X(c);d=g.Ng("span");g.Ug(d,"Vous voyez ce produit, car nous pensons qu'il est pertinent pour la vid\u00e9o. Il se peut que le marchand r\u00e9mun\u00e8re Google.");
c.md(d,"adInfo");W3(a,g.Bg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",ya:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ga:["yt-badge","yt-badge-live"],ya:"EN DIRECT MAINTENANT"}:null,e={G:"div",Ga:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:Q3(c))||""},U:[U3(b.xx,d),{G:"div",L:"iv-card-content",U:[T3(b),S3("h2","iv-card-primary-link",b.title),V3(b),f]}]}]},
c=new g.X(e),W3(a,g.Bg("iv-click-target",c.element),b,b.url),c;default:return null}},wQa=function(a,b){if(0===a.cards.length)return 0;
a=g.Nb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},zQa=function(a){return a.i?"productListing"===a.i.card.type:g.Nm(a.cards,function(b){return"productListing"===b.card.type})},f4=function(a){g.M(a.J.getRootNode(),"ytp-cards-shopping-active",zQa(a))},yQa=function(a,b){if(!g.ir(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.cy(),d=a.i?a.i.card.Be:a.Be;
c&&d&&g.ty(c,[d]);a.i=b;f4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.Bt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&xQa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
xQa=function(a,b){a.X.yb?(b=new y3([0,
a.u.scrollTop],[0,b.fD.offsetTop],600,JPa),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.yK(a.X,!0),a.u.scrollTop=b.fD.offsetTop,g.yK(a.X,!1))},g4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},qQa=function(a,b){return g.Mb(a.cards,function(c){return c.card.id===b})},h4=function(a,b,c){X3.call(this,a,b);
this.annotation=c;this.isActive=!1},AQa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},i4=function(a,b,c){h4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},BQa=function(a,b){var c=void 0===c?0:c;
var d=HPa(b).width;g.mm(b,d);c=new A3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,IPa);g.H(a,c);a.context.B.Qa(c,"begin",function(){g.vm(b,!0)});
c.play()},EQa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ga:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({G:"div",Ga:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.ON(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Ea(d));var f=a.createElement({G:"div",Ga:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ga:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.vm(h,!1);var l=a.createElement({G:"div",Ga:["branding-context-container-outer"]});l.appendChild(h);g.fm(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.I(function(){CQa(a,h,l)},500);
g.H(a,a.B);a.context.i.Qa(a.element,"mouseover",function(){DQa(a,h,l,f,b.image_height)});
a.context.i.Qa(a.element,"mouseout",function(){a.B.start()})}},DQa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.um(b);a.i||(b.style.width=g.lm(f.width,!0),c.style.width=g.lm(f.width,!0));g.fm(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.fm(d,"right","1px");a.C=!0;g.vm(b,!0);a.D=new g.I(function(){g.L(this.element,"iv-branding-active")},0,a);
a.D.start()}},CQa=function(a,b,c){g.kr(a.element,"iv-branding-active");
a.I=new g.I(function(){g.vm(b,!1);a.i||(c.style.width=g.lm(0,!0))},250);
a.I.start();a.C=!1},FQa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},j4=function(a,b,c){h4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ga:["iv-promo-contents"]});this.D=new g.I(function(){d.i.setAttribute("aria-hidden","true");g.vm(d.B,!1);g.vm(d.u,!0)},700,this);
g.H(this,this.D)},GQa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=hQa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ga:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&Y3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.ag(f,Q3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
ya:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ga:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ga:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",ya:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Y3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.i,
"iv-click-target");e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",ya:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ga:["yt-badge","iv-promo-badge-live"],ya:"EN DIRECT MAINTENANT"})),g.L(a.i,"iv-click-target"),e&&Y3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);
p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ga:["iv-promo-expand","ytp-button"]});a.u.title="Agrandir";a.context.i.Qa(a.u,"click",function(q){k4(a,5E3,q)});
c.appendChild(a.u);g.vm(a.u,!1);a.context.i.Qa(a.element,"mouseover",a.iS,a);a.context.i.Qa(a.element,"mouseout",a.hS,a);a.context.i.Qa(a.element,"touchend",function(q){k4(a,5E3,q)});
a.B=a.createElement({G:"button",Ga:["iv-promo-close","ytp-button"]});a.B.title="Fermer";a.context.i.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.dS:a.cS,a);c.appendChild(a.B);g.jr(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},k4=function(a,b,c){c.stopPropagation();
HQa(a);IQa(a,b);a.i.focus()},JQa=function(a){a.isCollapsed||a.S||a.C||(g.L(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},HQa=function(a){a.D.stop();
a.isCollapsed&&(g.lr(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.vm(a.u,!1),g.vm(a.B,!0))},IQa=function(a,b){a.C||(a.C=g.Hh(function(){l4(this);
JQa(this)},b,a))},l4=function(a){a.C&&(g.B.clearTimeout(a.C),a.C=null)},KQa=function(a){this.J=a},sQa=function(a,b,c){b&&(c?m4(a,b.map(function(d){return g.Tq(d,c)})):m4(a,b))},m4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.wv(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},n4=function(a){g.LM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.I={};this.logger=new KQa(this.player);this.C=new g.WC(this);this.D=this.bl=null;this.events=new g.WC(this);this.K=this.i=null;this.X=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.VP,this);this.subscribe("resize",this.lA,this);this.player.V().S.subscribe("vast_info_card_add",this.VM,this);g.H(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.X({G:"div",Ga:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.yM(this.player,this.u.element,4);this.u.hide();this.B=new g.X({G:"div",Ga:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Fq()&&this.load();var c=this.createElement({G:"style"});(g.zg("HEAD")[0]||document.body).appendChild(c);g.he(this,function(){g.Rg(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},LQa=function(a){a=a.createElement({G:"div",
Ga:["annotation","annotation-type-custom"]});g.vm(a,!1);return a},MQa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.yK(a.u,b);g.yK(a.B,b)},NQa=function(a,b,c){a.S=!0;
a.D=g.Yt(b,c)},OQa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(OQa(a,e))}return c},RQa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Pt(h)&&h.responseXML?h.responseXML:null)&&o4(a,h)}};
g.mv()&&(d.onFinish=PQa(a,d.onFinish));d.postParams={ic_only:"1"};QQa(d,c);a.S=!0;g.Yt(b.Va,d)}}},QQa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Qu&&(a.postParams.ic_coll=b.Qu);b.yy&&(a.postParams.ic_xml=b.yy);b.Ax&&(a.postParams.ic_track=b.Ax)},SQa=function(a){var b=new g.X({G:"div"});
g.vm(b.element,!1);var c=new b4(a.player,b.element,p4(a));g.H(c,b);b.Ea(a.u.element);c.gx();return c},p4=function(a){if(!a.K){var b=new B3(a);
g.H(a,b);var c=new g.Pk(a);g.H(a,c);a.K=new FQa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Vd)}return a.K},o4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.cy();if(e){var f=g.by();f&&g.oy(void 0,e,f,[g.Zx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=OQa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=P3(f.type,TQa),p=P3(f.style,UQa),q=ZPa(f.data),t=0!==q.length?JSON.parse(q):{};var u=f.action;f=eQa;if(null==u)var v=null;else if(g.Ma(u)){l=[];for(var y=g.r(u),z=y.next();!z.done;z=y.next()){var C=f(z.value);
C&&l.push(C)}v=l}else{var G=f(u);v=G?[G]:[]}e=m&&n?new fQa(m,n,p,v,t):null}else e=null}catch(xa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=LQa(f),J=null;switch(l.type){case "branding":if(f.player.V().Db)break;f.u.element.appendChild(F);J=new i4(F,p4(f),l);break;case "promotion":g.yM(f.player,F,4),J=new j4(F,p4(f),l)}J&&J.gx();if(f=J)g.H(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=SQa(a),g.H(a,a.i));if("card"===e.type){c=a.i;var U=e&&e.data&&e.data.card_type;
f=e.data;if(U)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,cO:l.teaser_impression,iB:l.teaser_click},F=f.tracking_params||{},J=null,U){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.Zx(F.card):null,Ti:F.teaser?g.Zx(F.teaser):null,Be:F.icon?g.Zx(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.Zx(F.card):
null,Ti:F.teaser?g.Zx(F.teaser):null,Be:F.icon?g.Zx(F.icon):null,xx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "productListing":f.signin_url&&(J=R3({target:"current",value:f.signin_url}));U=[];for(var K=f.offers||[],V=0;V<K.length;V++)U.push(new kQa(g.pg(K[V].merchant),g.pg(K[V].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.Zx(F.card):null,Ti:F.teaser?g.Zx(F.teaser):null,Be:F.icon?g.Zx(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,oy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),lda:J,kda:f.signin_title?f.signin_title:void 0,jda:f.signin_message?f.signin_message:void 0,offers:U};e4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.Zx(F.card):null,Ti:F.teaser?g.Zx(F.teaser):
null,Be:F.icon?g.Zx(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,oy:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};e4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Gl:F.card?g.Zx(F.card):null,Ti:F.teaser?g.Zx(F.teaser):null,Be:F.icon?g.Zx(F.icon):null,xx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:R3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},e4(c,e)}}else oQa(a.i,e);c=!0}}c&&(t3(a.player),a.lA())},VQa=function(a,b){var c=!1;
a.i||(a.i=SQa(a),g.H(a,a.i));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(pQa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Sz(b.headerText):"",g.Ug(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.Zx(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Zx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Be=b.icon.infoCardIconRenderer.trackingParams?
g.Zx(b.icon.infoCardIconRenderer.trackingParams):null,t3(a.player),a.lA())},WQa=function(a,b,c,d,e){if(!a.player.V().Db){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new bQa("openUrl","click",new $Pa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Sz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Sz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Sz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Sz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Sz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Sz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new fQa(c,"branding","branding",f,d);l=LQa(a);a.u.element.appendChild(l);f=new i4(l,p4(a),f);f.gx();g.H(f,f);a.I[c]=f}},PQa=function(a,b){return function(){var c=g.Ba.apply(0,arguments);
a.isDisposed()||a.X.push(g.tv.Of(function(){b.apply(null,g.la(c))}))}},XQa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.rM.prototype.Bt=g.ca(17,function(a,b){var c=g.$M(this.tb());c&&c.Bt(a,b)});
var v3={},w3=null;g.Ta(y3,g.vr);g.k=y3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Ec())return!1;x3(this);this.startTime=a=g.Sa();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.hA();this.oi("play");-1==this.i&&this.oi("resume");this.i=1;var b=g.Pa(this);b in v3||(v3[b]=this);LPa();MPa(this,a);return!0};
g.k.stop=function(a){x3(this);this.i=0;a&&(this.progress=1);NPa(this,this.progress);this.oi("stop");this.Cw()};
g.k.pause=function(){this.Ec()&&(x3(this),this.i=-1,this.oi("pause"))};
g.k.xa=function(){0==this.i||this.stop(!1);this.oi("destroy");y3.ge.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.fC=function(){this.oi("animate")};
g.k.oi=function(a){this.dispatchEvent(new OPa(a,this))};
g.Ta(OPa,g.ie);g.Ta(z3,y3);z3.prototype.C=g.Ia;z3.prototype.fC=function(){this.C();z3.ge.fC.call(this)};
z3.prototype.Cw=function(){this.C();z3.ge.Cw.call(this)};
z3.prototype.hA=function(){this.C();z3.ge.hA.call(this)};
g.Ta(A3,z3);A3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(B3,g.E);B3.prototype.Qa=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.Wu(a,b,c);this.i.push(a);return a};
B3.prototype.Pz=function(a,b,c,d){c=(0,g.D)(c,d||this.u);a=g.ev(a,b,c);this.i.push(a);return a};
B3.prototype.pc=function(a){g.Xu(a);g.Ub(this.i,a)};
B3.prototype.xa=function(){g.Xu(this.i);this.i.length=0;g.E.prototype.xa.call(this)};g.w(F3,g.LM);g.k=F3.prototype;g.k.load=function(){g.LM.prototype.load.call(this);if(!G3(this)){var a=g.Pqa(this.player.getVideoData());a?(a=E3(a,QPa(this)),H3(this,a,!1)):RPa(this)}};
g.k.unload=function(){H3(this,null);this.B&&(this.B.abort(),this.B=null);g.LM.prototype.unload.call(this)};
g.k.jf=function(a,b){return G3(this)?"loadCustomEndscreenRenderer"===a?(a=E3(b,"new"),H3(this,a),!0):null:null};
g.k.getOptions=function(){return G3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<YQa.length;f++){var h=Math.abs(b.width-YQa[f]);if(-1===e||d>=h)e=f,d=h}d=ZQa[e];this.u&&g.fm(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.tm(e.element,Math.round(h.width*a.width),f);g.mm(e.element,m,n);g.lr(e.element,$Qa);m=h.left+h.width/2;h=h.top+l/2;g.L(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.lr(e.element,ZQa);g.L(e.element,d);(e=g.Ag(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.fm(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())O3(this,this.endscreen.impressionUrls),(a=g.cy())&&this.endscreen.visualElement&&g.py(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");O3(this,c.impressionUrls);(b=g.cy())&&g.py(b,c.visualElement,void 0);this.player.V().u&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.kr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.kr(b,"ytp-ce-shown");this.player.V().u&&this.player.Na("endscreenelementhidden",a)}};
g.k.wW=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c=g.r(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.lr(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var YQa=[346,426,470,506,570,640,853,1280,1920],ZQa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),$Qa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var aQa={I1:"current",Q7:"new"};var cQa={CLOSE:"close",j8:"openUrl",SUBSCRIBE:"subscribe"},dQa={LZ:"click",CLOSE:"close",m3:"hidden",I9:"rollOut",J9:"rollOver",A$:"shown"};var UQa={LY:"anchored",PO:"branding",CHANNEL:"channel",H1:"cta",q3:"highlightText",E4:"label",PLAYLIST:"playlist",c9:"popup",J$:"speech",SUBSCRIBE:"subscribe",baa:"title",VIDEO:"video",Hba:"website"},TQa={PO:"branding",yZ:"card",X1:"drawer",o3:"highlight",g6:"marker",m9:"promotion",TEXT:"text",fca:"widget"};g.w(X3,g.E);g.k=X3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.az(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Va.set(a,e);this.context.J.Dd([a])};
g.k.gx=function(){this.context.u.subscribe("resize",this.qy,this)};
g.k.gC=function(a,b,c,d,e,f){if(this.bb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Rg(this.element)};
g.k.qy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=Q3(a);if(f){var h=mQa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.gt(f||"");m&&n&&(n.v||n.list)?e.context.J.Oj(n.v,b,n.list,!1):g.HL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);m4(this.context.logger,c,l,d);lQa(f)||(c=g.cy(),d=b.itct,c&&d&&g.uy(c,g.Zx(d)))}};
g.k.xa=function(){this.Sa.clear();this.Va.clear();g.E.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.w(b4,X3);g.k=b4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.um(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.qy=function(){var a=this.isAvailable();g.vm(this.element,a);g.M(this.context.J.getRootNode(),g.jT.IV_DRAWER_ENABLED,a);t3(this.J)};
g.k.destroy=function(){this.J.Bt(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.Ev(this.Z);g.Xu(this.va);this.La&&this.La.dispose();this.D&&this.D.dispose();X3.prototype.destroy.call(this)};
g.k.pR=function(){if(this.B){m4(this.context.logger,g4(this).tracking.close);var a=g.cy();a&&this.K&&g.uy(a,this.K);a4(this)}};
g.k.BR=function(){g.M(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.US=function(){var a=g.cy(),b=g4(this);b=b?b.Be:this.Be;a&&b&&g.sy(a,[b])};
g.k.SS=function(){var a=g.cy(),b=g4(this);b=b?b.Be:this.Be;a&&b&&g.ty(a,[b])};
g.k.UP=function(){var a=g4(this);m4(this.context.logger,a.tracking.cO);var b=g.cy();b&&a&&g.sy(b,[a.Ti,a.Be])};
g.k.VS=function(){var a=g.cy(),b=g4(this);a&&b&&g.ty(a,[b.Ti])};
g.k.TP=function(a){var b=g4(this),c=g.cy();this.i?a?(a=this.context.logger,m4(a,b.tracking.iB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ti&&g.uy(c,b.Ti)):(a=this.context.logger,m4(a,b.tracking.iB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Be&&g.uy(c,b.Be)):(a=this.context.logger,m4(a,b.tracking.iB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Be&&g.uy(c,this.Be))};g.w(h4,X3);h4.prototype.gx=function(){X3.prototype.gx.call(this);AQa(this)};
h4.prototype.show=function(){X3.prototype.show.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.sy(a,[g.Zx(b.itct)])};
h4.prototype.hide=function(){X3.prototype.hide.call(this);var a=g.cy(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ty(a,[g.Zx(b.itct)])};g.w(i4,h4);
i4.prototype.show=function(){if(!this.isActive){h4.prototype.show.call(this);if(!this.K){g.L(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ga:["branding-img","iv-click-target"],W:{"aria-label":"Filigrane de cha\u00eene",src:a.image_url,width:a.image_width,height:a.image_height}});g.vm(this.u,!1);var b=this.createElement({G:"div",Ga:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=hQa(this.annotation))&&Y3(this,this.u,b,this.annotation.id,
a.session_data);EQa(this,a);this.K=!0}g.vm(this.element,!0);this.isActive=!0;this.u&&BQa(this,this.u)}};
i4.prototype.hide=function(){this.isActive&&(h4.prototype.hide.call(this),g.vm(this.element,!1),this.isActive=!1)};
i4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);h4.prototype.destroy.call(this)};g.w(j4,h4);g.k=j4.prototype;g.k.show=function(){this.isActive||(h4.prototype.show.call(this),this.X||(GQa(this),this.X=!0),g.vm(this.element,!0),g.Hh(function(){g.kr(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,l4(this),HQa(this),IQa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.L(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.gC=function(a,b,c,d,e,f){return this.isCollapsed?!1:h4.prototype.gC.call(this,a,b,c,d,e,f)};
g.k.iS=function(a){this.S=!0;k4(this,500,a)};
g.k.hS=function(){this.S=!1;JQa(this)};
g.k.cS=function(a){a.stopPropagation();this.hide()};
g.k.dS=function(a){a.stopPropagation();l4(this);this.isCollapsed=!0;g.L(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();h4.prototype.destroy.call(this)};g.w(n4,g.LM);g.k=n4.prototype;g.k.jf=function(a,b){if(!XQa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.T1(b))&&o4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(rQa(this.i,b),t3(this.player)),!0}return null};
g.k.getOptions=function(){return XQa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Fq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.qL||a.S.get(b.videoId)||g.tG(b)||g.uG(b)?!0:!1};
g.k.lA=function(){if(this.B){var a=this.player.eb().getVideoContentRect(!0);g.tm(this.B.element,a.width,a.height);g.mm(this.B.element,a.left,a.top)}if(this.i){var b=this.player.nj();a=this.i;b=b.width;g.M(a.C,"iv-drawer-small",426>=b);g.M(a.C,"iv-drawer-big",1280<=b)}};
g.k.VP=function(a){MQa(this,a.state);g.T(a.state,2)&&(this.Bh()&&this.qk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Bt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Pt(h)&&h.responseXML?h.responseXML:null)&&(o4(b,h),g.L(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.LM.prototype.load.call(this);MQa(this,this.player.zb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.mv()&&(a=PQa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&QQa(e,f);f=f&&(f.yy||f.Qu);if(!c.Bl||f)c.Va?NQa(this,c.Va,e):(this.bl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.bl));
g.yM(this.player,this.B.element,4);this.lA();(f=g.tG(c))&&VQa(this,f);(f=g.uG(c))&&f.featuredChannel&&WQa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.bl&&(this.player.removeEventListener("videodatachange",this.bl),this.bl=null),NQa(this,b.Va,a))};
g.k.unload=function(){this.player.Xe("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,t3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.I={};this.u.hide();g.LM.prototype.unload.call(this);this.B.detach();this.bl&&(this.player.removeEventListener("videodatachange",this.bl),this.bl=null)};
g.k.VM=function(a){a===this.player.getVideoData().videoId&&(this.loaded?RQa(this):this.load())};
g.k.Bh=function(){return!!this.i&&this.i.isAvailable()};
g.k.qk=function(){this.Bh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Bh();this.i&&(a?c?$3(this.i,c,b):$3(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):a4(this.i))};
g.k.Bt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.VM,this);g.kr(this.player.getRootNode(),g.jT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.tv.gi(a[b]);this.X.length=0;g.LM.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.KM("annotations_module",n4);g.KM("creatorendscreen",F3);})(_yt_player);
