(function(g){var window=this;var A3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Ws(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},B3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},Ata=function(a,b){var c=new g.Vs;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},Bta=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];
if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else if(239<e&&365>e){f=a[c++];var k=a[c++],l=a[c++];e=((e&7)<<18|(f&63)<<12|(k&63)<<6|l&63)-65536;b[d++]=String.fromCharCode(55296+(e>>10));b[d++]=String.fromCharCode(56320+(e&1023))}else f=a[c++],k=a[c++],b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|k&63)}return b.join("")},Cta=function(){this.u=[];
this.o=[]},C3=function(a,b){return b?a.o.concat(a.u):a.o},D3=function(a,b){switch(b.kind){case "asr":Dta(b,a.u);
break;default:Dta(b,a.o)}},Dta=function(a,b){g.Za(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},E3=function(){g.A.call(this);
this.u=new Cta;this.B=[]},F3=function(a,b,c){E3.call(this,a);
this.o=null;this.B=b.lw;this.w=c},G3=function(){this.segments=[]},Eta=function(a,b){var c=g.qb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.eb(a.segments,c),g.eb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.nb(a.segments,c,0,b),g.nb(a.segments,c+1,0,b)))},H3=function(a,b,c,d,e,f){g.A.call(this);
this.policy=a;this.player=b;this.J=c;this.C=d;this.B=e;this.G=f;this.I=this.player.N();this.A=new G3;this.u=this.w=this.o=null;this.F=new g.H(this.qy,1E3,this);this.events=new g.O(this);g.C(this,this.F);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.YA);this.YA();this.qy()},Fta=function(a,b){var c=g.hw(b,a.policy,{}).oc(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.u=g.mr(c,d,3,100).then(function(e){a.ga();var f=!(a.B?e.response:e.responseText)||400<=e.status,k=g.Hw(e);k?(e=g.hw(a.w,a.policy,{}),f=a.w,g.dw(f.u,e,k),f.requestId=e.get("req_id"),Fta(a,a.w)):(f||null===a.C||(k=a.w.o[0],a.B?a.C(e.response,1E3*(k.startTime+a.player.Db())):a.C(e.responseText,1E3*(k.startTime+a.player.Db()))),a.w=null,a.u=null)});
a.w=b;Eta(a.A,a.w.o[0].u)},I3=function(a,b){E3.call(this,b.N());
this.o=a;this.F=b;this.w=null;this.A=!1;this.C=g.jz(this.F.N())&&!this.o.u},Gta=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.qL(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Vs({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Hta=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},Ita=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.qL(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},J3=function(a,b,c,d,e){E3.call(this,e||null);
c=c||g.qq(a).hl||"";c=c.split("_").join("-");this.A=g.sq(a,{hl:c});this.w=b;this.C=!!d;this.F={};this.o=null},K3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.mD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.u=f;this.o=k},L3=function(a,b,c,d,e){g.mD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Jta=function(a){a=void 0===a?{}:a;
var b="_"+M3++;return new L3(0,0x8000000000000,0,b,a)},N3=function(a,b,c,d,e,f,k){var l={};
g.Ta(l,b);g.Ta(l,a.params);g.Ta(l,c);var m={};g.Ta(m,b.Bb);a.params.Bb&&g.Ta(m,a.params.Bb);g.Ta(m,c.Bb);l.Bb=m;g.Q.call(this,{D:"div",H:"caption-window",O:{id:"caption-window-"+a.id,dir:1===l.Rc?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",H:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.T=!1;this.w=a;this.Y=this.U=null;this.Oa=e;this.Ja=f;this.Ha=k;this.F=null;this.ca=.96*e;this.xa=.96*f;this.u=l;this.Ga=c;this.B=this.o["captions-text"];
this.Aa=null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.ha=this.aa*Kta(m);a=new g.Pr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.tI,this);a.subscribe("dragmove",this.sI,this);a.subscribe("dragend",this.rI,this);this.sa=this.na=0;b="";this.u.windowOpacity&&(a=g.C1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+")");a={"background-color":b,display:!1===this.u.isVisible?"none":
"","text-align":Lta[this.u.textAlign]};this.Aa&&(a["border-radius"]=b?this.ha/8+"px":"");if(this.A=2===this.w.params.Rc||3===this.w.params.Rc)b=this.element,c="vertical-rl",1===this.u.Ku&&(c="vertical-lr"),g.je&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.vh(b,"-o-writing-mode",c),g.vh(b,"-webkit-writing-mode",c),g.vh(b,"writing-mode",c),g.vh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.w.params.Rc&&(g.vh(b,"text-orientation",""),g.vh(b,"transform","rotate(180deg)"));g.vh(this.element,
a);switch(this.u.ag){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},Kta=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Mta=function(a,b){var c={},d=b.background?b.background:a.u.Bb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Bb.backgroundOpacity;d=g.C1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ha/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*Kta(b)+"px";d=1;e=b.color||a.u.Bb.color;if(b.color||null!=b.textOpacity)e=g.C1(e),d=null==b.textOpacity?a.u.Bb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.er&&(k=e=b.er);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.fl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Bb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ve&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.QF&&(c.visibility="hidden");1===b.Ox&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.lz||g.mz,3===a.w.params.Rc?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.gf||2===b.gf||3===b.gf||4===b.gf||5===b.gf)if(g.lz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.gf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Nta=function(a){a.F=g.qe("SPAN");
g.vh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},Ota=function(a,b){var c=g.qe("SPAN");
g.vh(c,{display:"inline-block","white-space":"pre-wrap"});g.vh(c,Mta(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.vh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.vh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Pta=function(a,b,c){a.T=a.T||!!c;
var d={};g.Ta(d,a.u.Bb);g.Ta(d,c||b.o);g.Ta(d,a.Ga.Bb);(c=!a.F)&&Nta(a);for(var e=a.U&&a.Y&&g.Ob(d,a.Y)?a.U:Ota(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.u,n=k[l];m&&!c?(Nta(a),e=Ota(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.re(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.lz||!g.zh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.zh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.le?g.vh(e,m,"1em"):g.vh(e,m,"0.5em")))}a.Y=d;a.U=e;a.C.push(b)},Rta=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Rb){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[p.getAttribute("p")];l=Qta(l.textContent,n.textContent,p.textContent,f.textContent,k);return new K3(a,b,e,c,l,d,m)}switch(m.Rb){case 9:case 10:m.gf=1;break;case 11:m.gf=2;break;case 12:m.gf=3;break;case 13:m.gf=4;break;case 14:m.gf=5}return new K3(a,b,e,c,l.textContent||"",d,m)},Qta=function(a,b,c,d,e){var f=g.fl(),k=
f?g.qe("DIV"):g.qe("RUBY"),l=g.qe("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.qe("DIV"):g.qe("RP");a.textContent=b;k.appendChild(a);b=f?g.qe("DIV"):g.qe("RT");b.textContent=c;k.appendChild(b);c=e.Rb;if(10===c||11===c||12===c||13===c||14===c)if(g.vh(b,"text-emphasis-style","filled circle"),g.vh(b,"text-emphasis-color","currentcolor"),g.vh(b,"webkit-text-emphasis","filled circle"),11===e.Rb||13===e.Rb)g.vh(b,"webkit-text-emphasis-position","under left"),g.vh(b,"text-emphasis-position","under left");c=!0;if(4===e.Rb||7===e.Rb||12===e.Rb||
14===e.Rb)g.vh(k,"ruby-position","over"),g.vh(k,"-webkit-ruby-position","before");else if(5===e.Rb||6===e.Rb||11===e.Rb||13===e.Rb)g.vh(k,"ruby-position","under"),g.vh(k,"-webkit-ruby-position","after"),c=!1;e=f?g.qe("DIV"):g.qe("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.vh(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.vh(f,"display","none"),f=f.nextElementSibling,g.vh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.vh(k.lastElementChild,"display","none"),d?(g.vh(k,"padding-top","0.6em"),g.vh(f,"top","0")):(g.vh(k,"padding-bottom","0.6em"),g.vh(f,"bottom","0")));return k},O3=function(){g.A.apply(this,arguments)},P3=function(a){O3.call(this);
this.A={};this.I={};this.J={};this.B="_"+M3++;this.C=a;this.G={};this.u=this.o=null;this.F=!0},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},R3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},S3=function(a,b){var c=Q3(a,b);
return void 0!=c?c:null},U3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return T3.test(c),c},Sta=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.J[d]:a.C);d=S3(b,"mh");null!=d&&(c.Qj=d);d=S3(b,"ju");null!=d&&(c.textAlign=d);d=S3(b,"pd");null!=d&&(c.Rc=d);d=S3(b,"sd");null!=d&&(c.Ku=d);d=U3(b,"wfc");null!=d&&(c.windowColor=d);d=Q3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},Tta=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.I[d]);d=S3(b,"ap");null!=d&&(c.ag=d);d=Q3(b,"cc");null!=d&&(c.Zg=d);d=Q3(b,"ah");null!=d&&(c.Ye=d);d=Q3(b,"rc");null!=d&&(c.Jg=d);d=Q3(b,"av");null!=d&&(c.Mg=d);return c},Uta=function(a,b,c,d){var e={};
g.Ta(e,Tta(a,b));g.Ta(e,Sta(a,b));d?g.Ob(e,a.C)?(d=a.B,e=a.C):d="_"+M3++:d=b.getAttribute("id")||"_"+M3++;a=Q3(b,"t")+c;b=Q3(b,"d")||0x8000000000000;if(2===e.Rc||3===e.Rc)c=e.Jg,e.Jg=e.Zg,e.Zg=c;return new L3(a,b,0,d,e)},V3=function(a){O3.call(this);
this.o=new Map;this.A=new Map;this.B=new Map;this.u=new Map;this.C=a},W3=function(a){a=g.Od(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Vta=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.A.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.B.get(b.wsWinStyleId));a=b.rcRowCount;void 0!=a&&(f.Jg=a);b=b.ccColCount;void 0!=b&&(f.Zg=b);if(2===f.Rc||3===f.Rc)b=f.Jg,f.Jg=f.Zg,f.Zg=b;return new L3(c,d,0,e,f)},X3=function(a,b,c,d,e,f,k){N3.call(this,a,b,c,d,e,f,k);
this.type=1},Z3=function(){this.w=this.time=this.mode=this.u=0;
this.A=new Y3(this);this.B=new Y3(this);this.o=[];this.clear()},Xta=function(a,b,c){if(255===a&&255===b||!a&&!b)return{ai:a,
Vg:b,result:0};a=Wta[a];b=Wta[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Vg===d;if(d)return{ai:a,Vg:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ai:a,Vg:b,result:2};return{ai:a,Vg:b,result:3}},Zta=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.w&&a.reset(),a.A.o.clear(),a.B.o.clear()):(a.w=0,Yta(a.A,b,c,d))},$ta=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.q(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Zta(a,d.nw,d.ow,b):1===d.type&&a.u&496&&Yta(a.B,d.nw,d.ow,b);a.o.length=0},$3=function(){this.type=0},a4=function(){this.state=this.Vg=this.ai=0},aua=function(){this.timestamp=this.o=0},b4=function(a){this.B=a;
this.w=[];this.o=this.u=this.row=0;this.style=new $3;for(a=this.A=0;15>=a;a++){this.w[a]=[];for(var b=0;32>=b;b++)this.w[a][b]=new aua}},c4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.B.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.w[m][p];
if(0!==t.o){0===c&&(c=m,d=p);n=String.fromCharCode(t.o);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===t.o||32===p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.w[k][m],t=p.o,0!==t&&(0===c&&(c=k,d=m),n=String.fromCharCode(t),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32===m||0===t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},fua=function(a,b){switch(a){case 0:return bua[(b&127)-32];
case 1:return cua[b&15];case 2:return dua[b&31];case 3:return eua[b&31]}return 0},d4=function(a){return a.w[a.row][a.u]},e4=function(a,b,c){2<=b&&1<a.u&&(--a.u,d4(a).o=0);
var d=d4(a);d.timestamp=a.B.time+0;d.o=fua(b,c);32>a.u&&a.u++},gua=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.w[b+e][f],l=a.w[c+e][f];
k.o=l.o;k.timestamp=l.timestamp}},f4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},g4=function(a){a.row=0<a.o?a.o:1;
a.u=1;f4(a,0,15)},h4=function(a){this.w=a;
this.B=0;this.style=new $3;this.C=new b4(this.w);this.F=new b4(this.w);this.text=new b4(this.w);this.u=this.C;this.A=this.F;this.o=this.u},i4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(c4(d,c),g4(a.u),g4(a.A),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.w.mode=1<<d.A;e?d.u=1:d.o!==b&&(d.o>b?(c4(d,c),f4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},hua=function(a){a.style.set(1);
a.o=a.A;a.o.o=0;a.o.style=a.style;a.w.mode=1<<a.o.A},iua=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.w.mode=1<<a.o.A},Y3=function(a){this.u=a;
this.B=0;this.w=new h4(this.u);this.C=new h4(this.u);this.o=new a4;this.A=this.w},Yta=function(a,b,c,d){a.o.update();
b=Xta(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ai;c=b.Vg;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&e4(a,0,b),c&96&&e4(a,0,c),0!==b&&0!==c&&3===a.style.type&&c4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.ai=e,b.Vg=c,b.state=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,k=1+d-c.o;gua(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));f4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:e4(b.o,0,32);break a;case 48:57===c?(d=b.o,d4(d).o=0,32>d.u&&d.u++):e4(b.o,1,c&15)}break;case 2:c&32&&e4(b.o,2,c&31);break;case 3:c&32&&e4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:hua(b);
break;case 33:d=b.o;1<d.u&&(--d.u,d4(d).o=0);break;case 36:d=b.o;b=d4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]===b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:i4(b,2,d);break;case 38:i4(b,3,d);break;case 39:i4(b,4,d);break;case 40:e4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.w.mode=1<<b.o.A;break;case 42:d=b.text;d.o=15;d.style.set(4);g4(d);iua(b);break;case 43:iua(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:c4(a,d)}f4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;c4(a,d);gua(a,b,b+1,a.o-1);f4(a,a.row,1)}break;case 46:f4(b.A,0,15);break;case 47:c4(b.u,d),b.A.updateTime(b.w.time+0),d=b.A,b.A=b.u,b.u=d,hua(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},jua=function(){},j4=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},k4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},l4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},m4=function(a,b){O3.call(this);
this.u=a;this.track="CC3"==b.languageName?4:0;this.o=new Z3;this.o.u=1<<this.track},n4=function(a){if("string"===typeof a)return!1;
a=new j4(a,8,0);return kua(a)},kua=function(a){if(!(a.o<a.u.byteLength)||1380139777!=l4(a))return!1;
a.version=k4(a);if(1<a.version)return!1;k4(a);k4(a);k4(a);return!0},o4=function(a,b,c,d,e,f,k){N3.call(this,a,b,c,d,e,f,k);
g.I(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.I=this.da=0;this.M=NaN;this.ya=0;this.Ba=null;this.ea=new g.H(this.IM,433,this);g.C(this,this.ea);g.vh(this.element,"overflow","hidden")},lua=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},mua=function(a){if(isNaN(a.M)){var b=a.u.Zg;
if(b){var c=g.qe("SPAN");g.Ae(c,"\u2013".repeat(b));g.vh(c,Mta(a,a.u.Bb));a.B.appendChild(c);a.M=c.offsetWidth;a.B.removeChild(c)}else a.M=0}return a.M},nua=function(a,b){if(!b)return"";
a.A&&1!=a.w.params.Ku&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},oua=function(a){a.G=[].concat(g.na(document.getElementsByClassName("caption-visual-line")));
for(var b=a.w.params.Jg,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.J=Math.max(mua(a),a.ya,lua(a,a.B))},pua=function(a,b){oua(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!=a.da){var d=0<c&&0==a.da;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),g.zn(a.ea));g.vh(a.B,"transform",nua(a,c));a.da=c}oua(a)},p4=function(){O3.call(this)},qua=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ve=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new K3(b,c,d,e.id,p.nodeValue,f||0<n,g.Mb(l)?void 0:l),m.push(p),e.o.push(p);else{var t={};g.Ta(t,l);qua(a,b,c,d,e,!0,p,t,m)}}},q4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},rua=function(a,b,c,d){d=Object.assign({Qj:0},d);
return new L3(a,b,c,"_"+M3++,d)},r4=function(a){g.A.call(this);
this.u=a;this.o=null},tua=function(a){var b={};
if(a=B3(a))b.lang=a,sua.test(a)&&(b.Rc=1);return b},u4=function(a){g.pL.call(this,a);
this.w=a.N();this.S=a.getVideoData();this.ya=g.KK(a);this.U=a;var b=null,c=g.po("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zn(c));this.ca=b;this.A={Bb:{}};this.C={Bb:{}};this.J=[];this.V={};this.aa={};this.M=!1;this.sa=g.rL(this.S,this.U);this.Aa=!!this.S.captionTracks.length;this.Ba=!!this.S.Qk;this.ha="3"===this.w.controlsType;b=a.app.B;c=!(!b||!b.Gm());this.xa=!(!b||!b.cj());this.B=this.ha&&c&&!this.sa;this.I=!this.B&&this.ha&&this.xa&&this.sa;this.u=this.F=this.G=this.Y=this.ra=
null;this.da=new r4(this.w);g.C(this,this.da);c=b=this.o=null;this.B||(b=new g.vn(this.CC,void 0,this),g.C(this,b),c=new g.H(this.kO,2E3,this),g.C(this,c));this.ea=b;this.na=c;this.T=new g.O(this);g.C(this,this.T);this.B||this.T.L(a,"resize",this.Vu);this.T.L(a,"onPlaybackAudioChange",this.nK);this.T.L(a,g.pD("captions"),this.ZG,this);this.T.L(a,"crx_captions",this.aH,this);s4(this,t4(this,"display-settings")||{})},v4=function(a){if(1===a.w.Yg||1===a.S.Yg||"alwayson"===g.AB(a.S,"yt:cc"))return!0;
if(2===a.w.Yg){var b=t4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().Zq;return"ON"===c||"on"===g.AB(a.S,"yt:cc")},w4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Mn||"FORCED_ON"===c.Zq},y4=function(a,b){if(a.u){if(a.F&&a.F.o)return a.F.o;
var c=b;c||(c=a.Ba?!1:a.Aa?!1:!0);c=C3(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.AB(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(B3(c[f])===d[e])return c[f];return a.F&&a.F.rr?a.F.rr:(d=c.find(function(k){return k.isDefault}))?d:c[0]||x4(a)}return null},x4=function(a){return a.F&&a.F.Mn},z4=function(a){var b=x4(a);
return!!b&&a.o===b},uua=function(a,b){for(var c=a.U.app.B.ib().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},B4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&A4(a,"module-enabled",!!b));a.o=b;w4(a)&&(a.o=x4(a));a.load()},vua=function(a,b){var c=a.ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.Rc&&d&&sua.test(d)&&(b.params.Rc=1);d=a.ya.getPlayerSize();switch(null!=b.params.Qj?b.params.Qj:1<b.o.length?1:0){case 1:return new X3(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new o4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new N3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},s4=function(a,b,c){c=void 0===c?!1:c;
var d=C4.Bb;a.A={};g.Ta(a.A,C4);a.A.Bb={};g.Ta(a.A.Bb,d);a.C={Bb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;T3.test(f);e.Bb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;T3.test(f);e.Bb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||C4.windowColor;T3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Bb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Ve?3:d.bold?1:d.Ve?2:0);f=f.Bb;switch(e){case 1:f.bold=!0;delete f.Ve;break;case 2:delete f.bold;f.Ve=!0;break;case 3:f.bold=!0;f.Ve=!0;break;default:delete f.bold,delete f.Ve}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=C4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.A;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Bb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bb.fontFamily=f;a.loaded&&a.Vu();c&&A4(a,"display-settings",b)},xua=function(a,b){if(b&&!a.G){var c=Jta({Rc:0,
lang:"fr"});a.G=[c,new K3(c.start,c.end-c.start,0,c.id,"Aper\u00e7u des sous-titres")];g.ZK(a.player,a.G)}else!b&&a.G&&(wua(a,a.G),a.G=null)},wua=function(a,b){g.tT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.fb(this.J,c)},a);
g.wn(a.ea)},t4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},A4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.GL.prototype.Rk=g.ca(11,function(){for(var a=g.ce(document,"track",void 0,this.o),b=0;b<a.length;b++)g.ve(a[b])});
g.fR.prototype.Rk=g.ca(10,function(){this.o.Rk()});
g.GL.prototype.Gm=g.ca(9,function(){return!!this.o.textTracks});
g.fR.prototype.Gm=g.ca(8,function(){return this.o.Gm()});
g.GL.prototype.Mk=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.fR.prototype.Mk=g.ca(6,function(a){this.o.Mk(a)});
g.vC.prototype.cj=g.ca(5,function(){});
g.GL.prototype.cj=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.fR.prototype.cj=g.ca(3,function(){return this.o.cj()});
g.Pt.prototype.Yn=g.ca(1,function(a){return(a=this.mg(a))?a.o:0});
g.Aw.prototype.Yn=g.ca(0,function(){return 0});
var sua=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.r(E3,g.A);E3.prototype.sB=function(){return!1};
E3.prototype.X=function(){this.Qh();g.A.prototype.X.call(this)};
g.r(F3,E3);F3.prototype.Os=function(a,b,c){this.ga();b=this.tl(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Qh();this.o=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
F3.prototype.Ps=function(a){if(this.w)for(var b=g.q(this.w.captionTracks),c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
F3.prototype.tl=function(a,b){var c=a.oc(),d={fmt:b};if("srv3"==b||"3"==b||"json3"==b)g.fl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=B3(a));return g.sq(c,d)};
F3.prototype.Qh=function(){this.o&&this.o.abort()};
G3.prototype.contains=function(a){a=g.qb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G3.prototype.length=function(){return this.segments.length/2};
g.r(H3,g.A);g.h=H3.prototype;g.h.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.h.YA=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.Db();var b=this.o;this.o=g.Xa(this.J.pg(a).o);b!==this.o&&this.G&&this.G()};
g.h.reset=function(){this.A=new G3;this.u&&(this.u.cancel(),this.u=null)};
g.h.qy=function(){this.ga();var a;if(a=null!==this.o)a=this.o,a=a.o.Cg(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ih(),a.o[0].duration?(this.A.contains(a.o[0].u)||Fta(this,a),this.o=g.Xa(a.o)):!g.R(this.I.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.player.Db()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.F.start()};
g.r(I3,E3);g.h=I3.prototype;g.h.Os=function(a,b,c){this.Qh();b=Hta(this,a.getId());b||(b=a.languageCode,b=this.o.u?Ita(this,b,"386"):Ita(this,b));if(b){var d=1E3*(b.index.Yn(b.index.Se())-b.index.jd(b.index.Se()));this.w=new H3(new g.Bv,this.F,b,function(e,f){c(e,a,f,d)},this.C||g.jt(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.sB=function(){var a=this.A;this.A=!1;return a};
g.h.Ps=function(a){var b;this.C?b=[new g.Vs({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Vs({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?Gta(this,"386"):Gta(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())D3(this.u,c.value);a()};
g.h.Qh=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.tl=function(){return""};
g.r(J3,E3);J3.prototype.Os=function(a,b,c){this.ga();b=this.tl(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Qh();this.o=g.Iq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
J3.prototype.Ps=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.sq(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
D3(this.u,new g.Vs({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:t},this.F[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Qh();this.o=g.Iq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
J3.prototype.tl=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=B3(a));return c=g.sq(c,d)};
J3.prototype.Qh=function(){this.o&&this.o.abort()};
var T3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Lta=["left","right","center","justify"];var C4={windowColor:"#080808",windowOpacity:0,textAlign:2,ag:7,Ye:50,Mg:100,Bb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(K3,g.mD);K3.prototype.toString=function(){return g.mD.prototype.toString.call(this)};g.r(L3,g.mD);L3.prototype.toString=function(){return g.mD.prototype.toString.call(this)};
var M3=0;g.r(N3,g.Q);g.h=N3.prototype;g.h.tI=function(a,b){var c=g.Lh(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.h.sI=function(a,b){var c=g.Oh(this.element),d=a-this.na-.02*this.Oa,e=b-this.sa-.02*this.Ja,f=(d+c.width/2)/this.ca*3;f=Math.floor(g.Od(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.Od(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ca;d=100*g.Od(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.Od(c,0,1);this.w.params.ag=l;this.w.params.Mg=c;this.w.params.Ye=d;this.u.ag=l;this.u.Mg=c;this.u.Ye=d;this.SB()};
g.h.rI=function(){g.Kn(this.element,"ytp-dragging")};
g.h.SB=function(){this.Yi(this.C)};
g.h.Yi=function(a){var b=Math.min(this.jx(),this.ca),c=this.ix(),d="";3===this.w.params.Rc&&(d="rotate(180deg)");g.vh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Rq(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Ye+2;d=this.u.ag;switch(d){case 0:case 3:case 6:b=this.u.Bb.fontSizeIncrement;!g.R(this.Ha,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.Rc&&3!==this.u.Rc&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Mg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.vh(this.element,a)};
g.h.Rq=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.T||this.C.length>b)b=0,this.T=!1,this.C=[],this.F=this.Y=this.U=null,g.te(this.B);for(;b<a.length;b++)Pta(this,a[b])};
g.h.jx=function(){return 0};
g.h.ix=function(){return 0};
g.h.toString=function(){return g.Q.prototype.toString.call(this)};g.r(O3,g.A);O3.prototype.w=function(){return[]};
O3.prototype.reset=function(){};g.r(P3,O3);P3.prototype.reset=function(){this.G={};this.u=this.o=null;this.F=!0};
P3.prototype.w=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ta(l,this.A[m]);m=R3(c,"b");null!=m&&(l.bold=
m);m=R3(c,"i");null!=m&&(l.Ve=m);m=R3(c,"u");null!=m&&(l.underline=m);m=S3(c,"et");null!=m&&(l.charEdgeStyle=m);m=S3(c,"of");null!=m&&(l.offset=m);m=U3(c,"bc");null!=m&&(l.background=m);m=U3(c,"ec");null!=m&&(l.er=m);m=U3(c,"fc");null!=m&&(l.color=m);m=S3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=Q3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=Q3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=Q3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=S3(c,"rb");null!=m&&10!=m&&0!=m&&(l.Rb=10<m?m-1:m);
c=S3(c,"hg");null!=c&&(l.Ox=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=Sta(this,c);break;case "wp":d=c.getAttribute("id"),this.I[d]=Tta(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=Uta(this,d,e,!1);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!R3(d,"a");n=
(Q3(d,"t")||0)+n;var p=Q3(d,"d")||5E3;m||(!this.F&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=this.A[d.getAttribute("p")],z=[].concat(g.na(d.childNodes));z.length&&(this.F=null!=d.getAttribute("d"));for(var B=0;B<z.length;B++){var D=z[B],E=void 0;0<B&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=this.A[F.getAttribute("p")])&&D.Rb&&(1===D.Rb?(D=z.slice(B,B+4),4===D.length&&(E=Rta(n,p,l,m,t,D,this.A),
B+=3)):E=Rta(n,p,l,m,t,[F],this.A)),!E){var J=F;E=n;F=p;D=l;var ha=m,qa=t,sc=J.textContent?J.textContent:"",$d=this.A[J.getAttribute("p")];J=Q3(J,"t")||0;E=new K3(E+J,F-J,qa,D,sc,ha,$d)}}else E=new K3(n,p,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId===this.B&&(this.o=Uta(this,d,e,!0),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var yua=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(V3,O3);V3.prototype.reset=function(){this.u.clear()};
V3.prototype.w=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Ve=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!=f.ecEdgeColor&&(k.er=W3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!=
f.fcForeColor&&(k.color=W3(f.fcForeColor));void 0!=f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!=f.bcBackColor&&(k.background=W3(f.bcBackColor));void 0!=f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Rb=10<l?l-1:l,k.gf=yua.get(k.Rb));f.hgHorizGroup&&(k.Ox=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=
f.mhModeHint&&(k.Qj=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&(k.Rc=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.Ku=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=W3(f.wfcWinFillColor)),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.A.get(l)),l=k,void 0!=f.ahHorPos&&(l.Ye=f.ahHorPos),
void 0!=f.apPoint&&(l.ag=f.apPoint),void 0!=f.avVerPos&&(l.Mg=f.avVerPos),void 0!=f.ccCols&&(l.Zg=f.ccCols),void 0!=f.rcRows&&(l.Jg=f.rcRows),this.A.set(d++,k);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=Vta(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+M3++,l=Vta(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,p=n?6:5,
t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var z=t[m],B=z.utf8;if(B){var D=z.tOffsetMs||0,E=null;z.pPenId&&(E=this.o.get(z.pPenId));if(2===(null!=l.params.Qj?l.params.Qj:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(z=E&&1===E.Rb)if(z=m,z+3>=t.length||!t[z+1].pPenId||!t[z+2].pPenId||!t[z+3].pPenId)z=!1;else{var F=t[z+1].pPenId;(F=this.o.get(F))&&F.Rb&&2==F.Rb?(F=t[z+2].pPenId,F=this.o.get(F),!F||!F.Rb||3>F.Rb?z=!1:(F=t[z+3].pPenId,z=(F=this.o.get(F))&&F.Rb&&2==F.Rb?!0:
!1)):z=!1}if(z){D=t[m+1].utf8;z=t[m+3].utf8;F=t[m+2].utf8;var J=this.o.get(t[m+2].pPenId);B=Qta(B,D,F,z,J);n=new K3(e,f,p,k,B,n,E);m+=3}else n=new K3(e+D,f-D,p,l.id,B,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};g.r(X3,N3);X3.prototype.Rq=function(a){var b=this.w.o;N3.prototype.Rq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,zua);var e=c.o;var f=d}Pta(this,c,d)}};
var zua={QF:!0};Z3.prototype.clear=function(){this.w=this.time=this.mode=0;this.o=[];this.reset()};
Z3.prototype.reset=function(){this.mode=0;this.A.reset(0);this.B.reset(1)};
var Wta=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];$3.prototype.set=function(a){this.type=a};
$3.prototype.get=function(){return this.type};
a4.prototype.clear=function(){this.state=0};
a4.prototype.update=function(){this.state=2===this.state?1:0};
a4.prototype.isValid=function(){return 0!==this.state};
a4.prototype.matches=function(a,b){return this.isValid()&&a===this.ai&&b===this.Vg};
aua.prototype.reset=function(){this.timestamp=this.o=0};
b4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
b4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
b4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var bua=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],cua=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],dua=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],eua=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];h4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.A=this.F;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Y3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};jua.prototype.B=function(){};g.r(j4,jua);j4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+M3++;c=c/1E3-this.F;d=d/1E3-this.F;a=new L3(c,d-c,5,f,{textAlign:0,ag:0,Ye:2.5*b,Mg:5.33*a});e=new K3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(m4,O3);m4.prototype.w=function(a){a=new j4(a,a.byteLength,this.u);if(kua(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=l4(a)*(1E3/45):1==a.version&&(a.A=4294967296*l4(a)+l4(a)),a.C=k4(a);0<a.C;a.C--){var b=k4(a),c=k4(a),d=k4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,nw:c,ow:d,order:b.o.length}))}$ta(this.o,a);return a.w}return[]};
m4.prototype.reset=function(){this.o.clear()};g.r(o4,N3);g.h=o4.prototype;g.h.SB=function(){g.An(this.ea)};
g.h.IM=function(){g.Kn(this.element,"ytp-rollup-mode");this.Yi(this.Ba,!0)};
g.h.ix=function(){return this.A?this.J:this.I};
g.h.jx=function(){return this.A?this.I:this.J};
g.h.Yi=function(a,b){this.Ba=a;if(this.w.params.Jg){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.J;this.I=this.J=0;N3.prototype.Yi.call(this,a);pua(this,b);N3.prototype.Yi.call(this,a)}else N3.prototype.Yi.call(this,a)};g.r(p4,O3);
p4.prototype.w=function(a,b){for(var c=[],d=a.split(Aua),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Bua.test(f)){var l=D4.exec(f);if(l&&4<=l.length){var m=q4(l[1]),n=q4(l[2])-m;m+=k;var p,t=p=void 0,u=void 0,z=void 0,B=(l=l[3])?l.split(" "):[];l={textAlign:2};B=g.q(B);for(var D=B.next();!D.done;D=B.next())if(D=D.value.split(":"),2==D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(z=D[0],l.Mg=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=E.split(",");
t=D[0];l.Ye=Number.parseInt(t,10);2==D.length&&(p=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Mg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Ye=0;break;case 1:l.Ye=100;break;default:l.Ye=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.ag=0>t||8<t?7:t;p=l;f=f.substring(D4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=rua(m,n,5,t),n=new K3(m,n,5,k.id,p,!1,g.Mb(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=p.split(Cua),1==u.length?(p=5,t=rua(m,n,p,t)):(z=p=6,t=Object.assign({Zg:32},t),t=new L3(m,n,z,"_"+M3++,t)),c.push(t),z=m,l=0;l<u.length;l++)B=u[l],0==l%2?(D=g.D1("<html>"+B+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(B))):E=D.firstChild,qua(this,z,n-(z-m),p,t,0<l,E,f,c)):z=q4(B)+k}D4.lastIndex=0}}return c};
var Bua=/^NOTE/,Aua=/(?:\r\n|\r|\n){2,}/,D4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Cua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(r4,g.A);r4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
r4.prototype.reset=function(){this.o&&this.o.reset()};
r4.prototype.X=function(){this.clear();g.A.prototype.X.call(this)};g.r(u4,g.pL);g.h=u4.prototype;g.h.X=function(){if(this.B||this.I){var a=this.U.app.B;a&&!a.ga()&&a.Rk()}else xua(this,!1);g.pL.prototype.X.call(this)};
g.h.load=function(){g.pL.prototype.load.call(this);var a=!g.R(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.F=this.player.getAudioTrack();if(this.u)this.o&&(this.da.clear(),this.B?uua(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Os(this.o,"json3",(0,g.x)(this.sN,this)),!a||this.B||this.I||z4(this)||this.player.ma("captionschanged",A3(this.o))),a||(this.o&&!z4(this)?this.player.ma("captionschanged",A3(this.o)):this.player.ma("onCaptionsTrackListChanged"));
else{var b;this.sa?b=new I3(this.S.la,this.player):this.Aa?b=new F3(this.w,this.S,this.player.getAudioTrack()):b=new J3(this.S.Qk,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.AB(this.S,"yt:cc_default_lang")||this.w.kc,this.S.Xq,this.w);this.u=b;g.C(this,this.u);b.Ps((0,g.x)(this.rN,this))}};
g.h.unload=function(){this.B&&this.o?uua(this,!1):(this.na&&g.Bn(this.na),g.oQ(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Qh(),this.da.clear(),this.G&&g.ZK(this.player,this.G),this.Vu());g.pL.prototype.unload.call(this);var a=g.W(this.player.app);a&&g.NH(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ha?this.B||this.I:w4(this)||v4(this))&&this.load()};
g.h.rN=function(){var a;this.M||v4(this)?a=y4(this,this.M):w4(this)&&(a=x4(this));if(this.B||this.I){for(var b=C3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Ws(e),srclang:B3(e),id:e.toString()};this.I||(f.src=this.u.tl(e,"vtt"));e===a&&(f["default"]=1);c.push(g.pe("TRACK",f))}a=this.U.app.B;a.Mk(c);c=a.ib();this.xa&&this.T.L(c.textTracks,"change",this.tN)}else!this.o&&a&&B4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.tN=function(){for(var a=this.U.app.B.ib().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=C3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&B4(this,b,!0)};
g.h.ZO=function(){!this.o&&this.B||this.unload()};
g.h.sN=function(a,b,c,d){if(a){this.u.sB()&&(this.J=[],g.oQ(this.U.app,"captions",void 0),g.wn(this.ea),this.da.reset());var e=this.da;c=c||0;d=d||0;if(e.u.fa("html5_disable_rawcc_killswitch")){if("string"!==typeof a){var f=new DataView(a);8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.eu(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),n4(a)||(a=Bta(new Uint8Array(a))))}}else"string"===typeof a||n4(a)||(f=new DataView(a),a=8>=f.byteLength||1718909296!==f.getUint32(4)?"":(f=g.eu(f,0,
1835295092))&&f.size?Bta(new Uint8Array(a.slice(f.dataOffset,f.dataOffset+f.size))):"");if(a)try{if("string"!==typeof a){var k=a,l=c,m=d;if(!n4(k))throw Error("Invalid binary caption track data");e.o||(e.o=new m4(m,b));var n=e.o.w(k,l)}else{if("WEBVTT"==a.substring(0,6))b=a,m=c,e.o||(e.o=new p4),l=e.o.w(b,m),.01>Math.random()&&g.Ko(Error("Deprecated subtitles format in web player: WebVTT")),k=l;else b:{l=a;if("{"===l[0])try{e.o||(e.o=new V3(tua(b)));k=e.o.w(l,c);break b}catch(D){g.M(D);k=[];break b}m=
g.D1(l);if(!m||!m.firstChild){var p=Error("Invalid caption track data");p.params=l;throw p;}if("timedtext"==m.firstChild.tagName){if(3==parseInt(m.firstChild.getAttribute("format"),10)){e.o||(e.o=new P3(tua(b),e.u));k=e.o.w(m,c);break b}var t=Error("Unsupported subtitles format in web player (Format2)");t.params=l;throw t;}if("transcript"==m.firstChild.tagName){var u=Error("Unsupported subtitles format in web player (Format1)");u.params=l;throw u;}var z=Error("Invalid caption track data");z.params=
l;throw z;}n=k}var B=n}catch(D){g.M(D),e.clear(),B=[]}else B=[];g.ZK(this.player,B);!this.M||this.I||z4(this)||g.Yy(this.w)||g.Zy(this.w)||(g.Bn(this.na),B=Jta({ag:0,Ye:5,Mg:5,Jg:2,textAlign:0,Rc:0,lang:"fr"}),this.Y=[B],e=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.ra||(n=new g.Et(g.iM()),g.C(this,n),this.ra=n.element),n=B.end-B.start,(b=g.Ws(this.o))&&this.Y.push(new K3(B.start,n,0,B.id,b)),this.Y.push(new K3(B.start,n,0,B.id,e[0]),new K3(B.start,n,0,B.id,this.ra,!0),new K3(B.start,
n,0,B.id,e[1],!0)),g.ZK(this.player,this.Y),g.zn(this.na));!this.M||this.I||z4(this)||(A4(this,"module-enabled",!0),this.F&&(this.F.o=this.o),(B=g.W(this.player.app))&&g.NH(B.B));this.M=!1}};
g.h.ZG=function(a){this.J.push(a);g.wn(this.ea)};
g.h.aH=function(a){g.fb(this.J,a);this.u instanceof I3&&this.u.C&&g.tT(this.player.app,[a],void 0);g.wn(this.ea)};
g.h.cO=function(a){if(a instanceof L3){var b=this.V[a.id];b&&b.w!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=vua(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.aa[b]||(this.aa[b]=[]),this.aa[b].push(a)};
g.h.kO=function(){wua(this,this.Y);this.Y=null};
g.h.CC=function(){this.ea.stop();g.Nb(this.aa);this.J.sort(g.oD);var a=this.J;if(this.G){var b=(0,g.we)(a,function(c){return-1===this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.cO,this);g.zb(this.V,function(c,d){this.aa[d]?(c.element.parentNode||g.cL(this.player,c.element,4),c.Yi(this.aa[d])):(c.dispose(),delete this.V[d])},this)};
g.h.rO=function(){s4(this,{},!0);g.R(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.eF=function(){var a=C4.Bb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ve?3:a.bold?1:a.Ve?2:0,textOpacity:a.textOpacity,windowColor:C4.windowColor,windowOpacity:C4.windowOpacity};var b=t4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.IC=function(a,b){b=void 0===b?!1:b;var c={};g.Ta(c,t4(this,"display-settings"));g.Ta(c,a);s4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.Vu=function(){!this.B&&this.loaded&&(g.zb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.CC())};
g.h.Nc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Od(b,-2,4);this.IC({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&B4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.w&&A4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Pa(b))break;if(g.Mb(b)){B4(this,null,!0);break}for(var d=C3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!=b.languageName||(c=b.translationLanguage?
Ata(f,b.translationLanguage):f)}!c||c==this.o&&this.loaded||B4(this,c,!0)}else return this.loaded&&this.o&&!z4(this)?A3(this.o):{};return"";case "tracklist":return this.u?(0,g.Ec)(C3(this.u.u,!(!b||!b.includeAsr)),function(k){return A3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||xua(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.w&&a.push("stickyLoading");return a};
g.h.AG=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.h.TO=function(){this.loaded&&this.o&&!z4(this)?(A4(this,"module-enabled",!1),this.unload(),w4(this,!0)&&B4(this,x4(this),!1)):B4(this,z4(this)||!this.o?y4(this,!0):this.o,!0)};
g.h.nK=function(){var a=z4(this);w4(this,a)?B4(this,this.player.getAudioTrack().Mn,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.ha?this.B||this.I:w4(this)||v4(this))&&(a?B4(this,y4(this),!1):this.load()))};g.EL.captions=u4;})(_yt_player);
