(function(g){var window=this;var p3=function(a){var b={languageCode:a.u,languageName:a.w,displayName:g.Tz(a),kind:a.A,name:a.B,id:a.H,is_servable:a.D,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},q3=function(a){return a.o?a.o.languageCode:a.u},Dpa=function(a,b){var c=new g.Sz;
c.u=a.u;c.w=a.w;c.B=a.B;c.A=a.A;c.isDefault=!1;c.D=a.D;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},Epa=function(){this.u=[];
this.o=[]},r3=function(a,b){return b?a.o.concat(a.u):a.o},s3=function(a,b){switch(b.A){case "asr":var c=a.u;
g.Ua(c,(0,g.x)(b.Nq,b))||c.push(b);break;default:c=a.o,g.Ua(c,(0,g.x)(b.Nq,b))||c.push(b)}},t3=function(a){g.E.call(this);
this.Xa=a;this.u=new Epa;this.B=[]},u3=function(a,b,c){t3.call(this,a);
this.o=null;this.B=b.wu;this.w=c},v3=function(){this.o=[]},w3=function(a,b,c,d,e,f){g.E.call(this);
this.J=a;this.w=b;this.U=b.O();this.B=new v3;this.o=null;this.D=d;this.K=f;this.u=this.A=null;this.P=c;this.C=e||!1;this.G=new g.J(this.Ew,1E3,this);g.H(this,this.G);this.H=new g.Q(this);g.H(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.tx);this.tx();this.Ew()},x3=function(a,b){b-=a.w.tb();
var c=a.o;a.o=g.Sa(a.P.wf(b).o);c!=a.o&&a.K&&a.K()},y3=function(a,b){var c=g.Hw(g.Sw(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Zp(c,d,3,100).then((0,g.x)(a.OK,a));a.A=b;c=a.B;d=a.A.o[0].u;var e=g.kb(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.$a(c.o,e),g.$a(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.gb(c.o,e,0,d),g.gb(c.o,e+1,0,d)))},z3=function(a,b){t3.call(this,b.O());
this.o=a;this.D=b;this.w=null;this.A=!1;this.C=g.vz(this.D.O())&&!this.o.u},A3=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.wQ(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Sz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Fpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},B3=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.wQ(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},C3=function(a,b,c,d,e){t3.call(this,e||null);
c=c||g.gp(a).hl||"";c=c.split("_").join("-");this.A=g.ip(a,{hl:c});this.w=b;this.C=!!d;this.D={};this.o=null},D3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.VD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.w=f;this.o=k},E3=function(a,b,c,d,e){g.VD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},G3=function(a){a=void 0===a?{}:a;
var b="_"+F3++;return new E3(0,0x8000000000000,0,b,a)},I3=function(a,b,c,d,e,f){var k={};
g.Oa(k,b);g.Oa(k,a.params);g.Oa(k,c);var l={};g.Oa(l,b.vb);a.params.vb&&g.Oa(l,a.params.vb);g.Oa(l,c.vb);k.vb=l;g.W.call(this,{F:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==k.qe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},L:[{F:"span",I:"captions-text",N:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.T=!1;this.A=a;this.ca=this.V=null;this.La=e;this.Ka=f;this.G=null;this.aa=.96*e;this.ya=.96*f;this.w=k;this.Ha=c;this.C=this.u["captions-text"];this.Aa=
null!=this.C.style["box-decoration-break"]||null!=this.C.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ia=this.Z*H3(l);a=new g.yM(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.bG,this);a.subscribe("dragmove",this.aG,this);a.subscribe("dragend",this.ZF,this);this.wa=this.na=0;b="";this.w.windowOpacity&&(a=g.G_(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":Gpa[this.w.textAlign]};
this.Aa&&(a["border-radius"]=b?this.ia/8+"px":"");if(this.B=2==this.A.params.qe||3==this.A.params.qe)b=this.element,c="vertical-rl",1==this.w.pA&&(c="vertical-lr"),g.Gd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.ag(b,"-o-writing-mode",c),g.ag(b,"-webkit-writing-mode",c),g.ag(b,"writing-mode",c),g.ag(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.A.params.qe&&(g.ag(b,"text-orientation",""),g.ag(b,"transform","rotate(180deg)"));g.ag(this.element,a);switch(this.w.Uf){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},H3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},J3=function(a,b){var c={},d=b.background?b.background:a.w.vb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.vb.backgroundOpacity;d=g.G_(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ia/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*H3(b)+"px";d=1;e=b.color||a.w.vb.color;if(b.color||null!=b.textOpacity)e=g.G_(e),d=null==b.textOpacity?a.w.vb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Eu&&(k=e=b.Eu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Jp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.vb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Le&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.OD&&(c.visibility="hidden");1==b.QD&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Fu||g.Dz,3==a.A.params.qe?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.pe||2==b.pe||3==b.pe||4==b.pe||5==b.pe)if(g.Fu)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.pe){case 4:case 3:c["text-emphasis-position"]="under left";c["webkit-text-emphasis-position"]=
"under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},K3=function(a){a.G=g.Nd("SPAN");
g.ag(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.C.appendChild(a.G)},L3=function(a,b){var c=g.Nd("SPAN");
g.ag(c,{display:"inline-block","white-space":"pre-wrap"});g.ag(c,J3(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.ag(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ag(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},M3=function(a,b,c){a.T=a.T||!!c;
var d={};g.Oa(d,a.w.vb);g.Oa(d,c||b.o);g.Oa(d,a.Ha.vb);(c=!a.G)&&K3(a);for(var e=a.V&&a.ca&&g.Yb(d,a.ca)?a.V:L3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.w,n=k[l];m&&!c?(K3(a),e=L3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Od(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Fu||!g.eg(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.eg(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),g.Id?
g.ag(e,m,"1em"):g.ag(e,m,"0.5em")))}a.ca=d;a.V=e;a.D.push(b)},N3=function(){},P3=function(){this.A=this.u=this.mode=this.w=0;
this.B=new O3(this);this.C=new O3(this);this.o=[];this.clear()},Hpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{yl:a,
zl:b,result:0};a=Q3[a];b=Q3[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{yl:a,zl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{yl:a,zl:b,result:2};return{yl:a,zl:b,result:3}},Ipa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,R3(a.B,b,c,d))},Jpa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?Ipa(a,d.yu,d.zu,b):1==d.type&&a.w&496&&R3(a.C,d.yu,d.zu,b)}a.o.length=0},S3=function(){this.o=0},T3=function(){this.u=this.w=this.o=0},U3=function(){this.timestamp=this.Sd=0},V3=function(a){this.w=[];
for(var b=0;15>=b;b++){this.w[b]=[];for(var c=0;32>=c;c++)this.w[b][c]=new U3}this.o=this.u=this.row=0;this.style=new S3;this.B=a;this.A=0},W3=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.w[m][q];
if(0!=t.Sd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Sd);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Sd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.w[k][m],t=q.Sd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Opa=function(a,b){switch(a){case 0:return Kpa[(b&127)-32];
case 1:return Lpa[b&15];case 2:return Mpa[b&31];case 3:return Npa[b&31]}return 0},X3=function(a){return a.w[a.row][a.u]},Y3=function(a,b,c){2<=b&&1<a.u&&(--a.u,X3(a).Sd=0);
var d=X3(a);d.timestamp=a.B.u+0;d.Sd=Opa(b,c);32>a.u&&a.u++},Z3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.w[b+e][f].ag(a.w[c+e][f])},$3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.w[b+d][e].reset()},a4=function(a){a.row=0<a.o?a.o:1;
a.u=1;$3(a,0,15)},b4=function(a){this.A=a;
this.B=0;this.style=new S3;this.C=new V3(a);this.D=new V3(a);this.G=new V3(a);this.u=this.C;this.w=this.D;this.o=this.u},c4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:W3(d,c),a4(a.u),a4(a.w),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.A;e?d.u=1:d.o!=b&&(d.o>b?(W3(d,c),$3(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},d4=function(a){a.style.set(1);
a.o=a.w;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.A},e4=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.A.mode=1<<a.o.A},O3=function(a){this.u=a;
this.o=new T3;this.B=0;this.w=new b4(a);this.C=new b4(a);this.A=this.w},R3=function(a,b,c,d){a.o.update();
b=Hpa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.yl;c=b.zl;if(32<=e||!e)a.u.mode&a.u.w&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.o,b&96&&Y3(a,0,b),c&96&&Y3(a,0,c),0!=b&&0!=c&&3==a.style.o&&W3(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.w=e,b.u=c,b.o=2,b=e&8?a.C:a.w,a.A=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.w))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Z3(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));$3(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:Y3(b.o,0,32);break a;case 48:57==c?(d=b.o,X3(d).Sd=0,32>d.u&&d.u++):Y3(b.o,1,c&15)}break;case 2:c&32&&Y3(b.o,2,c&31);break;case 3:c&32&&Y3(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:d4(b);break;case 33:d=
b.o;1<d.u&&(--d.u,X3(d).Sd=0);break;case 36:d=b.o;b=X3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.w[a][c]==b){for(;32>=c;c++)d.w[a][c].reset();break}break;case 37:c4(b,2,d);break;case 38:c4(b,3,d);break;case 39:c4(b,4,d);break;case 40:Y3(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.A;break;case 42:d=b.G;d.o=15;d.style.set(4);a4(d);e4(b);break;case 43:e4(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:W3(a,d)}$3(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;W3(a,d);Z3(a,b,b+1,a.o-1);$3(a,a.row,1)}break;case 46:$3(b.w,0,15);break;case 47:W3(b.u,d),b.w.updateTime(b.A.u+0),d=b.w,b.w=b.u,b.u=d,d4(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},f4=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Wc){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var u=g.Jp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=u?g.Nd("DIV"):g.Nd("RUBY");l=l.textContent;var y=g.Nd("SPAN");y.textContent=l;f.appendChild(y);n.getAttribute("p");y=u?g.Nd("DIV"):g.Nd("RP");l=n.textContent;y.textContent=l;f.appendChild(y);k=k[q.getAttribute("p")];l=q.textContent;q=u?g.Nd("DIV"):g.Nd("RT");q.textContent=l;f.appendChild(q);l=k.Wc;if(10==l||11==l||12==l||13==l||14==l)if(g.ag(q,"text-emphasis",
"filled circle"),g.ag(q,"webkit-text-emphasis","filled circle"),k.Wc==k.Wc==11||13==k.Wc)g.ag(q,"webkit-text-emphasis-position","under left"),g.ag(q,"text-emphasis-position","under left");q=!0;if(4==k.Wc||7==k.Wc||12==k.Wc||14==k.Wc)g.ag(f,"ruby-position","over"),g.ag(f,"-webkit-ruby-position","before");else if(5==k.Wc||6==k.Wc||11==k.Wc||13==k.Wc)g.ag(f,"ruby-position","under"),g.ag(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;t=u?g.Nd("DIV"):g.Nd("RP");t.textContent=
l;f.appendChild(t);u&&(u=q,g.ag(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.ag(t,"display","none"),t=t.nextElementSibling,g.ag(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ag(f.lastElementChild,"display","none"),u?(g.ag(f,"padding-top","0.6em"),g.ag(t,"top","0")):(g.ag(f,"padding-bottom","0.6em"),g.ag(t,"bottom","0")));return new D3(a,b,e,c,f,d,m)}switch(m.Wc){case 9:case 10:m.pe=
1;break;case 11:m.pe=2;break;case 12:m.pe=3;break;case 13:m.pe=4;break;case 14:m.pe=5}return new D3(a,b,e,c,l.textContent||"",d,m)},g4=function(){g.E.apply(this,arguments)},h4=function(a){g4.call(this);
this.w={};this.H={};this.J={};this.B="_"+F3++;this.C=a;this.G={};this.u=this.o=null;this.D=!0},i4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},j4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},k4=function(a,b){var c=i4(a,b);
return void 0!=c?c:null},m4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return l4.test(c),c},n4=function(a,b){var c={},d=b.getAttribute("ws");
g.Oa(c,d?a.J[d]:a.C);d=k4(b,"mh");null!=d&&(c.Gq=d);d=k4(b,"ju");null!=d&&(c.textAlign=d);d=k4(b,"pd");null!=d&&(c.qe=d);d=k4(b,"sd");null!=d&&(c.pA=d);d=m4(b,"wfc");null!=d&&(c.windowColor=d);d=i4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},o4=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Oa(c,a.H[d]);d=k4(b,"ap");null!=d&&(c.Uf=d);d=i4(b,"cc");null!=d&&(c.Ml=d);d=i4(b,"ah");null!=d&&(c.Me=d);d=i4(b,"rc");null!=d&&(c.Dk=d);d=i4(b,"av");null!=d&&(c.Gg=d);return c},p4=function(a,b,c,d){var e={};
g.Oa(e,o4(a,b));g.Oa(e,n4(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+F3++:d=b.getAttribute("id")||"_"+F3++;a=i4(b,"t")+c;b=i4(b,"d")||0x8000000000000;if(2==e.qe||3==e.qe)c=e.Dk,e.Dk=e.Ml,e.Ml=c;return new E3(a,b,0,d,e)},q4=function(a,b,c,d,e,f,k){I3.call(this,a,b,c,d,e,f,k);
this.type=1},r4=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.o=0;this.u=new DataView(a);this.w=[]},s4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},t4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},u4=function(a,b){g4.call(this);
this.u=a;this.track="CC3"==b.w?4:0;this.o=new P3;this.o.w=1<<this.track},w4=function(a){if("string"===typeof a)return!1;
a=new r4(a,8,0);return v4(a)},v4=function(a){if(!(a.o<a.u.byteLength)||1380139777!=t4(a))return!1;
a.version=s4(a);if(1<a.version)return!1;s4(a);s4(a);s4(a);return!0},x4=function(a,b,c,d,e,f,k){I3.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.K=this.J=this.fa=0;this.P=NaN;this.xa=0;this.Ca=null;this.ea=new g.J(this.TK,433,this);g.H(this,this.ea);g.ag(this.element,"overflow","hidden")},Ppa=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},Qpa=function(a){if(isNaN(a.P)){var b=a.w.Ml;
if(b){var c=g.Nd("SPAN");g.Xd(c,"\u2013".repeat(b));g.ag(c,J3(a,a.w.vb));a.C.appendChild(c);a.P=c.offsetWidth;a.C.removeChild(c)}else a.P=0}return a.P},Rpa=function(a,b){if(!b)return"";
a.B&&1!=a.A.params.pA&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},y4=function(a){a.H=[].concat(g.na(document.getElementsByClassName("caption-visual-line")));
for(var b=a.A.params.Dk,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.K=Math.max(Qpa(a),a.xa,Ppa(a,a.C))},Spa=function(a,b){y4(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.Xm(a.ea));g.ag(a.C,"transform",Rpa(a,c));a.fa=c}y4(a)},z4=function(){g4.call(this)},A4=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Le=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType){q=new D3(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(q);var t=e;g.H(t,q);t.o.push(q)}else t={},g.Oa(t,l),A4(a,b,c,d,e,!0,q,t,m)}},B4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},C4=function(a,b,c,d){d=Object.assign({Gq:0},d);
return new E3(a,b,c,"_"+F3++,d)},D4=function(a){g.E.call(this);
this.u=a;this.o=null},G4=function(a){g.vQ.call(this,a);
this.w=a.O();this.S=a.getVideoData();this.wa=g.OK(a);this.T=a;var b=null,c=g.Mn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wn(c));this.ca=b;this.A={vb:{}};this.C={vb:{}};this.J=[];this.U={};this.da={};this.K=!1;this.ia=g.xQ(this.S,this.T);this.ya=!!this.S.captionTracks.length;this.xa=!!this.S.nj;this.fa="3"==this.w.controlsType;b=a.app.B;c=!(!b||!b.Rk());this.na=!(!b||!b.Hh());this.B=this.fa&&c&&!this.ia;this.H=!this.B&&this.fa&&this.na&&this.ia;this.u=this.D=this.G=this.V=this.ea=
null;this.Z=new D4(this.w);g.H(this,this.Z);c=b=this.o=null;this.B||(b=new g.Um(this.GA,void 0,this),g.H(this,b),c=new g.J(this.wM,2E3,this),g.H(this,c));this.aa=b;this.oa=c;this.P=new g.Q(this);g.H(this,this.P);this.B||this.P.M(a,"resize",this.Ts);this.P.M(a,"onPlaybackAudioChange",this.vI);this.P.M(a,g.YD("captions"),this.aF,this);this.P.M(a,"crx_captions",this.bF,this);E4(this,F4(this,"display-settings")||{})},H4=function(a){if(1==a.w.Xf||1==a.S.Xf||"alwayson"==g.KC(a.S,"yt:cc"))return!0;
if(2==a.w.Xf){var b=F4(a,"module-enabled");if(null!=b)return!!b}if(a.S.captionTracks.length)var c=a.player.getAudioTrack().fp;return"ON"==c||"on"==g.KC(a.S,"yt:cc")},I4=function(a,b){if(a.o&&(void 0===b||!b)||!a.S.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Yl||"FORCED_ON"==c.fp},K4=function(a,b){if(a.u){if(a.D&&a.D.o)return a.D.o;
var c=b;c||(c=a.xa?!1:a.ya?!1:!0);c=r3(a.u.u,c);for(var d=[a.S.captionsLanguagePreference,a.w.captionsLanguagePreference,g.KC(a.S,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(q3(c[f])==d[e])return c[f];return a.D&&a.D.qp?a.D.qp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||J4(a)}return null},J4=function(a){return a.D&&a.D.Yl},L4=function(a){var b=J4(a);
return!!b&&a.o==b},M4=function(a,b){for(var c=a.T.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},O4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&N4(a,"module-enabled",!!b));a.o=b;I4(a)&&(a.o=J4(a));a.load()},Tpa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Gq?b.params.Gq:1<b.o.length?1:0){case 1:return new q4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);case 2:return new x4(b,a.A,a.C,c,d.width,d.height,a.w.experiments);default:return new I3(b,a.A,a.C,c,d.width,d.height,a.w.experiments)}},E4=function(a,b,c){var d=P4.vb;
a.A={};g.Oa(a.A,P4);a.A.vb={};g.Oa(a.A.vb,d);a.C={vb:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;l4.test(f);e.vb.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;l4.test(f);e.vb.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||P4.windowColor;l4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.vb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.vb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.Le?3:d.bold?1:d.Le?2:0);f=f.vb;switch(e){case 1:f.bold=!0;delete f.Le;break;case 2:delete f.bold;f.Le=!0;break;case 3:f.bold=!0;f.Le=!0;break;default:delete f.bold,delete f.Le}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.vb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=P4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.vb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.vb.fontFamily=f;a.loaded&&a.Ts();c&&N4(a,"display-settings",b)},R4=function(a,b){if(b&&!a.G){var c=G3({qe:0,
lang:"fr"});a.G=[c,new D3(c.start,c.end-c.start,0,c.id,"Aper\u00e7u des sous-titres")];g.bL(a.player,a.G)}else!b&&a.G&&(Q4(a,a.G),a.G=null)},Q4=function(a,b){g.iU(a.player.app,b,void 0);
(0,g.z)(b,function(c){g.ab(this.J,c)},a);
a.aa.hi()},F4=function(a,b){if(!a.ca)return null;
try{var c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},N4=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.Sz.prototype.Nq=g.ca(11,function(a){return a?this.toString()==a.toString():!1});
g.fv.prototype.mm=g.ca(10,function(a){return(a=this.fg(a))?a.o:0});
g.jx.prototype.mm=g.ca(9,function(){return 0});
g.Bt.prototype.oj=g.ca(8,function(){for(var a=g.yd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Sd(a[b])});
g.kS.prototype.oj=g.ca(7,function(){this.o.oj()});
g.Bt.prototype.Rk=g.ca(6,function(){return!!this.o.textTracks});
g.kS.prototype.Rk=g.ca(5,function(){return this.o.Rk()});
g.Bt.prototype.jj=g.ca(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.kS.prototype.jj=g.ca(3,function(a){this.o.jj(a)});
g.qt.prototype.Hh=g.ca(2,function(){});
g.Bt.prototype.Hh=g.ca(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.kS.prototype.Hh=g.ca(0,function(){return this.o.Hh()});
var Upa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,l4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(t3,g.E);t3.prototype.pz=function(){return!1};
t3.prototype.Y=function(){this.Hg();g.E.prototype.Y.call(this)};
g.r(u3,t3);u3.prototype.Eq=function(a,b,c){b=this.Fj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Hg();this.o=g.Ap(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
u3.prototype.Fq=function(a){if(this.w)for(var b=g.p(this.w.captionTracks),c=b.next();!c.done;c=b.next())s3(this.u,c.value);a()};
u3.prototype.Fj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.Jp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=q3(a));return g.ip(c,d)};
u3.prototype.Hg=function(){this.o&&this.o.abort()};
v3.prototype.contains=function(a){a=g.kb(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
v3.prototype.length=function(){return this.o.length/2};
g.r(w3,g.E);g.h=w3.prototype;g.h.Y=function(){g.E.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.tx=function(){x3(this,this.w.getCurrentTime())};
g.h.reset=function(){this.B=new v3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Ew=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.If(a);!a||this.u||this.o&&30<this.o.startTime-this.w.getCurrentTime()||(a=this.o,a=a.o.zi(a),a.o[0].duration?(this.B.contains(a.o[0].u)||y3(this,a),this.o=g.Sa(a.o)):!g.R(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.w.tb()<this.w.getCurrentTime()&&x3(this,this.w.getCurrentTime()));this.G.start()};
g.h.OK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.ox(a);c?(a=g.Sw(this.A,this.J,{}),b=this.A,g.Ow(b.u,a,c),b.requestId=a.get("req_id"),y3(this,this.A)):(b||null===this.D||(c=this.A.o[0],this.C?this.D(a.response,1E3*(c.startTime+this.w.tb())):this.D(a.responseText,1E3*(c.startTime+this.w.tb()))),this.u=this.A=null)};
g.r(z3,t3);g.h=z3.prototype;g.h.Eq=function(a,b,c){this.Hg();b=Fpa(this,a.getId());b||(b=a.u,b=this.o.u?B3(this,b,"386"):B3(this,b));if(b){var d=1E3*(b.index.mm(b.index.je())-b.index.Ic(b.index.je()));this.w=new w3(new g.Jw,this.D,b,function(e,f){c(e,a,f,d)},this.C||g.Cs(b.info),(0,g.x)(function(){this.w&&this.w.reset();
this.A=!0},this))}};
g.h.pz=function(){var a=this.A;this.A=!1;return a};
g.h.Fq=function(a){var b;this.C?b=[new g.Sz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Sz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?A3(this,"386"):A3(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())s3(this.u,c.value);a()};
g.h.Hg=function(){this.w&&(this.w.dispose(),this.w=null)};
g.h.Fj=function(){return""};
g.r(C3,t3);C3.prototype.Eq=function(a,b,c){b=this.Fj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Hg();this.o=g.Ap(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
C3.prototype.Fq=function(a){var b=this.A,c={type:"list",tlangs:1,v:this.w,vssids:1};this.C&&(c.asrs=1);b=g.ip(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
s3(this.u,new g.Sz({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.D[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Hg();this.o=g.Ap(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
C3.prototype.Fj=function(a,b){var c=this.A,d={v:this.w,type:"track",lang:a.u,name:a.getName(),kind:a.A,fmt:b};a.o&&(d.tlang=q3(a));return c=g.ip(c,d)};
C3.prototype.Hg=function(){this.o&&this.o.abort()};var Gpa=["left","right","center","justify"];var P4={windowColor:"#080808",windowOpacity:0,textAlign:2,Uf:7,Me:50,Gg:100,vb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(D3,g.VD);D3.prototype.toString=function(){return g.VD.prototype.toString.call(this)};g.r(E3,g.VD);E3.prototype.toString=function(){return g.VD.prototype.toString.call(this)};
var F3=0;g.r(I3,g.W);g.h=I3.prototype;g.h.bG=function(a,b){var c=g.qg(this.element,this.element.parentElement);this.na=a-c.x;this.wa=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.aG=function(a,b){var c=g.tg(this.element),d=a-this.na-.02*this.La,e=b-this.wa-.02*this.Ka,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.ld(f,0,2));var k=(e+c.height/2)/this.ya*3;k=Math.floor(g.ld(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.ld(d,0,1);c=(e+k/2*c.height)/this.ya;c=100*g.ld(c,0,1);this.A.params.Uf=l;this.A.params.Gg=c;this.A.params.Me=d;this.w.Uf=l;this.w.Gg=c;this.w.Me=d;this.Oz()};
g.h.ZF=function(){g.hn(this.element,"ytp-dragging")};
g.h.Oz=function(){this.Eh(this.D)};
g.h.Eh=function(a){var b=Math.min(this.Av(),this.aa),c=this.zv(),d="";3==this.A.params.qe&&(d="rotate(180deg)");g.ag(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.To(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.Me+2;d=this.w.Uf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Gg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ag(this.element,a)};
g.h.To=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.T||this.D.length>b)b=0,this.T=!1,this.D=[],this.G=this.ca=this.V=null,g.Qd(this.C);for(;b<a.length;b++)M3(this,a[b])};
g.h.Av=function(){return 0};
g.h.zv=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};N3.prototype.B=function(){};P3.prototype.clear=function(){this.A=this.u=this.mode=0;this.o=[];this.reset()};
P3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Q3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];S3.prototype.set=function(a){this.o=a};
S3.prototype.get=function(){return this.o};
T3.prototype.clear=function(){this.o=0};
T3.prototype.update=function(){this.o=2==this.o?1:0};
T3.prototype.matches=function(a,b){return 0!=this.o&&a==this.w&&b==this.u};
U3.prototype.ag=function(a){this.Sd=a.Sd;this.timestamp=a.timestamp};
U3.prototype.reset=function(){this.timestamp=this.Sd=0};
V3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.w[b][c].timestamp=a};
V3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.w[b][c];a=0==d.Sd?a+"_":a+String.fromCharCode(d.Sd)}a+="\n"}return a};
V3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.w[b][c].reset();this.A=a;this.o=0;this.u=this.row=1};
var Kpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Lpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Mpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Npa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];b4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.w=this.D;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
O3.prototype.reset=function(a){this.B=a;this.o.clear();this.A=this.w;this.w.reset(a,0);this.C.reset(a,1)};g.r(g4,g.E);g4.prototype.reset=function(){};g.r(h4,g4);h4.prototype.reset=function(){this.G={};this.u=this.o=null;this.D=!0};
h4.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.w,l={},m=c.getAttribute("p");m&&g.Oa(l,this.w[m]);m=j4(c,"b");null!=m&&(l.bold=
m);m=j4(c,"i");null!=m&&(l.Le=m);m=j4(c,"u");null!=m&&(l.underline=m);m=k4(c,"et");null!=m&&(l.charEdgeStyle=m);m=k4(c,"of");null!=m&&(l.offset=m);m=m4(c,"bc");null!=m&&(l.background=m);m=m4(c,"ec");null!=m&&(l.Eu=m);m=m4(c,"fc");null!=m&&(l.color=m);m=k4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=i4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=i4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=i4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=k4(c,"rb");null!=m&&10!=m&&0!=m&&(l.Wc=10<m?m-1:m);
m=k4(c,"hg");null!=m&&(l.QD=m);c=k4(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.pe=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=n4(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=o4(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=p4(this,d,e,!1);g.H(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.B;m=!!j4(d,"a");n=(i4(d,"t")||0)+n;var q=i4(d,"d")||5E3;m||(!this.D&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.w[d.getAttribute("p")],y=[].concat(g.na(d.childNodes));y.length&&(this.D=null!=d.getAttribute("d"));for(var B=0;B<y.length;B++){var C=y[B],G=void 0;0<B&&(m=!0);var I=void 0;1==C.nodeType&&(I=C);if(I&&"s"==I.tagName){if((C=this.w[I.getAttribute("p")])&&C.Wc&&(1==C.Wc?(C=y.slice(B,
B+4),4==C.length&&(G=f4(n,q,l,m,t,C,this.w),B+=3)):G=f4(n,q,l,m,t,[I],this.w)),!G){var F=I;G=n;I=q;C=l;var M=m,V=t,ha=F.textContent?F.textContent:"",Da=this.w[F.getAttribute("p")];F=i4(F,"t")||0;G=new D3(G+F,I-F,V,C,ha,M,Da)}}else G=new D3(n,q,t,l,C.textContent||"",m,u);k.push(G);this.u=G}if(0<k.length)for(k[0].windowId==this.B&&(this.o=p4(this,d,e,!0),g.H(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.H(l,k),l.o.push(k),c.push(k)}e=c}else e=
[];return e};g.r(q4,I3);q4.prototype.To=function(a){var b=this.A.o;I3.prototype.To.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Oa(d,c.o);g.Oa(d,Vpa);var e=c.o;var f=d}M3(this,c,d)}};
var Vpa={OD:!0};g.r(r4,N3);r4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+F3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new E3(c,d-c,5,f,{textAlign:0,Uf:0,Me:2.5*b,Gg:5.33*a});e=new D3(c,d-c,5,f,e);this.w.push(a);this.w.push(e)}};
g.r(u4,g4);u4.prototype.A=function(a){a=new r4(a,a.byteLength,this.u);if(v4(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.A=t4(a)*(1E3/45):1==a.version&&(a.A=4294967296*t4(a)+t4(a)),a.C=s4(a);0<a.C;a.C--){var b=s4(a),c=s4(a),d=s4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.A,type:this.track,yu:c,zu:d,order:b.o.length}))}Jpa(this.o,a);return a.w}return[]};
u4.prototype.reset=function(){this.o.clear()};g.r(x4,I3);g.h=x4.prototype;g.h.Oz=function(){g.Ym(this.ea)};
g.h.TK=function(){g.hn(this.element,"ytp-rollup-mode");this.Eh(this.Ca,!0)};
g.h.zv=function(){return this.B?this.K:this.J};
g.h.Av=function(){return this.B?this.J:this.K};
g.h.Eh=function(a,b){this.Ca=a;if(this.A.params.Dk){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.xa=this.K;this.J=this.K=0;I3.prototype.Eh.call(this,a);Spa(this,b);I3.prototype.Eh.call(this,a)}else I3.prototype.Eh.call(this,a)};g.r(z4,g4);
z4.prototype.A=function(a,b){for(var c=[],d=a.split(Wpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Xpa.test(f)){var l=S4.exec(f);if(l&&4<=l.length){var m=B4(l[1]),n=B4(l[2])-m;m+=k;var q,t=q=void 0,u=void 0,y=void 0,B=(l=l[3])?l.split(" "):[];l={textAlign:2};B=g.p(B);for(var C=B.next();!C.done;C=B.next())if(C=C.value.split(":"),2==C.length){var G=C[1];switch(C[0]){case "line":C=G.split(",");C[0].endsWith("%")&&(y=C[0],l.Gg=Number.parseInt(y,10),2==C.length&&(u=C[1].trim()));break;case "position":C=G.split(",");
t=C[0];l.Me=Number.parseInt(t,10);2==C.length&&(q=C[1].trim());break;case "align":switch(G){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.Gg=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.Me=0;break;case 1:l.Me=100;break;default:l.Me=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Uf=0>t||8<t?7:t;q=l;f=f.substring(S4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=C4(m,n,5,t),n=new D3(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.H(k,n),k.o.push(n);else for(u=q.split(Ypa),1==u.length?(q=5,t=C4(m,n,q,t)):(y=q=6,t=Object.assign({Ml:32},t),t=new E3(m,n,y,"_"+F3++,t)),c.push(t),y=m,l=0;l<u.length;l++)B=u[l],0==l%2?(C=g.H_("<html>"+B+"</html>"),C.getElementsByTagName("parsererror").length?
(G=C.createElement("span"),G.appendChild(C.createTextNode(B))):G=C.firstChild,A4(this,y,n-(y-m),q,t,0<l,G,f,c)):y=B4(B)+k}S4.lastIndex=0}}return c};
var Xpa=/^NOTE/,Wpa=/(?:\r\n|\r|\n){2,}/,S4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ypa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(D4,g.E);D4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
D4.prototype.reset=function(){this.o&&this.o.reset()};
D4.prototype.Y=function(){this.clear();g.E.prototype.Y.call(this)};g.r(G4,g.vQ);g.h=G4.prototype;g.h.Y=function(){if(this.B||this.H){var a=this.T.app.B;a&&a.oj()}else R4(this,!1);g.vQ.prototype.Y.call(this)};
g.h.load=function(){g.vQ.prototype.load.call(this);var a=!g.R(this.w.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.u)this.o&&(this.Z.clear(),this.B?M4(this,!0):3!=this.player.getPresentingPlayerType()&&this.u.Eq(this.o,"srv3",(0,g.x)(this.CL,this)),!a||this.B||this.H||L4(this)||this.player.la("captionschanged",p3(this.o))),a||(this.o&&!L4(this)?this.player.la("captionschanged",p3(this.o)):this.player.la("onCaptionsTrackListChanged"));else{var b;
this.ia?b=new z3(this.S.ka,this.player):this.ya?b=new u3(this.w,this.S,this.player.getAudioTrack()):b=new C3(this.S.nj,this.S.videoId,this.S.captionsLanguagePreference||this.w.captionsLanguagePreference||g.KC(this.S,"yt:cc_default_lang")||this.w.fc,this.S.cp,this.w);this.u=b;g.H(this,this.u);b.Fq((0,g.x)(this.BL,this))}};
g.h.unload=function(){this.B&&this.o?M4(this,!1):(this.oa&&g.Zm(this.oa),g.BR(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Hg(),this.Z.clear(),this.G&&g.bL(this.player,this.G),this.Ts());g.vQ.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.uI(a.B);this.player.la("captionschanged",{})};
g.h.create=function(){(this.fa?this.B||this.H:I4(this)||H4(this))&&this.load()};
g.h.BL=function(){var a;this.K||H4(this)?a=K4(this,this.K):I4(this)&&(a=J4(this));if(this.B||this.H){for(var b=r3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Tz(e),srclang:q3(e),id:e.toString()};this.H||(f.src=this.u.Fj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Md("TRACK",f))}a=this.T.app.B;a.jj(c);c=a.Za();this.na&&this.P.M(c.textTracks,"change",this.DL)}else!this.o&&a&&O4(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.DL=function(){for(var a=this.T.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=r3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&O4(this,b,!0)};
g.h.mN=function(){!this.o&&this.B||this.unload()};
g.h.CL=function(a,b,c,d){if(a){this.u.pz()&&(this.J=[],g.BR(this.T.app,"captions",void 0),this.aa.hi(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Av(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!w4(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var u=a,y=c,B=d;if(!w4(u))throw Error("Invalid binary caption track data");e.o||(e.o=new u4(B,b));var C=e.o.A(u,y)}else{if("WEBVTT"==a.substring(0,6)){b=a;y=c;e.o||(e.o=new z4);var G=e.o.A(b,y);.01>Math.random()&&
g.qo(Error("Deprecated subtitles format in web player: WebVTT"));u=G}else b:{G=a;y=g.H_(G);if(!y||!y.firstChild){var I=Error("Invalid caption track data");I.params=G;throw I;}if("timedtext"==y.firstChild.tagName){if(3==parseInt(y.firstChild.getAttribute("format"),10)){if(!e.o){G={};if(B=q3(b))G.lang=B,Upa.test(B)&&(G.qe=1);e.o=new h4(G,e.u)}u=e.o.A(y,c);break b}var F=Error("Unsupported subtitles format in web player (Format2)");F.params=G;throw F;}if("transcript"==y.firstChild.tagName){var M=Error("Unsupported subtitles format in web player (Format1)");
M.params=G;throw M;}var V=Error("Invalid caption track data");V.params=G;throw V;}C=u}var ha=C}catch(Da){g.N(Da),e.clear(),ha=[]}else ha=[];g.bL(this.player,ha);!this.K||this.H||L4(this)||g.lz(this.w)||g.mz(this.w)||(g.Zm(this.oa),ha=G3({Uf:0,Me:5,Gg:5,Dk:2,textAlign:0,qe:0,lang:"fr"}),this.V=[ha],e=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.ea||(C=new g.Eu(g.gN()),g.H(this,C),this.ea=C.element),C=ha.end-ha.start,(b=g.Tz(this.o))&&this.V.push(new D3(ha.start,C,0,ha.id,b)),this.V.push(new D3(ha.start,
C,0,ha.id,e[0]),new D3(ha.start,C,0,ha.id,this.ea,!0),new D3(ha.start,C,0,ha.id,e[1],!0)),g.bL(this.player,this.V),g.Xm(this.oa));!this.K||this.H||L4(this)||(N4(this,"module-enabled",!0),this.D&&(this.D.o=this.o),(ha=g.U(this.player.app))&&g.uI(ha.B));this.K=!1}};
g.h.aF=function(a){this.J.push(a);this.aa.hi()};
g.h.bF=function(a){g.ab(this.J,a);this.u instanceof z3&&this.u.C&&g.iU(this.player.app,[a],void 0);this.aa.hi()};
g.h.pM=function(a){if(a instanceof E3){var b=this.U[a.id];b&&b.A!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=Tpa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.da[b]||(this.da[b]=[]),this.da[b].push(a)};
g.h.wM=function(){Q4(this,this.V);this.V=null};
g.h.GA=function(){this.aa.stop();g.Xb(this.da);this.J.sort(g.XD);var a=this.J;if(this.G){var b=(0,g.Td)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.z)(a,this.pM,this);g.Hb(this.U,function(c,d){this.da[d]?(c.element.parentNode||g.fL(this.player,c.element,4),c.Eh(this.da[d])):(c.dispose(),delete this.U[d])},this)};
g.h.BM=function(){E4(this,{},!0);g.R(this.w.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.h.eD=function(){var a=P4.vb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Le?3:a.bold?1:a.Le?2:0,textOpacity:a.textOpacity,windowColor:P4.windowColor,windowOpacity:P4.windowOpacity};var b=F4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.LA=function(a,b){var c={};g.Oa(c,F4(this,"display-settings"));g.Oa(c,a);E4(this,c,b);this.player.la("captionssettingschanged")};
g.h.Ts=function(){!this.B&&this.loaded&&(g.Hb(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.GA())};
g.h.wc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ld(b,-2,4);this.LA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&O4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.w.wb&&N4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.Ka(b))break;if(g.Wb(b)){O4(this,null,!0);break}for(var d=r3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.w!=b.languageName||(c=b.translationLanguage?Dpa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||O4(this,c,!0)}else return this.loaded&&this.o&&!L4(this)?p3(this.o):{};return"";case "tracklist":return this.u?(0,g.ee)(r3(this.u.u,!(!b||!b.includeAsr)),function(k){return p3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||R4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.w.wb&&a.push("stickyLoading");return a};
g.h.ZE=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.eN=function(){this.loaded&&this.o&&!L4(this)?(N4(this,"module-enabled",!1),this.unload(),I4(this,!0)&&O4(this,J4(this),!1)):O4(this,L4(this)||!this.o?K4(this,!0):this.o,!0)};
g.h.vI=function(){var a=L4(this);I4(this,a)?O4(this,this.player.getAudioTrack().Yl,!1):this.S.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.B||this.H:I4(this)||H4(this))&&(a?O4(this,K4(this),!1):this.load()))};g.LQ.captions=G4;})(_yt_player);
