(function(g){var window=this;'use strict';var qab=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},rab=function(a){return g.aI(a)?g.GG(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},sab=function(a,b){var c=new g.uI;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},tab=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.y(f,g.Ux(),2);if(3!=f.j){d=f.u;if(!d)throw g.tx("gct");return g.y(f,g.jJ(d),3)}e=f.u;return f.return(e.get("captions",c))})},uab=function(a,b,c){tab(a,b).then(function(d){d&&c(d.trackData,new g.uI(d.metadata))})},xab=function(a){if(!vab.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(wab,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},yab=function(){return g.fB("yt-player-caption-display-settings")},B4=function(){this.segments=[]},zab=function(a,b){var c=g.zb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.ob(a.segments,c),g.ob(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.xb(a.segments,c,0,b),g.xb(a.segments,c+1,0,b)))},Aab=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.ea=c;this.T=d;this.D=e;this.Z=f;this.C=new B4;this.I=-1;this.B=this.u=this.j=null;this.J=new g.Tn(this.BT,1E3,this);this.events=new g.HF(this);g.E(this,this.J);g.E(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.zy);this.zy();this.BT()},Bab=function(a){return a.j&&a.j.C?a.j.C+a.player.Ld()<a.player.getCurrentTime():!1},Cab=function(a,b){var c=g.OE(b,a.policy,{}).Ue(),d={format:"RAW",
withCredentials:!0};a.policy.Ya&&(d.method="POST",d.postBody=b.Au()||(0,g.zX)([120,0]));a.D&&(d.responseType="arraybuffer");a.B=g.$v(c,d,3,100).then(function(e){a:{e=e.xhr;a.isDisposed();if(a.u){var f=!(a.D?e.response:e.responseText)||400<=e.status,h=g.Sua(e);if(h){e=g.OE(a.u,a.policy,{});a.u.lk(e,h);Cab(a,a.u);break a}f?a.player.xa("capfail",{status:e.status}):(a.player.Hh().dj("fcb_r"),h=a.u.bb[0].Na,null!=a.T&&a.I!==h&&(f=a.u.bb[0],a.D?a.T(e.response,1E3*(f.startTime+a.player.Ld())):a.T(e.responseText,
1E3*(f.startTime+a.player.Ld())),a.I=h))}a.u=null;a.B=null}}).Tj(function(e){a.u=null;
a.B=null;var f;a.player.xa("capfail",{status:null==(f=e.xhr)?void 0:f.status})});
a.u=b;zab(a.C,a.u.bb[0].Na)},C4=function(a,b){g.UQ.call(this,b.V());
this.u=a;this.F=b;this.B=null;this.D=!1;this.I=g.cI(this.F.V())&&!this.u.isManifestless},Eab=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.XQ(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.F.V().S("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.s9a.get(e);null==q&&(q=Dab[e]||Dab[e.replace(/-/g,"_")],g.s9a.set(e,q));h=q||h}c.push(new g.uI({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Fab=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},Gab=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.XQ(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},Iab=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in Hab?Hab.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.Bz=d;var e=function(f){return function(){return String(a[f.Bz])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.Bz+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.Bz,"gi"),e);c={Bz:c.Bz}}return b},D4=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Ce);a.params.Ce&&Object.assign(q,a.params.Ce);Object.assign(q,c.Ce);p.Ce=q;var r=1===p.Uh,v=[{G:"span",K:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],x,z,B;(l=l.ib("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(z=x.captions)?void 0:null==(B=z.playerCaptionsTracklistRenderer)?void 0:B.openTranscriptCommand))&&v.unshift({G:"button",K:"caption-edit",
X:{tabindex:"0","aria-label":Iab()},W:[{G:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{G:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{G:"div",K:"caption-window",X:{id:"caption-window-"+a.id,dir:r?"rtl":"ltr",tabindex:"0",lang:p.lang},W:v});var D=this;this.I=[];this.Ba=!1;this.u=a;this.Ma=
this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.J=null;this.maxWidth=.96*f;this.Wa=.96*h;this.j=p;this.Nc=c;this.oa=b;this.C=this.Ea("captions-text");this.hc=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Qa=Jab(d,e,f,h);this.Hc=m;l&&(this.D=this.Ea("caption-edit"),this.N(this.D,"click",function(){D.Hc()}));
this.type=0;this.gb=this.Qa*Kab(q);a=new g.US(this.element,!0);g.E(this,a);a.subscribe("dragstart",this.bY,this);a.subscribe("dragmove",this.aY,this);a.subscribe("dragend",this.ZX,this);this.wb=this.ob=this.Tb=this.Gb=0;a="";this.j.windowOpacity&&(a=xab(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":Lab[this.j.textAlign]};this.hc&&(b["border-radius"]=a?this.gb/8+"px":"");(this.B=2===this.u.params.Uh||
3===this.u.params.Uh)&&Mab(this,this.element);g.ul(this.element,b);switch(this.j.fl){case 0:case 1:case 2:g.ao(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.ao(this.element,"ytp-caption-window-bottom")}},Mab=function(a,b){var c="vertical-rl";
1===a.j.eO&&(c="vertical-lr");g.Fe&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.ul(b,"-o-writing-mode",c);g.ul(b,"-webkit-writing-mode",c);g.ul(b,"writing-mode",c);g.ul(b,"text-orientation","upright");g.ao(b,"ytp-vertical-caption");3===a.u.params.Uh&&(g.ul(b,"text-orientation",""),g.ul(b,"transform","rotate(180deg)"))},Kab=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Nab=function(a,b){var c={},d=b.background?b.background:a.j.Ce.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Ce.backgroundOpacity;d=xab(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.hc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.gb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Qa*Kab(b)+"px";d=1;e=b.color||a.j.Ce.color;if(b.color||null!=b.textOpacity)e=xab(e),d=null==b.textOpacity?a.j.Ce.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.sJ&&(h=e=b.sJ);var l=a.Qa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.kw()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Ce.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.o2&&(c.visibility="hidden");1===b.XS&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.eI||g.rx,3===a.u.params.Uh?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Wm||2===b.Wm||3===b.Wm||4===b.Wm||5===b.Wm)if(g.eI)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Wm){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Oab=function(a){a.J=g.Ne("SPAN");
g.ul(a.J,{display:"block"});g.ao(a.J,"caption-visual-line");a.C.appendChild(a.J)},Pab=function(a,b){var c=g.Ne("SPAN");
g.ul(c,{display:"inline-block","white-space":"pre-wrap"});g.ul(c,Nab(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.ul(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ul(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Qab=function(a,b,c){a.Ba=a.Ba||!!c;
var d={};Object.assign(d,a.j.Ce);Object.assign(d,c||b.j);Object.assign(d,a.Nc.Ce);(c=!a.J)&&Oab(a);for(var e=a.Ka&&a.Ma&&g.Wc(d,a.Ma)?a.Ka:Pab(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Oab(a),e=Pab(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Oe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.eI||!g.wl(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.wl(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Cc?g.ul(e,m,"1em"):g.ul(e,m,"0.5em")))}a.Ma=d;a.Ka=e;a.I.push(b)},Jab=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},E4=function(a,b,c,d){g.UQ.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.C=b.qJ},F4=function(a,b,c,d,e,f,h,l,m,n){D4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},G4=function(a,b,c,d,e,f,h,l,m,n){D4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.T=[];this.ea=this.Z=this.Va=0;this.Aa=NaN;this.Rb=0;this.Bc=null;this.Ya=new g.Tn(this.s5,433,this);this.D&&(n.rb(this.D,this,167342),this.N(this.D,"click",function(){n.sb(p.D)}),a=new g.US(this.element,!0),g.E(this,a),a.subscribe("hoverstart",function(){n.Sa(p.D,!0)},this));
g.ao(this.element,"ytp-caption-window-rollup");g.E(this,this.Ya);g.ul(this.element,"overflow","hidden")},Rab=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.eO&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},Sab=function(a){a.T=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.qq,c=0,d=0,e=a.T.length-1;c<b&&-1<e;){var f=a.T[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.T.length<b&&(d*=b/a.T.length);a.Z=d;b=Math;c=b.max;isNaN(a.Aa)&&((d=a.j.Xq)?(e=g.Ne("SPAN"),g.Ve(e,"\u2013".repeat(d)),g.ul(e,Nab(a,a.j.Ce)),a.C.appendChild(e),a.Aa=e.offsetWidth,a.C.removeChild(e)):a.Aa=0);d=a.C;a.ea=c.call(b,a.Aa,a.Rb,(a.B?d.offsetHeight:d.offsetWidth)+1)},Uab=function(a,b){Sab(a);
var c=a.T.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.Z-c;if(c!==a.Va){var d=0<c&&0===a.Va;b||isNaN(c)||d||(g.ao(a.element,"ytp-rollup-mode"),g.Un(a.Ya));g.ul(a.C,"transform",Rab(a,c));a.Va=c}Sab(a)},H4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.JB.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},I4=function(a,b,c,d,e){g.JB.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Vab=function(a){var b="_"+J4++;
return new I4(0,0x8000000000000,0,b,a)},Xab=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Jf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Wab(l.textContent,n.textContent,p.textContent,f.textContent,h);return new H4(a,b,e,c,l,d,m)}switch(m.Jf){case 9:case 10:m.Wm=1;break;case 11:m.Wm=2;break;case 12:m.Wm=3;break;case 13:m.Wm=4;break;case 14:m.Wm=5}return new H4(a,b,e,c,l.textContent||"",d,m)},Wab=function(a,b,c,d,e){var f=g.kw(),h=
f?g.Ne("DIV"):g.Ne("RUBY"),l=g.Ne("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ne("DIV"):g.Ne("RP");a.textContent=b;h.appendChild(a);b=f?g.Ne("DIV"):g.Ne("RT");b.textContent=c;h.appendChild(b);c=e.Jf;if(10===c||11===c||12===c||13===c||14===c)if(g.ul(b,"text-emphasis-style","filled circle"),g.ul(b,"text-emphasis-color","currentcolor"),g.ul(b,"webkit-text-emphasis","filled circle"),11===e.Jf||13===e.Jf)g.ul(b,"webkit-text-emphasis-position","under left"),g.ul(b,"text-emphasis-position","under left");c=!0;if(4===e.Jf||7===e.Jf||12===e.Jf||
14===e.Jf)g.ul(h,"ruby-position","over"),g.ul(h,"-webkit-ruby-position","before");else if(5===e.Jf||6===e.Jf||11===e.Jf||13===e.Jf)g.ul(h,"ruby-position","under"),g.ul(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ne("DIV"):g.Ne("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ul(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ul(f,"display","none"),f=f.nextElementSibling,g.ul(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ul(h.lastElementChild,"display","none"),d?(g.ul(h,"padding-top","0.6em"),g.ul(f,"top","0")):(g.ul(h,"padding-bottom","0.6em"),g.ul(f,"bottom","0")));return h},K4=function(){g.C.apply(this,arguments)},L4=function(a){K4.call(this);
this.C=a;this.pens={};this.T={};this.Z={};this.D="_"+J4++;this.J={};this.B=this.j=null;this.I=!0},M4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},N4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},O4=function(a,b){a=M4(a,b);
return void 0!==a?a:null},Q4=function(a,b){a=a.getAttribute(b);
if(null!=a)return P4.test(a),a},Yab=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=O4(b,"mh");null!=a&&(c.oy=a);a=O4(b,"ju");null!=a&&(c.textAlign=a);a=O4(b,"pd");null!=a&&(c.Uh=a);a=O4(b,"sd");null!=a&&(c.eO=a);a=Q4(b,"wfc");null!=a&&(c.windowColor=a);b=M4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Zab=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.T[d]);a=O4(b,"ap");null!=a&&(c.fl=a);a=M4(b,"cc");null!=a&&(c.Xq=a);a=M4(b,"ah");null!=a&&(c.Gj=a);a=M4(b,"rc");null!=a&&(c.qq=a);b=M4(b,"av");null!=b&&(c.Xm=b);return c},$ab=function(a,b,c,d){var e={};
Object.assign(e,Zab(a,b));Object.assign(e,Yab(a,b));d?g.Wc(e,a.C)?(d=a.D,e=a.C):d="_"+J4++:d=b.getAttribute("id")||"_"+J4++;a=M4(b,"t")+c;b=M4(b,"d")||0x8000000000000;if(2===e.Uh||3===e.Uh)c=e.qq,e.qq=e.Xq,e.Xq=c;return new I4(a,b,0,d,e)},R4=function(a){K4.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},S4=function(a){a=g.ce(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},abb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.qq=a);b=b.ccColCount;void 0!==b&&(f.Xq=b);if(2===f.Uh||3===f.Uh)b=f.qq,f.qq=f.Xq,f.Xq=b;return new I4(c,d,0,e,f)},cbb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new bbb(this);this.D=new bbb(this);this.j=[];this.clear()},ebb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Nt:a,
Tq:b,result:0};a=dbb[a];b=dbb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Tq===d;if(d)return{Nt:a,Tq:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Nt:a,Tq:b,result:2};return{Nt:a,Tq:b,result:3}},gbb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,fbb(a.C,b,c,d))},hbb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?gbb(a,d.mR,d.nR,b):1===d.type&&a.u&496&&fbb(a.D,d.mR,d.nR,b);a.j.length=0},T4=function(){this.type=0},U4=function(){this.state=this.Tq=this.Nt=0},ibb=function(){this.timestamp=this.j=0},V4=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new T4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new ibb}},W4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},nbb=function(a,b){switch(a){case 0:return jbb[(b&127)-32];
case 1:return kbb[b&15];case 2:return lbb[b&31];case 3:return mbb[b&31]}return 0},X4=function(a){return a.B[a.row][a.u]},Y4=function(a,b,c){2<=b&&1<a.u&&(--a.u,X4(a).j=0);
var d=X4(a);d.timestamp=a.D.time+0;d.j=nbb(b,c);32>a.u&&a.u++},obb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},Z4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},pbb=function(a){a.row=0<a.j?a.j:1;
a.u=1;Z4(a,0,15)},qbb=function(a){this.B=a;
this.D=0;this.style=new T4;this.I=new V4(this.B);this.J=new V4(this.B);this.text=new V4(this.B);this.u=this.I;this.C=this.J;this.j=this.u},rbb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(W4(d,c),pbb(a.u),pbb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(W4(d,c),Z4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},sbb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},tbb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},bbb=function(a){this.j=a;
this.D=0;this.B=new qbb(this.j);this.I=new qbb(this.j);this.u=new U4;this.C=this.B},fbb=function(a,b,c,d){a.u.update();
b=ebb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Nt;c=b.Tq;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&Y4(a,0,b),c&96&&Y4(a,0,c),0!==b&&0!==c&&3===a.style.type&&W4(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Nt=e,b.Tq=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;obb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Z4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:Y4(b.j,0,32);break a;case 48:57===c?(d=b.j,X4(d).j=0,32>d.u&&d.u++):Y4(b.j,1,c&15)}break;case 2:c&32&&Y4(b.j,2,c&31);break;case 3:c&32&&Y4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:sbb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,X4(d).j=0);break;case 36:d=b.j;b=X4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:rbb(b,2,d);break;case 38:rbb(b,3,d);break;case 39:rbb(b,4,d);break;case 40:Y4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);pbb(d);tbb(b);break;case 43:tbb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:W4(a,d)}Z4(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;W4(a,d);obb(a,b,b+1,a.j-1);Z4(a,a.row,1)}break;case 46:Z4(b.C,0,15);break;case 47:W4(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,sbb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},ubb=function(){},$4=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},a5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},b5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},c5=function(a,b){K4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new cbb;this.j.u=1<<this.track},wbb=function(a){if("string"===typeof a)return!1;
a=new $4(a,8,0);return vbb(a)},vbb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==b5(a))return!1;
a.version=a5(a);if(1<a.version)return!1;a5(a);a5(a);a5(a);return!0},d5=function(){K4.call(this)},xbb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new H4(b,c,d,e.id,p.nodeValue,f||0<n,g.Tc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);xbb(a,b,c,d,e,!0,p,q,m)}}},ybb=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},zbb=function(a,b,c,d){d=Object.assign({oy:0},d);
return new I4(a,b,c,"_"+J4++,d)},e5=function(a,b){g.C.call(this);
this.F=a;this.Y=b;this.parser=null;this.j=this.F.Fx()},Fbb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=Abb(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.UN;l="string"!==typeof q?l.concat(Bbb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(Cbb(a,q,r)):l.concat(Dbb(a,c,q,r))}var v=l}catch(x){g.CA(x),a.clear(),v=[]}if(0!==v.length)return v}b=Ebb(b);if(!b)return[];try{return"string"!==typeof b?Bbb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Cbb(a,b,d):Dbb(a,c,b,d)}catch(x){return g.CA(x),a.clear(),[]}},Ebb=function(a){if("string"===
typeof a||wbb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.QD(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.BD(a)},Abb=function(a,b,c){if("string"===typeof b||wbb(b))return[{trackData:b,
UN:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.Gta(d);if(a.j&&e){var f=g.yta(e),h=g.zta(e);e=e.j;f&&e&&a.j.XC(e,f,h)}f=g.ZD(d,1835295092);if(!f||!f.length||!f[0].size)return[];a=[];f=g.t(f.entries());for(h=f.next();!h.done;h=f.next())e=g.t(h.value),h=e.next().value,e=e.next().value,e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.BD(e),a.push({trackData:e,UN:c+1E3*h});Gbb(d,a,c);return a=a.filter(function(l){return!!l.trackData})},
Gbb=function(a,b,c){var d=g.QD(a,0,1836476516),e=9E4;
d&&(e=g.RD(d)||9E4);d=0;var f=g.ZD(a,1836019558);f=g.t(f.entries());for(var h=f.next();!h.done;h=f.next()){var l=g.t(h.value);h=l.next().value;l=l.next().value;h<b.length&&(l=g.QD(a,l.dataOffset,1953653094))&&(l=g.QD(a,l.dataOffset,1952867444))&&(l=g.XD(l)/e*1E3,0===h&&(d=l),b[h].UN=l-d+c||c*h*1E3)}},Bbb=function(a,b,c,d,e){if(!wbb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new c5(e,b));return a.parser.u(c,d)},Cbb=function(a,b,c){a.parser||(a.parser=new d5);
a=a.parser.u(b,c);.01>Math.random()&&g.DA(Error("Deprecated subtitles format in web player: WebVTT"));return a},Dbb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new R4(Hbb(b))),a.parser.u(c,d)}catch(f){return g.CA(f),[]}var e=g.z4a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new L4(Hbb(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Hbb=function(a){var b=
{};
if(a=g.xI(a))b.lang=a,g.S5a.test(a)&&(b.Uh=1);return b},f5=function(a){g.RQ.call(this,a);
var b=this;this.F=a;this.Y=this.F.V();this.videoData=this.F.getVideoData();this.wb=this.F.fb();this.B={Ce:{}};this.D={Ce:{}};this.Ba=[];this.ea={};this.Va={};this.ya=!1;this.hc=g.oK(this.videoData);this.gb=g.LKa(this.videoData,this.F);this.Rb=!!this.videoData.captionTracks.length;this.xc=!!this.videoData.mf;this.Ya="3"===this.Y.controlsType;this.u=this.I=this.J=this.Qa=this.ob=null;this.Wa=new e5(this.F,this.Y);this.j=null;this.Aa=new g.HF(this);this.T=new g.T({G:"div",K:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.Z={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.Uo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Io(d));this.storage=c;var e;this.Gb=!(null==(e=a.Ae())||!e.RC());this.C=Ibb(this);this.oa=!this.C&&this.Ya&&this.Gb&&this.gb;g.E(this,this.Wa);this.C?this.Ma=this.Ka=null:(this.Ka=new g.Rn(this.vO,void 0,this),g.E(this,this.Ka),this.Ma=new g.Tn(this.N6,2E3,this),g.E(this,this.Ma));g.E(this,this.Aa);g.iQ(this.player,this.T.element,
4);g.E(this,this.T);this.C||this.Aa.N(a,"resize",this.yO);(this.Tb=g.HH(this.Y)&&!g.lA()&&!this.F.isFullscreen()&&!this.C&&!this.oa)&&this.Aa.N(a,"resize",this.C4);this.Aa.N(a,"onPlaybackAudioChange",this.S3);this.Aa.N(a,g.LB("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.N(a,g.MB("captions"),function(f){b.onCueRangeExit(f)});
Jbb(this,yab()||{})},Mbb=function(a){if(1===a.Y.ob||1===a.videoData.pL||"alwayson"===g.YJ(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.Y.ob){if(g.aI(a.Y))var c=Kbb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=qab(a.player.getAudioTrack(),g.aI(a.Y));var d=g.YJ(a.videoData,"yt:cc");if(void 0===Lbb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.YJ(a.videoData,"yt:cc")},g5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.u||"FORCED_ON"===a.B},Lbb=function(a){var b=void 0,c=g.Mw(g.Lw.getInstance(),65);
if(g.aI(a.Y)&&null!=c){if(null!=Kbb(a))return!1;b=!c}return b},Nbb=function(a){var b;
a.hc?b=new E4(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.gb?b=new C4(a.videoData.j,a.player):a.Rb?b=new g.VQ(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.YQ(a.Y,a.videoData.mf,a.videoData.videoId,g.gCa(a.videoData),a.videoData.Xl);return b},i5=function(a,b){if(a.u){if(a.I&&a.I.C)return a.I.C;
b||(b=a.xc?!1:a.Rb?!1:!0);b=b||!!g.Mw(g.Lw.getInstance(),66);b=g.SQ(a.u.j,b);if(rab(a.Y)){var c=a.F.isInline()?void 0:g.fB("yt-player-caption-sticky-language");c=[c,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.YJ(a.videoData,"yt:cc_default_lang")];for(var d=!1,e=0;e<c.length;e++){var f=c[e];if(f){d=!0;for(var h=0;h<b.length;h++)if(g.xI(b[h])===f)return b[h];f=f.split("-")[0];for(h=0;h<b.length;h++)if(g.xI(b[h])===f)return b[h]}}if(d){var l;return(null==(l=a.I)?void 0:l.j)||
h5(a)}}else for(l=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.YJ(a.videoData,"yt:cc_default_lang")],c=0;c<l.length;c++)for(d=0;d<b.length;d++)if(g.xI(b[d])===l[c])return b[d];return a.I&&a.I.j?a.I.j:(l=b.find(function(m){return m.isDefault}))?l:b[0]||h5(a)}return null},h5=function(a){return a.I&&a.I.u},j5=function(a){var b=h5(a);
return!!b&&a.j===b},Obb=function(a){g.SQ(a.u.j,!0);
var b=qab(a.player.getAudioTrack(),g.aI(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=i5(a,a.ya):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&g5(a)?c=h5(a):Lbb(a)||a.ya||Mbb(a)?c=i5(a,a.ya):g5(a)&&(c=h5(a));if(a.C||a.oa){var d=g.SQ(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Ne("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.vI(f));h.setAttribute("srclang",g.xI(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.u.yu(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.F.Ae();c.bA(b);c=c.vb();a.Gb&&a.Aa.N(c.textTracks,"change",a.a6)}else!a.j&&c&&k5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},Pbb=function(a,b){var c=a.F.Ae().vb().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},k5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ya=c,a.ya&&(g.aI(a.Y)?l5(a,!!b):m5(a,!!b)));a.j=b;g5(a)&&(a.j=h5(a));a.load()},Rbb=function(a,b){if(b instanceof I4){var c=a.ea[b.id];
c&&c.u!==b&&(c.dispose(),delete a.ea[b.id],c=null);c||(c=Qbb(a,b))&&(a.ea[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},Qbb=function(a,b){var c=a.wb.getVideoContentRect(!0).height,d=a.wb.getVideoContentRect(!0).width;
if(!c||!d)return null;var e=a.j?g.xI(a.j):null;e&&g.S5a.test(e)&&(b.params.Uh=1);var f=a.wb.getPlayerSize();c*=a.Z.height;d*=a.Z.width;e=f.height*a.Z.height;f=f.width*a.Z.width;"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.oy?b.params.oy:1<b.j.length?1:0){case 1:return new F4(b,a.B,a.D,d,c,f,e,a.Y.experiments,a.NH.bind(a),a.F);case 2:return new G4(b,a.B,a.D,d,c,f,e,a.Y.experiments,a.NH.bind(a),a.F);default:return new D4(b,a.B,a.D,d,c,f,e,a.Y.experiments,
a.NH.bind(a),a.F)}},Jbb=function(a,b,c){c=void 0===c?!1:c;
var d=n5.Ce;a.B={};Object.assign(a.B,n5);a.B.Ce={};Object.assign(a.B.Ce,d);a.D={Ce:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;P4.test(f);e.Ce.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;P4.test(f);e.Ce.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||n5.windowColor;P4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ce.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Ce.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ce;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ce.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=n5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ce.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ce.fontFamily=f;a.loaded&&a.yO();c&&g.eB("yt-player-caption-display-settings",b,2592E3)},Tbb=function(a,b,c){b&&!a.J?(b=Vab({Uh:0,
lang:"fr"}),a.J=[b,new H4(b.start,b.end-b.start,0,b.id,null!=c?c:"Aper\u00e7u des sous-titres")],a.player.Ke(a.J)):!b&&a.J&&(Sbb(a,a.J),a.J=null)},Sbb=function(a,b){a.player.Th(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.pb(a.Ba,c.value);g.Sn(a.Ka)},m5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},l5=function(a,b){a.F.isInline()||g.eB("yt-player-sticky-caption",b,2592E3)},Kbb=function(a){if(!a.F.isInline())return g.fB("yt-player-sticky-caption")},Ibb=function(a){var b,c=!(null==(b=a.F.Ae())||!b.QC());
return a.Ya&&c&&!a.gb};
g.EV.prototype.NA=g.ba(41,function(a){var b=2;this.Ya.has(a)?b=0:g.GOa(this,a)&&(b=1);return b});
g.iY.prototype.NA=g.ba(40,function(a){return this.wd.NA(a)});
g.EV.prototype.XC=g.ba(39,function(a,b,c){this.Ba.set(a,{du:b,Zz:c})});
g.iY.prototype.XC=g.ba(38,function(a,b,c){this.wd.XC(a,b,c)});
g.lR.prototype.ax=g.ba(31,function(){for(var a=g.Be(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Se(a[b])});
g.nV.prototype.ax=g.ba(30,function(){this.mediaElement.ax()});
g.lR.prototype.RC=g.ba(29,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.nV.prototype.RC=g.ba(28,function(){return this.mediaElement.RC()});
g.lR.prototype.QC=g.ba(27,function(){return!!this.j.textTracks});
g.nV.prototype.QC=g.ba(26,function(){return this.mediaElement.QC()});
g.lR.prototype.bA=g.ba(25,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.nV.prototype.bA=g.ba(24,function(a){this.mediaElement.bA(a)});
g.UQ.prototype.SM=g.ba(23,function(){return!1});
g.UQ.prototype.ls=g.ba(22,function(){});
g.VQ.prototype.ls=g.ba(21,function(a,b,c){var d=this;this.isDisposed();b=this.yu(a,b);this.Fq();this.u=g.Wv(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.YQ.prototype.ls=g.ba(20,function(a,b,c){var d=this;this.isDisposed();b=this.yu(a,b);this.Fq();this.u=g.Wv(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.cY.prototype.eB=g.ba(10,function(){return this.I});
g.nZ.prototype.eB=g.ba(9,function(){var a;return(null==(a=g.UP(this))?void 0:a.Fx())||null});
g.bQ.prototype.Fx=g.ba(8,function(){return this.app.eB()});
g.$Y.prototype.Fx=g.ba(7,function(){var a;return(null==(a=this.Ja)?void 0:a.eB())||null});
g.pD.prototype.XE=g.ba(3,function(a){return(a=this.Wn(a))?a.j:0});
g.cF.prototype.XE=g.ba(2,function(){return 0});
var wab=/#(.)(.)(.)/,vab=/^#(?:[0-9a-f]{3}){1,2}$/i,Dab={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};B4.prototype.contains=function(a){a=g.zb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
B4.prototype.length=function(){return this.segments.length/2};
g.w(Aab,g.C);g.k=Aab.prototype;g.k.ra=function(){g.C.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.zy=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ld();var b=this.j;this.j=g.eb(this.ea.Nr(a).bb);b!==this.j&&this.Z&&this.Z()};
g.k.reset=function(){this.C=new B4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.BT=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Nq(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.Rz(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Fx()){var c=a.bb[0].j.info.id,d=a.bb[0].Na,e=a.bb[0].B;if(this.policy.Ya){if(b=b.Au(e,d,c,3))a.J=b}else if(c=b.Xn(e,d,c,3))if(b=b.NA(d),0===b)c&&(a.u=new g.iD(c));else if(2===b){this.J.start();Bab(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.bb[0].duration?(this.C.contains(a.bb[0].Na)||Cab(this,a),this.j=g.eb(a.bb)):Bab(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.w(C4,g.UQ);g.k=C4.prototype;g.k.ls=function(a,b,c){var d=this;this.Fq();b=Fab(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?Gab(this,b,"386"):Gab(this,b));if(b){var e=1E3*(b.index.XE(b.index.qm())-b.index.getStartTime(b.index.qm())),f=new g.WQ(this.Y);this.B=new Aab(f,this.F,b,function(h,l){c(h,a,l,e)},this.I||g.aF(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.SM=function(){var a=this.D;this.D=!1;return a};
g.k.by=function(a){var b=this.I?[new g.uI({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.uI({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?Eab(this,"386"):Eab(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.TQ(this.j,c.value);a()};
g.k.Fq=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.yu=function(){return""};
var P4=/^#(?:[0-9a-f]{3}){1,2}$/i,Hab=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ea("yt.msgs_",Hab);var Lab=["left","right","center","justify"];g.w(D4,g.T);g.k=D4.prototype;g.k.bY=function(a,b){this.ob=a;this.wb=b;var c=g.Dl(this.element,this.element.parentElement);this.Gb=a-c.x;this.Tb=b-c.y};
g.k.aY=function(a,b){if(a!==this.ob||b!==this.wb){g.$n(this.element,"ytp-dragging")||g.ao(this.element,"ytp-dragging");var c=g.Fl(this.element);a=a-this.Gb-.02*this.playerWidth;var d=b-this.Tb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ce(e,0,2));var f=(d+c.height/2)/this.Wa*3;f=Math.floor(g.ce(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ce(a,0,1);c=(d+f/2*c.height)/this.Wa;c=100*g.ce(c,0,1);this.u.params.fl=b;this.u.params.Xm=c;this.u.params.Gj=a;this.u.params.isDefault=
!1;this.j.fl=b;this.j.Xm=c;this.j.Gj=a;this.j.isDefault=!1;this.oa.fl=b;this.oa.Xm=c;this.oa.Gj=a;this.oa.isDefault=!1;this.AV()}};
g.k.ZX=function(){g.co(this.element,"ytp-dragging")};
g.k.AV=function(){this.Uy(this.I)};
g.k.getType=function(){return this.type};
g.k.Uy=function(a){var b=Math.min(this.jS(),this.maxWidth),c=this.iS(),d="";3===this.u.params.Uh&&(d="rotate(180deg)");g.ul(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.aJ(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Gj+2,f=this.j.fl;switch(f){case 0:case 3:case 6:(b=this.j.Ce.fontSizeIncrement)&&0<b&&2!==this.j.Uh&&3!==
this.j.Uh&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.Xm+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.ul(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);a=c/d;this.D.style.height=a+"px";this.D.style.width=a+"px";this.element.style.paddingLeft=a+5+"px";this.element.style.paddingRight=a+5+"px";this.element.style.marginLeft="-"+(a+5)+"px";this.element.style.marginRight="-"+(a+5)+"px"}};
g.k.aJ=function(a){var b;for(b=0;b<a.length&&a[b]===this.I[b];b++);if(this.Ba||this.I.length>b)b=0,this.Ba=!1,this.I=[],this.J=this.Ma=this.Ka=null,g.Qe(this.C);for(;b<a.length;b++)Qab(this,a[b])};
g.k.jS=function(){return 0};
g.k.iS=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};g.w(E4,g.UQ);E4.prototype.ls=function(a,b,c){uab(this.videoData.videoId,a.vssId,c)};
E4.prototype.by=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.TQ(this.j,c.value);a()};g.w(F4,D4);F4.prototype.aJ=function(a){var b=this.u.j;D4.prototype.aJ.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Ubb);var e=c.j;var f=d}Qab(this,c,d)}};
var Ubb={o2:!0};g.w(G4,D4);g.k=G4.prototype;g.k.AV=function(){g.Vn(this.Ya)};
g.k.s5=function(){g.co(this.element,"ytp-rollup-mode");this.Uy(this.Bc,!0)};
g.k.iS=function(){return this.B?this.ea:this.Z};
g.k.jS=function(){return this.B?this.Z:this.ea};
g.k.Uy=function(a,b){this.Bc=a;if(this.u.params.qq){for(var c=0,d=0;d<this.I.length&&c<a.length;d++)this.I[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.I.concat(a.slice(c)));this.Rb=this.ea;this.Z=this.ea=0;D4.prototype.Uy.call(this,a);Uab(this,b)}D4.prototype.Uy.call(this,a)};g.w(H4,g.JB);H4.prototype.toString=function(){return g.JB.prototype.toString.call(this)};g.w(I4,g.JB);I4.prototype.toString=function(){return g.JB.prototype.toString.call(this)};
var J4=0;g.w(K4,g.C);K4.prototype.u=function(){return[]};
K4.prototype.reset=function(){};g.w(L4,K4);L4.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
L4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=N4(a,"b");
null!=l&&(h.bold=l);l=N4(a,"i");null!=l&&(h.italic=l);l=N4(a,"u");null!=l&&(h.underline=l);l=O4(a,"et");null!=l&&(h.charEdgeStyle=l);l=O4(a,"of");null!=l&&(h.offset=l);l=Q4(a,"bc");null!=l&&(h.background=l);l=Q4(a,"ec");null!=l&&(h.sJ=l);l=Q4(a,"fc");null!=l&&(h.color=l);l=O4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=M4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=M4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=M4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=O4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Jf=10<l?l-1:l);a=O4(a,"hg");null!=a&&(h.XS=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Yab(this,a);break;case "wp":c=a.getAttribute("id"),this.T[c]=Zab(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=$ab(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!N4(a,"a");l=(M4(a,"t")||0)+l;var m=M4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var v=q[r],x=void 0;0<r&&(h=!0);var z=void 0;1===v.nodeType&&(z=v);if(z&&"s"===z.tagName){if((v=(v=z.getAttribute("p"))?this.pens[v]:null)&&v.Jf&&(1===v.Jf?(v=q.slice(r,r+
4),4===v.length&&(x=Xab(l,m,f,h,n,v,this.pens),r+=3)):x=Xab(l,m,f,h,n,[z],this.pens)),!x){var B=z;x=l;z=m;v=f;var D=h,G=n,F=B.textContent?B.textContent:"",K=B.getAttribute("p");K=K?this.pens[K]:null;B=M4(B,"t")||0;x=new H4(x+B,z-B,G,v,F,D,K)}}else x=new H4(l,m,n,f,v.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=$ab(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Vbb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(R4,K4);R4.prototype.reset=function(){this.B.clear()};
R4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.sJ=S4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=S4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=S4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Jf=10<h?h-1:h,f.Wm=Vbb.get(f.Jf));e.hgHorizGroup&&(f.XS=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.oy=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Uh=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.eO=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=S4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Gj=e.ahHorPos),void 0!==e.apPoint&&(f.fl=e.apPoint),void 0!==e.avVerPos&&(f.Xm=e.avVerPos),void 0!==e.ccCols&&(f.Xq=e.ccCols),void 0!==e.rcRows&&(f.qq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=abb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+J4++,h=abb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],v=r.utf8;if(v){var x=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.oy?h.params.oy:1<h.j.length?1:0)&&m&&"\n"===v)continue;if(r=z&&1===z.Jf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.Jf&&2===B.Jf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.Jf||3>B.Jf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.Jf&&2===B.Jf?!0:!1)):r=!1}if(r){x=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var D=this.j.get(p[l+2].pPenId);v=Wab(v,x,B,r,D);m=new H4(d,e,n,f,v,m,z);l+=3}else m=new H4(d+x,e-x,n,h.id,v,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};cbb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
cbb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var dbb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];T4.prototype.set=function(a){this.type=a};
T4.prototype.get=function(){return this.type};
U4.prototype.clear=function(){this.state=0};
U4.prototype.update=function(){this.state=2===this.state?1:0};
U4.prototype.isValid=function(){return 0!==this.state};
U4.prototype.matches=function(a,b){return this.isValid()&&a===this.Nt&&b===this.Tq};
ibb.prototype.reset=function(){this.timestamp=this.j=0};
V4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
V4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
V4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var jbb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],kbb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],lbb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],mbb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];qbb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
bbb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};ubb.prototype.C=function(){};g.w($4,ubb);$4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+J4++;c=c/1E3-this.I;d=d/1E3-this.I;a=new I4(c,d-c,5,f,{textAlign:0,fl:0,Gj:2.5*b,Xm:5.33*a});e=new H4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.w(c5,K4);c5.prototype.u=function(a){a=new $4(a,a.byteLength,this.B);if(vbb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=b5(a)*(1E3/45):1===a.version&&(a.B=4294967296*b5(a)+b5(a)),a.D=a5(a);0<a.D;a.D--){var b=a5(a),c=a5(a),d=a5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,mR:c,nR:d,order:b.j.length}))}hbb(this.j,a);return a.u}return[]};
c5.prototype.reset=function(){this.j.clear()};g.w(d5,K4);
d5.prototype.u=function(a,b){var c=[];a=a.split(Wbb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Xbb.test(e)){var h=Ybb.exec(e);if(h&&4<=h.length){var l=ybb(h[1]),m=ybb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,v="";n=g.t(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var z=x[1];switch(x[0]){case "line":x=z.split(",");x[0].endsWith("%")&&(p=x[0],h.Xm=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
z.split(",");r=x[0];h.Gj=Number.parseInt(r,10);2===x.length&&(v=x[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Gj=0;break;case 1:h.Gj=100;break;case 2:h.Gj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(v){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.fl=q}e=e.substring(Ybb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");v=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=zbb(l,m,5,v),m=new H4(l,m,5,f.id,h,!1,g.Tc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Zbb),1===q.length?(h=5,v=zbb(l,m,h,v)):(p=h=6,v=Object.assign({Xq:32},v),v=new I4(l,m,p,"_"+J4++,v)),c.push(v),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(x=g.z4a("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(z=x.createElement("span"),z.appendChild(x.createTextNode(n))):z=x.firstChild,xbb(this,p,m-(p-l),h,v,0<r,z,e,c)):p=ybb(n)+f}Ybb.lastIndex=0}}return c};
var Xbb=/^NOTE/,Wbb=/(?:\r\n|\r|\n){2,}/,Ybb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Zbb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.pV.Mx(d5,{u:"wvppt"});g.w(e5,g.C);e5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
e5.prototype.reset=function(){this.parser&&this.parser.reset()};
e5.prototype.ra=function(){g.C.prototype.ra.call(this);this.clear()};var n5={windowColor:"#080808",windowOpacity:0,textAlign:2,fl:7,Gj:50,Xm:100,isDefault:!0,Ce:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(f5,g.RQ);g.k=f5.prototype;g.k.ra=function(){if(this.C||this.oa){var a=this.F.Ae();a&&!a.isDisposed()&&a.ax()}else Tbb(this,!1);g.RQ.prototype.ra.call(this)};
g.k.Hv=function(){if(this.Ya)return this.C||this.oa;var a=qab(this.player.getAudioTrack(),g.aI(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?g5(this):Lbb(this)||g5(this)?!0:Mbb(this)};
g.k.load=function(){var a=this;g.RQ.prototype.load.call(this);this.I=this.player.getAudioTrack();this.u?this.j&&(this.Wa.clear(),this.C?Pbb(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.ls(this.j,"json3",function(b,c,d,e){if(b){a.u.SM()&&(a.Ba=[],a.F.Sf("captions"),g.Sn(a.Ka),a.Wa.reset());b=Fbb(a.Wa,b,c,d,e);a.player.Ke(b,void 0,a.gb);if(!(!a.ya||a.oa||j5(a)||g.RH(a.Y)||g.KH(a.Y)||g.LH(a.Y)||"shortspage"===a.Y.Aa||a.player.isInline())){g.Wn(a.Ma);b=Vab({fl:0,Gj:5,Xm:5,qq:2,textAlign:0,
Uh:0,lang:"fr"});a.Qa=[b];d=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."];a.ob||(e=new g.ZM(g.qN()),g.E(a,e),a.ob=e.element);e=b.end-b.start;var f=g.vI(a.j);f&&a.Qa.push(new H4(b.start,e,0,b.id,f));a.Qa.push(new H4(b.start,e,0,b.id,d[0]),new H4(b.start,e,0,b.id,a.ob,!0),new H4(b.start,e,0,b.id,d[1],!0));a.player.Ke(a.Qa);g.Un(a.Ma)}!a.ya||a.oa||j5(a)||(g.aI(a.Y)?l5(a,!0):m5(a,!0),a.I&&(a.I.C=a.j),a.player.Rv());var h;null==(h=a.F.Sc())||h.xa("cc",{kind:c.kind});a.ya=!1}}),this.C||this.oa||
j5(this)||this.player.Oa("captionschanged",g.wI(this.j))):(this.u=Nbb(this),g.E(this,this.u),this.u.by(function(){Obb(a)}))};
g.k.unload=function(){this.C&&this.j?Pbb(this,!1):(this.Ma&&g.Wn(this.Ma),this.player.Sf("captions"),this.Ba=[],this.u&&this.u.Fq(),this.Wa.clear(),this.J&&this.player.Ke(this.J),this.yO());g.RQ.prototype.unload.call(this);this.player.Rv();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.Hv()&&this.load();var a;a:{var b,c,d;if(this.Y.S("suggest_caption_correction_menu_item")&&this.Y.S("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.t(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.F.ma("showpromotooltip",this.T.element)};
g.k.a6=function(){for(var a=this.F.Ae().vb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.SQ(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&k5(this,b,!0)};
g.k.P7=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ba.push(a);g.Sn(this.Ka)};
g.k.onCueRangeExit=function(a){g.pb(this.Ba,a);this.u instanceof C4&&this.u.I&&this.player.Th([a]);g.Sn(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.T.element.id};
g.k.N6=function(){Sbb(this,this.Qa);this.Qa=null};
g.k.vO=function(){var a=this;if(!this.Tb||!this.C){this.Ka.stop();g.gba(this.Va);this.Ba.sort(g.KB);var b=this.Ba;if(this.J){var c=g.pm(b,function(f){return-1===this.J.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())Rbb(this,c.value);b={};c=g.t(Object.entries(this.ea));for(var d=c.next();!d.done;b={ot:b.ot,Vl:b.Vl},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.ot=d;b.Vl=e;this.Va[b.ot]?(b.Vl.element.parentNode||(b.Vl instanceof G4||b.Vl instanceof F4||g.Lc(this.ea,function(f){return function(h,l){l!==f.ot&&h.u.params.fl===f.Vl.u.params.fl&&h.u.params.Gj===f.Vl.u.params.Gj&&h.u.params.Xm===f.Vl.u.params.Xm&&(h.dispose(),delete a.ea[l]);
return l===f.ot}}(b),this),this.T.element.appendChild(b.Vl.element)),b.Vl.Uy(this.Va[b.ot])):(b.Vl.dispose(),delete this.ea[b.ot])}}};
g.k.R6=function(){Jbb(this,{},!0);this.player.Oa("captionssettingschanged")};
g.k.E1=function(){var a=n5.Ce;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:n5.windowColor,windowOpacity:n5.windowOpacity};var b=yab()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.SW=function(a,b){var c={};Object.assign(c,yab());Object.assign(c,a);Jbb(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.yO=function(){!this.C&&this.loaded&&(g.Ic(this.ea,function(a,b){a.dispose();delete this.ea[b]},this),this.vO())};
g.k.kh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ce(b,-2,4);this.SW({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&k5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Y.D&&(g.aI(this.Y)?l5(this,!!b):m5(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.La(b))break;if(g.Tc(b)){k5(this,null,!0);break}a=g.SQ(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==b.languageName||
(c=b.translationLanguage?sab(e,b.translationLanguage):e)}this.jH(b.position);!c||c===this.j&&this.loaded||(b=g.Eva(),a=g.xI(c),b.length&&a===b[b.length-1]||(b.push(a),g.eB("yt-player-caption-language-preferences",b)),rab(this.Y)&&!this.F.isInline()&&g.eB("yt-player-caption-sticky-language",a),k5(this,c,!0))}else return this.loaded&&this.j&&!j5(this)?g.wI(this.j):{};return"";case "tracklist":return this.u?g.Gg(g.SQ(this.u.j,!(!b||!b.includeAsr)),function(f){return g.wI(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||Tbb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||Tbb(this,!!b,b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.D&&a.push("stickyLoading");return a};
g.k.Ip=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.xI(a));return{cc:b}}return{}};
g.k.D7=function(){this.isSubtitlesOn()?(g.aI(this.Y)?l5(this,!1):m5(this,!1),this.unload(),g5(this,!0)&&k5(this,h5(this),!1)):this.uW()};
g.k.uW=function(){this.isSubtitlesOn()||k5(this,j5(this)||!this.j?i5(this,!0):this.j,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!j5(this)};
g.k.S3=function(){var a=j5(this);g5(this,a)?k5(this,this.player.getAudioTrack().u,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Hv()&&(a?k5(this,i5(this),!1):this.load()))};
g.k.jH=function(a){a&&(this.Z={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.T.element.style.top=100*this.Z.top+"%",this.T.element.style.left=100*this.Z.left+"%",this.T.element.style.width=100*this.Z.width+"%",this.T.element.style.height=100*this.Z.height+"%")};
g.k.C4=function(){var a=this.F.Ae();a&&!a.isDisposed()&&a.ax();this.F.isFullscreen()?(this.C=this.Ya=!0,this.loaded&&Obb(this)):(this.Ya="3"===this.Y.controlsType,this.C=Ibb(this));k5(this,this.j)};
g.k.NH=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Oa("innertubeCommand",d)};
g.pV.Mx(f5,{vO:"smucd"});g.QQ("captions",f5);})(_yt_player);
