(function(g){var window=this;var oGa=function(a,b){a.xa("onAutonavCoundownStarted",b)},X4=function(a,b,c){var d=b.Ma();
g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.ne(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.rI&&(b.lengthText?(f=b.lengthText||null,h=b.Au||null):b.lengthSeconds&&(f=g.bP(b.lengthSeconds),h=g.bP(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.eU(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.rI?b.isLivePlayback:null,n=b instanceof g.rI?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Mp||g.tL("Regarder $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.Sk(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Qp};b instanceof g.fU&&(d.playlist_length=b.getLength());a.update(d)},Y4=function(a){var b=a.T(),c=b.B;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{G:"div",la:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{G:"div",U:{"aria-label":"{{timestamp}}"},la:["ytp-autonav-timestamp"],Z:"{{duration}}"},{G:"div",la:["ytp-autonav-live-stamp"],Z:"En direct"},
{G:"div",la:["ytp-autonav-upcoming-stamp"],Z:"\u00c0 venir"},{G:"div",L:"ytp-autonav-list-overlay",S:[{G:"div",L:"ytp-autonav-mix-text",Z:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",la:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Z:"{{title}}"},{G:"div",la:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Z:"{{author}}"},{G:"div",la:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Z:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.u=c;this.wa("click",this.onClick);this.wa("keypress",this.B)},$4=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.F=b;this.C=0;var d=a.T(),e=d.B;this.J=a;this.suggestion=null;this.u=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Z:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:e?d.F:""},S:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{G:"div",U:{"aria-label":"{{timestamp}}"},la:["ytp-autonav-timestamp"],Z:"{{duration}}"},{G:"div",la:["ytp-autonav-live-stamp"],Z:"En direct"},{G:"div",la:["ytp-autonav-upcoming-stamp"],Z:"\u00c0 venir"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",S:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
Z:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",Z:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",Z:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",Z:"{{author_and_views}}"}]}]}]});g.D(this,this.u);this.u.ga(this.element);e||this.N(this.u.ka("ytp-autonav-endscreen-link-container"),"click",this.PE);g.ZT(this.J,this.element,this,115127);g.ZT(this.J,this.u.ka("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});
g.D(this,this.overlay);this.overlay.ga(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.D(this,this.B);this.B.ga(this.element);this.cancelButton=new g.V({G:"button",la:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Annuler la lecture automatique"},Z:"Annuler"});g.D(this,this.cancelButton);this.cancelButton.ga(this.B.element);this.cancelButton.wa("click",this.hM,this);g.ZT(this.J,this.cancelButton.element,this,
115129);this.playButton=new g.V({G:"a",la:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},Z:"Regarder"});g.D(this,this.playButton);this.playButton.ga(this.B.element);this.playButton.wa("click",this.PE,this);g.ZT(this.J,this.playButton.element,this,115130);this.D=new g.F(function(){Z4(c)},500);
g.D(this,this.D);this.OE();this.N(a,"autonavvisibility",this.OE)},Z4=function(a){var b=a5(a),c=Math.min(a.C?Date.now()-a.C:0,b);
b5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.ug()?a.select(!0):a.ug()&&a.D.start()},a5=function(a){var b=a.J.app.getVideoData().Ts;
return 0<=b?b:g.P(a.J.T().experiments,"autoplay_time")||1E4},b5=function(a,b){b=void 0===b?-1:b;
var c=a.u.ka("ytp-autonav-endscreen-upnext-header");g.He(c);if(0<=b){var d=String(b),e="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Prochaine vid\u00e9o dans $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.Ge("Prochaine vid\u00e9o dans $SECONDS".slice(0,f)));var h=g.Fe("span");g.pn(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ne(h,d);c.appendChild(h);c.appendChild(g.Ge("Prochaine vid\u00e9o dans $SECONDS".slice(f+e.length)));return}}g.Ne(c,"\u00c0 suivre")},
c5=function(a,b){g.V.call(this,{G:"div",
la:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},e5=function(a){g.V.call(this,{G:"div",
la:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",S:[{G:"span",L:"ytp-upnext-header",Z:"\u00c0 suivre"},{G:"span",L:"ytp-upnext-title",Z:"{{title}}"},{G:"span",L:"ytp-upnext-author",Z:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},S:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},S:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",S:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
Z:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.F=this.ka("ytp-svg-autoplay-ring");this.C=this.notification=this.u=this.suggestion=null;this.D=new g.F(this.kt,5E3,this);this.B=0;var b=this.ka("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",la:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Annuler la lecture automatique"},Z:"Annuler"});g.D(this,this.cancelButton);this.cancelButton.wa("click",this.kN,this);this.cancelButton.ga(b);
g.D(this,this.D);g.ZT(this.api,this.element,this,18788);b=this.ka("ytp-upnext-autoplay-icon");this.N(b,"click",this.lN);this.bF();this.N(a,"autonavvisibility",this.bF);this.N(a,"mdxnowautoplaying",this.lP);this.N(a,"mdxautoplaycanceled",this.mP);this.N(a,"mdxautoplayupnext",this.lI);d5(this)&&(a=(a=g.MT(g.HT(this.api)))?a.wK():null)&&this.lI(a);g.J(this.element,"ytp-upnext-mobile",this.api.T().u)},d5=function(a){return 3===a.api.getPresentingPlayerType()},pGa=function(a,b){return b?b:0<=a.api.app.getVideoData().Ts?
a.api.app.getVideoData().Ts:g.P(a.api.T().experiments,"autoplay_time")||1E4},f5=function(a,b){var c=pGa(a,b),d=Math,e=d.min;
var f=(0,g.N)()-a.B;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.F.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.ug()&&!d5(a)?a.select(!0):a.ug()&&a.u.start()},g5=function(a){c5.call(this,a,"autonav-endscreen");
this.videoData=this.suggestions=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",S:[{G:"div",la:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Z:"Plus de vid\u00e9os"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.C=null;this.F=this.I=!1;this.B=new $4(this.player);g.D(this,this.B);this.B.ga(this.element);a.getVideoData().Kl?this.u=this.B:(this.u=new e5(a),g.BP(this.player,this.u.element,4),g.D(this,this.u));this.D=new g.tR(this);
g.D(this,this.D);g.D(this,this.table);this.table.ga(this.element);this.table.show();g.D(this,this.K);this.K.ga(this.table.element);this.hide()},qGa=function(a,b){return g.Oc(b.suggestions,function(c){c=g.uW(a.player.T(),c);
g.D(a,c);return c})},h5=function(a){var b=a.Do();
b!==a.F&&(a.F=b,a.player.V("autonavvisibility"),a.F?(a.B!==a.u&&a.B.hide(),a.table.hide()):(a.B!==a.u&&a.B.show(),a.table.show()))},i5=function(a){return 400>=a.width||360>=a.height},j5=function(a){c5.call(this,a,"subscribecard-endscreen");
this.u=new g.V({G:"div",L:"ytp-subscribe-card",S:[{G:"img",L:"ytp-author-image",U:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",S:[{G:"div",L:"ytp-author-name",Z:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.D(this,this.u);this.u.ga(this.element);var b=a.getVideoData();this.subscribeButton=new g.iV("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.kg,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.ga(this.u.ka("html5-subscribe-button-container"));
this.N(a,"videodatachange",this.oa);this.oa();this.hide()},k5=function(a){var b=a.T(),c=g.pB||g.xg?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",la:e,U:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",S:[{G:"span",L:"ytp-videowall-still-info-bg",S:[{G:"span",L:"ytp-videowall-still-info-content",U:c,S:[{G:"span",L:"ytp-videowall-still-info-title",Z:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
Z:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",Z:"En direct"},{G:"span",L:"ytp-videowall-still-info-duration",Z:"{{duration}}"}]}]}]},{G:"span",la:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",S:[" (",{G:"span",Z:"{{playlist_length}}"},")"]}]},{G:"span",la:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{G:"span",
L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",Z:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.u=new g.tR(this);g.D(this,this.u);this.wa("click",this.onClick);this.wa("keypress",this.C);this.u.N(a,"videodatachange",this.Ra);g.MN(a,this.element,this);this.Ra()},l5=function(a){c5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=this.suggestions=null;this.F=this.P=!1;this.K=null;this.B=new g.tR(this);g.D(this,this.B);this.I=new g.F(function(){g.I(b.element,"ytp-show-tiles")},0);
g.D(this,this.I);var c=new g.V({G:"button",la:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Pr\u00e9c\u00e9dente"},S:[g.VN()]});g.D(this,c);c.ga(this.element);c.wa("click",this.kM,this);this.table=new g.GN({G:"div",L:"ytp-endscreen-content"});g.D(this,this.table);this.table.ga(this.element);c=new g.V({G:"button",la:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Suivante"},S:[g.WN()]});g.D(this,c);c.ga(this.element);c.wa("click",this.jM,this);a.getVideoData().Kl?this.u=new $4(a,!0):
this.u=new e5(a);g.D(this,this.u);g.BP(this.player,this.u.element,4);this.hide()},m5=function(a){return g.XT(a.player)&&a.Pp()&&!a.D},rGa=function(a,b){return g.Oc(b.suggestions,function(c){c=g.uW(a.J.T(),c);
g.D(a,c);return c})},n5=function(a){var b=a.Do();
b!==a.P&&(a.P=b,a.player.V("autonavvisibility"))},o5=function(a){g.JS.call(this,a);
var b=this;this.endScreen=null;this.u=this.B=this.C=!1;this.listeners=new g.tR(this);g.D(this,this.listeners);this.env=a.T();sGa(a)?(this.C=!0,tGa(this),this.u?this.endScreen=new g5(a):this.endScreen=new l5(this.player)):this.env.Ne?this.endScreen=new j5(this.player):this.endScreen=new c5(this.player);g.D(this,this.endScreen);g.BP(this.player,this.endScreen.element,4);uGa(this);this.listeners.N(a,"videodatachange",this.Ra,this);this.listeners.N(a,g.hF("endscreen"),function(c){b.FE()&&(b.endScreen.created||
b.endScreen.create(),"load"===c.getId()&&b.load())});
this.listeners.N(a,g.iF("endscreen"),function(c){"load"===c.getId()&&b.loaded&&b.unload()})},tGa=function(a){var b=a.player.getVideoData();
if(!b||a.u===b.jp&&a.B===b.Kl)return!1;a.u=b.jp;a.B=b.Kl;return!0},sGa=function(a){a=a.T();
return a.ub&&!a.Ne},uGa=function(a){g.WT(a.player,"endscreen");
var b=a.player.getVideoData();b=new g.eF(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.eF(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.zN(a.player,[b,c])};
g.u(Y4,g.V);Y4.prototype.select=function(){(g.GT(this.J,this.suggestion.Ma().videoId,this.suggestion.Ad,this.suggestion.getPlaylistId(),void 0,this.suggestion.Jx||void 0)||this.J.ba("web_player_endscreen_double_log_fix_killswitch"))&&g.$T(this.J,this.element)};
Y4.prototype.onClick=function(a){g.AU(a,this.J,this.u,this.suggestion.Ad||void 0)&&this.select()};
Y4.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.kp(a)||(this.select(),g.ip(a))}};
Y4.prototype.Qd=function(a){g.J(this.element,"ytp-suggestion-card-with-margin",a)};g.u($4,g.V);g.k=$4.prototype;g.k.Zq=function(a){this.suggestion!==a&&(this.suggestion=a,X4(this.u,a),this.playButton.ya("url",this.suggestion.Sk()),this.Qd())};
g.k.Qd=function(){var a=this.J.Pi(!0,this.J.isFullscreen());g.J(this.element,"ytp-autonav-endscreen-small-mode",this.Ie(a));g.J(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.ew);g.J(this.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!g.IT(this.J));g.J(this.J.getRootNode(),"countdown-running",this.ug());g.J(this.element,"ytp-player-content",g.IT(this.J));g.ug(this.overlay.element,{width:a.width+"px"});if(!this.ug()){g.IT(this.J)?b5(this,Math.round(a5(this)/
1E3)):b5(this);a=!!this.suggestion&&!!this.suggestion.Qp;var b=g.IT(this.J)||!a;g.J(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.J(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.JN(this.B,g.IT(this.J))}};
g.k.ug=function(){return 0<this.C};
g.k.lp=function(){this.ug()||(this.C=Date.now(),Z4(this),oGa(this.J,a5(this)),g.J(this.J.getRootNode(),"countdown-running",this.ug()))};
g.k.Xm=function(){this.rk();Z4(this)};
g.k.rk=function(){this.ug()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.rk()};
g.k.PE=function(a){g.AU(a,this.J)&&(a.currentTarget===this.playButton.element?g.$T(this.J,this.playButton.element):a.currentTarget===this.u.ka("ytp-autonav-endscreen-link-container")&&(a=this.u.ka("ytp-autonav-endscreen-link-container"),g.QN(this.J,a,!0),g.$T(this.J,a)),this.select())};
g.k.hM=function(){g.$T(this.J,this.cancelButton.element);g.KT(this.J,!0)};
g.k.OE=function(){var a=g.IT(this.J);this.F&&this.fb!==a&&g.JN(this,a);this.Qd();g.QN(this.J,this.element,a);g.QN(this.J,this.cancelButton.element,a);g.QN(this.J,this.u.ka("ytp-autonav-endscreen-link-container"),a);g.QN(this.J,this.playButton.element,a)};
g.k.Ie=function(a){return 400>a.width||459>a.height};g.u(c5,g.V);g.k=c5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Pp=function(){return!1};
g.k.Do=function(){return!1};
g.k.cE=function(){return!1};g.u(e5,g.V);g.k=e5.prototype;g.k.kt=function(){this.notification&&(this.D.stop(),this.Mb(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.Zq=function(a){this.suggestion=a;X4(this,a,"hqdefault.jpg")};
g.k.bF=function(){g.JN(this,g.IT(this.api));g.QN(this.api,this.element,g.IT(this.api))};
g.k.DP=function(){window.focus();this.kt()};
g.k.lp=function(a){var b=this;this.ug()||(g.Po("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.B=(0,g.N)(),this.u=new g.F(function(){f5(b,a)},25),f5(this,a),oGa(this.api,pGa(this,a)));
g.sn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.ug=function(){return!!this.u};
g.k.Xm=function(){this.rk();this.B=(0,g.N)();f5(this);g.I(this.element,"ytp-upnext-autoplay-paused")};
g.k.rk=function(){this.ug()&&(this.u.dispose(),this.u=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.Q(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ma(),this.kt(),this.notification=new Notification("\u00c0 suivre",{body:b.title,icon:b.ne()}),this.C=this.N(this.notification,"click",this.DP),this.D.start())}this.rk();this.api.nextVideo(!1,a)};
g.k.lN=function(a){!g.Me(this.cancelButton.element,g.ep(a))&&g.AU(a,this.api)&&this.select()};
g.k.kN=function(){g.KT(this.api,!0)};
g.k.lP=function(a){d5(this);this.show();this.lp(a)};
g.k.lI=function(a){d5(this);this.suggestion&&this.suggestion.Ma().videoId===a.Ma().videoId||this.Zq(a)};
g.k.mP=function(){d5(this);this.rk();this.hide()};
g.k.ca=function(){this.rk();this.kt();g.V.prototype.ca.call(this)};g.u(g5,c5);g.k=g5.prototype;g.k.create=function(){c5.prototype.create.call(this);this.D.N(this.player,"appresize",this.Qd);this.D.N(this.player,"onVideoAreaChange",this.Qd);this.D.N(this.player,"videodatachange",this.Ra);this.D.N(this.player,"autonavchange",this.NE);this.D.N(this.player,"autonavcancel",this.gM);this.Ra()};
g.k.show=function(){c5.prototype.show.call(this);(this.I||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.KT(this.player,!1);g.XT(this.player)&&this.Pp()&&!this.C?(h5(this),2===this.videoData.autonavState?this.player.T().ba("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.lp():3===this.videoData.autonavState&&this.u.Xm()):(g.KT(this.player,!0),h5(this));this.Qd()};
g.k.hide=function(){c5.prototype.hide.call(this);this.u.Xm();h5(this)};
g.k.Qd=function(){var a=this.player.Pi(!0,this.player.isFullscreen());h5(this);this.B.Qd();g.J(this.element,"ytp-autonav-cancelled-small-mode",this.Ie(a));g.J(this.element,"ytp-autonav-cancelled-tiny-mode",800>a.width&&!i5(a));g.J(this.element,"ytp-autonav-cancelled-mini-mode",i5(a));if(!this.F){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Qd(1===c%2)}}};
g.k.Ra=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=qGa(this,a))&&this.suggestions.length)for(this.u.Zq(this.suggestions[0]),this.u!==this.B&&this.B.Zq(this.suggestions[0]),a=0;a<vGa.length;++a){var b=vGa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new Y4(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,X4(c,b));g.D(this,this.videos[a]);this.videos[a].ga(this.K.element)}}this.Qd()}};
g.k.NE=function(a){1===a?(this.I=!1,this.C=this.videoData.clientPlaybackNonce,this.u.rk(),this.fb&&this.Qd()):(this.I=!0,this.Do()&&(2===a?this.u.lp():3===a&&this.u.Xm()))};
g.k.gM=function(a){a?this.NE(1):(this.C=null,this.I=!1)};
g.k.Pp=function(){return 1!==this.videoData.autonavState};
g.k.Ie=function(a){return(910>a.width||459>a.height)&&!(800>a.width&&!i5(a))&&!i5(a)};
g.k.Do=function(){return this.fb&&g.XT(this.player)&&this.Pp()&&!this.C};
var vGa=[1,3,2,4];g.u(j5,c5);j5.prototype.oa=function(){var a=this.player.getVideoData();this.u.update({profilePicture:a.lf,author:a.author});this.subscribeButton.channelId=a.kg;var b=this.subscribeButton;a.subscribed?b.B():b.C()};g.u(k5,g.V);k5.prototype.select=function(){(g.GT(this.api,this.suggestion.Ma().videoId,this.suggestion.Ad,this.suggestion.getPlaylistId(),void 0,this.suggestion.Jx||void 0)||this.api.ba("web_player_endscreen_double_log_fix_killswitch"))&&g.$T(this.api,this.element)};
k5.prototype.onClick=function(a){g.AU(a,this.api,this.B,this.suggestion.Ad||void 0)&&this.select()};
k5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.kp(a)||(this.select(),g.ip(a))}};
k5.prototype.Ra=function(){var a=this.api.getVideoData(),b=this.api.T();this.B=a.qc?!1:b.B};g.u(l5,c5);g.k=l5.prototype;g.k.create=function(){c5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=rGa(this,a),this.videoData=a);this.Qd();this.B.N(this.player,"appresize",this.Qd);this.B.N(this.player,"onVideoAreaChange",this.Qd);this.B.N(this.player,"videodatachange",this.Ra);this.B.N(this.player,"autonavchange",this.lz);this.B.N(this.player,"autonavcancel",this.iM);a=this.videoData.autonavState;a!==this.K&&this.lz(a);this.B.N(this.element,"transitionend",this.RQ)};
g.k.destroy=function(){g.ut(this.B);g.gg(this.stills);this.stills=[];this.suggestions=null;c5.prototype.destroy.call(this);g.sn(this.element,"ytp-show-tiles");this.I.stop();this.K=this.videoData.autonavState};
g.k.Pp=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){c5.prototype.show.call(this);g.sn(this.element,"ytp-show-tiles");this.player.T().u?g.kn(this.I):this.I.start();(this.F||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.KT(this.player,!1);m5(this)?(n5(this),2===this.videoData.autonavState?this.player.T().ba("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.lp():3===this.videoData.autonavState&&this.u.Xm()):(g.KT(this.player,!0),n5(this))};
g.k.hide=function(){c5.prototype.hide.call(this);this.u.Xm();n5(this)};
g.k.RQ=function(a){g.ep(a)===this.element&&this.Qd()};
g.k.Qd=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=this.J.Pi(!0,this.J.isFullscreen()),b=g.BT(this.J);b&&(b=b.ge()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Kg(a,m,n);g.ug(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.u.Zq(this.suggestions[0]);this.u instanceof $4&&this.u.Qd();g.J(this.element,"ytp-endscreen-takeover",m5(this));n5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.de(p+this.C,l),0!==r){t=this.stills[c];t||(t=new k5(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var y=Math.floor(m*f/b),x=Math.floor(n*(h+r)/e)-w-4,B=Math.floor(m*(f+r)/b)-y-4;g.Cg(t.element,y,w);g.Kg(t.element,B,x);g.ug(t.element,"transitionDelay",(h+f)/20+"s");g.J(t.element,"ytp-videowall-still-mini",1===r);g.J(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),w=g.qn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",X4(r,p,w),g.hD(t)&&(t=p.Sk(),t=g.Md(t,g.eV({},"emb_rel_end")),r.ya("url",t)),(p=(p=p.Ad)&&p.itct)&&g.NN(r.api,r.element,p));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Je(e.element),g.fg(e);this.stills.length=c}};
g.k.Ra=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.suggestions=rGa(this,a),this.videoData=a,this.Qd())};
g.k.jM=function(){this.C+=this.stills.length;this.Qd()};
g.k.kM=function(){this.C-=this.stills.length;this.Qd()};
g.k.cE=function(){return this.u.ug()};
g.k.lz=function(a){1===a?(this.F=!1,this.D=this.videoData.clientPlaybackNonce,this.u.rk(),this.fb&&this.Qd()):(this.F=!0,this.fb&&m5(this)&&(2===a?this.u.lp():3===a&&this.u.Xm()))};
g.k.iM=function(a){if(a){for(a=0;a<this.stills.length;a++)g.QN(this.J,this.stills[a].element,!0);this.lz(1)}else this.D=null,this.F=!1;this.Qd()};
g.k.Do=function(){return this.fb&&m5(this)};g.u(o5,g.JS);g.k=o5.prototype;g.k.FE=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!sGa(this.player)||b;var c=a.un||g.qD(a.Sa),d=g.Y0(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.EE=function(){return this.endScreen.Do()};
g.k.iL=function(){return this.EE()?this.endScreen.cE():!1};
g.k.ca=function(){g.WT(this.player,"endscreen");g.JS.prototype.ca.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.WH;if(b&&b.videoId){var c=g.HT(this.player).Vc.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.IG?a=!1:(g.GT(this.player,b.videoId,void 0,void 0,!0,b),c&&c.Hu("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.JS.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.JS.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Ra=function(){uGa(this);this.C&&tGa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.u?this.endScreen=new g5(this.player):this.endScreen=new l5(this.player),g.D(this,this.endScreen),g.BP(this.player,this.endScreen.element,4))};g.qU.endscreen=o5;})(_yt_player);
