(function(g){var window=this;var bHa=function(a,b){return g.Pb(a,b)},Z5=function(a,b,c){a.C.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.C,b,c)},cHa=function(a,b){var c=[];
g.hj(b,function(d){try{var e=g.Zn.prototype.B.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Yn(e)&&c.push(d)},a);
return c},dHa=function(a,b){var c=cHa(a,b);
g.Cb(c,function(d){g.Zn.prototype.remove.call(this,d)},a)},eHa=function(a){if(a.ue){if(a.ue.locationOverrideToken)return{locationOverrideToken:a.ue.locationOverrideToken};
if(null!=a.ue.latitudeE7&&null!=a.ue.longitudeE7)return{latitudeE7:a.ue.latitudeE7,longitudeE7:a.ue.longitudeE7}}return null},fHa=function(a,b){g.jb(a,b)||a.push(b)},b6=function(a){var b=0,c;
for(c in a)b++;return b},gHa=function(a,b){var c=b instanceof g.Ec?b:g.Kc(b,/^data:image\//i.test(b));
a.src=g.Fc(c)},c6=function(){},hHa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},iHa=function(a){if(a.Hf&&"function"==typeof a.Hf)return a.Hf();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Lb(a)},jHa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)g.Cb(a,b,void 0);else{if(a.Sg&&"function"==typeof a.Sg)var c=a.Sg();else if(a.Hf&&"function"==typeof a.Hf)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Mb(a);d=iHa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},kHa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.B=d);return e},d6=function(a,b){g.Lo[a]=!0;
var c=g.Jo();c&&c.publish.apply(c,arguments);g.Lo[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",lHa(this,a.capabilities||""),mHa(this,a.experiments||""))},lHa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Ta(bHa,nHa)).forEach(function(c){a.capabilities.add(c)})},mHa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},oHa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},pHa=function(a){return new f6(a)},qHa=function(a){return Array.isArray(a)?g.Oc(a,pHa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return Array.isArray(a)?"["+g.Oc(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},rHa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},k6=function(a,b){return g.fb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},l6=function(a,b){return g.fb(a,function(c){return g6(c,b)})},sHa=function(){var a=(0,g.iu)();
a&&dHa(a,a.u.wj(!0))},m6=function(){var a=g.lu("yt-remote-connected-devices")||[];
g.zb(a);return a},tHa=function(a){if(g.kb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},uHa=function(a){g.ku("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.lu("yt-remote-device-id");a||(a=j6(),g.ku("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.jb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.jb(a,b);g.nu()&&g.Bb(a,b);a=tHa(a);if(g.kb(a))try{g.yq("remote_sid")}catch(c){}else try{g.wq("remote_sid",a.join(","),-1)}catch(c){}},vHa=function(){return g.lu("yt-remote-session-browser-channel")},wHa=function(){return g.lu("yt-remote-local-screens")||[]},xHa=function(){g.ku("yt-remote-lounge-token-expiration",!0,86400)},yHa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(wHa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.qh(c,function(d){return!g.jb(b,d)})&&xHa();
g.ku("yt-remote-local-screens",a,31536E3)},zHa=function(a,b){g.ku("yt-remote-session-browser-channel",a);
g.ku("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.jb(c,d)||c.push(d);uHa(c);p6()},q6=function(a){a||(g.mu("yt-remote-session-screen-id"),g.mu("yt-remote-session-video-id"));
p6();a=m6();g.ob(a,o6());uHa(a)},AHa=function(){if(!r6){var a=g.jo();
a&&(r6=new g.Kn(a))}},BHa=function(){AHa();
return r6?!!r6.get("yt-remote-use-staging-server"):!1},CHa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},DHa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?EHa(a.shift(),function(){s6(a)}):t6()},FHa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},EHa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.kd(d,g.sg(a));(document.head||document.documentElement).appendChild(d)},t6=function(){var a=DHa();
a&&a(!1,"No cast extension found")},HHa=function(){if(GHa){var a=2,b=DHa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;EHa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},IHa=function(){HHa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");s6(b)},u6=function(a,b,c){g.C.call(this);
this.I=null!=c?(0,g.z)(a,c):a;this.yf=b;this.F=(0,g.z)(this.BK,this);this.u=!1;this.B=0;this.C=this.Za=null;this.D=[]},v6=function(a,b,c){g.C.call(this);
this.D=null!=c?a.bind(c):a;this.yf=b;this.C=null;this.u=!1;this.B=0;this.Za=null},w6=function(a){a.Za=g.Lm(function(){a.Za=null;
a.u&&!a.B&&(a.u=!1,w6(a))},a.yf);
var b=a.C;a.C=null;a.D.apply(null,b)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return hHa(a)},y6=function(){},z6=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){A6.dispatchEvent(new JHa(A6,a))},JHa=function(a){g.El.call(this,"statevent",a)},C6=function(){},KHa=function(){},MHa=function(a){return(a=LHa(a))?new ActiveXObject(a):new XMLHttpRequest},LHa=function(a){if(!a.B&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.B=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.B},D6=function(a,b,c,d){this.u=a;
this.B=b;this.R=c;this.K=d||1;this.F=45E3;this.D=new g.f1(this);this.C=new g.Km;this.C.setInterval(250)},OHa=function(a,b,c){a.np=1;
a.Bk=$5(b.clone());a.Zm=c;a.I=!0;NHa(a,null)},E6=function(a,b,c,d,e){a.np=1;
a.Bk=$5(b.clone());a.Zm=null;a.I=c;e&&(a.uH=!1);NHa(a,d)},NHa=function(a,b){a.fp=g.A();
F6(a);a.El=a.Bk.clone();a6(a.El,"t",a.K);a.As=0;a.xe=a.u.Cx(a.u.Wr()?b:null);0<a.sy&&(a.Qv=new v6((0,g.z)(a.zI,a,a.xe),a.sy));a.D.wa(a.xe,"readystatechange",a.CR);var c=a.Bm?g.Vb(a.Bm):{};a.Zm?(a.Aw="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.xe.send(a.El,a.Aw,a.Zm,c)):(a.Aw="GET",a.uH&&!g.Ae&&(c.Connection="close"),a.xe.send(a.El,a.Aw,null,c));a.u.Xh(1)},RHa=function(a,b,c){for(var d=!0;!a.fm&&a.As<c.length;){var e=PHa(a,c);
if(e==G6){4==b&&(a.Uk=4,B6(15),d=!1);break}else if(e==QHa){a.Uk=4;B6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.Uk=1,B6(17),d=!1);a.ji=a.ji&&d;d||(I6(a),J6(a))},PHa=function(a,b){var c=a.As,d=b.indexOf("\n",c);
if(-1==d)return G6;c=Number(b.substring(c,d));if(isNaN(c))return QHa;d+=1;if(d+c>b.length)return G6;var e=b.substr(d,c);a.As=d+c;return e},THa=function(a,b){a.fp=g.A();
F6(a);var c=b?window.location.hostname:"";a.El=a.Bk.clone();Z5(a.El,"DOMAIN",c);Z5(a.El,"t",a.K);try{a.oi=new ActiveXObject("htmlfile")}catch(n){I6(a);a.Uk=7;B6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in K6)h=K6[h];else if(h in SHa)h=K6[h]=SHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
K6[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.fd(g.gc("b/12014412"),d+"</body></html>");a.oi.open();a.oi.write(g.bd(c));a.oi.close();a.oi.parentWindow.m=(0,g.z)(a.UQ,a);a.oi.parentWindow.d=(0,g.z)(a.sG,a,!0);a.oi.parentWindow.rpcClose=(0,g.z)(a.sG,a,!1);c=a.oi.createElement("DIV");a.oi.parentWindow.document.body.appendChild(c);d=g.Jc(a.El.toString());d=g.od(g.Fc(d));d=g.fd(g.gc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,d);a.u.Xh(1)},F6=function(a){a.eB=g.A()+a.F;
UHa(a,a.F)},UHa=function(a,b){if(null!=a.zp)throw Error("WatchDog timer not null");
a.zp=z6((0,g.z)(a.dR,a),b)},L6=function(a){a.zp&&(g.v.clearTimeout(a.zp),a.zp=null)},J6=function(a){a.u.uD()||a.fm||a.u.au(a)},I6=function(a){L6(a);
g.fg(a.Qv);a.Qv=null;a.C.stop();g.mBa(a.D);if(a.xe){var b=a.xe;a.xe=null;b.abort();b.dispose()}a.oi&&(a.oi=null)},H6=function(a,b){try{a.u.kG(a,b),a.u.Xh(4)}catch(c){}},WHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;VHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){WHa(a,b,c,d,f)},f)})}},VHa=function(a,b,c){var d=new Image;
d.onload=function(){try{M6(d),c(!0)}catch(e){}};
d.onerror=function(){try{M6(d),c(!1)}catch(e){}};
d.onabort=function(){try{M6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{M6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
gHa(d,a)},M6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},N6=function(a){g.am.call(this);
this.headers=new g.Nm;this.fa=a||null;this.C=!1;this.aa=this.u=null;this.Aa=this.P="";this.I=0;this.D="";this.F=this.ma=this.R=this.ha=!1;this.K=0;this.X=null;this.Ja="";this.Y=this.ia=!1},XHa=function(a){return g.ye&&g.ae(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},YHa=function(a){return"content-type"==a.toLowerCase()},$Ha=function(a,b){a.C=!1;
a.u&&(a.F=!0,a.u.abort(),a.F=!1);a.D=b;a.I=5;ZHa(a);O6(a)},ZHa=function(a){a.ha||(a.ha=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},bIa=function(a){if(a.C&&"undefined"!=typeof g.k1)if(a.aa[1]&&4==P6(a)&&2==a.getStatus())Q6(a,"Local request error detected and ignored");
else if(a.R&&4==P6(a))g.Lm(a.hG,0,a);else if(a.dispatchEvent("readystatechange"),4==P6(a)){Q6(a,"Request complete");a.C=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xd(1,String(a.P));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!aIa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.I=6;try{var l=2<P6(a)?a.u.statusText:""}catch(m){l=""}a.D=l+" ["+a.getStatus()+"]";ZHa(a)}}finally{O6(a)}}},O6=function(a,b){if(a.u){cIa(a);
var c=a.u,d=a.aa[0]?g.Ka:null;a.u=null;a.aa=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},cIa=function(a){a.u&&a.Y&&(a.u.ontimeout=null);
a.X&&(g.v.clearTimeout(a.X),a.X=null)},P6=function(a){return a.u?a.u.readyState:0},R6=function(a){try{return a.u?a.u.responseText:""}catch(b){return""}},Q6=function(a,b){return b+" ["+a.Aa+" "+a.P+" "+a.getStatus()+"]"},dIa=function(a){this.u=a;
this.B=new y6},eIa=function(a){var b=S6(a.u,a.Rp,"/mail/images/cleardot.gif");
$5(b);WHa(b.toString(),5E3,(0,g.z)(a.BJ,a),3,2E3);a.Xh(1)},U6=function(a){var b=a.u.R;
if(null!=b)B6(5),b?(B6(11),T6(a.u,a,!1)):(B6(12),T6(a.u,a,!0));else if(a.hg=new D6(a,void 0,void 0,void 0),a.hg.Bm=a.qy,b=a.u,b=S6(b,b.Wr()?a.Cq:null,a.ry),B6(5),!g.ye||g.be(10))a6(b,"TYPE","xmlhttp"),E6(a.hg,b,!1,a.Cq,!1);else{a6(b,"TYPE","html");var c=a.hg;a=!!a.Cq;c.np=3;c.Bk=$5(b.clone());THa(c,a)}},V6=function(a,b,c){this.Ka=1;
this.u=[];this.C=[];this.D=new y6;this.K=a||null;this.R=null!=b?b:null;this.F=c||!1},fIa=function(a,b){this.u=a;
this.map=b;this.context=null},iIa=function(a,b,c,d){g.El.call(this,"timingevent",a);
this.size=b;this.Nr=d},jIa=function(a){g.El.call(this,"serverreachability",a)},mIa=function(a){kIa(a);
if(3==a.Ka){var b=a.mr++,c=a.Ft.clone();Z5(c,"SID",a.B);Z5(c,"RID",b);Z5(c,"TYPE","terminate");W6(a,c);b=new D6(a,a.B,b,void 0);b.np=2;b.Bk=$5(c.clone());gHa(new Image,b.Bk.toString());b.fp=g.A();F6(b)}lIa(a)},nIa=function(a){a.aK(1,0);
a.Ft=S6(a,null,a.py);X6(a)},kIa=function(a){a.Gk&&(a.Gk.abort(),a.Gk=null);
a.Sd&&(a.Sd.cancel(),a.Sd=null);a.yj&&(g.v.clearTimeout(a.yj),a.yj=null);Y6(a);a.Wf&&(a.Wf.cancel(),a.Wf=null);a.Kk&&(g.v.clearTimeout(a.Kk),a.Kk=null)},oIa=function(a,b){if(0==a.Ka)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new fIa(a.LN++,b));2!=a.Ka&&3!=a.Ka||X6(a)},pIa=function(a){var b=0;
a.Sd&&b++;a.Wf&&b++;return b},X6=function(a){a.Wf||a.Kk||(a.Kk=z6((0,g.z)(a.rG,a),0),a.Zn=0)},rIa=function(a,b){if(1==a.Ka){if(!b){a.mr=Math.floor(1E5*Math.random());
var c=a.mr++,d=new D6(a,"",c,void 0);d.Bm=a.Tk;var e=Z6(a),f=a.Ft.clone();Z5(f,"RID",c);Z5(f,"CVER","1");W6(a,f);OHa(d,f,e);a.Wf=d;a.Ka=2}}else 3==a.Ka&&(b?qIa(a,b):0==a.u.length||a.Wf||qIa(a))},qIa=function(a,b){if(b)if(6<a.gm){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.mr-1;var d=Z6(a)}else c=b.R,d=b.Zm;else c=a.mr++,d=Z6(a);var e=a.Ft.clone();Z5(e,"SID",a.B);Z5(e,"RID",c);Z5(e,"AID",a.ro);W6(a,e);c=new D6(a,a.B,c,a.Zn+1);c.Bm=a.Tk;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wf=c;OHa(c,e,d)},W6=function(a,b){if(a.vf){var c=a.vf.XC();
c&&g.Eb(c,function(d,e){Z5(b,e,d)})}},Z6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.gm&&0<b){var d=a.u[0].u;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={xn:e.xn},f++){e.xn=a.u[f].u;var h=a.u[f].map;e.xn=6>=a.gm?f:e.xn-d;try{g.Eb(h,function(l){return function(m,n){c.push("req"+l.xn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.xn+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},sIa=function(a){a.Sd||a.yj||(a.I=1,a.yj=z6((0,g.z)(a.qG,a),0),a.Mn=0)},$6=function(a){if(a.Sd||a.yj||3<=a.Mn)return!1;
a.I++;a.yj=z6((0,g.z)(a.qG,a),tIa(a,a.Mn));a.Mn++;return!0},T6=function(a,b,c){a.xw=c;
a.Ri=b.Lj;a.F||nIa(a)},Y6=function(a){null!=a.lm&&(g.v.clearTimeout(a.lm),a.lm=null)},tIa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.vf&&(c=null);var d=(0,g.z)(a.mS,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),$5(c));VHa(c.toString(),1E4,d)}else B6(2);uIa(a,b)},uIa=function(a,b){a.Ka=0;
a.vf&&a.vf.lC(b);lIa(a);kIa(a)},lIa=function(a){a.Ka=0;
a.Ri=-1;if(a.vf)if(0==a.C.length&&0==a.u.length)a.vf.rx();else{g.rb(a.C);var b=g.rb(a.u);a.C.length=0;a.u.length=0;a.vf.rx(b)}},S6=function(a,b,c){var d=g.Ym(c);
if(""!=d.u)b&&g.Sm(d,b+"."+d.u),g.Tm(d,d.D);else{var e=window.location;d=kHa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.jq&&g.Eb(a.jq,function(f,h){Z5(d,h,f)});
Z5(d,"VER",a.gm);W6(a,d);return d},vIa=function(){},wIa=function(){this.u=[];
this.B=[]},xIa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.C.call(this);
this.u=new g.F(this.NQ,0,this);g.D(this,this.u);this.yf=5E3;this.B=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},c7=function(a,b,c,d){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
this.aa=a;this.I=b;this.C=new g.Jn;this.B=new b7(this.OR,this);this.u=null;this.X=!1;this.F=null;this.P="";this.R=this.D=0;this.K=[];this.fa=c;this.Y=d},yIa=function(a){return{firstTestResults:[""],
secondTestResults:!a.u.xw,sessionId:a.u.B,arrayId:a.u.ro}},zIa=function(a,b){a.R=b||0;
a.B.stop();d7(a);a.u&&(3==a.u.getState()&&rIa(a.u),mIa(a.u));a.R=0},e7=function(a){return!!a.u&&3==a.u.getState()},d7=function(a){if(a.u){var b=a.Y(),c=a.u.Tk||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.u.Tk=c}},AIa=function(a,b){(a.I.loungeIdToken=b)||a.B.stop()},f7=function(a){this.scheme="https";
this.port=this.domain="";this.u="/api/lounge";this.B=!0;a=a||document.location.href;var b=Number(g.xd(4,a))||"";b&&(this.port=":"+b);this.domain=g.yd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Cc(a,"10.0")&&(this.B=!1))},g7=function(a,b){var c=a.u;
a.B&&(c=a.scheme+"://"+a.domain+a.port+a.u);return g.Md(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.D,d,!0),onError:g.Ta(a.C,e),Bg:g.Ta(a.F,e)};c&&(a.tc=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.qq(b,a)},EIa=function(){var a=BIa;
CIa();i7.push(a);DIa(i7)},j7=function(a,b){CIa();
var c=i7,d=FIa(a,String(b));g.kb(c)?GIa(d):(DIa(c),g.Cb(c,function(e){e(d)}))},CIa=function(){i7||(i7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",i7,void 0))},GIa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},DIa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];g.Cb(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},FIa=function(a,b){var c=(g.A()-HIa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.O.call(this);
this.I=a;this.screens=[]},IIa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},JIa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!k6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=IIa(a,b[d])||c;return c},KIa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},o7=function(a,b,c,d){g.O.call(this);
this.I=a;this.F=b;this.C=c;this.D=d;this.B=0;this.u=null;this.Za=NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.u=NaN;p7(this);this.info("Initializing with "+i6(this.screens))},LIa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.z)(a.JK,a),(0,g.z)(a.IK,a))}},p7=function(a){if(g.vo("deprecate_pair_servlet_enabled"))return JIa(a,[]);
var b=qHa(wHa());b=g.Ke(b,function(c){return!c.uuid});
return JIa(a,b)},r7=function(a,b){yHa(g.Oc(a.screens,oHa));
b&&xHa()},t7=function(a,b){g.O.call(this);
this.I=b;var c=g.lu("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.I(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.jb(c,l)}this.u=d;this.F=a;this.C=this.D=NaN;this.B=null;s7("Initialized with "+g.Nj(this.u))},MIa=function(a,b,c){var d=g7(a.F,"/pairing/get_screen_availability");
h7(a.F,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},u7=function(a,b){a:if(b6(b)!=b6(a.u))var c=!1;
else{c=g.Mb(b);for(var d=0,e=c.length;d<e;++d)if(!a.u[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Nj(a.u)),a.u=b,a.V("screenChange"));NIa(a)},v7=function(a){isNaN(a.C)||g.Io(a.C);
a.C=g.Go((0,g.z)(a.gA,a),0<a.D&&a.D<g.A()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},OIa=function(a){var b={};
g.Cb(a.I(),function(c){c.token?b[c.token]=c.id:this.Cd("Requesting availability of screen w/o lounge token.")});
return b},NIa=function(a){a=g.Mb(g.Fb(a.u,function(b){return b}));
g.zb(a);a.length?g.ku("yt-remote-online-screen-ids",a.join(","),60):g.mu("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.u=this.B=null;this.C=[];this.D={};PIa(this)},RIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.sg();if(h=(c?l6(h,c):null)||l6(h,b)){h.uuid=b;var l=x7(a,h);MIa(a.u,l,function(m){e(m?l:null)})}else c?QIa(a,c,(0,g.z)(function(m){var n=x7(this,new f6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));MIa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},SIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},QIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tc:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.qq(g7(a.F,"/pairing/get_lounge_token_batch"),e)},TIa=function(a){a.screens=a.B.sg();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.screens))},PIa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.z)(a.PK,a));TIa(a);a.C=qHa(g.lu("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+i6(a.C));a.u=new t7(a.F,(0,g.z)(a.sg,a,!0));a.u.subscribe("screenChange",(0,g.z)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.ku("yt-remote-automatic-screen-cache",g.Oc(a.C,oHa)));y7(a);a.D[b.uuid]=b.id;g.ku("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.lu("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.O.call(this);
this.aa=c;this.R=a;this.u=b;this.K=null},A7=function(a,b){j7(a.aa,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.B=null;this.C=0;this.F=(0,g.z)(this.QS,this);this.D=(0,g.z)(this.kR,this);this.C=g.Go((0,g.z)(function(){UIa(this,null)},this),12E4)},VIa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Nj(void 0));
var b={type:"getMdxSessionStatus"};a.B?a.B.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.z)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Nj(b))},UIa=function(a,b){g.Io(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.z)(a.Av,a),d=(0,g.z)(a.zg,a);a.nD(b,c,d,5)}}else a.zg(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.I=null;this.P="";this.fa=c;this.X=null;this.F=g.Ka;this.D=NaN;this.Y=(0,g.z)(this.US,this);this.B=g.Ka},WIa=function(a){a.B=a.R.HI(a.P,a.u.label,a.u.friendlyName,(0,g.z)(function(b){this.B=g.Ka;
this.Av(b)},a),(0,g.z)(function(b){this.B=g.Ka;
this.zg(b)},a))},XIa=function(a){var b={};
b.pairingCode=a.P;b.theme=a.fa;BHa()&&(b.env_useStageMdx=1);return g.Kd(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.B=g.Go((0,g.z)(this.uo,this,null),150)},E7=function(a,b){g.O.call(this);
this.B=a;this.K=b.appId||"233637DE";this.I=b.theme||"cl";this.R=b.disableCastApi||!1;this.u=null;this.F=!1;this.C=[];this.D=(0,g.z)(this.cQ,this)},YIa=function(a,b){return b?g.fb(a.C,function(c){return g6(b,c.label)},a):null},F7=function(a){j7("Controller",a)},BIa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},G7=function(a){return a.F||!!a.C.length||!!a.u},H7=function(a,b,c){b!=a.u&&(g.fg(a.u),(a.u=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.u):a.V("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.z)(a.oG,a,b)),b.getScreen()?a.V("yt-remote-cast2-session-change",b.getScreen()):c&&a.u.uo(null)):a.V("yt-remote-cast2-session-change",null))},ZIa=function(a){var b=a.B.GI(),c=a.u&&a.u.u;
a=g.Oc(b,function(d){c&&g6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=YIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},eJa=function(a,b,c,d){d.disableCastApi?I7("Cannot initialize because disabled by Mdx config."):$Ia()?aJa(b,d)&&(J7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?bJa(a,c):(window.__onGCastApiAvailable=function(e,f){e?bJa(a,c):(K7("Failed to load cast API: "+f),L7(!1),J7(!1),g.mu("yt-remote-cast-available"),g.mu("yt-remote-cast-receiver"),
cJa(),c(!1))},d.loadCastApiSetupScript?g.So("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?IHa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(HHa(),s6(dJa.map(FHa))))):I7("Cannot initialize because not running Chrome")},cJa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);fJa(!1);g.Oo(N7);N7.length=0},O7=function(){return!!g.lu("yt-remote-cast-installed")},gJa=function(){var a=g.lu("yt-remote-cast-receiver");
return a?a.friendlyName:null},hJa=function(){I7("clearCurrentReceiver");
g.mu("yt-remote-cast-receiver")},iJa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.No("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},$Ia=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.pB||a},jJa=function(a,b){M7().init(a,b)},aJa=function(a,b){var c=!1;
M7()||(c=new E7(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.ku("yt-remote-cast-available",d);d6("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){I7("onReceiverSelected: "+d.friendlyName);
g.ku("yt-remote-cast-receiver",d);d6("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){I7("onReceiverResumed: "+d.friendlyName);
g.ku("yt-remote-cast-receiver",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){I7("onSessionChange: "+h6(d));
d||g.mu("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
I7("cloudview.createSingleton_: "+c);return c},M7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},bJa=function(a,b){L7(!0);
J7(!1);jJa(a,function(c){c?(fJa(!0),g.Po("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.mu("yt-remote-cast-available"),g.mu("yt-remote-cast-receiver"),cJa());b(c)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.ku("yt-remote-cast-installed",a)},P7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},fJa=function(a){I7("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.K=this.R=0;this.u=null;this.hasNext=this.Ti=!1;this.P=this.I=this.B=this.F=0;this.D=NaN;this.C=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.u=null;a.playerState=-1;a.Ti=!1;a.hasNext=!1;a.R=0;a.K=g.A();a.F=0;a.B=0;a.I=0;a.P=0;a.D=NaN;a.C=!1},U7=function(a){return a.Hb()?(g.A()-a.K)/1E3:0},V7=function(a,b){a.R=b;
a.K=g.A()},W7=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.K)/1E3+a.R;
case -1E3:return 0}return a.R},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.u);b.hasPrevious=a.Ti;b.hasNext=a.hasNext;b.playerTime=a.R;b.playerTimeAt=a.K;b.seekableStart=a.F;b.seekableEnd=a.B;b.duration=a.I;b.loadedTime=a.P;b.liveIngestionTime=a.D;return b},$7=function(a,b){g.O.call(this);
this.Ka=0;this.C=a;this.F=[];this.D=new wIa;this.B=this.u=null;this.R=(0,g.z)(this.xO,this);this.I=(0,g.z)(this.rr,this);this.K=(0,g.z)(this.wO,this);this.P=(0,g.z)(this.EO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.vA,this),kJa(this))):c=3;0!=c&&(b?this.vA(c):g.Go((0,g.z)(function(){this.vA(c)},this),0));
var d=iJa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.P)},a8=function(a){return new S7(a.C.getPlayerContextData())},kJa=function(a){g.Cb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Ta(this.YP,b),this))},a)},lJa=function(a){g.Cb(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},b8=function(a){return 1==a.getState()},c8=function(a,b){var c=a.D;
50>c.u.length+c.B.length&&a.D.B.push(b)},e8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.C.sendMessage(b,c)},d8=function(a,b){lJa(a);
a.C.setPlayerContextData(Y7(b));kJa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.R),a.B.removeMediaListener(a.I),a.rr(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.R),a.B.addMediaListener(a.I),a.B.media.length&&a.rr(a.B.media[0]))},mJa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;V7(d,a.u.getEstimatedTime());d8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.z)(function(d){this.Cd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Cd("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.O.call(this);
this.F=NaN;this.Y=!1;this.R=this.K=this.P=this.X=NaN;this.aa=[];this.D=this.I=this.C=this.Lb=this.u=null;this.ha=a;this.aa.push(g.cp(window,"beforeunload",(0,g.z)(this.DK,this)));this.B=[];this.Lb=new S7;this.fa=b.id;this.u=nJa(this,c);this.u.subscribe("handlerOpened",this.BO,this);this.u.subscribe("handlerClosed",this.yO,this);this.u.subscribe("handlerError",this.zO,this);this.u.subscribe("handlerMessage",this.AO,this);AIa(this.u,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Lb.videoId;
g.nu()&&g.ku("yt-remote-session-video-id",d)},this)},i8=function(a){j7("conn",a)},nJa=function(a,b){return new c7(g7(a.ha,"/bc"),b,!1,function(){return a.CI()})},j8=function(a,b){a.V("proxyStateChange",b)},oJa=function(a){a.F=g.Go((0,g.z)(function(){i8("Connecting timeout");
this.Un(1)},a),2E4)},k8=function(a){g.Io(a.F);
a.F=NaN},l8=function(a){g.Io(a.X);
a.X=NaN},pJa=function(a){m8(a);
a.P=g.Go((0,g.z)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.Io(a.P);
a.P=NaN},rJa=function(a,b){b&&(k8(a),l8(a));
var c=e7(a.u)&&isNaN(a.F);b==c?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.mD()&&a.Lb.reset(),j8(a,1),n8(a,"getNowPlaying"),qJa(a)):a.Un(1)},sJa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Lb.videoId&&(g.Sb(b.params)?a.Lb.u=null:a.Lb.u=b.params,a.V("remotePlayerChange"))},tJa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Lb.listId=b.params.listId||a.Lb.listId;X7(a.Lb,c,d);a.V("remoteQueueChange")},vJa=function(a,b){b.params=b.params||{};
tJa(a,b);uJa(a,b);a.V("autoplayDismissed")},uJa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
V7(a.Lb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Lb.playerState&&(c=-1E3);a.Lb.playerState=c;c=Number(b.params.loadedTime);a.Lb.P=isNaN(c)?0:c;a.Lb.gi(Number(b.params.duration));c=a.Lb;var d=Number(b.params.liveIngestionTime);c.D=d;c.C=isNaN(d)?!1:!0;c=a.Lb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.F=isNaN(d)?0:d;c.B=isNaN(e)?0:e;1==a.Lb.playerState?pJa(a):m8(a);a.V("remotePlayerChange")},wJa=function(a,b){if(-1E3!=a.Lb.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Lb.playerState=c;c=parseInt(b.params.currentTime,10);V7(a.Lb,isNaN(c)?0:c);a.V("remotePlayerChange")}},xJa=function(a,b){var c="true"==b.params.muted;
a.Lb.volume=parseInt(b.params.volume,10);a.Lb.muted=c;a.V("remotePlayerChange")},yJa=function(a,b){a.I=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},zJa=function(a,b){var c="true"==b.params.hasNext;
a.Lb.Ti="true"==b.params.hasPrevious;a.Lb.hasNext=c;a.V("previousNextChange")},qJa=function(a){g.Io(a.R);
a.R=g.Go((0,g.z)(a.Un,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Nj(c)):i8("Sending: action="+b);
a.u.sendMessage(b,c)},o8=function(a){n7.call(this,"ScreenServiceProxy");
this.xf=a;this.u=[];this.u.push(this.xf.$_s("screenChange",(0,g.z)(this.CL,this)));this.u.push(this.xf.$_s("onlineScreenChange",(0,g.z)(this.FP,this)))},DJa=function(a,b){AHa();
if(!r6||!r6.get("yt-remote-disable-remote-module-for-dev")){b=g.L("MDX_CONFIG")||b;sHa();p6();p8||(p8=new f7(b?b.loungeApiHost:void 0),BHa()&&(p8.u="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",q8,void 0));AJa();var c=r8();if(!c){var d=new w7(p8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=r8();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});eJa(a,d,function(h){h?s8()&&R7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){d6("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ja("yt.mdx.remote.initialized_")){g.Fa("yt.mdx.remote.initialized_",!0,void 0);
t8("Initializing: "+g.Nj(b));u8.push(g.No("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")}));
u8.push(g.No("yt-remote-cast2-receiver-selected",function(){v8(null);d6("yt-remote-auto-connect","cast-selector-receiver")}));
u8.push(g.No("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")}));
u8.push(g.No("yt-remote-cast2-session-change",BJa));u8.push(g.No("yt-remote-connection-change",function(h){h?R7(s8(),"YouTube TV"):w8()||(R7(null,null),hJa())}));
e=x8();b.isAuto&&(e.id+="#dial");g.vo("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);t8(" -- with channel params: "+g.Nj(e));e?(g.ku("yt-remote-session-app",e.app),g.ku("yt-remote-session-name",e.name)):(g.mu("yt-remote-session-app"),g.mu("yt-remote-session-name"));g.Fa("yt.mdx.remote.channelParams_",e,void 0);c.start();s8()||CJa()}}},EJa=function(){var a=r8().xf.$_gos();
var b=y8();b&&z8()&&(k6(a,b)||a.push(b));return rHa(a)},A8=function(){var a=FJa();
!a&&O7()&&gJa()&&(a={key:"cast-selector-receiver",name:gJa()});return a},FJa=function(){var a=EJa(),b=y8();
b||(b=w8());return g.fb(a,function(c){return b&&g6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().sg();return l6(b,a)},BJa=function(a){t8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=y8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){j7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},GJa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},HJa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||GJa("");g.Fa("yt.mdx.remote.connection_",a,void 0);q8&&(g.Cb(q8,function(c){c(a)}),q8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},w8=function(){var a=g.nu();
if(!a)return null;var b=r8();if(!b)return null;b=b.sg();return l6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{GJa(a.id);var c=new h8(p8,a,x8());c.connect(b,HJa());c.subscribe("beforeDisconnect",function(d){d6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},CJa=function(){var a=w8();
a?(t8("Resume connection to: "+h6(a)),C8(a,0)):(q6(),hJa(),t8("Skipping connecting because no session screen found."))},AJa=function(){var a=x8();
if(g.Sb(a)){a=o6();var b=g.lu("yt-remote-session-name")||"",c=g.lu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},I8=function(a,b,c){g.C.call(this);
var d=this;this.B=a;this.J=b;this.yb=c;this.events=new g.tR(this);this.X=this.events.N(this.J,"onVolumeChange",function(e){IJa(d,e)});
this.F=!1;this.suggestion=null;this.I=new g.AM(64);this.u=new g.F(this.GH,500,this);this.C=new g.F(this.HH,1E3,this);this.R=new u6(this.AS,0,this);this.D={};this.P=new g.F(this.nI,1E3,this);this.K=new v6(this.seekTo,1E3,this);this.Y=g.Ka;g.D(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.jP);this.events.N(b,"captionschanged",this.uO);this.events.N(b,"captionssettingschanged",this.MH);this.events.N(b,"videoplayerreset",this.Bv);this.events.N(b,"mdxautoplaycancel",function(){d.yb.IC()});
a=this.yb;a.na();a.subscribe("proxyStateChange",this.jG,this);a.subscribe("remotePlayerChange",this.wr,this);a.subscribe("remoteQueueChange",this.Bv,this);a.subscribe("previousNextChange",this.gG,this);a.subscribe("nowAutoplaying",this.bG,this);a.subscribe("autoplayDismissed",this.CF,this);g.D(this,this.u);g.D(this,this.C);g.D(this,this.R);g.D(this,this.P);g.D(this,this.K);this.MH();this.Bv();this.wr()},IJa=function(a,b){if(J8(a)){a.yb.unsubscribe("remotePlayerChange",a.wr,a);
var c=Math.round(b.volume),d=!!b.muted,e=a8(a.yb);if(c!==e.volume||d!==e.muted)a.yb.setVolume(c,d),a.P.start();a.yb.subscribe("remotePlayerChange",a.wr,a)}},JJa=function(a){a.sc(0);
a.u.stop();a.vb(new g.AM(64))},K8=function(a,b){if(J8(a)&&!a.F){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Zb(c,b));a.yb.DI(a.J.getVideoData(1).videoId,c);a.D=a8(a.yb).u}},L8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.yb.playVideo(c.videoId,b,d,e,c.playerParams,c.Ug,eHa(c));a.vb(new g.AM(1))},KJa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{ND:1});
c&&c.length?(a.J.setOption("captions","track",b),a.F=!1):(a.J.loadModule("captions"),a.F=!0)}else a.J.setOption("captions","track",{})},J8=function(a){return a8(a.yb).videoId===a.J.getVideoData(1).videoId},M8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-manual-pairing-popup-title",Z:"Nous allons bient\u00f4t supprimer la possibilit\u00e9 de se connecter \u00e0 un t\u00e9l\u00e9viseur via Internet \u00e0 l'aide d'un code"},{G:"div",L:"ytp-mdx-manual-pairing-popup-buttons",S:[{G:"button",la:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Z:"En savoir plus"},{G:"button",la:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],
Z:"OK"}]}]}]});this.u=new g.mO(this,250);this.learnMoreButton=this.ka("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ka("ytp-mdx-manual-pairing-popup-ok");g.D(this,this.u);this.N(this.learnMoreButton,"click",this.B);this.N(this.okButton,"click",this.C)},N8=function(){g.V.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",S:[{G:"div",L:"ytp-mdx-popup-title",Z:"Vous \u00eates d\u00e9connect\u00e9"},{G:"div",L:"ytp-mdx-popup-description",Z:"Les vid\u00e9os que vous visionnez peuvent \u00eatre ajout\u00e9es \u00e0 l'historique des vid\u00e9os regard\u00e9es sur votre t\u00e9l\u00e9viseur et avoir une influence sur les recommandations qui vous sont faites. Pour \u00e9viter ce probl\u00e8me, annulez et connectez-vous \u00e0 YouTube sur un ordinateur."},
{G:"div",L:"ytp-mdx-privacy-popup-buttons",S:[{G:"button",la:["ytp-button","ytp-mdx-privacy-popup-cancel"],Z:"Annuler"},{G:"button",la:["ytp-button","ytp-mdx-privacy-popup-confirm"],Z:"Confirmer"}]}]}]});this.u=new g.mO(this,250);this.cancelButton=this.ka("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ka("ytp-mdx-privacy-popup-confirm");g.D(this,this.u);this.N(this.cancelButton,"click",this.B);this.N(this.confirmButton,"click",this.C)},O8=function(a){g.V.call(this,{G:"div",
L:"ytp-remote",S:[{G:"div",L:"ytp-remote-display-status",S:[{G:"div",L:"ytp-remote-display-status-icon",S:[g.Ona()]},{G:"div",L:"ytp-remote-display-status-text",Z:"{{statustext}}"}]}]});this.api=a;this.u=new g.mO(this,250);g.D(this,this.u);this.N(a,"presentingplayerstatechange",this.B);LJa(this,g.uK(a))},LJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.tL("Erreur sur $RECEIVER_NAME",c):b.Hb()||g.U(b,4)?g.tL("Lecture sur $RECEIVER_NAME",c):g.tL("Connect\u00e9 \u00e0 $RECEIVER_NAME",c);a.ya("statustext",c);a.u.show()}else a.u.hide()},P8=function(a,b){g.wX.call(this,"Lire sur",0,a,b);
this.J=a;this.Dl={};this.N(a,"onMdxReceiversChange",this.D);this.N(a,"presentingplayerstatechange",this.D);this.D()},Q8=function(a){g.JS.call(this,a);
this.Qh={key:j6(),name:"Cet ordinateur"};this.zi=null;this.subscriptions=[];this.Rz=this.yb=null;this.Dl=[this.Qh];this.Hk=this.Qh;this.Pc=new g.AM(64);this.lE=0;this.Je=-1;this.wo=null;this.zr=this.Ju=!1;this.Ym=this.Uo=null;if(!g.xD(this.player.T())){a=this.player;var b=g.BT(a);b&&(b=b.Qk())&&(b=new P8(a,b),g.D(this,b));b=new O8(a);g.D(this,b);g.BP(a,b.element,4);this.Uo=new N8;g.D(this,this.Uo);g.BP(a,this.Uo.element,4);g.Q(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.Q(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.wo=new M8,g.D(this,this.wo),g.BP(a,this.wo.element,4));this.zr=!!w8();this.Ju=!!g.lu("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.Ym&&(a.player.removeEventListener("presentingplayerstatechange",a.Ym),a.Ym=null)},MJa=function(a,b,c){a.Pc=c;
a.player.V("presentingplayerstatechange",new g.EK(c,b))},NJa=function(a,b,c){var d=!1;
1===b?d=!a.zr:2===b&&(d=!a.Ju);d&&g.GK(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.Hk.key)if(b.key===a.Qh.key)B8();
else{if(a.wo&&!a.Ju&&b!==a.Qh&&"cast-selector-receiver"!==b.key&&g.HD(a.player.T()))OJa(a);else{var c;(c=!g.Q(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.zr||!a.Uo);(c?0:g.HD(a.player.T())||g.LD(a.player.T()))&&PJa(a)}a.Hk=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.Q(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Ma(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ug,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=eHa(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Nj(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,P7()?M7().setLaunchParams(c):K7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?d6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().sg(),(c=l6(c,b.key))&&C8(c,1))}},PJa=function(a){g.uK(a.player).Hb()?a.player.pauseVideo():(a.Ym=function(b){NJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Ym));
a.Uo&&a.Uo.Bc();z8()||(G8=!0)},OJa=function(a){g.uK(a.player).Hb()?a.player.pauseVideo():(a.Ym=function(b){NJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Ym));
a.wo&&a.wo.Bc();z8()||(G8=!0)},SHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},K6={"'":"\\'"},QJa={},nHa={KT:"atp",R2:"ska",O1:"que",U_:"mus",Q2:"sus",qX:"dsp",h2:"seq",z_:"mic",pW:"dpa"},r6,n6="",GHa=CHa("loadCastFramework")||CHa("loadCastApplicationFramework"),dJa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(u6,g.C);g.k=u6.prototype;g.k.AK=function(a){this.D=arguments;this.u=!1;this.Za?this.C=g.A()+this.yf:this.Za=g.Lm(this.F,this.yf)};
g.k.stop=function(){this.Za&&(g.v.clearTimeout(this.Za),this.Za=null);this.C=null;this.u=!1;this.D=[]};
g.k.pause=function(){++this.B};
g.k.resume=function(){this.B&&(--this.B,!this.B&&this.u&&(this.u=!1,this.I.apply(null,this.D)))};
g.k.ca=function(){this.stop();u6.Jd.ca.call(this)};
g.k.BK=function(){this.C?(this.Za=g.Lm(this.F,this.C-g.A()),this.C=null):(this.Za=null,this.B?this.u=!0:(this.u=!1,this.I.apply(null,this.D)))};g.u(v6,g.C);g.k=v6.prototype;g.k.zE=function(a){this.C=arguments;this.Za||this.B?this.u=!0:w6(this)};
g.k.stop=function(){this.Za&&(g.v.clearTimeout(this.Za),this.Za=null,this.u=!1,this.C=null)};
g.k.pause=function(){this.B++};
g.k.resume=function(){this.B--;this.B||!this.u||this.Za||(this.u=!1,w6(this))};
g.k.ca=function(){g.C.prototype.ca.call(this);this.stop()};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var A6=new g.am;g.u(JHa,g.El);C6.prototype.u=null;C6.prototype.getOptions=function(){var a;(a=this.u)||(a={},LHa(this)&&(a[0]=!0,a[1]=!0),a=this.u=a);return a};var T8;g.Va(KHa,C6);T8=new KHa;g.k=D6.prototype;g.k.Bm=null;g.k.ji=!1;g.k.zp=null;g.k.eB=null;g.k.fp=null;g.k.np=null;g.k.Bk=null;g.k.El=null;g.k.Zm=null;g.k.xe=null;g.k.As=0;g.k.oi=null;g.k.Aw=null;g.k.Uk=null;g.k.Dq=-1;g.k.uH=!0;g.k.fm=!1;g.k.sy=0;g.k.Qv=null;var QHa={},G6={};g.k=D6.prototype;g.k.setTimeout=function(a){this.F=a};
g.k.CR=function(a){a=a.target;var b=this.Qv;b&&3==P6(a)?b.zE():this.zI(a)};
g.k.zI=function(a){try{if(a==this.xe)a:{var b=P6(this.xe),c=this.xe.I,d=this.xe.getStatus();if(g.ye&&!g.be(10)||g.Ae&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xg&&!R6(this.xe))break a;this.fm||4!=b||7==c||(8==c||0>=d?this.u.Xh(3):this.u.Xh(2));L6(this);var e=this.xe.getStatus();this.Dq=e;var f=R6(this.xe);(this.ji=200==e)?(4==b&&I6(this),this.I?(RHa(this,b,f),g.xg&&this.ji&&3==b&&(this.D.wa(this.C,"tick",this.xR),this.C.start())):H6(this,f),this.ji&&!this.fm&&(4==b?this.u.au(this):(this.ji=
!1,F6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Uk=3,B6(13)):(this.Uk=0,B6(14)),I6(this),J6(this))}}catch(h){this.xe&&R6(this.xe)}finally{}};
g.k.xR=function(){var a=P6(this.xe),b=R6(this.xe);this.As<b.length&&(L6(this),RHa(this,a,b),this.ji&&4!=a&&F6(this))};
g.k.UQ=function(a){z6((0,g.z)(this.TQ,this,a),0)};
g.k.TQ=function(a){this.fm||(L6(this),H6(this,a),F6(this))};
g.k.sG=function(a){z6((0,g.z)(this.SQ,this,a),0)};
g.k.SQ=function(a){this.fm||(I6(this),this.ji=a,this.u.au(this),this.u.Xh(4))};
g.k.cancel=function(){this.fm=!0;I6(this)};
g.k.dR=function(){this.zp=null;var a=g.A();0<=a-this.eB?(2!=this.np&&this.u.Xh(3),I6(this),this.Uk=2,B6(18),J6(this)):UHa(this,this.eB-a)};
g.k.getLastError=function(){return this.Uk};g.Va(N6,g.am);var aIa=/^https?$/i,RJa=["POST","PUT"];g.k=N6.prototype;
g.k.send=function(a,b,c,d){if(this.u)throw Error("[goog.net.XhrIo] Object is active with another request="+this.P+"; newUri="+a);b=b?b.toUpperCase():"GET";this.P=a;this.D="";this.I=0;this.Aa=b;this.ha=!1;this.C=!0;this.u=this.fa?MHa(this.fa):MHa(T8);this.aa=this.fa?this.fa.getOptions():T8.getOptions();this.u.onreadystatechange=(0,g.z)(this.hG,this);try{c6(Q6(this,"Opening Xhr")),this.ma=!0,this.u.open(b,String(a),!0),this.ma=!1}catch(f){c6(Q6(this,"Error opening Xhr: "+f.message));$Ha(this,f);return}a=
c||"";var e=this.headers.clone();d&&jHa(d,function(f,h){e.set(h,f)});
d=g.fb(e.Sg(),YHa);c=g.v.FormData&&a instanceof g.v.FormData;!g.jb(RJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.u.setRequestHeader(h,f)},this);
this.Ja&&(this.u.responseType=this.Ja);"withCredentials"in this.u&&this.u.withCredentials!==this.ia&&(this.u.withCredentials=this.ia);try{cIa(this),0<this.K&&(this.Y=XHa(this.u),c6(Q6(this,"Will abort after "+this.K+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.u.timeout=this.K,this.u.ontimeout=(0,g.z)(this.wD,this)):this.X=g.Lm(this.wD,this.K,this)),c6(Q6(this,"Sending request")),this.R=!0,this.u.send(a),this.R=!1}catch(f){c6(Q6(this,"Send error: "+f.message)),$Ha(this,f)}};
g.k.wD=function(){"undefined"!=typeof g.k1&&this.u&&(this.D="Timed out after "+this.K+"ms, aborting",this.I=8,Q6(this,this.D),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.u&&this.C&&(Q6(this,"Aborting"),this.C=!1,this.F=!0,this.u.abort(),this.F=!1,this.I=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),O6(this))};
g.k.ca=function(){this.u&&(this.C&&(this.C=!1,this.F=!0,this.u.abort(),this.F=!1),O6(this,!0));N6.Jd.ca.call(this)};
g.k.hG=function(){this.na()||(this.ma||this.R||this.F?bIa(this):this.bQ())};
g.k.bQ=function(){bIa(this)};
g.k.isActive=function(){return!!this.u};
g.k.getStatus=function(){try{return 2<P6(this)?this.u.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.D?this.D:String(this.D)};g.k=dIa.prototype;g.k.qy=null;g.k.hg=null;g.k.Rv=!1;g.k.vD=null;g.k.Dt=null;g.k.az=null;g.k.ry=null;g.k.Ka=null;g.k.Lj=-1;g.k.Cq=null;g.k.Rp=null;g.k.connect=function(a){this.ry=a;a=S6(this.u,null,this.ry);B6(3);this.vD=g.A();var b=this.u.K;null!=b?(this.Cq=b[0],(this.Rp=b[1])?(this.Ka=1,eIa(this)):(this.Ka=2,U6(this))):(a6(a,"MODE","init"),this.hg=new D6(this,void 0,void 0,void 0),this.hg.Bm=this.qy,E6(this.hg,a,!1,null,!0),this.Ka=0)};
g.k.BJ=function(a){if(a)this.Ka=2,U6(this);else{B6(4);var b=this.u;b.Ri=b.Gk.Lj;a7(b,9)}a&&this.Xh(2)};
g.k.Cx=function(a){return this.u.Cx(a)};
g.k.abort=function(){this.hg&&(this.hg.cancel(),this.hg=null);this.Lj=-1};
g.k.uD=function(){return!1};
g.k.kG=function(a,b){this.Lj=a.Dq;if(0==this.Ka)if(b){try{var c=this.B.parse(b)}catch(d){c=this.u;c.Ri=this.Lj;a7(c,2);return}this.Cq=c[0];this.Rp=c[1]}else c=this.u,c.Ri=this.Lj,a7(c,2);else if(2==this.Ka)if(this.Rv)B6(7),this.az=g.A();else if("11111"==b){if(B6(6),this.Rv=!0,this.Dt=g.A(),c=this.Dt-this.vD,!g.ye||g.be(10)||500>c)this.Lj=200,this.hg.cancel(),B6(12),T6(this.u,this,!0)}else B6(8),this.Dt=this.az=g.A(),this.Rv=!1};
g.k.au=function(){this.Lj=this.hg.Dq;if(this.hg.ji)0==this.Ka?this.Rp?(this.Ka=1,eIa(this)):(this.Ka=2,U6(this)):2==this.Ka&&((!g.ye||g.be(10)?!this.Rv:200>this.az-this.Dt)?(B6(11),T6(this.u,this,!1)):(B6(12),T6(this.u,this,!0)));else{0==this.Ka?B6(9):2==this.Ka&&B6(10);var a=this.u;this.hg.getLastError();a.Ri=this.Lj;a7(a,2)}};
g.k.Wr=function(){return this.u.Wr()};
g.k.isActive=function(){return this.u.isActive()};
g.k.Xh=function(a){this.u.Xh(a)};g.k=V6.prototype;g.k.Tk=null;g.k.jq=null;g.k.Wf=null;g.k.Sd=null;g.k.py=null;g.k.Ft=null;g.k.ZB=null;g.k.Zt=null;g.k.mr=0;g.k.LN=0;g.k.vf=null;g.k.Kk=null;g.k.yj=null;g.k.lm=null;g.k.Gk=null;g.k.xw=null;g.k.ro=-1;g.k.kE=-1;g.k.Ri=-1;g.k.Zn=0;g.k.Mn=0;g.k.gm=8;g.Va(iIa,g.El);g.Va(jIa,g.El);g.k=V6.prototype;g.k.connect=function(a,b,c,d,e){B6(0);this.py=b;this.jq=c||{};d&&void 0!==e&&(this.jq.OSID=d,this.jq.OAID=e);this.F?(z6((0,g.z)(this.rC,this,a),100),nIa(this)):this.rC(a)};
g.k.rC=function(a){this.Gk=new dIa(this);this.Gk.qy=this.Tk;this.Gk.B=this.D;this.Gk.connect(a)};
g.k.uD=function(){return 0==this.Ka};
g.k.getState=function(){return this.Ka};
g.k.rG=function(a){this.Kk=null;rIa(this,a)};
g.k.qG=function(){this.yj=null;this.Sd=new D6(this,this.B,"rpc",this.I);this.Sd.Bm=this.Tk;this.Sd.sy=0;var a=this.ZB.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.B);Z5(a,"CI",this.xw?"0":"1");Z5(a,"AID",this.ro);W6(this,a);if(!g.ye||g.be(10))Z5(a,"TYPE","xmlhttp"),E6(this.Sd,a,!0,this.Zt,!1);else{Z5(a,"TYPE","html");var b=this.Sd,c=!!this.Zt;b.np=3;b.Bk=$5(a.clone());THa(b,c)}};
g.k.kG=function(a,b){if(0!=this.Ka&&(this.Sd==a||this.Wf==a))if(this.Ri=a.Dq,this.Wf==a&&3==this.Ka)if(7<this.gm){try{var c=this.D.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.yj){if(this.Sd)if(this.Sd.fp+3E3<this.Wf.fp)Y6(this),this.Sd.cancel(),this.Sd=null;else break a;$6(this);B6(19)}}else this.kE=c[1],0<this.kE-this.ro&&37500>c[2]&&this.xw&&0==this.Mn&&!this.lm&&(this.lm=z6((0,g.z)(this.qO,this),6E3));else a7(this,11)}else b!=QJa.dW.u&&a7(this,11);else if(this.Sd==
a&&Y6(this),!g.pc(b)){c=this.D.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ro=e[0];e=e[1];2==this.Ka?"c"==e[0]?(this.B=e[1],this.Zt=e[2],e=e[3],null!=e?this.gm=e:this.gm=6,this.Ka=3,this.vf&&this.vf.nC(),this.ZB=S6(this,this.Wr()?this.Zt:null,this.py),sIa(this)):"stop"==e[0]&&a7(this,7):3==this.Ka&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.vf&&this.vf.mC(e),this.Mn=0)}}};
g.k.qO=function(){null!=this.lm&&(this.lm=null,this.Sd.cancel(),this.Sd=null,$6(this),B6(20))};
g.k.au=function(a){if(this.Sd==a){Y6(this);this.Sd=null;var b=2}else if(this.Wf==a)this.Wf=null,b=1;else return;this.Ri=a.Dq;if(0!=this.Ka)if(a.ji)1==b?(b=A6,b.dispatchEvent(new iIa(b,a.Zm?a.Zm.length:0,g.A()-a.fp,this.Zn)),X6(this),this.C.length=0):sIa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ri)){if(d=1==b)this.Wf||this.Kk||1==this.Ka||2<=this.Zn?d=!1:(this.Kk=z6((0,g.z)(this.rG,this,a),tIa(this,this.Zn)),this.Zn++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,
5);break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.k.aK=function(a){if(!g.jb(arguments,this.Ka))throw Error("Unexpected channel state: "+this.Ka);};
g.k.mS=function(a){a?B6(2):(B6(1),uIa(this,8))};
g.k.Cx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N6;a.ia=!1;return a};
g.k.isActive=function(){return!!this.vf&&this.vf.isActive(this)};
g.k.Xh=function(a){var b=A6;b.dispatchEvent(new jIa(b,a))};
g.k.Wr=function(){return!(!g.ye||g.be(10))};
g.k=vIa.prototype;g.k.nC=function(){};
g.k.mC=function(){};
g.k.lC=function(){};
g.k.rx=function(){};
g.k.XC=function(){return{}};
g.k.isActive=function(){return!0};g.k=wIa.prototype;g.k.isEmpty=function(){return g.kb(this.u)&&g.kb(this.B)};
g.k.clear=function(){this.u=[];this.B=[]};
g.k.contains=function(a){return g.jb(this.u,a)||g.jb(this.B,a)};
g.k.remove=function(a){var b=this.u;var c=(0,g.rBa)(b,a);0<=c?(g.nb(b,c),b=!0):b=!1;return b||g.ob(this.B,a)};
g.k.Hf=function(){for(var a=[],b=this.u.length-1;0<=b;--b)a.push(this.u[b]);var c=this.B.length;for(b=0;b<c;++b)a.push(this.B[b]);return a};g.Va(b7,g.C);g.k=b7.prototype;g.k.NQ=function(){this.yf=Math.min(3E5,2*this.yf);this.C();this.B&&this.start()};
g.k.start=function(){var a=this.yf+15E3*Math.random();this.u.Sb(a);this.B=g.A()+a};
g.k.stop=function(){this.u.stop();this.B=0};
g.k.isActive=function(){return this.u.isActive()};
g.k.reset=function(){this.u.stop();this.yf=5E3};g.Va(c7,vIa);g.k=c7.prototype;g.k.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.k.nl=function(a){return this.C.Cm(a)};
g.k.V=function(a,b){return this.C.V.apply(this.C,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.fg(this.C),zIa(this),g.fg(this.B),this.B=null,this.Y=function(){return""})};
g.k.na=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.u||2!=this.u.getState()){this.P="";this.B.stop();this.F=a||null;this.D=b||0;a=this.aa+"/test";b=this.aa+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.fa),e=this.u;e&&(e.vf=null);d.vf=this;this.u=d;d7(this);if(this.u){d=g.L("ID_TOKEN");var f=this.u.Tk||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.u.Tk=f}e?(3!=e.getState()&&0==pIa(e)||e.getState(),this.u.connect(a,b,this.I,e.B,e.ro)):c?this.u.connect(a,
b,this.I,c.sessionId,c.arrayId):this.u.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Zb(c,b);this.B.isActive()||2==(this.u?this.u.getState():0)?this.K.push(c):e7(this)&&(d7(this),oIa(this.u,c))};
g.k.nC=function(){this.B.reset();this.F=null;this.D=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)oIa(this.u,a[b])}this.V("handlerOpened")};
g.k.lC=function(a){var b=2==a&&401==this.u.Ri;4==a||b||this.B.start();this.V("handlerError",a)};
g.k.rx=function(a){if(!this.B.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.XC=function(){var a={v:2};this.P&&(a.gsessionid=this.P);0!=this.D&&(a.ui=""+this.D);0!=this.R&&(a.ui=""+this.R);this.F&&g.Zb(a,this.F);return a};
g.k.mC=function(a){"S"==a[0]?this.P=a[1]:"gracefulReconnect"==a[0]?(this.B.start(),mIa(this.u)):this.V("handlerMessage",new xIa(a[0],a[1]))};
g.k.OR=function(){this.B.isActive();0==pIa(this.u)&&this.connect(this.F,this.D)};f7.prototype.D=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.F=function(a){a(Error("request timed out"))};var HIa=g.A(),i7=null,l7=Array(50),k7=-1,m7=!1;g.Va(n7,g.O);n7.prototype.sg=function(){return this.screens};
n7.prototype.contains=function(a){return!!k6(this.screens,a)};
n7.prototype.get=function(a){return a?l6(this.screens,a):null};
n7.prototype.info=function(a){j7(this.I,a)};g.u(o7,g.O);g.k=o7.prototype;g.k.start=function(){!this.u&&isNaN(this.Za)&&this.FI()};
g.k.stop=function(){this.u&&(this.u.abort(),this.u=null);isNaN(this.Za)||(g.Io(this.Za),this.Za=NaN)};
g.k.ca=function(){this.stop();g.O.prototype.ca.call(this)};
g.k.FI=function(){this.Za=NaN;this.u=g.qq(g7(this.I,"/pairing/get_screen"),{method:"POST",tc:{pairing_code:this.F},timeout:5E3,onSuccess:(0,g.z)(this.NS,this),onError:(0,g.z)(this.MS,this),Bg:(0,g.z)(this.OS,this)})};
g.k.NS=function(a,b){this.u=null;var c=b.screen||{};c.dialId=this.C;c.name=this.D;this.V("pairingComplete",new f6(c))};
g.k.MS=function(a){this.u=null;a.status&&404==a.status?this.B>=SJa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=SJa[this.B],this.Za=g.Go((0,g.z)(this.FI,this),a),this.B++):this.V("pairingFailed",Error("Server error "+a.status))};
g.k.OS=function(){this.u=null;this.V("pairingFailed",Error("Server not responding"))};
var SJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(q7,n7);g.k=q7.prototype;g.k.start=function(){p7(this)&&this.V("screenChange");!g.lu("yt-remote-lounge-token-expiration")&&LIa(this);g.Io(this.u);this.u=g.Go((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){p7(this);IIa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||LIa(this)};
g.k.remove=function(a,b){var c=p7(this);KIa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.k.uw=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.k.ca=function(){g.Io(this.u);q7.Jd.ca.call(this)};
g.k.JK=function(a){p7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.I,"Missed "+b+" lounge tokens.")};
g.k.IK=function(a){j7(this.I,"Requesting lounge tokens failed: "+a)};g.u(t7,g.O);g.k=t7.prototype;g.k.start=function(){var a=parseInt(g.lu("yt-remote-fast-check-period")||"0",10);(this.D=g.A()-144E5<a?0:a)?v7(this):(this.D=g.A()+3E5,g.ku("yt-remote-fast-check-period",this.D),this.gA())};
g.k.isEmpty=function(){return g.Sb(this.u)};
g.k.update=function(){s7("Updating availability on schedule.");var a=this.I(),b=g.Fb(this.u,function(c,d){return c&&!!l6(a,d)},this);
u7(this,b)};
g.k.ca=function(){g.Io(this.C);this.C=NaN;this.B&&(this.B.abort(),this.B=null);g.O.prototype.ca.call(this)};
g.k.gA=function(){g.Io(this.C);this.C=NaN;this.B&&this.B.abort();var a=OIa(this);if(b6(a)){var b=g7(this.F,"/pairing/get_screen_availability");this.B=h7(this.F,b,{lounge_token:g.Mb(a).join(",")},(0,g.z)(this.vQ,this,a),(0,g.z)(this.uQ,this))}else u7(this,{}),v7(this)};
g.k.vQ=function(a,b){this.B=null;var c=g.Mb(OIa(this));if(g.Ab(c,g.Mb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.Cd("Changing Screen set during request."),this.gA()};
g.k.uQ=function(a){this.Cd("Screen availability failed: "+a);this.B=null;v7(this)};
g.k.Cd=function(a){j7("OnlineScreenService",a)};g.Va(w7,n7);g.k=w7.prototype;g.k.start=function(){this.B.start();this.u.start();this.screens.length&&(this.V("screenChange"),this.u.isEmpty()||this.V("onlineScreenChange"))};
g.k.add=function(a,b,c){this.B.add(a,b,c)};
g.k.remove=function(a,b,c){this.B.remove(a,b,c);this.u.update()};
g.k.uw=function(a,b,c,d){this.B.contains(a)?this.B.uw(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.I,a),d(Error(a)))};
g.k.sg=function(a){return a?this.screens:g.qb(this.screens,g.Ke(this.C,function(b){return!this.contains(b)},this))};
g.k.GI=function(){return g.Ke(this.sg(!0),function(a){return!!this.u.u[a.id]},this)};
g.k.HI=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.fg(f);d(x7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.fg(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.PS=function(a,b,c,d){g.qq(g7(this.F,"/pairing/get_screen"),{method:"POST",tc:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new f6(f.screen||{});if(!h.name||SIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);SIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(x7(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
Bg:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.ca=function(){g.fg(this.B);g.fg(this.u);w7.Jd.ca.call(this)};
g.k.PK=function(){TIa(this);this.V("screenChange");this.u.update()};
w7.prototype.dispose=w7.prototype.dispose;g.Va(z7,g.O);g.k=z7.prototype;g.k.getScreen=function(){return this.K};
g.k.Av=function(a){this.K=a;this.V("sessionScreen",this.K)};
g.k.zg=function(a){this.na()||(a&&A7(this,""+a),this.K=null,this.V("sessionScreen",null))};
g.k.info=function(a){j7(this.aa,a)};
g.k.JI=function(){return null};
g.k.sA=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.ca=function(){this.sA("");z7.Jd.ca.call(this)};g.u(B7,z7);g.k=B7.prototype;g.k.rA=function(a){if(this.B){if(this.B==a)return;A7(this,"Overriding cast sesison with new session object");this.B.removeUpdateListener(this.F);this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.B=a;this.B.addUpdateListener(this.F);this.B.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);VIa(this)};
g.k.uo=function(a){this.info("launchWithParams no-op for Cast: "+g.Nj(a))};
g.k.stop=function(){this.B?this.B.stop((0,g.z)(function(){this.zg()},this),(0,g.z)(function(){this.zg(Error("Failed to stop receiver app."))},this)):this.zg(Error("Stopping cast device witout session."))};
g.k.sA=function(){};
g.k.ca=function(){this.info("disposeInternal");g.Io(this.C);this.C=0;this.B&&(this.B.removeUpdateListener(this.F),this.B.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.B=null;z7.prototype.ca.call(this)};
g.k.kR=function(a,b){if(!this.na())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Nj(c));switch(d){case "mdxSessionStatus":UIa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.k.nD=function(a,b,c,d){RIa(this.R,this.u.label,a,this.u.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Go((0,g.z)(this.nD,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.JI=function(){return this.B};
g.k.QS=function(a){this.na()||a||(A7(this,"Cast session died."),this.zg())};g.u(C7,z7);g.k=C7.prototype;g.k.rA=function(a){this.C=a;this.C.addUpdateListener(this.Y)};
g.k.uo=function(a){this.X=a;this.F()};
g.k.stop=function(){this.B();this.B=g.Ka;g.Io(this.D);this.C?this.C.stop((0,g.z)(this.zg,this,null),(0,g.z)(this.zg,this,"Failed to stop DIAL device.")):this.zg()};
g.k.ca=function(){this.B();this.B=g.Ka;g.Io(this.D);this.C&&this.C.removeUpdateListener(this.Y);this.C=null;z7.prototype.ca.call(this)};
g.k.US=function(a){this.na()||a||(A7(this,"DIAL session died."),this.B(),this.B=g.Ka,this.zg())};
g.k.Dy=function(a){this.P=j6();if(this.X){var b=new chrome.cast.DialLaunchResponse(!0,XIa(this));a(b);WIa(this)}else this.F=(0,g.z)(function(){g.Io(this.D);this.F=g.Ka;this.D=NaN;var c=new chrome.cast.DialLaunchResponse(!0,XIa(this));a(c);WIa(this)},this),this.D=g.Go((0,g.z)(function(){this.F()},this),100)};
g.k.gL=function(a,b,c){RIa(this.R,this.I.receiver.label,a,this.u.friendlyName,(0,g.z)(function(d){d&&d.token?(this.Av(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Dy(b,c)},this),(0,g.z)(function(d){A7(this,"Failed to get DIAL screen: "+d);
this.Dy(b,c)},this))};g.u(D7,z7);D7.prototype.stop=function(){this.zg()};
D7.prototype.rA=function(){};
D7.prototype.uo=function(){g.Io(this.B);this.B=NaN;var a=l6(this.R.sg(),this.u.label);a?this.Av(a):this.zg(Error("No such screen"))};
D7.prototype.ca=function(){g.Io(this.B);this.B=NaN;z7.prototype.ca.call(this)};g.u(E7,g.O);g.k=E7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.R||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.fQ,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.mG,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.MO,this);chrome.cast.initialize(c,(0,g.z)(function(){this.na()||
(chrome.cast.addReceiverActionListener(this.D),EIa(),this.B.subscribe("onlineScreenChange",(0,g.z)(this.II,this)),this.C=ZIa(this),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(h){this.Cd("Failed to set initial custom receivers: "+g.Nj(h))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.z)(function(h){this.Cd("Failed to initialize API: "+g.Nj(h));
b(!1)},this))};
g.k.TR=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.u){var c=this.u.getScreen();if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.u.u.friendlyName),H7(this,null)}if(a&&b){if(!this.u){c=l6(this.B.sg(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=YIa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.Ka,(0,g.z)(function(e){this.Cd("Failed to set initial custom receivers: "+g.Nj(e))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.B,d),!0)}this.u.sA(b)}else F7("setConnectedScreenStatus: no screen.")};
g.k.UR=function(a){this.na()?this.Cd("Setting connection data on disposed cast v2"):this.u?this.u.uo(a):this.Cd("Setting connection data without a session")};
g.k.SS=function(){this.na()?this.Cd("Stopping session on disposed cast v2"):this.u?(this.u.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.mG,this),(0,g.z)(this.xQ,this))};
g.k.ca=function(){this.B.unsubscribe("onlineScreenChange",(0,g.z)(this.II,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=BIa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.ob(b||[],a);g.fg(this.u);g.O.prototype.ca.call(this)};
g.k.Cd=function(a){j7("Controller",a)};
g.k.oG=function(a,b){this.u==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.k.cQ=function(a,b){if(!this.na())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.u)if(this.u.u.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.u.u.friendlyName),this.u.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.u.getScreen()&&this.V("yt-remote-cast2-session-change",this.u.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.B,a));break;case chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.B,a,this.I));break;case chrome.cast.ReceiverType.CAST:H7(this,new B7(this.B,a));break;default:this.Cd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.u&&this.u.u.label==a.label?this.u.stop():this.Cd("Stopping receiver w/o session: "+a.friendlyName)}else this.Cd("onReceiverAction_ called without receiver.")};
g.k.MO=function(a){if(this.na())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Cd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.u?this.u.u:null;if(!c||c.label!=b.label)return this.Cd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.u.getScreen())return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.u.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Cd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.B,b,this.I))}b=this.u;b.I=a;return b.I.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.gL,b,(b.I.extraData||{}).screenId||null)):new Promise((0,g.z)(b.Dy,b))};
g.k.mG=function(a){if(!this.na()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.u)if(b.receiverType==chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.B,b),!0);else{this.Cd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.u.u,d=l6(this.B.sg(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.fg(this.u),this.u=new B7(this.B,b),this.u.subscribe("sessionScreen",(0,g.z)(this.oG,this,this.u)),this.u.uo(null));this.u.rA(a)}}};
g.k.RS=function(){return this.u?this.u.JI():null};
g.k.xQ=function(a){this.na()||(this.Cd("Failed to estabilish a session: "+g.Nj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.k.fQ=function(a){F7("Receiver availability updated: "+a);if(!this.na()){var b=G7(this);this.F=a==chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.k.II=function(){this.na()||(this.C=ZIa(this),F7("Updating custom receivers: "+g.Nj(this.C)),chrome.cast.setCustomReceivers(this.C,g.Ka,(0,g.z)(function(){this.Cd("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.UR;E7.prototype.setConnectedScreenStatus=E7.prototype.TR;E7.prototype.stopSession=E7.prototype.SS;E7.prototype.getCastSession=E7.prototype.RS;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.k=S7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.u=a.trackData,this.Ti=a.hasPrevious,this.hasNext=a.hasNext,this.R=a.playerTime,this.K=a.playerTimeAt,this.F=a.seekableStart,this.B=a.seekableEnd,this.I=a.duration,this.P=a.loadedTime,this.D=a.liveIngestionTime,this.C=!isNaN(this.D))};
g.k.Hb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.gi=function(a){this.I=isNaN(a)?0:a};
g.k.getDuration=function(){return this.C?this.I+U7(this):this.I};
g.k.clone=function(){return new S7(Y7(this))};g.u($7,g.O);g.k=$7.prototype;g.k.getState=function(){return this.Ka};
g.k.play=function(){b8(this)?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){b8(this)?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,W7(a8(this))),this.V("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(b8(this)){if(this.u){var b=a8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Hb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.V("remotePlayerChange")}else c8(this,g.Ta(this.seekTo,a))};
g.k.stop=function(){if(b8(this)){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);d8(this,a);this.V("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(b8(this)){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.z)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Cd("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.z)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Cd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Ta(this.setVolume,a,b))};
g.k.DI=function(a,b){if(b8(this)){var c=a8(this),d={videoId:a};b&&(c.u={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Nj(b.style),g.Zb(d,c.u));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Ta(this.DI,a,b))};
g.k.setAudioTrack=function(a,b){if(b8(this)){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=a8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Ta(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=a8(this);c=c||0;var m={videoId:a,currentIndex:c};X7(l,a,c);void 0!==b&&(V7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Nj(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.Jv=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Ta(this.Jv,a,b))};
g.k.nextVideo=function(a,b){if(b8(this)){if(a&&b){var c=a8(this);X7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Ta(this.nextVideo,a,b))};
g.k.IC=function(){b8(this)?f8(this,"dismissAutoplay"):c8(this,this.IC)};
g.k.dispose=function(){if(3!=this.Ka){var a=this.Ka;this.Ka=3;this.V("proxyStateChange",a,this.Ka)}g.O.prototype.dispose.call(this)};
g.k.ca=function(){lJa(this);this.C=null;this.D.clear();Z7(this,null);g.O.prototype.ca.call(this)};
g.k.vA=function(a){if((a!=this.Ka||2==a)&&3!=this.Ka&&0!=a){var b=this.Ka;this.Ka=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,g.kb(b.u)&&(b.u=b.B,b.u.reverse(),b.B=[]),a.u.pop().apply(this);else 3==a&&this.dispose()}};
g.k.YP=function(a,b){this.V(a,b)};
g.k.xO=function(a){if(!a)this.rr(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.rr=function(a){j7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.K);if(this.u=a)this.u.addUpdateListener(this.K),mJa(this),this.V("remotePlayerChange")};
g.k.wO=function(a){a?(mJa(this),this.V("remotePlayerChange")):this.rr(null)};
g.k.MA=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.EO=function(){var a=iJa();a&&Z7(this,a)};
g.k.Cd=function(a){j7("CP",a)};g.u(h8,g.O);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Lb.listId=c);this.Lb.videoId=d;this.Lb.index=h||0;this.Lb.state=3;V7(this.Lb,m);this.D="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Nj(l));this.u.connect({method:"setPlaylist",
params:g.Nj(l)},a,vHa())}else i8("Connecting without params"),this.u.connect({},a,vHa());oJa(this)};
g.k.dispose=function(){this.na()||(this.V("beforeDispose"),j8(this,3));g.O.prototype.dispose.call(this)};
g.k.ca=function(){k8(this);m8(this);l8(this);g.Io(this.K);this.K=NaN;g.Io(this.R);this.R=NaN;this.C=null;g.dp(this.aa);this.aa.length=0;this.u.dispose();g.O.prototype.ca.call(this);this.D=this.I=this.B=this.Lb=this.u=null};
g.k.DK=function(){this.Un(2)};
g.k.BO=function(){i8("Channel opened");this.Y&&(this.Y=!1,l8(this),this.X=g.Go((0,g.z)(function(){i8("Timing out waiting for a screen.");this.Un(1)},this),15E3));
zHa(yIa(this.u),this.fa)};
g.k.yO=function(){i8("Channel closed");isNaN(this.F)?q6(!0):q6();this.dispose()};
g.k.zO=function(a){q6();isNaN(this.xq())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.Y=!0,i8("Channel error: "+a+" with reconnection in "+this.xq()+" ms"),j8(this,2))};
g.k.AO=function(a){a.params?i8("Received: action="+a.action+", params="+g.Nj(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.B=g.Oc(a,function(c){return new e6(c)});
a=!!g.fb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
rJa(this,a);break;case "loungeScreenDisconnected":g.pb(this.B,function(c){return"LOUNGE_SCREEN"==c.type});
rJa(this,!1);break;case "remoteConnected":var b=new e6(x6(a.params.device));g.fb(this.B,function(c){return b?c.id==b.id:!1})||fHa(this.B,b);
break;case "remoteDisconnected":b=new e6(x6(a.params.device));g.pb(this.B,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":tJa(this,a);break;case "nowPlaying":vJa(this,a);break;case "onStateChange":uJa(this,a);break;case "onAdStateChange":wJa(this,a);break;case "onVolumeChanged":xJa(this,a);break;case "onSubtitlesTrackChanged":sJa(this,a);break;case "nowAutoplaying":yJa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.V("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.D=
a.params.autoplayMode;this.V("autoplayModeChange",this.D);"DISABLED"==this.D&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":zJa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.KR=function(){if(this.C){var a=this.C;this.C=null;this.Lb.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.vK=function(){var a=3;this.na()||(a=0,isNaN(this.xq())?e7(this.u)&&isNaN(this.F)&&(a=1):a=2);return a};
g.k.Un=function(a){i8("Disconnecting with "+a);k8(this);this.V("beforeDisconnect",a);1==a&&q6();zIa(this.u,a);this.dispose()};
g.k.tK=function(){var a=this.Lb;this.C&&(a=this.Lb.clone(),X7(a,this.C,a.index));return Y7(a)};
g.k.VR=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.Lb.videoId&&(this.C=b.videoId,g.Io(this.K),this.K=g.Go((0,g.z)(this.KR,this),5E3));var c=[];this.Lb.listId==b.listId&&this.Lb.videoId==b.videoId&&this.Lb.index==b.index||c.push("remoteQueueChange");this.Lb.playerState==b.playerState&&this.Lb.volume==b.volume&&this.Lb.muted==b.muted&&W7(this.Lb)==W7(b)&&g.Nj(this.Lb.u)==g.Nj(b.u)||c.push("remotePlayerChange");this.Lb.reset(a);g.Cb(c,function(d){this.V(d)},this)};
g.k.mD=function(){var a=this.u.I.id,b=g.fb(this.B,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.xq=function(){var a=this.u;return a.B.isActive()?a.B.B-g.A():NaN};
g.k.kK=function(){return this.D||"UNSUPPORTED"};
g.k.lK=function(){return this.I||""};
g.k.LS=function(){if(!isNaN(this.xq())){var a=this.u.B;g.kn(a.u);a.start()}};
g.k.RR=function(a,b){n8(this,a,b);qJa(this)};
g.k.CI=function(){var a=g.xq("SID","")||"",b=g.xq("SAPISID","")||"",c=g.xq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.sf(g.Xe(a),2);b=g.sf(g.Xe(b),2);c=g.sf(g.Xe(c),2);return g.sf(g.Xe(a+","+b+","+c),2)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.nl;h8.prototype.getProxyState=h8.prototype.vK;h8.prototype.disconnect=h8.prototype.Un;h8.prototype.getPlayerContextData=h8.prototype.tK;h8.prototype.setPlayerContextData=h8.prototype.VR;h8.prototype.getOtherConnectedRemoteId=h8.prototype.mD;h8.prototype.getReconnectTimeout=h8.prototype.xq;h8.prototype.getAutoplayMode=h8.prototype.kK;h8.prototype.getAutoplayVideoId=h8.prototype.lK;h8.prototype.reconnect=h8.prototype.LS;
h8.prototype.sendMessage=h8.prototype.RR;h8.prototype.getXsrfToken=h8.prototype.CI;g.u(o8,n7);g.k=o8.prototype;g.k.sg=function(a){return this.xf.$_gs(a)};
g.k.contains=function(a){return!!this.xf.$_c(a)};
g.k.get=function(a){return this.xf.$_g(a)};
g.k.start=function(){this.xf.$_st()};
g.k.add=function(a,b,c){this.xf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.xf.$_r(a,b,c)};
g.k.uw=function(a,b,c,d){this.xf.$_un(a,b,c,d)};
g.k.ca=function(){for(var a=0,b=this.u.length;a<b;++a)this.xf.$_ubk(this.u[a]);this.u.length=0;this.xf=null;n7.prototype.ca.call(this)};
g.k.CL=function(){this.V("screenChange")};
g.k.FP=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.PS;w7.prototype.$_gsppc=w7.prototype.HI;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.uw;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.sg;w7.prototype.$_gos=w7.prototype.GI;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.nl;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.u(I8,g.C);g.k=I8.prototype;g.k.ca=function(){g.C.prototype.ca.call(this);this.u.stop();this.C.stop();this.R.stop();this.Y();var a=this.yb;a.unsubscribe("proxyStateChange",this.jG,this);a.unsubscribe("remotePlayerChange",this.wr,this);a.unsubscribe("remoteQueueChange",this.Bv,this);a.unsubscribe("previousNextChange",this.gG,this);a.unsubscribe("nowAutoplaying",this.bG,this);a.unsubscribe("autoplayDismissed",this.CF,this);this.yb=this.B=null};
g.k.QE=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.yb.Ka)if(J8(this)){if(!a8(this.yb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":a8(this.yb).Hb()?this.yb.pause():this.yb.play();break;case "control_play":this.yb.play();break;case "control_pause":this.yb.pause();break;case "control_seek":this.K.zE(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.uO=function(a){this.R.AK(a)};
g.k.AS=function(a){this.QE("control_subtitles_set_track",g.Sb(a)?null:a)};
g.k.MH=function(){var a=this.J.getOption("captions","track");g.Sb(a)||K8(this,a)};
g.k.sc=function(a){this.B.sc(a,this.J.getVideoData().lengthSeconds)};
g.k.jP=function(){g.Sb(this.D)||KJa(this,this.D);this.F=!1};
g.k.jG=function(a,b){this.C.stop();2===b&&this.HH()};
g.k.wr=function(){if(J8(this)){this.u.stop();var a=a8(this.yb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.Je=1;break;case 1082:case 1083:this.B.Je=0;break;default:this.B.Je=-1}switch(a.playerState){case 1081:case 1:this.vb(new g.AM(8));this.GH();break;case 1085:case 3:this.vb(new g.AM(9));break;case 1083:case 0:this.vb(new g.AM(2));this.K.stop();this.sc(this.J.getVideoData().lengthSeconds);break;case 1084:this.vb(new g.AM(4));break;case 2:this.vb(new g.AM(4));this.sc(W7(a));
break;case -1:this.vb(new g.AM(64));break;case -1E3:this.vb(new g.AM(128,{errorCode:"mdx.remoteerror",errorMessage:"Cette vid\u00e9o ne peut pas \u00eatre visionn\u00e9e \u00e0 distance."}))}a=a8(this.yb).u;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.D=a,KJa(this,a));a=a8(this.yb);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.P.isActive()||this.nI()}else JJa(this)};
g.k.gG=function(){this.J.V("mdxpreviousnextchange")};
g.k.Bv=function(){J8(this)||JJa(this)};
g.k.bG=function(a){isNaN(a)||this.J.V("mdxnowautoplaying",a)};
g.k.CF=function(){this.J.V("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.yb.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===a8(this.yb).playerState?L8(this,a):b&&this.yb.seekTo(a)};
g.k.nI=function(){var a=this;if(J8(this)){var b=a8(this.yb);this.events.Mb(this.X);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.X=this.events.N(this.J,"onVolumeChange",function(c){IJa(a,c)})}};
g.k.GH=function(){this.u.stop();if(!this.yb.na()){var a=a8(this.yb);a.Hb()&&this.vb(new g.AM(8));this.sc(W7(a));this.u.start()}};
g.k.HH=function(){this.C.stop();this.u.stop();var a=this.yb.C.getReconnectTimeout();2==this.yb.Ka&&!isNaN(a)&&this.C.start()};
g.k.vb=function(a){this.C.stop();var b=this.I;if(!g.FM(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&g.F0(this.J.app,c);this.I=a;MJa(this.B,b,a)}};g.u(M8,g.V);M8.prototype.Bc=function(){this.u.show()};
M8.prototype.nb=function(){this.u.hide()};
M8.prototype.B=function(){g.RL("https://support.google.com/youtube/answer/7640706")};
M8.prototype.C=function(){d6("mdx-manual-pairing-popup-ok");this.nb()};g.u(N8,g.V);N8.prototype.Bc=function(){this.u.show()};
N8.prototype.nb=function(){this.u.hide()};
N8.prototype.B=function(){d6("mdx-privacy-popup-cancel");this.nb()};
N8.prototype.C=function(){d6("mdx-privacy-popup-confirm");this.nb()};g.u(O8,g.V);O8.prototype.B=function(a){LJa(this,a.state)};g.u(P8,g.wX);P8.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Dl=g.Db(a,this.u,this),g.xX(this,g.Oc(a,this.u)),a=this.J.getOption("remote","currentReceiver"),this.Mc(this.u(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.u=function(a){return a.key};
P8.prototype.Th=function(a){return"cast-selector-receiver"===a?"Caster sur\u2026":this.Dl[a].name};
P8.prototype.af=function(a){g.wX.prototype.af.call(this,a);this.J.setOption("remote","currentReceiver",this.Dl[a]);this.Xa.nb()};g.u(Q8,g.JS);g.k=Q8.prototype;
g.k.create=function(){var a=this.player.T(),b=g.nD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.Q(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.Q(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.Q(a.experiments,"enable_cast_short_lived_lounge_token")};DJa(b,a);this.subscriptions.push(g.No("yt-remote-before-disconnect",this.sO,this));this.subscriptions.push(g.No("yt-remote-connection-change",this.gQ,this));this.subscriptions.push(g.No("yt-remote-receiver-availability-change",
this.iG,this));this.subscriptions.push(g.No("yt-remote-auto-connect",this.eQ,this));this.subscriptions.push(g.No("yt-remote-receiver-resumed",this.dQ,this));this.subscriptions.push(g.No("mdx-privacy-popup-confirm",this.AR,this));this.subscriptions.push(g.No("mdx-privacy-popup-cancel",this.zR,this));this.subscriptions.push(g.No("mdx-manual-pairing-popup-ok",this.wL,this));this.iG()};
g.k.load=function(){this.player.cancelPlayback();g.JS.prototype.load.call(this);this.zi=new I8(this,this.player,this.yb);var a=(a=HJa())?a.currentTime:0;var b=E8()?new $7(z8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!==a&&this.sc(a);MJa(this,this.Pc,this.Pc);g.N0(this.player.app,6)};
g.k.unload=function(){this.player.V("mdxautoplaycanceled");this.Hk=this.Qh;g.gg(this.zi,this.yb);this.yb=this.zi=null;g.JS.prototype.unload.call(this);g.N0(this.player.app,5);R8(this)};
g.k.ca=function(){g.Oo(this.subscriptions);g.JS.prototype.ca.call(this)};
g.k.ij=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.zi.QE.apply(this.zi,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Je};
g.k.wK=function(){return this.loaded?this.zi.suggestion:null};
g.k.Ti=function(){return this.yb?a8(this.yb).Ti:!1};
g.k.hasNext=function(){return this.yb?a8(this.yb).hasNext:!1};
g.k.sc=function(a,b){this.lE=a||0;this.player.V("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.lE};
g.k.getProgressState=function(){var a=a8(this.yb),b=this.player.getVideoData();return{allowSeeking:g.Q(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.He():!a.isAdPlaying()&&this.player.He(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.D+U7(a):a.D,isAtLiveHead:1>=(a.C?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.P,seekableEnd:a.C?a.B+U7(a):a.B,seekableStart:0<a.F?a.F+
U7(a):a.F}};
g.k.nextVideo=function(){this.yb&&this.yb.nextVideo()};
g.k.Jv=function(){this.yb&&this.yb.Jv()};
g.k.sO=function(a){1===a&&(this.Rz=this.yb?a8(this.yb):null)};
g.k.gQ=function(){var a=E8()?new $7(z8(),void 0):null;if(a){var b=this.Hk;this.loaded&&this.unload();this.yb=a;this.Rz=null;b.key!==this.Qh.key&&(this.Hk=b,this.load())}else g.fg(this.yb),this.yb=null,this.loaded&&(this.unload(),(a=this.Rz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,W7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.iG=function(){var a=[this.Qh],b=a.concat,c=EJa();O7()&&g.lu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Dl=b.call(a,c);a=A8()||this.Qh;S8(this,a);this.player.xa("onMdxReceiversChange")};
g.k.eQ=function(){var a=A8();S8(this,a)};
g.k.dQ=function(){this.Hk=A8()};
g.k.AR=function(){this.zr=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.zR=function(){this.zr=!1;R8(this);S8(this,this.Qh);this.Hk=this.Qh;G8=!1;H8=null;this.player.playVideo()};
g.k.wL=function(){this.Ju=!0;R8(this);g.ku("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.Ae=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Dl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?Q7():S8(this,b)),this.loaded?this.Hk:this.Qh;case "quickCast":return 2===this.Dl.length&&"cast-selector-receiver"===this.Dl[1].key?(b&&Q7(),!0):!1}};
g.k.MA=function(){this.yb.MA()};
g.k.ii=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.qU.remote=Q8;})(_yt_player);
