(function(g){var window=this;var t3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.WF(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.u,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},u3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},gFa=function(a,b){var c=new g.VF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.u=a.u;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},hFa=function(){this.B=[];
this.u=[]},v3=function(a,b){switch(b.kind){case "asr":iFa(b,a.B);
break;default:iFa(b,a.u)}},iFa=function(a,b){g.db(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},w3=function(){g.C.call(this);
this.B=new hFa;this.D=[]},x3=function(a,b,c){w3.call(this,a);
this.audioTrack=c;this.u=null;this.D=b.qA},y3=function(){this.segments=[]},jFa=function(a,b){var c=g.xb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.nb(a.segments,c),g.nb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.ub(a.segments,c,0,b),g.ub(a.segments,c+1,0,b)))},z3=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.W=c;this.I=d;this.F=e;this.N=f;this.P=this.player.T();this.D=new y3;this.B=this.C=this.u=null;this.K=new g.F(this.zC,1E3,this);this.events=new g.cR(this);g.D(this,this.K);g.D(this,this.events);this.events.R(b,"SEEK_COMPLETE",this.cD);this.cD();this.zC()},kFa=function(a,b){var c=g.hw(b,a.policy,{}).Bd(),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.B=g.hs(c,d,3,100).then(function(e){a:{a.ma();if(a.C){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.CA(e);if(h){e=g.hw(a.C,a.policy,{});f=a.C;g.dw(f.B,e,h);f.requestId=e.get("req_id");kFa(a,a.C);break a}f||null==a.I||(h=a.C.u[0],a.F?a.I(e.response,1E3*(h.startTime+a.player.tc())):a.I(e.responseText,1E3*(h.startTime+a.player.tc())))}a.C=null;a.B=null}});
a.C=b;jFa(a.D,a.C.u[0].B)},A3=function(a,b){w3.call(this,b.T());
this.na=a;this.J=b;this.u=null;this.C=!1;this.F=g.pD(this.J.T())&&!this.na.isManifestless},lFa=function(a,b){var c=[],d;
for(d in a.na.u)if(a.na.u.hasOwnProperty(d)){var e=a.na.u[d];if(g.$T(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.VF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},mFa=function(a,b){return null!=b&&b in a.na.u?a.na.u[b]:null},nFa=function(a,b,c){var d=[],e;
for(e in a.na.u)if(a.na.u.hasOwnProperty(e)){var f=a.na.u[e];if(g.$T(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},B3=function(a,b,c,d,e){w3.call(this,e||null);
this.videoId=b;this.XB=d;this.F={};this.u=null;b=c||g.Dp(a).hl||"";b=b.split("_").join("-");this.C=g.Fp(a,{hl:b})},C3=function(a,b,c,d,e,f,h){var l={};
g.Sa(l,b);g.Sa(l,a.params);g.Sa(l,c);var m={};g.Sa(m,b.Bc);a.params.Bc&&g.Sa(m,a.params.Bc);g.Sa(m,c.Bc);l.Bc=m;g.V.call(this,{G:"div",L:"caption-window",U:{id:"caption-window-"+a.id,dir:1===l.u?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},S:[{G:"span",L:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Y=!1;this.B=a;this.fa=this.ca=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.I=null;this.maxWidth=.96*e;this.Ha=.96*f;this.u=l;
this.jb=c;this.D=this.ha("captions-text");this.Va=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.ea=d/360*16;this.type=0;this.va=this.ea*oFa(m);a=new g.Ls(this.element,!0);g.D(this,a);a.subscribe("dragstart",this.EK,this);a.subscribe("dragmove",this.DK,this);a.subscribe("dragend",this.CK,this);this.Pa=this.Aa=0;b="";this.u.windowOpacity&&(a=g.e1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":pFa[this.u.textAlign]};this.Va&&(a["border-radius"]=b?this.va/8+"px":"");if(this.C=2===this.B.params.u||3===this.B.params.u)b=this.element,c="vertical-rl",1===this.u.C&&(c="vertical-lr"),g.re&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.lg(b,"-o-writing-mode",c),g.lg(b,"-webkit-writing-mode",c),g.lg(b,"writing-mode",c),g.lg(b,"text-orientation","upright"),g.H(b,"ytp-vertical-caption"),3===this.B.params.u&&(g.lg(b,"text-orientation",
""),g.lg(b,"transform","rotate(180deg)"));g.lg(this.element,a);switch(this.u.bh){case 0:case 1:case 2:g.H(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.H(this.element,"ytp-caption-window-bottom")}},oFa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},qFa=function(a,b){var c={},d=b.background?b.background:a.u.Bc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Bc.backgroundOpacity;d=g.e1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Va&&(c["box-decoration-break"]="clone",c["border-radius"]=a.va/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ea*oFa(b)+"px";d=1;e=b.color||a.u.Bc.color;if(b.color||null!=b.textOpacity)e=g.e1(e),d=null==b.textOpacity?a.u.Bc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Fv&&(h=e=b.Fv);var l=a.ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.dr()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Bc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.wh&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.hJ&&(c.visibility="hidden");1===b.TB&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.uD||g.bC,3===a.B.params.u?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Qh||2===b.Qh||3===b.Qh||4===b.Qh||5===b.Qh)if(g.uD)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Qh){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},rFa=function(a){a.I=g.Ae("SPAN");
g.lg(a.I,{display:"block"});g.H(a.I,"caption-visual-line");a.D.appendChild(a.I)},sFa=function(a,b){var c=g.Ae("SPAN");
g.lg(c,{display:"inline-block","white-space":"pre-wrap"});g.lg(c,qFa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.lg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.lg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},tFa=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Sa(d,a.u.Bc);g.Sa(d,c||b.u);g.Sa(d,a.jb.Bc);(c=!a.I)&&rFa(a);for(var e=a.ca&&a.fa&&g.Ub(d,a.fa)?a.ca:sFa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(rFa(a),e=sFa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Be(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.uD||!g.pg(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.pg(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),
g.ve?g.lg(e,m,"1em"):g.lg(e,m,"0.5em")))}a.fa=d;a.ca=e;a.F.push(b)},D3=function(a,b,c,d,e,f,h){C3.call(this,a,b,c,d,e,f,h);
this.type=1},E3=function(a,b,c,d,e,f,h){C3.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.W=this.P=this.ka=0;this.X=NaN;this.Qa=0;this.Xa=null;this.la=new g.F(this.DO,433,this);g.H(this.element,"ytp-caption-window-rollup");g.D(this,this.la);g.lg(this.element,"overflow","hidden")},uFa=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.C&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},vFa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.B,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.P=d;b=Math;c=b.max;isNaN(a.X)&&((d=a.u.hk)?(e=g.Ae("SPAN"),g.Ie(e,"\u2013".repeat(d)),g.lg(e,qFa(a,a.u.Bc)),a.D.appendChild(e),a.X=e.offsetWidth,a.D.removeChild(e)):a.X=0);d=a.D;a.W=c.call(b,a.X,a.Qa,(a.C?d.offsetHeight:d.offsetWidth)+1)},wFa=function(a,b){vFa(a);
var c=a.K.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.P-c;if(c!==a.ka){var d=0<c&&0===a.ka;b||isNaN(c)||d||(g.H(a.element,"ytp-rollup-mode"),a.la.Lb());g.lg(a.D,"transform",uFa(a,c));a.ka=c}vFa(a)},F3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.ZD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.u=h},G3=function(a,b,c,d,e){g.ZD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.u=[]},xFa=function(a){var b="_"+H3++;
return new G3(0,0x8000000000000,0,b,a)},zFa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.ld){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=yFa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new F3(a,b,e,c,l,d,m)}switch(m.ld){case 9:case 10:m.Qh=1;break;case 11:m.Qh=2;break;case 12:m.Qh=3;break;case 13:m.Qh=4;break;case 14:m.Qh=5}return new F3(a,b,e,c,l.textContent||"",d,m)},yFa=function(a,b,c,d,e){var f=g.dr(),h=
f?g.Ae("DIV"):g.Ae("RUBY"),l=g.Ae("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ae("DIV"):g.Ae("RP");a.textContent=b;h.appendChild(a);b=f?g.Ae("DIV"):g.Ae("RT");b.textContent=c;h.appendChild(b);c=e.ld;if(10===c||11===c||12===c||13===c||14===c)if(g.lg(b,"text-emphasis-style","filled circle"),g.lg(b,"text-emphasis-color","currentcolor"),g.lg(b,"webkit-text-emphasis","filled circle"),11===e.ld||13===e.ld)g.lg(b,"webkit-text-emphasis-position","under left"),g.lg(b,"text-emphasis-position","under left");c=!0;if(4===e.ld||7===e.ld||12===e.ld||
14===e.ld)g.lg(h,"ruby-position","over"),g.lg(h,"-webkit-ruby-position","before");else if(5===e.ld||6===e.ld||11===e.ld||13===e.ld)g.lg(h,"ruby-position","under"),g.lg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ae("DIV"):g.Ae("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.lg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.lg(f,"display","none"),f=f.nextElementSibling,g.lg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.lg(h.lastElementChild,"display","none"),d?(g.lg(h,"padding-top","0.6em"),g.lg(f,"top","0")):(g.lg(h,"padding-bottom","0.6em"),g.lg(f,"bottom","0")));return h},I3=function(){g.C.apply(this,arguments)},J3=function(a){I3.call(this);
this.I=a;this.D={};this.P={};this.W={};this.F="_"+H3++;this.N={};this.B=this.u=null;this.K=!0},K3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},L3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},M3=function(a,b){var c=K3(a,b);
return void 0!==c?c:null},O3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return N3.test(c),c},AFa=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.W[d]:a.I);d=M3(b,"mh");null!=d&&(c.tn=d);d=M3(b,"ju");null!=d&&(c.textAlign=d);d=M3(b,"pd");null!=d&&(c.u=d);d=M3(b,"sd");null!=d&&(c.C=d);d=O3(b,"wfc");null!=d&&(c.windowColor=d);d=K3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},BFa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.P[d]);d=M3(b,"ap");null!=d&&(c.bh=d);d=K3(b,"cc");null!=d&&(c.hk=d);d=K3(b,"ah");null!=d&&(c.pg=d);d=K3(b,"rc");null!=d&&(c.B=d);d=K3(b,"av");null!=d&&(c.Th=d);return c},CFa=function(a,b,c,d){var e={};
g.Sa(e,BFa(a,b));g.Sa(e,AFa(a,b));d?g.Ub(e,a.I)?(d=a.F,e=a.I):d="_"+H3++:d=b.getAttribute("id")||"_"+H3++;a=K3(b,"t")+c;b=K3(b,"d")||0x8000000000000;if(2===e.u||3===e.u)c=e.B,e.B=e.hk,e.hk=c;return new G3(a,b,0,d,e)},P3=function(a){I3.call(this);
this.I=a;this.u=new Map;this.D=new Map;this.F=new Map;this.B=new Map},Q3=function(a){a=g.Wd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},DFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.B=a);b=b.ccColCount;void 0!==b&&(f.hk=b);if(2===f.u||3===f.u)b=f.B,f.B=f.hk,f.hk=b;return new G3(c,d,0,e,f)},S3=function(){this.C=this.time=this.mode=this.B=0;
this.D=new R3(this);this.F=new R3(this);this.u=[];this.clear()},FFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{sl:a,
ck:b,result:0};a=EFa[a];b=EFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.ck===d;if(d)return{sl:a,ck:b,result:1}}else if(b&128&&1<=a&&31>=a)return{sl:a,ck:b,result:2};return{sl:a,ck:b,result:3}},HFa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.u.clear(),a.F.u.clear()):(a.C=0,GFa(a.D,b,c,d))},IFa=function(a,b){a.u.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.u),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?HFa(a,d.sA,d.tA,b):1===d.type&&a.B&496&&GFa(a.F,d.sA,d.tA,b);a.u.length=0},T3=function(){this.type=0},U3=function(){this.state=this.ck=this.sl=0},JFa=function(){this.timestamp=this.u=0},V3=function(a){this.F=a;
this.C=[];this.u=this.B=this.row=0;this.style=new T3;for(a=this.D=0;15>=a;a++){this.C[a]=[];for(var b=0;32>=b;b++)this.C[a][b]=new JFa}},W3=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.C[m][p];
if(0!==r.u){0===c&&(c=m,d=p);n=String.fromCharCode(r.u);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.u||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.F(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.C[h][m],r=p.u,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.F(c,d,e,f,l),e=f,l="",d=c=0},OFa=function(a,b){switch(a){case 0:return KFa[(b&127)-32];
case 1:return LFa[b&15];case 2:return MFa[b&31];case 3:return NFa[b&31]}return 0},X3=function(a){return a.C[a.row][a.B]},Y3=function(a,b,c){2<=b&&1<a.B&&(--a.B,X3(a).u=0);
var d=X3(a);d.timestamp=a.F.time+0;d.u=OFa(b,c);32>a.B&&a.B++},PFa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.C[b+e][f],l=a.C[c+e][f];
h.u=l.u;h.timestamp=l.timestamp}},Z3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},$3=function(a){a.row=0<a.u?a.u:1;
a.B=1;Z3(a,0,15)},a4=function(a){this.C=a;
this.F=0;this.style=new T3;this.I=new V3(this.C);this.K=new V3(this.C);this.text=new V3(this.C);this.B=this.I;this.D=this.K;this.u=this.B},b4=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.u||(W3(d,c),$3(a.B),$3(a.D),d.row=15,d.u=b,e=!0)}a.style.set(3);a.u=d;a.u.style=a.style;a.C.mode=1<<d.D;e?d.B=1:d.u!==b&&(d.u>b?(W3(d,c),Z3(d,d.row-d.u,b)):d.row<b&&(b=d.u),d.u=b)},QFa=function(a){a.style.set(1);
a.u=a.D;a.u.u=0;a.u.style=a.style;a.C.mode=1<<a.u.D},RFa=function(a){a.style.set(4);
a.u=a.text;a.u.style=a.style;a.C.mode=1<<a.u.D},R3=function(a){this.B=a;
this.F=0;this.C=new a4(this.B);this.I=new a4(this.B);this.u=new U3;this.D=this.C},GFa=function(a,b,c,d){a.u.update();
b=FFa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.sl;c=b.ck;if(32<=e||!e)a.B.mode&a.B.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.u,b&96&&Y3(a,0,b),c&96&&Y3(a,0,c),0!==b&&0!==c&&3===a.style.type&&W3(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.sl=e,b.ck=c,b.state=2,b=e&8?a.I:a.C,a.D=b,a.B.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.B.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.B.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.u;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.u&&(d=c.u,d===c.row))break;var f=1+c.row-c.u,h=1+d-c.u;PFa(c,h,f,c.u);b=f;e=c.u;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Z3(c,b,e)}}c.row=d;c.B=a+1}else switch(e&7){case 1:switch(c&112){case 32:Y3(b.u,0,32);break a;case 48:57===c?(d=b.u,X3(d).u=0,32>d.B&&d.B++):Y3(b.u,1,c&15)}break;case 2:c&32&&Y3(b.u,2,c&31);break;case 3:c&32&&Y3(b.u,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:QFa(b);
break;case 33:d=b.u;1<d.B&&(--d.B,X3(d).u=0);break;case 36:d=b.u;b=X3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]===b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:b4(b,2,d);break;case 38:b4(b,3,d);break;case 39:b4(b,4,d);break;case 40:Y3(b.u,0,32);break;case 41:b.style.set(2);b.u=b.B;b.u.u=0;b.u.style=b.style;b.C.mode=1<<b.u.D;break;case 42:d=b.text;d.u=15;d.style.set(4);$3(d);RFa(b);break;case 43:RFa(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:W3(a,d)}Z3(a,
0,15);break;case 45:b:{a=b.u;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.B=1;break b}case 3:}2>a.u&&(a.u=2,a.row<a.u&&(a.row=a.u));b=a.row-a.u+1;W3(a,d);PFa(a,b,b+1,a.u-1);Z3(a,a.row,1)}break;case 46:Z3(b.D,0,15);break;case 47:W3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,QFa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.u,32<(d.B+=c&3)&&(d.B=32)}}},SFa=function(){},c4=function(a,b,c){this.N=a;
this.K=c;this.version=this.I=this.D=this.u=0;this.B=new DataView(this.N);this.C=[]},d4=function(a){var b=a.u;
a.u+=1;return a.B.getUint8(b)},e4=function(a){var b=a.u;
a.u+=4;return a.B.getUint32(b)},f4=function(a,b){I3.call(this);
this.B=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.u=new S3;this.u.B=1<<this.track},g4=function(a){if("string"===typeof a)return!1;
a=new c4(a,8,0);return TFa(a)},TFa=function(a){if(!(a.u<a.B.byteLength)||1380139777!==e4(a))return!1;
a.version=d4(a);if(1<a.version)return!1;d4(a);d4(a);d4(a);return!0},h4=function(){I3.call(this)},UFa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.wh=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new F3(b,c,d,e.id,p.nodeValue,f||0<n,g.Sb(l)?void 0:l),m.push(p),e.u.push(p);else{var r={};g.Sa(r,l);UFa(a,b,c,d,e,!0,p,r,m)}}},i4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},VFa=function(a,b,c,d){d=Object.assign({tn:0},d);
return new G3(a,b,c,"_"+H3++,d)},j4=function(a){g.C.call(this);
this.B=a;this.u=null},XFa=function(a){var b={};
if(a=u3(a))b.lang=a,WFa.test(a)&&(b.u=1);return b},m4=function(a){g.sS.call(this,a);
var b=this;this.J=a;this.C=this.J.T();this.videoData=this.J.getVideoData();this.Va=g.aF(this.J);this.D={Bc:{}};this.F={Bc:{}};this.W=[];this.P={};this.la={};this.ca=!1;this.Ha=g.Ota(this.videoData,this.J);this.Xa=!!this.videoData.captionTracks.length;this.jb=!!this.videoData.Go;this.Aa="3"===this.C.controlsType;this.B=this.K=this.N=this.ka=this.Ca=null;this.va=new j4(this.C);this.u=null;this.fa=new g.cR(this);var c=null,d=g.Nn("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.xn(d));this.storage=
c;c=a.app.D;d=!(!c||!c.Cq());this.Qa=!(!c||!c.tm());this.I=this.Aa&&d&&!this.Ha;this.Y=!this.I&&this.Aa&&this.Qa&&this.Ha;g.D(this,this.va);this.I?this.ea=this.X=null:(this.X=new g.Um(this.kG,void 0,this),g.D(this,this.X),this.ea=new g.F(this.WP,2E3,this),g.D(this,this.ea));g.D(this,this.fa);this.I||this.fa.R(a,"resize",this.gz);this.fa.R(a,"onPlaybackAudioChange",this.CM);this.fa.R(a,g.bE("captions"),function(e){b.W.push(e);b.X.Lb()});
this.fa.R(a,g.cE("captions"),function(e){g.ob(b.W,e);b.B instanceof A3&&b.B.F&&g.fN(b.player.app,[e],void 0);b.X.Lb()});
k4(this,l4(this,"display-settings")||{})},YFa=function(a){if(1===a.C.gj||1===a.videoData.gj||"alwayson"===g.oH(a.videoData,"yt:cc"))return!0;
if(2===a.C.gj){var b=l4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().C;return"ON"===c||"on"===g.oH(a.videoData,"yt:cc")},n4=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.B||"FORCED_ON"===c.C},ZFa=function(a){var b=!1,c=g.xs(g.vs.getInstance(),65);
g.tD(a.C)&&null!=c&&(b=!c);return b},$Fa=function(a){return a.Aa?a.I||a.Y:ZFa(a)||n4(a)?!0:YFa(a)},p4=function(a,b){if(a.B){if(a.K&&a.K.F)return a.K.F;
var c=b;c||(c=a.jb?!1:a.Xa?!1:!0);c=a.B.Ml(c);for(var d=[a.videoData.captionsLanguagePreference,a.C.captionsLanguagePreference,g.oH(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(u3(c[f])===d[e])return c[f];return a.K&&a.K.D?a.K.D:(d=c.find(function(h){return h.isDefault}))?d:c[0]||o4(a)}return null},o4=function(a){return a.K&&a.K.B},q4=function(a){var b=o4(a);
return!!b&&a.u===b},aGa=function(a,b){for(var c=a.J.app.D.Na().textTracks,d=a.u.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},s4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ca=c,a.ca&&r4(a,"module-enabled",!!b));a.u=b;n4(a)&&(a.u=o4(a));a.load()},bGa=function(a,b){var c=a.Va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.u?a.u.languageCode:null;!b.params.u&&d&&WFa.test(d)&&(b.params.u=1);d=a.Va.getPlayerSize();switch(null!=b.params.tn?b.params.tn:1<b.u.length?1:0){case 1:return new D3(b,a.D,a.F,c,d.width,d.height,a.C.experiments);case 2:return new E3(b,a.D,a.F,c,d.width,d.height,a.C.experiments);default:return new C3(b,a.D,a.F,c,d.width,d.height,a.C.experiments)}},k4=function(a,b,c){c=void 0===c?!1:c;
var d=t4.Bc;a.D={};g.Sa(a.D,t4);a.D.Bc={};g.Sa(a.D.Bc,d);a.F={Bc:{}};var e=b.backgroundOverride?a.F:a.D,f=b.background||d.background;N3.test(f);e.Bc.background=f;e=b.colorOverride?a.F:a.D;f=b.color||d.color;N3.test(f);e.Bc.color=f;e=b.windowColorOverride?a.F:a.D;f=b.windowColor||t4.windowColor;N3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.D;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Bc.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.wh?3:d.bold?1:d.wh?2:0);f=f.Bc;switch(e){case 1:f.bold=!0;delete f.wh;break;case 2:delete f.bold;f.wh=!0;break;case 3:f.bold=!0;f.wh=!0;break;default:delete f.bold,delete f.wh}e=b.textOpacityOverride?a.F:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bc.textOpacity=f;e=b.windowOpacityOverride?a.F:a.D;f=b.windowOpacity;null==f&&(f=t4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.D;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Bc.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bc.fontFamily=f;a.loaded&&a.gz();c&&r4(a,"display-settings",b)},dGa=function(a,b){if(b&&!a.N){var c=xFa({u:0,
lang:"fr"});a.N=[c,new F3(c.start,c.end-c.start,0,c.id,"Aper\u00e7u des sous-titres")];g.eN(a.player,a.N)}else!b&&a.N&&(cGa(a,a.N),a.N=null)},cGa=function(a,b){g.fN(a.player.app,b,void 0);
g.Cb(b,function(c){g.ob(this.W,c)},a);
a.X.Lb()},l4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},r4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.IS.prototype.Jo=g.ca(11,function(){for(var a=g.ke(document,"track",void 0,this.u),b=0;b<a.length;b++)g.Ee(a[b])});
g.JS.prototype.Jo=g.ca(10,function(){this.u.Jo()});
g.IS.prototype.Cq=g.ca(9,function(){return!!this.u.textTracks});
g.JS.prototype.Cq=g.ca(8,function(){return this.u.Cq()});
g.IS.prototype.Ao=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.u.appendChild(a[b])});
g.JS.prototype.Ao=g.ca(6,function(a){this.u.Ao(a)});
g.AS.prototype.tm=g.ca(5,function(){});
g.IS.prototype.tm=g.ca(4,function(){return!(!this.u.textTracks||!this.u.textTracks.addEventListener)});
g.JS.prototype.tm=g.ca(3,function(){return this.u.tm()});
g.Nt.prototype.rs=g.ca(1,function(a){return(a=this.ki(a))?a.u:0});
g.Ew.prototype.rs=g.ca(0,function(){return 0});
var WFa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;hFa.prototype.Ml=function(a){return a?this.u.concat(this.B):this.u};
g.u(w3,g.C);g.k=w3.prototype;g.k.Ml=function(a){return this.B.Ml(a)};
g.k.Ws=function(){};
g.k.Xs=function(){};
g.k.Wj=function(){};
g.k.en=function(){return""};
g.k.UE=function(){return!1};
g.k.ba=function(){this.Wj();g.C.prototype.ba.call(this)};
g.u(x3,w3);x3.prototype.Ws=function(a,b,c){var d=this;this.ma();b=this.en(a,b);this.Wj();this.u=g.Vp(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
x3.prototype.Xs=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())v3(this.B,c.value);a()};
x3.prototype.en=function(a,b){var c=a.Bd(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.dr()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=u3(a));return g.Fp(c,d)};
x3.prototype.Wj=function(){this.u&&this.u.abort()};
y3.prototype.contains=function(a){a=g.xb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
y3.prototype.length=function(){return this.segments.length/2};
g.u(z3,g.C);g.k=z3.prototype;g.k.ba=function(){g.C.prototype.ba.call(this);this.B&&this.B.cancel()};
g.k.cD=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.tc();var b=this.u;this.u=g.bb(this.W.rj(a).u);b!==this.u&&this.N&&this.N()};
g.k.reset=function(){this.D=new y3;this.B&&(this.B.cancel(),this.B=null)};
g.k.zC=function(){this.ma();var a;if(a=null!=this.u)a=this.u,a=a.u.Jj(a);!a||this.B||this.u&&30<this.u.startTime-this.player.getCurrentTime()||(a=this.u.qk(),a.u[0].duration?(this.D.contains(a.u[0].B)||kFa(this,a),this.u=g.bb(a.u)):!g.Q(this.P.experiments,"force_caption_seek_for_live_killswitch")&&this.u&&this.u.I&&this.u.I+this.player.tc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.K.start()};
g.u(A3,w3);g.k=A3.prototype;g.k.Ws=function(a,b,c){var d=this;this.Wj();b=mFa(this,a.getId());b||(b=a.languageCode,b=this.na.isManifestless?nFa(this,b,"386"):nFa(this,b));if(b){var e=1E3*(b.index.rs(b.index.nh())-b.index.Pe(b.index.nh()));this.u=new z3(new g.Yv,this.J,b,function(f,h){c(f,a,h,e)},this.F||g.qv(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.UE=function(){var a=this.C;this.C=!1;return a};
g.k.Xs=function(a){var b=this.F?[new g.VF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.VF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.na.isManifestless?lFa(this,"386"):lFa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())v3(this.B,c.value);a()};
g.k.Wj=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.en=function(){return""};
g.u(B3,w3);B3.prototype.Ws=function(a,b,c){var d=this;this.ma();b=this.en(a,b);this.Wj();this.u=g.Vp(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
B3.prototype.Xs=function(a){var b=this,c=this.C,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.XB&&(d.asrs=1);c=g.Fp(c,d);this.Wj();this.u=g.Vp(c,{format:"RAW",onSuccess:function(e){b.u=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");v3(b.B,new g.VF({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.F[m.languageCode]=m.languageName,b.D.push(m)}a()},
withCredentials:!0})};
B3.prototype.en=function(a,b){var c=this.C,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=u3(a));return c=g.Fp(c,d)};
B3.prototype.Wj=function(){this.u&&this.u.abort()};
var N3=/^#(?:[0-9a-f]{3}){1,2}$/i;var pFa=["left","right","center","justify"];g.u(C3,g.V);g.k=C3.prototype;g.k.EK=function(a,b){var c=g.zg(this.element,this.element.parentElement);this.Aa=a-c.x;this.Pa=b-c.y;g.H(this.element,"ytp-dragging")};
g.k.DK=function(a,b){var c=g.Bg(this.element),d=a-this.Aa-.02*this.playerWidth,e=b-this.Pa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Wd(f,0,2));var h=(e+c.height/2)/this.Ha*3;h=Math.floor(g.Wd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Wd(d,0,1);c=(e+h/2*c.height)/this.Ha;c=100*g.Wd(c,0,1);this.B.params.bh=l;this.B.params.Th=c;this.B.params.pg=d;this.u.bh=l;this.u.Th=c;this.u.pg=d;this.yF()};
g.k.CK=function(){g.en(this.element,"ytp-dragging")};
g.k.yF=function(){this.Xn(this.F)};
g.k.Xn=function(a){var b=Math.min(this.qB(),this.maxWidth),c=this.pB(),d="";3===this.B.params.u&&(d="rotate(180deg)");g.lg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.qv(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.pg+2;d=this.u.bh;switch(d){case 0:case 3:case 6:b=this.u.Bc.fontSizeIncrement;!g.Q(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.u&&3!==this.u.u&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Th+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.lg(this.element,a)};
g.k.qv=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Y||this.F.length>b)b=0,this.Y=!1,this.F=[],this.I=this.fa=this.ca=null,g.Ce(this.D);for(;b<a.length;b++)tFa(this,a[b])};
g.k.qB=function(){return 0};
g.k.pB=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.u(D3,C3);D3.prototype.qv=function(a){var b=this.B.u;C3.prototype.qv.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.u===e)var d=f;else{d={};g.Sa(d,c.u);g.Sa(d,eGa);var e=c.u;var f=d}tFa(this,c,d)}};
var eGa={hJ:!0};g.u(E3,C3);g.k=E3.prototype;g.k.yF=function(){g.Xm(this.la)};
g.k.DO=function(){g.en(this.element,"ytp-rollup-mode");this.Xn(this.Xa,!0)};
g.k.pB=function(){return this.C?this.W:this.P};
g.k.qB=function(){return this.C?this.P:this.W};
g.k.Xn=function(a,b){this.Xa=a;if(this.B.params.B){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Qa=this.W;this.P=this.W=0;C3.prototype.Xn.call(this,a);wFa(this,b)}C3.prototype.Xn.call(this,a)};g.u(F3,g.ZD);F3.prototype.toString=function(){return g.ZD.prototype.toString.call(this)};g.u(G3,g.ZD);G3.prototype.toString=function(){return g.ZD.prototype.toString.call(this)};
var H3=0;g.u(I3,g.C);I3.prototype.C=function(){return[]};
I3.prototype.reset=function(){};g.u(J3,I3);J3.prototype.reset=function(){this.N={};this.B=this.u=null;this.K=!0};
J3.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.D,l={},m=c.getAttribute("p");m&&g.Sa(l,this.D[m]);m=L3(c,"b");null!=m&&
(l.bold=m);m=L3(c,"i");null!=m&&(l.wh=m);m=L3(c,"u");null!=m&&(l.underline=m);m=M3(c,"et");null!=m&&(l.charEdgeStyle=m);m=M3(c,"of");null!=m&&(l.offset=m);m=O3(c,"bc");null!=m&&(l.background=m);m=O3(c,"ec");null!=m&&(l.Fv=m);m=O3(c,"fc");null!=m&&(l.color=m);m=M3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=K3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=K3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=K3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=M3(c,"rb");null!=m&&10!==m&&0!==m&&(l.ld=
10<m?m-1:m);c=M3(c,"hg");null!=c&&(l.TB=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.W[d]=AFa(this,c);break;case "wp":d=c.getAttribute("id"),this.P[d]=BFa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.u=CFa(this,d,e,!1);(d=this.N[this.u.id])&&d.end>this.u.start&&(d.end=this.u.start);this.N[this.u.id]=this.u;c.push(this.u);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.F;m=!!L3(d,
"a");n=(K3(d,"t")||0)+n;var p=K3(d,"d")||5E3;m||(!this.K&&this.B&&this.B.windowId===l&&this.B.end>n&&(this.B.end=n),this.B&&"\n"===this.B.text&&(this.B.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.D[t]:null;var w=Array.from(d.childNodes);w.length&&(this.K=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],B=void 0;0<x&&(m=!0);var E=void 0;1===y.nodeType&&(E=y);if(E&&"s"===E.tagName){if((y=(y=E.getAttribute("p"))?this.D[y]:null)&&y.ld&&(1===y.ld?(y=w.slice(x,x+4),4===y.length&&
(B=zFa(n,p,l,m,r,y,this.D),x+=3)):B=zFa(n,p,l,m,r,[E],this.D)),!B){var G=E;B=n;E=p;y=l;var J=m,I=r,Ca=G.textContent?G.textContent:"",ta=G.getAttribute("p");ta=ta?this.D[ta]:null;G=K3(G,"t")||0;B=new F3(B+G,E-G,I,y,Ca,J,ta)}}else B=new F3(n,p,r,l,y.textContent||"",m,t);h.push(B);this.B=B}if(0<h.length)for(h[0].windowId===this.F&&(this.u=CFa(this,d,e,!0),c.push(this.u)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.u.id,this.u.u.push(h),c.push(h)}e=c}else e=[];return e};var fGa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(P3,I3);P3.prototype.reset=function(){this.B.clear()};
P3.prototype.C=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.u.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.wh=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.Fv=Q3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=Q3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=Q3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.ld=10<l?l-1:l,h.Qh=fGa.get(h.ld));f.hgHorizGroup&&(h.TB=f.hgHorizGroup);this.u.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.F.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.tn=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.u=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.C=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=Q3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.F.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.D.get(l)),void 0!==f.ahHorPos&&
(h.pg=f.ahHorPos),void 0!==f.apPoint&&(h.bh=f.apPoint),void 0!==f.avVerPos&&(h.Th=f.avVerPos),void 0!==f.ccCols&&(h.hk=f.ccCols),void 0!==f.rcRows&&(h.B=f.rcRows),this.D.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=DFa(this,m,e,f,h),d.push(e),this.B.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+H3++,l=DFa(this,m,e,f,h),d.push(l),this.B.set(h,l));0===f&&(f=5E3);l=this.B.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.u.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,B=null;w.pPenId&&(B=this.u.get(w.pPenId));if(2===(null!=l.params.tn?l.params.tn:1<l.u.length?1:0)&&n&&"\n"===x)continue;if(w=B&&1===B.ld)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var E=r[w+1].pPenId;(E=this.u.get(E))&&E.ld&&2===E.ld?(E=r[w+2].pPenId,E=this.u.get(E),!E||!E.ld||3>E.ld?w=!1:(E=r[w+3].pPenId,w=(E=this.u.get(E))&&
E.ld&&2===E.ld?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;E=r[m+2].utf8;var G=this.u.get(r[m+2].pPenId);x=yFa(x,y,E,w,G);n=new F3(e,f,p,h,x,n,B);m+=3}else n=new F3(e+y,f-y,p,l.id,x,n,B||t);n&&(d.push(n),l.u.push(n))}n=!0}}}else d=[];return d};S3.prototype.clear=function(){this.C=this.time=this.mode=0;this.u=[];this.reset()};
S3.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var EFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];T3.prototype.set=function(a){this.type=a};
T3.prototype.get=function(){return this.type};
U3.prototype.clear=function(){this.state=0};
U3.prototype.update=function(){this.state=2===this.state?1:0};
U3.prototype.isValid=function(){return 0!==this.state};
U3.prototype.matches=function(a,b){return this.isValid()&&a===this.sl&&b===this.ck};
JFa.prototype.reset=function(){this.timestamp=this.u=0};
V3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
V3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0===d.u?a+"_":a+String.fromCharCode(d.u)}a+="\n"}return a};
V3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.D=a;this.u=0;this.B=this.row=1};
var KFa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],LFa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],MFa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],NFa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];a4.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.B=this.I;this.D=this.K;this.u=this.B;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
R3.prototype.reset=function(a){this.F=a;this.u.clear();this.D=this.C;this.C.reset(a,0);this.I.reset(a,1)};SFa.prototype.F=function(){};g.u(c4,SFa);c4.prototype.F=function(a,b,c,d,e){if(c<d){var f="_"+H3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new G3(c,d-c,5,f,{textAlign:0,bh:0,pg:2.5*b,Th:5.33*a});e=new F3(c,d-c,5,f,e);this.C.push(a);this.C.push(e)}};
g.u(f4,I3);f4.prototype.C=function(a){a=new c4(a,a.byteLength,this.B);if(TFa(a)){for(;a.u<a.B.byteLength;)for(0===a.version?a.D=e4(a)*(1E3/45):1===a.version&&(a.D=4294967296*e4(a)+e4(a)),a.I=d4(a);0<a.I;a.I--){var b=d4(a),c=d4(a),d=d4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.u,b.u.push({time:a.D,type:this.track,sA:c,tA:d,order:b.u.length}))}IFa(this.u,a);return a.C}return[]};
f4.prototype.reset=function(){this.u.clear()};g.u(h4,I3);
h4.prototype.C=function(a,b){for(var c=[],d=a.split(gGa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!hGa.test(f)){var l=u4.exec(f);if(l&&4<=l.length){var m=i4(l[1]),n=i4(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var B=y[1];switch(y[0]){case "line":y=B.split(",");y[0].endsWith("%")&&(r=y[0],l.Th=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
B.split(",");w=y[0];l.pg=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(B){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Th=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.pg=0;break;case 1:l.pg=100;break;default:l.pg=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.bh=0>r||8<r?7:r;f=f.substring(u4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=VFa(m,n,5,x),n=new F3(m,n,5,h.id,l,!1,g.Sb(f)?void 0:f),c.push(h),c.push(n),h.u.push(n);else for(t=l.split(iGa),1===t.length?(l=5,x=VFa(m,n,l,x)):(r=l=6,x=Object.assign({hk:32},x),x=new G3(m,n,r,"_"+H3++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.f1("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(B=y.createElement("span"),B.appendChild(y.createTextNode(p))):B=y.firstChild,UFa(this,r,n-(r-m),l,x,0<w,B,f,c)):r=i4(p)+h}u4.lastIndex=0}}return c};
var hGa=/^NOTE/,gGa=/(?:\r\n|\r|\n){2,}/,u4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),iGa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(j4,g.C);j4.prototype.clear=function(){this.u&&this.u.dispose();this.u=null};
j4.prototype.reset=function(){this.u&&this.u.reset()};
j4.prototype.ba=function(){g.C.prototype.ba.call(this);this.clear()};var t4={windowColor:"#080808",windowOpacity:0,textAlign:2,bh:7,pg:50,Th:100,Bc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(m4,g.sS);g.k=m4.prototype;g.k.ba=function(){if(this.I||this.Y){var a=this.J.app.D;a&&!a.ma()&&a.Jo()}else dGa(this,!1);g.sS.prototype.ba.call(this)};
g.k.load=function(){var a=this;g.sS.prototype.load.call(this);var b=!g.Q(this.C.experiments,"web_player_captions_track_list_changed_killswitch");this.K=this.player.getAudioTrack();if(this.B)this.u&&(this.va.clear(),this.I?aGa(this,!0):3!==this.player.getPresentingPlayerType()&&this.B.Ws(this.u,"json3",function(d,e,f,h){if(d){a.B.UE()&&(a.W=[],g.GT(a.J,"captions"),a.X.Lb(),a.va.reset());var l=a.va;f=f||0;h=h||0;if(l.B.aa("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.tu(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),g4(d)||(d=g.Re(new Uint8Array(d))))}}else"string"===typeof d||g4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.tu(m,0,1835295092))&&m.size?g.Re(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!g4(n))throw Error("Invalid binary caption track data");l.u||(l.u=new f4(r,e));var t=l.u.C(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.u||(l.u=new h4),p=l.u.C(e,r),.01>Math.random()&&g.Ur(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.u||(l.u=new P3(XFa(e)));n=l.u.C(p,f);break b}catch(G){g.Tr(G);n=[];break b}r=g.f1(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.u||(l.u=new J3(XFa(e),l.B));n=l.u.C(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var B=Error("Invalid caption track data");B.params=p;throw B;}t=n}var E=t}catch(G){g.Tr(G),l.clear(),E=[]}else E=[];g.eN(a.player,E);!a.ca||a.Y||q4(a)||g.cD(a.C)||g.dD(a.C)||(a.ea.jg(),E=xFa({bh:0,pg:5,Th:5,B:2,textAlign:0,u:0,lang:"fr"}),a.ka=[E],l=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],a.Ca||(t=new g.mN(g.JN()),g.D(a,t),a.Ca=t.element),
t=E.end-E.start,(e=g.WF(a.u))&&a.ka.push(new F3(E.start,t,0,E.id,e)),a.ka.push(new F3(E.start,t,0,E.id,l[0]),new F3(E.start,t,0,E.id,a.Ca,!0),new F3(E.start,t,0,E.id,l[1],!0)),g.eN(a.player,a.ka),a.ea.Lb());!a.ca||a.Y||q4(a)||(r4(a,"module-enabled",!0),a.K&&(a.K.F=a.u),(E=g.Z(a.player.app))&&g.d_(E.F));a.ca=!1}}),!b||this.I||this.Y||q4(this)||this.player.xa("captionschanged",t3(this.u))),b||(this.u&&!q4(this)?this.player.xa("captionschanged",t3(this.u)):this.player.xa("onCaptionsTrackListChanged"));
else{var c;this.Ha?c=new A3(this.videoData.na,this.player):this.Xa?c=new x3(this.C,this.videoData,this.player.getAudioTrack()):c=new B3(this.videoData.Go,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.C.captionsLanguagePreference||g.oH(this.videoData,"yt:cc_default_lang")||this.C.hf,this.videoData.Bv,this.C);this.B=c;g.D(this,this.B);c.Xs(function(){var d;ZFa(a)||a.ca||YFa(a)?d=p4(a,a.ca):n4(a)&&(d=o4(a));if(a.I||a.Y){for(var e=a.B.Ml(!0),f=[],h=0;h<e.length;h++){var l=e[h],
m=g.Ae("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.WF(l));m.setAttribute("srclang",u3(l));m.setAttribute("id",l.toString());a.Y||m.setAttribute("src",a.B.en(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.app.D;d.Ao(f);f=d.Na();a.Qa&&a.fa.R(f.textTracks,"change",a.eP)}else!a.u&&d&&s4(a,d),a.player.xa("onCaptionsTrackListChanged"),a.player.xa("onApiChange")})}};
g.k.unload=function(){this.I&&this.u?aGa(this,!1):(this.ea&&this.ea.jg(),g.GT(this.player,"captions"),this.W=[],this.B&&this.B.Wj(),this.va.clear(),this.N&&g.eN(this.player,this.N),this.gz());g.sS.prototype.unload.call(this);var a=g.Z(this.player.app);a&&g.d_(a.F);this.player.xa("captionschanged",{})};
g.k.create=function(){$Fa(this)&&this.load()};
g.k.eP=function(){for(var a=this.J.app.D.Na().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=this.B.Ml(!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&s4(this,b,!0)};
g.k.KQ=function(){!this.u&&this.I||this.unload()};
g.k.PP=function(a){if(a instanceof G3){var b=this.P[a.id];b&&b.B!==a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=bGa(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.la[b]||(this.la[b]=[]),this.la[b].push(a)};
g.k.WP=function(){cGa(this,this.ka);this.ka=null};
g.k.kG=function(){var a=this;this.X.stop();g.Tb(this.la);this.W.sort(g.aE);var b=this.W;if(this.N){var c=g.Fe(b,function(d){return-1===this.N.indexOf(d)},this);
c.length&&(b=c)}g.Cb(b,this.PP,this);g.Eb(this.P,function(d,e){a.la[e]?(d.element.parentNode||(d instanceof E3||d instanceof D3||g.Ib(a.P,function(f,h){h!==e&&f.B.params.bh===d.B.params.bh&&f.B.params.pg===d.B.params.pg&&f.B.params.Th===d.B.params.Th&&(f.dispose(),delete a.P[h]);return h===e},a),g.iP(a.player,d.element,4)),d.Xn(a.la[e])):(d.dispose(),delete a.P[e])},this)};
g.k.aQ=function(){k4(this,{},!0);g.Q(this.C.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.xa("captionssettingschanged")};
g.k.CI=function(){var a=t4.Bc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.wh?3:a.bold?1:a.wh?2:0,textOpacity:a.textOpacity,windowColor:t4.windowColor,windowOpacity:t4.windowOpacity};var b=l4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.rG=function(a,b){var c={};g.Sa(c,l4(this,"display-settings"));g.Sa(c,a);k4(this,c,b);this.player.xa("captionssettingschanged")};
g.k.gz=function(){!this.I&&this.loaded&&(g.Eb(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.kG())};
g.k.pe=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Wd(b,-2,4);this.rG({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&s4(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.C.C&&r4(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.I)break;if(!g.Oa(b))break;if(g.Sb(b)){s4(this,null,!0);break}for(var d=this.B.Ml(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
gFa(f,b.translationLanguage):f)}!c||c===this.u&&this.loaded||s4(this,c,!0)}else return this.loaded&&this.u&&!q4(this)?t3(this.u):{};return"";case "tracklist":return this.B?g.Lc(this.B.Ml(!(!b||!b.includeAsr)),function(h){return t3(h)}):[];
case "translationLanguages":return this.B?this.B.D.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||dGa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.C.C&&a.push("stickyLoading");return a};
g.k.DJ=function(){var a=this.u;return a?{cc:a.vssId}:{}};
g.k.BQ=function(){this.loaded&&this.u&&!q4(this)?(r4(this,"module-enabled",!1),this.unload(),n4(this,!0)&&s4(this,o4(this),!1)):s4(this,q4(this)||!this.u?p4(this,!0):this.u,!0)};
g.k.CM=function(){var a=q4(this);n4(this,a)?s4(this,this.player.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),$Fa(this)&&(a?s4(this,p4(this),!1):this.load()))};g.eU.captions=m4;})(_yt_player);
