(function(g){var window=this;var OGa=function(a,b){a.xa("onAutonavCoundownStarted",b)},Y4=function(a,b,c){var d=b.Ka();
g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.ce(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.rG&&(b.lengthText?(f=b.lengthText||null,h=b.Ss||null):b.lengthSeconds&&(f=g.JO(b.lengthSeconds),h=g.JO(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.ST(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.rG?b.isLivePlayback:null,n=b instanceof g.rG?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.Bo||g.IJ("Regarder $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.vk(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.Eo};b instanceof g.TT&&(d.playlist_length=b.getLength());a.update(d)},Z4=function(a){var b=a.T(),c=b.B;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:c?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{G:"div",ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{G:"div",U:{"aria-label":"{{timestamp}}"},ia:["ytp-autonav-timestamp"],Z:"{{duration}}"},{G:"div",ia:["ytp-autonav-live-stamp"],Z:"En direct"},
{G:"div",ia:["ytp-autonav-upcoming-stamp"],Z:"\u00c0 venir"},{G:"div",L:"ytp-autonav-list-overlay",S:[{G:"div",L:"ytp-autonav-mix-text",Z:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Z:"{{title}}"},{G:"div",ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Z:"{{author}}"},{G:"div",ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Z:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.u=c;this.wa("click",this.onClick);this.wa("keypress",this.B)},a5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.F=b;this.C=0;var d=a.T(),e=d.B;this.J=a;this.suggestion=null;this.u=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{G:"div",L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",Z:"{{autoplayAlternativeHeader}}"},
{G:"a",L:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:e?d.F:""},S:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{G:"div",U:{"aria-label":"{{timestamp}}"},ia:["ytp-autonav-timestamp"],Z:"{{duration}}"},{G:"div",ia:["ytp-autonav-live-stamp"],Z:"En direct"},{G:"div",ia:["ytp-autonav-upcoming-stamp"],Z:"\u00c0 venir"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",S:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",
Z:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",Z:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",Z:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",Z:"{{author_and_views}}"}]}]}]});g.D(this,this.u);this.u.ga(this.element);e||this.R(this.u.ha("ytp-autonav-endscreen-link-container"),"click",this.aD);g.KT(this.J,this.element,this,115127);g.KT(this.J,this.u.ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});
g.D(this,this.overlay);this.overlay.ga(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.D(this,this.B);this.B.ga(this.element);this.cancelButton=new g.V({G:"button",ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],U:{"aria-label":"Annuler la lecture automatique"},Z:"Annuler"});g.D(this,this.cancelButton);this.cancelButton.ga(this.B.element);this.cancelButton.wa("click",this.oK,this);g.KT(this.J,this.cancelButton.element,this,
115129);this.playButton=new g.V({G:"a",ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],U:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},Z:"Regarder"});g.D(this,this.playButton);this.playButton.ga(this.B.element);this.playButton.wa("click",this.aD,this);g.KT(this.J,this.playButton.element,this,115130);this.D=new g.F(function(){$4(c)},500);
g.D(this,this.D);this.ZC();this.R(a,"autonavvisibility",this.ZC)},$4=function(a){var b=b5(a),c=Math.min(a.C?Date.now()-a.C:0,b);
c5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.mg()?a.select(!0):a.mg()&&a.D.start()},b5=function(a){var b=a.J.app.getVideoData().lr;
return 0<=b?b:g.P(a.J.T().experiments,"autoplay_time")||1E4},c5=function(a,b){b=void 0===b?-1:b;
var c=a.u.ha("ytp-autonav-endscreen-upnext-header");g.Ce(c);if(0<=b){var d=String(b),e="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Prochaine vid\u00e9o dans $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.Be("Prochaine vid\u00e9o dans $SECONDS".slice(0,f)));var h=g.Ae("span");g.bn(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Ie(h,d);c.appendChild(h);c.appendChild(g.Be("Prochaine vid\u00e9o dans $SECONDS".slice(f+e.length)));return}}g.Ie(c,"Suivante")},
d5=function(a,b){g.V.call(this,{G:"div",
ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},f5=function(a){g.V.call(this,{G:"div",
ia:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",S:[{G:"span",L:"ytp-upnext-header",Z:"\u00c0 suivre"},{G:"span",L:"ytp-upnext-title",Z:"{{title}}"},{G:"span",L:"ytp-upnext-author",Z:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},S:[{G:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},S:[{G:"circle",L:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",S:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
Z:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=a;this.cancelButton=null;this.F=this.ha("ytp-svg-autoplay-ring");this.C=this.notification=this.u=this.suggestion=null;this.D=new g.F(this.Ar,5E3,this);this.B=0;var b=this.ha("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",ia:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Annuler la lecture automatique"},Z:"Annuler"});g.D(this,this.cancelButton);this.cancelButton.wa("click",this.sL,this);this.cancelButton.ga(b);
g.D(this,this.D);g.KT(this.api,this.element,this,18788);b=this.ha("ytp-upnext-autoplay-icon");this.R(b,"click",this.tL);this.mD();this.R(a,"autonavvisibility",this.mD);this.R(a,"mdxnowautoplaying",this.CN);this.R(a,"mdxautoplaycanceled",this.DN);this.R(a,"mdxautoplayupnext",this.qG);e5(this)&&(a=(a=g.wT(g.rT(this.api)))?a.AI():null)&&this.qG(a);g.K(this.element,"ytp-upnext-mobile",this.api.T().u)},e5=function(a){return 3===a.api.getPresentingPlayerType()},PGa=function(a,b){return b?b:0<=a.api.app.getVideoData().lr?
a.api.app.getVideoData().lr:g.P(a.api.T().experiments,"autoplay_time")||1E4},g5=function(a,b){var c=PGa(a,b),d=Math,e=d.min;
var f=(0,g.N)()-a.B;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.F.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.mg()&&!e5(a)?a.select(!0):a.mg()&&a.u.start()},h5=function(a){d5.call(this,a,"autonav-endscreen");
this.videoData=this.suggestions=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",S:[{G:"div",ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Z:"Plus de vid\u00e9os"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.C=null;this.F=this.I=!1;this.B=new a5(this.player);g.D(this,this.B);this.B.ga(this.element);a.getVideoData().dl?this.u=this.B:(this.u=new f5(a),g.iP(this.player,this.u.element,4),g.D(this,this.u));this.D=new g.cR(this);
g.D(this,this.D);g.D(this,this.table);this.table.ga(this.element);this.table.show();g.D(this,this.K);this.K.ga(this.table.element);this.hide()},QGa=function(a,b){return g.Lc(b.suggestions,function(c){c=g.VW(a.player.T(),c);
g.D(a,c);return c})},i5=function(a){var b=a.An();
b!==a.F&&(a.F=b,a.player.V("autonavvisibility"),a.F?(a.B!==a.u&&a.B.hide(),a.table.hide()):(a.B!==a.u&&a.B.show(),a.table.show()))},j5=function(a){return 400>=a.width||360>=a.height},RGa=function(a){d5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.V({G:"div",L:"ytp-subscribe-card",S:[{G:"img",L:"ytp-author-image",U:{src:b.sf}},{G:"div",L:"ytp-subscribe-card-right",S:[{G:"div",L:"ytp-author-name",Z:b.author},{G:"div",L:"html5-subscribe-button-container"}]}]});g.D(this,this.u);this.u.ga(this.element);this.subscribeButton=new g.XU("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,b.zg,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.ga(this.u.ha("html5-subscribe-button-container"));
this.hide()},k5=function(a){var b=a.T(),c=g.iA||g.og?{style:"will-change: opacity"}:void 0,d=b.B,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",ia:e,U:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{G:"div",L:"ytp-videowall-still-image",U:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",S:[{G:"span",L:"ytp-videowall-still-info-bg",S:[{G:"span",L:"ytp-videowall-still-info-content",U:c,S:[{G:"span",L:"ytp-videowall-still-info-title",Z:"{{title}}"},{G:"span",L:"ytp-videowall-still-info-author",
Z:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",Z:"En direct"},{G:"span",L:"ytp-videowall-still-info-duration",Z:"{{duration}}"}]}]}]},{G:"span",ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",S:[" (",{G:"span",Z:"{{playlist_length}}"},")"]}]},{G:"span",ia:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:[{G:"span",
L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",Z:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.u=new g.cR(this);g.D(this,this.u);this.wa("click",this.onClick);this.wa("keypress",this.C);this.u.R(a,"videodatachange",this.Oa);g.sN(a,this.element,this);this.Oa()},l5=function(a){d5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=this.suggestions=null;this.F=this.P=!1;this.K=null;this.B=new g.cR(this);g.D(this,this.B);this.I=new g.F(function(){g.H(b.element,"ytp-show-tiles")},0);
g.D(this,this.I);var c=new g.V({G:"button",ia:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Pr\u00e9c\u00e9dente"},S:[g.BN()]});g.D(this,c);c.ga(this.element);c.wa("click",this.rK,this);this.table=new g.mN({G:"div",L:"ytp-endscreen-content"});g.D(this,this.table);this.table.ga(this.element);c=new g.V({G:"button",ia:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Suivante"},S:[g.CN()]});g.D(this,c);c.ga(this.element);c.wa("click",this.qK,this);a.getVideoData().dl?this.u=new a5(a,!0):
this.u=new f5(a);g.D(this,this.u);g.iP(this.player,this.u.element,4);this.hide()},m5=function(a){return g.JT(a.player)&&a.Do()&&!a.D},SGa=function(a,b){return g.Lc(b.suggestions,function(c){c=g.VW(a.J.T(),c);
g.D(a,c);return c})},n5=function(a){var b=a.An();
b!==a.P&&(a.P=b,a.player.V("autonavvisibility"))},o5=function(a){g.sS.call(this,a);
var b=this;this.endScreen=null;this.u=this.B=this.C=!1;this.listeners=new g.cR(this);g.D(this,this.listeners);this.env=a.T();TGa(a)?(this.C=!0,UGa(this),this.u?this.endScreen=new h5(a):this.endScreen=new l5(this.player)):this.env.yd?this.endScreen=new RGa(this.player):this.endScreen=new d5(this.player);g.D(this,this.endScreen);g.iP(this.player,this.endScreen.element,4);VGa(this);this.listeners.R(a,"videodatachange",this.Oa,this);this.listeners.R(a,g.bE("endscreen"),function(c){b.PC()&&(b.endScreen.created||
b.endScreen.create(),"load"===c.getId()&&b.load())});
this.listeners.R(a,g.cE("endscreen"),function(c){"load"===c.getId()&&b.loaded&&b.unload()})},UGa=function(a){var b=a.player.getVideoData();
if(!b||a.u===b.Zn&&a.B===b.dl)return!1;a.u=b.Zn;a.B=b.dl;return!0},TGa=function(a){a=a.T();
return a.Xa&&!a.yd},VGa=function(a){g.GT(a.player,"endscreen");
var b=a.player.getVideoData();b=new g.ZD(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.ZD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.eN(a.player,[b,c])};
g.u(Z4,g.V);Z4.prototype.select=function(){(g.qT(this.J,this.suggestion.Ka().videoId,this.suggestion.md,this.suggestion.getPlaylistId(),void 0,this.suggestion.Uv||void 0)||this.J.aa("web_player_endscreen_double_log_fix_killswitch"))&&g.LT(this.J,this.element)};
Z4.prototype.onClick=function(a){g.oU(a,this.J,this.u,this.suggestion.md||void 0)&&this.select()};
Z4.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.Oo(a)||(this.select(),g.No(a))}};
Z4.prototype.Gd=function(a){g.K(this.element,"ytp-suggestion-card-with-margin",a)};g.u(a5,g.V);g.k=a5.prototype;g.k.Ip=function(a){this.suggestion!==a&&(this.suggestion=a,Y4(this.u,a),this.playButton.ya("url",this.suggestion.vk()),this.Gd())};
g.k.Gd=function(){var a=this.J.mi(!0,this.J.isFullscreen());g.K(this.element,"ytp-autonav-endscreen-small-mode",this.ye(a));g.K(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.uu);g.K(this.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!g.sT(this.J));g.K(this.J.getRootNode(),"countdown-running",this.mg());g.K(this.element,"ytp-player-content",g.sT(this.J));g.lg(this.overlay.element,{width:a.width+"px"});if(!this.mg()){g.sT(this.J)?c5(this,Math.round(b5(this)/
1E3)):c5(this);a=!!this.suggestion&&!!this.suggestion.Eo;var b=g.sT(this.J)||!a;g.K(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.K(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.pN(this.B,g.sT(this.J))}};
g.k.mg=function(){return 0<this.C};
g.k.bo=function(){this.mg()||(this.C=Date.now(),$4(this),OGa(this.J,b5(this)),g.K(this.J.getRootNode(),"countdown-running",this.mg()))};
g.k.lm=function(){this.Uj();$4(this)};
g.k.Uj=function(){this.mg()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Uj()};
g.k.aD=function(a){g.oU(a,this.J)&&(a.currentTarget===this.playButton.element?g.LT(this.J,this.playButton.element):a.currentTarget===this.u.ha("ytp-autonav-endscreen-link-container")&&(a=this.u.ha("ytp-autonav-endscreen-link-container"),g.wN(this.J,a,!0),g.LT(this.J,a)),this.select())};
g.k.oK=function(){g.LT(this.J,this.cancelButton.element);g.uT(this.J,!0)};
g.k.ZC=function(){var a=g.sT(this.J);this.F&&this.ab!==a&&g.pN(this,a);this.Gd();g.wN(this.J,this.element,a);g.wN(this.J,this.cancelButton.element,a);g.wN(this.J,this.u.ha("ytp-autonav-endscreen-link-container"),a);g.wN(this.J,this.playButton.element,a)};
g.k.ye=function(a){return 400>a.width||459>a.height};g.u(d5,g.V);g.k=d5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.Do=function(){return!1};
g.k.An=function(){return!1};
g.k.mC=function(){return!1};g.u(f5,g.V);g.k=f5.prototype;g.k.Ar=function(){this.notification&&(this.D.stop(),this.Hb(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.Ip=function(a){this.suggestion=a;Y4(this,a,"hqdefault.jpg")};
g.k.mD=function(){g.pN(this,g.sT(this.api));g.wN(this.api,this.element,g.sT(this.api))};
g.k.UN=function(){window.focus();this.Ar()};
g.k.bo=function(a){var b=this;this.mg()||(g.to("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.B=(0,g.N)(),this.u=new g.F(function(){g5(b,a)},25),g5(this,a),OGa(this.api,PGa(this,a)));
g.en(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.mg=function(){return!!this.u};
g.k.lm=function(){this.Uj();this.B=(0,g.N)();g5(this);g.H(this.element,"ytp-upnext-autoplay-paused")};
g.k.Uj=function(){this.mg()&&(this.u.dispose(),this.u=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.Q(this.api.T().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ka(),this.Ar(),this.notification=new Notification("\u00c0 suivre",{body:b.title,icon:b.ce()}),this.C=this.R(this.notification,"click",this.UN),this.D.start())}this.Uj();this.api.nextVideo(!1,a)};
g.k.tL=function(a){!g.He(this.cancelButton.element,g.Jo(a))&&g.oU(a,this.api)&&this.select()};
g.k.sL=function(){g.uT(this.api,!0)};
g.k.CN=function(a){e5(this);this.show();this.bo(a)};
g.k.qG=function(a){e5(this);this.suggestion&&this.suggestion.Ka().videoId===a.Ka().videoId||this.Ip(a)};
g.k.DN=function(){e5(this);this.Uj();this.hide()};
g.k.ba=function(){this.Uj();this.Ar();g.V.prototype.ba.call(this)};g.u(h5,d5);g.k=h5.prototype;g.k.create=function(){d5.prototype.create.call(this);this.D.R(this.player,"appresize",this.Gd);this.D.R(this.player,"onVideoAreaChange",this.Gd);this.D.R(this.player,"videodatachange",this.Oa);this.D.R(this.player,"autonavchange",this.YC);this.D.R(this.player,"autonavcancel",this.nK);this.Oa()};
g.k.show=function(){d5.prototype.show.call(this);(this.I||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.uT(this.player,!1);g.JT(this.player)&&this.Do()&&!this.C?(i5(this),2===this.videoData.autonavState?this.player.T().aa("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.bo():3===this.videoData.autonavState&&this.u.lm()):(g.uT(this.player,!0),i5(this));this.Gd()};
g.k.hide=function(){d5.prototype.hide.call(this);this.u.lm();i5(this)};
g.k.Gd=function(){var a=this.player.mi(!0,this.player.isFullscreen());i5(this);this.B.Gd();g.K(this.element,"ytp-autonav-cancelled-small-mode",this.ye(a));g.K(this.element,"ytp-autonav-cancelled-tiny-mode",800>a.width&&!j5(a));g.K(this.element,"ytp-autonav-cancelled-mini-mode",j5(a));if(!this.F){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Gd(1===c%2)}}};
g.k.Oa=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=QGa(this,a))&&this.suggestions.length)for(this.u.Ip(this.suggestions[0]),this.u!==this.B&&this.B.Ip(this.suggestions[0]),a=0;a<WGa.length;++a){var b=WGa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new Z4(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,Y4(c,b));g.D(this,this.videos[a]);this.videos[a].ga(this.K.element)}}this.Gd()}};
g.k.YC=function(a){1===a?(this.I=!1,this.C=this.videoData.clientPlaybackNonce,this.u.Uj(),this.ab&&this.Gd()):(this.I=!0,this.An()&&(2===a?this.u.bo():3===a&&this.u.lm()))};
g.k.nK=function(a){a?this.YC(1):(this.C=null,this.I=!1)};
g.k.Do=function(){return 1!==this.videoData.autonavState};
g.k.ye=function(a){return(910>a.width||459>a.height)&&!(800>a.width&&!j5(a))&&!j5(a)};
g.k.An=function(){return this.ab&&g.JT(this.player)&&this.Do()&&!this.C};
var WGa=[1,3,2,4];g.u(RGa,d5);g.u(k5,g.V);k5.prototype.select=function(){(g.qT(this.api,this.suggestion.Ka().videoId,this.suggestion.md,this.suggestion.getPlaylistId(),void 0,this.suggestion.Uv||void 0)||this.api.aa("web_player_endscreen_double_log_fix_killswitch"))&&g.LT(this.api,this.element)};
k5.prototype.onClick=function(a){g.oU(a,this.api,this.B,this.suggestion.md||void 0)&&this.select()};
k5.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.Oo(a)||(this.select(),g.No(a))}};
k5.prototype.Oa=function(){var a=this.api.getVideoData(),b=this.api.T();this.B=a.jc?!1:b.B};g.u(l5,d5);g.k=l5.prototype;g.k.create=function(){d5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=SGa(this,a),this.videoData=a);this.Gd();this.B.R(this.player,"appresize",this.Gd);this.B.R(this.player,"onVideoAreaChange",this.Gd);this.B.R(this.player,"videodatachange",this.Oa);this.B.R(this.player,"autonavchange",this.yx);this.B.R(this.player,"autonavcancel",this.pK);a=this.videoData.autonavState;a!==this.K&&this.yx(a);this.B.R(this.element,"transitionend",this.fP)};
g.k.destroy=function(){g.Hs(this.B);g.Yf(this.stills);this.stills=[];this.suggestions=null;d5.prototype.destroy.call(this);g.en(this.element,"ytp-show-tiles");this.I.stop();this.K=this.videoData.autonavState};
g.k.Do=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){d5.prototype.show.call(this);g.en(this.element,"ytp-show-tiles");this.player.T().u?g.Xm(this.I):this.I.start();(this.F||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.uT(this.player,!1);m5(this)?(n5(this),2===this.videoData.autonavState?this.player.T().aa("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):this.u.bo():3===this.videoData.autonavState&&this.u.lm()):(g.uT(this.player,!0),n5(this))};
g.k.hide=function(){d5.prototype.hide.call(this);this.u.lm();n5(this)};
g.k.fP=function(a){g.Jo(a)===this.element&&this.Gd()};
g.k.Gd=function(){if(this.suggestions&&this.suggestions.length){g.H(this.element,"ytp-endscreen-paginate");var a=this.J.mi(!0,this.J.isFullscreen()),b=g.lT(this.J);b&&(b=b.Ud()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Ag(a,m,n);g.lg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.u.Ip(this.suggestions[0]);this.u instanceof a5&&this.u.Gd();g.K(this.element,"ytp-endscreen-takeover",m5(this));n5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.Xd(p+this.C,l),0!==r){t=this.stills[c];t||(t=new k5(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,B=Math.floor(m*(f+r)/b)-x-4;g.tg(t.element,x,w);g.Ag(t.element,B,y);g.lg(t.element,"transitionDelay",(h+f)/20+"s");g.K(t.element,"ytp-videowall-still-mini",1===r);g.K(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.T(),w=g.cn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",Y4(r,p,w),g.OC(t)&&(t=p.vk(),t=g.Ed(t,g.TU({},"emb_rel_end")),r.ya("url",t)),(p=(p=p.md)&&p.itct)&&g.tN(r.api,r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ee(e.element),g.Xf(e);this.stills.length=c}};
g.k.Oa=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.suggestions=SGa(this,a),this.videoData=a,this.Gd())};
g.k.qK=function(){this.C+=this.stills.length;this.Gd()};
g.k.rK=function(){this.C-=this.stills.length;this.Gd()};
g.k.mC=function(){return this.u.mg()};
g.k.yx=function(a){1===a?(this.F=!1,this.D=this.videoData.clientPlaybackNonce,this.u.Uj(),this.ab&&this.Gd()):(this.F=!0,this.ab&&m5(this)&&(2===a?this.u.bo():3===a&&this.u.lm()))};
g.k.pK=function(a){if(a){for(a=0;a<this.stills.length;a++)g.wN(this.J,this.stills[a].element,!0);this.yx(1)}else this.D=null,this.F=!1;this.Gd()};
g.k.An=function(){return this.ab&&m5(this)};g.u(o5,g.sS);g.k=o5.prototype;g.k.PC=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!TGa(this.player)||b;var c=a.Dm||g.XC(a.Ra),d=g.Z0(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.OC=function(){return this.endScreen.An()};
g.k.nJ=function(){return this.OC()?this.endScreen.mC():!1};
g.k.ba=function(){g.GT(this.player,"endscreen");g.sS.prototype.ba.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.cG;if(b&&b.videoId){var c=g.rT(this.player).Mc.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.RE?a=!1:(g.qT(this.player,b.videoId,void 0,void 0,!0,b),c&&c.Ys("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.sS.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.sS.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.Oa=function(){VGa(this);this.C&&UGa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.u?this.endScreen=new h5(this.player):this.endScreen=new l5(this.player),g.D(this,this.endScreen),g.iP(this.player,this.endScreen.element,4))};g.eU.endscreen=o5;})(_yt_player);
